MLIR: lib/Analysis/AffineStructures.cpp File Reference
AffineStructures.cpp File Reference
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LinearTransform.h"
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "affine-structures"
#define DEBUG_TYPE "fm"
#define DEBUG_TYPE "affine-structures"
Enumerations
enum BoundCmpResult
Functions
static LogicalResult getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineConstraints *localVarCst)
static bool areIdsAligned (const FlatAffineValueConstraints &a, const FlatAffineValueConstraints &b)
Checks if two constraint systems are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints &cst, unsigned start, unsigned end)
Checks if the SSA values associated with cst's identifiers in range [start, end) are unique.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineConstraints &cst)
Checks if the SSA values associated with cst's identifiers are unique.
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints &cst, FlatAffineConstraints::IdKind kind)
Checks if the SSA values associated with cst's identifiers of kind kind are unique.
static void mergeAndAlignIds (unsigned offset, FlatAffineValueConstraints *a, FlatAffineValueConstraints *b)
Merge and align the identifiers of A and B starting at 'offset', so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with A's original identifiers appearing first followed by any of B's identifiers that didn't appear in A.
static void turnSymbolIntoDim (FlatAffineValueConstraints *cst, Value id)
static bool findConstraintWithNonZeroAt (const FlatAffineConstraints &cst, unsigned colIdx, bool isEq, unsigned *rowIdx)
template<bool isEq>
static void normalizeConstraintByGCD (FlatAffineConstraints *constraints, unsigned rowIdx)
static void eliminateFromConstraint (FlatAffineConstraints *constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq)
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
static unsigned getBestIdToEliminate (const FlatAffineConstraints &cst, unsigned start, unsigned end)
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
bool eqInvolvesSuffixDims (const FlatAffineConstraints &fac, unsigned eqIndex, unsigned numDims)
bool ineqInvolvesSuffixDims (const FlatAffineConstraints &fac, unsigned ineqIndex, unsigned numDims)
void removeConstraintsInvolvingSuffixDims (FlatAffineConstraints &fac, unsigned unboundedDims)
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point)
Helper to evaluate an affine expression at a point.
static LogicalResult getDivRepr (const FlatAffineConstraints &cst, unsigned pos, unsigned ubIneq, unsigned lbIneq, SmallVector< int64_t, 8 > &expr, unsigned &divisor)
Check if the pos^th identifier can be represented as a division using upper bound inequality at position ubIneq and lower bound inequality at position lbIneq.
static Optional< std::pair< unsigned, unsigned > > computeSingleVarRepr (const FlatAffineConstraints &cst, const SmallVector< bool, 8 > &foundRepr, unsigned pos, SmallVector< int64_t, 8 > &dividend, unsigned &divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
static bool detectAsMod (const FlatAffineConstraints &cst, unsigned pos, int64_t lbConst, int64_t ubConst, SmallVectorImpl< AffineExpr > &memo, MLIRContext *context)
static bool detectAsFloorDiv (const FlatAffineConstraints &cst, unsigned pos, MLIRContext *context, SmallVectorImpl< AffineExpr > &exprs)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant) given the initial set of expressions in exprs.
static void fillInequality (FlatAffineConstraints *cst, unsigned r, int64_t val)
static void negateInequality (FlatAffineConstraints *cst, unsigned r)
static void eliminateRedundantLocalId (FlatAffineConstraints &fac, unsigned pos1, unsigned pos2)
Eliminate pos2^th local identifier, replacing its every instance with pos1^th local identifier.
static int findEqualityToConstant (const FlatAffineConstraints &cst, unsigned pos, bool symbolic=false)
Finds an equality that equates the specified identifier to a constant.
static std::pair< unsigned, unsigned > getNewNumDimsSymbols (unsigned pos, const FlatAffineConstraints &cst)
static void getCommonConstraints (const FlatAffineConstraints &a, const FlatAffineConstraints &b, FlatAffineConstraints &c)
static LogicalResult computeLocalVars (const FlatAffineConstraints &cst, SmallVectorImpl< AffineExpr > &memo, MLIRContext *context)
Compute an explicit representation for local vars.
static bool isColZero (const FlatAffineConstraints &cst, unsigned pos)
Returns true if the pos^th column is all zero for both inequalities and equalities.
static void getIndependentConstraints (const FlatAffineConstraints &cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > &nbIneqIndices, SmallVectorImpl< unsigned > &nbEqIndices)
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Macro Definition Documentation
DEBUG_TYPE [1/3]
#define DEBUG_TYPE "affine-structures"
Definition at line 3316 of file AffineStructures.cpp.
DEBUG_TYPE [2/3]
#define DEBUG_TYPE "fm"
Definition at line 3316 of file AffineStructures.cpp.
DEBUG_TYPE [3/3]
#define DEBUG_TYPE "affine-structures"
Definition at line 3316 of file AffineStructures.cpp.
Enumeration Type Documentation
BoundCmpResult
enum BoundCmpResult
Definition at line 3381 of file AffineStructures.cpp.
Function Documentation
areIdsAligned()
static bool areIdsAligned (const FlatAffineValueConstraints & a, const FlatAffineValueConstraints & b) static
Checks if two constraint systems are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
Definition at line 436 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::getMaybeValues(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumIds(), and mlir::FlatAffineConstraints::getNumSymbolIds().
Referenced by mlir::FlatAffineValueConstraints::areIdsAlignedWithOther(), mergeAndAlignIds(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
areIdsUnique() [1/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints & cst, unsigned start, unsigned end) static
Checks if the SSA values associated with cst's identifiers in range [start, end) are unique.
Definition at line 453 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::getMaybeValues(), and mlir::FlatAffineConstraints::getNumIds().
Referenced by areIdsUnique(), mergeAndAlignIds(), and mlir::FlatAffineValueConstraints::mergeSymbolIds().
areIdsUnique() [2/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineConstraints & cst) static
Checks if the SSA values associated with cst's identifiers are unique.
Definition at line 473 of file AffineStructures.cpp.
References areIdsUnique(), and mlir::FlatAffineConstraints::getNumIds().
areIdsUnique() [3/3]
static bool LLVM_ATTRIBUTE_UNUSED areIdsUnique (const FlatAffineValueConstraints & cst, FlatAffineConstraints::IdKind kind) static
Checks if the SSA values associated with cst's identifiers of kind kind are unique.
Definition at line 479 of file AffineStructures.cpp.
computeLocalVars()
static LogicalResult computeLocalVars (const FlatAffineConstraints & cst, SmallVectorImpl< AffineExpr > & memo, MLIRContext * context) static
Compute an explicit representation for local vars.
For all systems coming from MLIR integer sets, maps, or expressions where local vars were introduced to model floordivs and mods, this always succeeds.
Definition at line 3563 of file AffineStructures.cpp.
References detectAsFloorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::FlatAffineConstraints::numDims, and mlir::success().
Referenced by mlir::FlatAffineConstraints::getAsIntegerSet(), and mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap().
computeSingleVarRepr()
static Optional<std::pair<unsigned, unsigned> > computeSingleVarRepr (const FlatAffineConstraints & cst, const SmallVector< bool, 8 > & foundRepr, unsigned pos, SmallVector< int64_t, 8 > & dividend, unsigned & divisor) static
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
foundRepr contains a boolean for each identifier indicating if the explicit representation for that identifier has already been computed. Returns the upper and lower bound inequalities using which the floordiv can be computed. If the representation could be computed, dividend and denominator are set. If the representation could not be computed, llvm::None is returned.
Definition at line 1435 of file AffineStructures.cpp.
References mlir::failed(), getDivRepr(), mlir::FlatAffineConstraints::getLowerAndUpperBoundIndices(), and mlir::FlatAffineConstraints::getNumIds().
Referenced by detectAsFloorDiv().
detectAsFloorDiv()
static bool detectAsFloorDiv (const FlatAffineConstraints & cst, unsigned pos, MLIRContext * context, SmallVectorImpl< AffineExpr > & exprs) static
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant) given the initial set of expressions in exprs.
If it can be, the corresponding position in exprs is set as the detected affine expr. For eg: 4q <= i + j <= 4q + 3 <=> q = (i + j) floordiv 4. An equality can also yield a floordiv: eg. 4q = i + j <=> q = (i + j) floordiv 4. 32q + 28 <= i <= 32q + 31 => q = i floordiv 32.
Definition at line 1791 of file AffineStructures.cpp.
References computeSingleVarRepr(), mlir::getAffineConstantExpr(), and mlir::FlatAffineConstraints::getNumIds().
Referenced by computeLocalVars(), and mlir::FlatAffineConstraints::getSliceBounds().
detectAsMod()
static bool detectAsMod (const FlatAffineConstraints & cst, unsigned pos, int64_t lbConst, int64_t ubConst, SmallVectorImpl< AffineExpr > & memo, MLIRContext * context) static
Definition at line 1626 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::AffineExpr::dyn_cast(), mlir::floorDiv(), mlir::getAffineConstantExpr(), mlir::FlatAffineConstraints::getConstantBound(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), and mlir::simplifyAffineExpr().
Referenced by mlir::FlatAffineConstraints::getSliceBounds().
eliminateFromConstraint()
static void eliminateFromConstraint (FlatAffineConstraints * constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq) static
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
Columns in range [elimColStart, pivotCol) will not be updated as they have already been eliminated.
Definition at line 915 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumCols(), and mlir::lcm().
Referenced by mlir::FlatAffineConstraints::gaussianEliminateIds(), and mlir::FlatAffineConstraints::removeRedundantLocalVars().
eliminateRedundantLocalId()
static void eliminateRedundantLocalId (FlatAffineConstraints & fac, unsigned pos1, unsigned pos2) static
Eliminate pos2^th local identifier, replacing its every instance with pos1^th local identifier.
This function is intended to be used to remove redundancy when local variables at position pos1 and pos2 are restricted to have the same value.
Definition at line 1925 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), and mlir::FlatAffineConstraints::removeId().
Referenced by mlir::FlatAffineConstraints::mergeLocalIds().
eqInvolvesSuffixDims()
bool eqInvolvesSuffixDims (const FlatAffineConstraints & fac, unsigned eqIndex, unsigned numDims)
Definition at line 1151 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::getNumIds(), and mlir::FlatAffineConstraints::numDims.
Referenced by removeConstraintsInvolvingSuffixDims().
fillInequality()
static void fillInequality (FlatAffineConstraints * cst, unsigned r, int64_t val) inline static
Definition at line 1822 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atIneq(), and mlir::FlatAffineConstraints::getNumCols().
Referenced by mlir::FlatAffineConstraints::removeRedundantInequalities().
findConstraintWithNonZeroAt()
static bool findConstraintWithNonZeroAt (const FlatAffineConstraints & cst, unsigned colIdx, bool isEq, unsigned * rowIdx) static
Definition at line 817 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumEqualities(), and mlir::FlatAffineConstraints::getNumInequalities().
Referenced by mlir::FlatAffineConstraints::gaussianEliminateIds(), mlir::FlatAffineConstraints::getSliceBounds(), and isColZero().
findEqualityToConstant()
static int findEqualityToConstant (const FlatAffineConstraints & cst, unsigned pos, bool symbolic = false) static
Finds an equality that equates the specified identifier to a constant.
Returns the position of the equality row. If 'symbolic' is set to true, symbols are also treated like a constant, i.e., an affine function of the symbols is also treated like a constant. Returns -1 if such an equality could not be found.
Definition at line 2666 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumEqualities(), and mlir::FlatAffineConstraints::getNumIds().
Referenced by mlir::FlatAffineConstraints::computeConstantLowerOrUpperBound(), mlir::FlatAffineConstraints::constantFoldId(), and mlir::FlatAffineConstraints::getConstantBoundOnDimSize().
getBestIdToEliminate()
static unsigned getBestIdToEliminate (const FlatAffineConstraints & cst, unsigned start, unsigned end) static
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
It is often best to eliminate in the increasing order of these counts when doing Fourier-Motzkin elimination since FM adds that many new constraints.
Definition at line 993 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumInequalities(), and min().
Referenced by mlir::FlatAffineConstraints::isEmpty(), and mlir::FlatAffineConstraints::projectOut().
getCommonConstraints()
static void getCommonConstraints (const FlatAffineConstraints & a, const FlatAffineConstraints & b, FlatAffineConstraints & c) static
Definition at line 3403 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::getEquality(), mlir::FlatAffineConstraints::getInequality(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), and mlir::FlatAffineConstraints::reset().
Referenced by mlir::FlatAffineConstraints::unionBoundingBox().
getDivRepr()
static LogicalResult getDivRepr (const FlatAffineConstraints & cst, unsigned pos, unsigned ubIneq, unsigned lbIneq, SmallVector< int64_t, 8 > & expr, unsigned & divisor) static
Check if the pos^th identifier can be represented as a division using upper bound inequality at position ubIneq and lower bound inequality at position lbIneq.
Let id be the pos^th identifier, then id is equivalent to expr floordiv divisor if there are constraints of the form: 0 <= expr - divisor * id <= divisor - 1 Rearranging, we have: divisor * id - expr + (divisor - 1) >= 0 <– Lower bound for 'id' -divisor * id + expr >= 0 <– Upper bound for 'id'
For example: 32*k >= 16*i + j - 31 <– Lower bound for 'k' 32*k <= 16*i + j <– Upper bound for 'k' expr = 16*i + j, divisor = 32 k = (16*i + j) floordiv 32
4q >= i + j - 2 <– Lower bound for 'q' 4q <= i + j + 1 <– Upper bound for 'q' expr = i + j + 1, divisor = 4 q = (i + j + 1) floordiv 4
If successful, expr is set to dividend of the division and divisor is set to the denominator of the division.
Definition at line 1379 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atIneq(), mlir::failure(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumInequalities(), and mlir::success().
Referenced by computeSingleVarRepr().
getFlattenedAffineExprs()
static LogicalResult getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineConstraints * localVarCst) static
Definition at line 74 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::clearAndCopyFrom(), mlir::failure(), mlir::FlatAffineConstraints::reset(), and mlir::success().
Referenced by mlir::getFlattenedAffineExprs().
getIndependentConstraints()
static void getIndependentConstraints (const FlatAffineConstraints & cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > & nbIneqIndices, SmallVectorImpl< unsigned > & nbEqIndices) static
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Definition at line 3701 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumIds(), and mlir::FlatAffineConstraints::getNumInequalities().
Referenced by mlir::FlatAffineConstraints::removeIndependentConstraints().
getNewNumDimsSymbols()
static std::pair<unsigned, unsigned> getNewNumDimsSymbols (unsigned pos, const FlatAffineConstraints & cst) static
Definition at line 3093 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::FlatAffineConstraints::numDims, and mlir::FlatAffineConstraints::numSymbols.
Referenced by mlir::FlatAffineConstraints::fourierMotzkinEliminate().
ineqInvolvesSuffixDims()
bool ineqInvolvesSuffixDims (const FlatAffineConstraints & fac, unsigned ineqIndex, unsigned numDims)
Definition at line 1158 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getNumIds(), and mlir::FlatAffineConstraints::numDims.
Referenced by removeConstraintsInvolvingSuffixDims().
isColZero()
static bool isColZero (const FlatAffineConstraints & cst, unsigned pos) static
Returns true if the pos^th column is all zero for both inequalities and equalities.
Definition at line 3640 of file AffineStructures.cpp.
References findConstraintWithNonZeroAt().
Referenced by mlir::FlatAffineConstraints::getAsIntegerSet().
mergeAndAlignIds()
static void mergeAndAlignIds (unsigned offset, FlatAffineValueConstraints * a, FlatAffineValueConstraints * b) static
Merge and align the identifiers of A and B starting at 'offset', so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with A's original identifiers appearing first followed by any of B's identifiers that didn't appear in A.
Local identifiers in B that have the same division representation as local identifiers in A are merged into one.
Definition at line 500 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::appendDimId(), areIdsAligned(), areIdsUnique(), mlir::FlatAffineValueConstraints::findId(), mlir::FlatAffineValueConstraints::getMaybeValues(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineValueConstraints::getValue(), mlir::FlatAffineValueConstraints::getValues(), mlir::FlatAffineValueConstraints::insertDimId(), mlir::FlatAffineConstraints::mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::FlatAffineValueConstraints::mergeAndAlignIdsWithOther(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
negateInequality()
static void negateInequality (FlatAffineConstraints * cst, unsigned r) inline static
Definition at line 1830 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atIneq(), and mlir::FlatAffineConstraints::getNumCols().
Referenced by mlir::FlatAffineConstraints::removeRedundantInequalities().
normalizeConstraintByGCD()
template<bool isEq> static void normalizeConstraintByGCD (FlatAffineConstraints * constraints, unsigned rowIdx) static
Definition at line 836 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), and mlir::FlatAffineConstraints::getNumCols().
Referenced by mlir::FlatAffineConstraints::gaussianEliminateIds(), mlir::FlatAffineConstraints::normalizeConstraintsByGCD(), and mlir::FlatAffineConstraints::removeRedundantLocalVars().
removeConstraintsInvolvingSuffixDims()
void removeConstraintsInvolvingSuffixDims (FlatAffineConstraints & fac, unsigned unboundedDims)
Definition at line 1166 of file AffineStructures.cpp.
References eqInvolvesSuffixDims(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), ineqInvolvesSuffixDims(), mlir::FlatAffineConstraints::removeEquality(), and mlir::FlatAffineConstraints::removeInequality().
Referenced by mlir::FlatAffineConstraints::findIntegerSample().
turnSymbolIntoDim()
static void turnSymbolIntoDim (FlatAffineValueConstraints * cst, Value id) static
Definition at line 613 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::findId(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::FlatAffineConstraints::setDimSymbolSeparation(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims().
valueAt()
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point) static
Helper to evaluate an affine expression at a point.
The expression is a list of coefficients for the dimensions followed by the constant term.
Definition at line 1331 of file AffineStructures.cpp.
References value.
Referenced by mlir::FlatAffineConstraints::containsPoint().