MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.cpp File Reference
BufferizableOpInterface.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
mlir::linalg::comprehensive_bufferize
Macros
#define DEBUG_TYPE "bufferizable-op-interface"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Functions
static Optional< Value > defaultAllocationFn (OpBuilder &b, Location loc, MemRefType type, ArrayRef< Value > dynShape)
Default allocation function that is used by the comprehensive bufferization pass.
static void defaultDeallocationFn (OpBuilder &b, Location loc, Value allocatedBuffer)
Default deallocation function that is used by the comprehensive bufferization pass.
static void defaultMemCpyFn (OpBuilder &b, Location loc, Value from, Value to)
Default memory copy function that is used by the comprehensive bufferization pass.
static void setInsertionPointAfter (OpBuilder &b, Value value)
static void moveInsertionPointToAllocationHoistingBarrier (OpBuilder &b)
Move the insertion point of the given builder to the beginning of a surrounding block as much as possible, while not crossing any allocation hoisting barriers.
static MemRefType getAllocationTypeAndShape (OpBuilder &b, Location loc, Value shapedValue, SmallVectorImpl< Value > &dynShape)
Compute the type of the memref to use for allocating the buffer for shapedValue.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 32 of file BufferizableOpInterface.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "bufferizable-op-interface"
Definition at line 31 of file BufferizableOpInterface.cpp.
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 33 of file BufferizableOpInterface.cpp.
Function Documentation
defaultAllocationFn()
static Optional<Value> defaultAllocationFn (OpBuilder & b, Location loc, MemRefType type, ArrayRef< Value > dynShape) static
Default allocation function that is used by the comprehensive bufferization pass.
The default currently creates a ranked memref using memref.alloc.
Definition at line 44 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64IntegerAttr(), and mlir::linalg::comprehensive_bufferize::kBufferAlignments.
Referenced by mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks().
defaultDeallocationFn()
static void defaultDeallocationFn (OpBuilder & b, Location loc, Value allocatedBuffer) static
Default deallocation function that is used by the comprehensive bufferization pass.
It expects to recieve back the value called from the defaultAllocationFn.
Definition at line 55 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks().
defaultMemCpyFn()
static void defaultMemCpyFn (OpBuilder & b, Location loc, Value from, Value to) static
Default memory copy function that is used by the comprehensive bufferization pass.
Creates a memref.copy op.
Definition at line 62 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks().
getAllocationTypeAndShape()
static MemRefType getAllocationTypeAndShape (OpBuilder & b, Location loc, Value shapedValue, SmallVectorImpl< Value > & dynShape) static
Compute the type of the memref to use for allocating the buffer for shapedValue.
Also returns (by reference in dynShape), the value for the dynamic dimensions in the returned memref type. The function may also set the insertion point to an earlier location, where the allocation should happen ("allocation hoisting").
Definition at line 505 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::createAllocDeallocFn(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), mlir::linalg::comprehensive_bufferize::getContiguousMemRefType(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), moveInsertionPointToAllocationHoistingBarrier(), and mlir::succeeded().
Referenced by mlir::linalg::comprehensive_bufferize::BufferizationState::createAllocDeallocFn().
moveInsertionPointToAllocationHoistingBarrier()
static void moveInsertionPointToAllocationHoistingBarrier (OpBuilder & b) static
Move the insertion point of the given builder to the beginning of a surrounding block as much as possible, while not crossing any allocation hoisting barriers.
Definition at line 474 of file BufferizableOpInterface.cpp.
References mlir::Region::front(), mlir::Region::getBlocks(), mlir::OpBuilder::getInsertionBlock(), mlir::Operation::getNumRegions(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Operation::getParentOp(), mlir::Operation::getRegion(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by getAllocationTypeAndShape().
setInsertionPointAfter()
static void setInsertionPointAfter (OpBuilder & b, Value value) static
Definition at line 192 of file BufferizableOpInterface.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), and mlir::OpBuilder::setInsertionPointAfterValue().