MLIR: include/mlir-c/Support.h File Reference
Support.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Classes
struct MlirStringRef
A pointer to a sized fragment of a string, not necessarily null-terminated.
struct MlirLogicalResult
A logical result value, essentially a boolean with named states.
Macros
#define MLIR_CAPI_EXPORTED __attribute__((visibility("default")))
Typedefs
typedef struct MlirStringRef MlirStringRef
typedef void(* MlirStringCallback) (MlirStringRef, void *)
A callback for returning string references.
typedef struct MlirLogicalResult MlirLogicalResult
Functions
static MlirStringRef mlirStringRefCreate (const char *str, size_t length)
Constructs a string reference from the pointer and length.
MLIR_CAPI_EXPORTED MlirStringRef mlirStringRefCreateFromCString (const char *str)
Constructs a string reference from a null-terminated C string.
MLIR_CAPI_EXPORTED bool mlirStringRefEqual (MlirStringRef string, MlirStringRef other)
Returns true if two string references are equal, false otherwise.
static bool mlirLogicalResultIsSuccess (MlirLogicalResult res)
Checks if the given logical result represents a success.
static bool mlirLogicalResultIsFailure (MlirLogicalResult res)
Checks if the given logical result represents a failure.
static MlirLogicalResult mlirLogicalResultSuccess ()
Creates a logical result representing a success.
static MlirLogicalResult mlirLogicalResultFailure ()
Creates a logical result representing a failure.
Macro Definition Documentation
MLIR_CAPI_EXPORTED
#define MLIR_CAPI_EXPORTED __attribute__((visibility("default")))
Definition at line 46 of file Support.h.
Referenced by mlirAffineExprIsNull(), mlirAffineMapIsNull(), mlirAttributeIsNull(), mlirBlockIsNull(), mlirContextIsNull(), mlirDialectIsNull(), mlirExecutionEngineIsNull(), mlirIntegerSetIsNull(), mlirLocationIsNull(), mlirModuleIsNull(), mlirOperationIsNull(), mlirPassManagerIsNull(), mlirRegionIsNull(), mlirStringRefCreate(), mlirSymbolTableIsNull(), mlirTypeIDIsNull(), mlirTypeIsNull(), and mlirValueIsNull().
Typedef Documentation
MlirLogicalResult
typedef struct MlirLogicalResult MlirLogicalResult
Definition at line 106 of file Support.h.
MlirStringCallback
typedef void(* MlirStringCallback) (MlirStringRef, void *)
A callback for returning string references.
This function is called back by the functions that need to return a reference to the portion of the string with the following arguments:
an MlirStringRef representing the current portion of the string
a pointer to user data forwarded from the printing call.
Definition at line 92 of file Support.h.
MlirStringRef
typedef struct MlirStringRef MlirStringRef
Definition at line 64 of file Support.h.
Function Documentation
mlirLogicalResultFailure()
static MlirLogicalResult mlirLogicalResultFailure () inline static
Creates a logical result representing a failure.
Definition at line 125 of file Support.h.
Referenced by mlirInferTypeOpInterfaceInferReturnTypes().
mlirLogicalResultIsFailure()
static bool mlirLogicalResultIsFailure (MlirLogicalResult res) inline static
Checks if the given logical result represents a failure.
Definition at line 114 of file Support.h.
Referenced by mlir::python::PyInferTypeOpInterface::inferReturnTypes(), and mlir::python::PySymbolTable::replaceAllSymbolUses().
mlirLogicalResultIsSuccess()
static bool mlirLogicalResultIsSuccess (MlirLogicalResult res) inline static
Checks if the given logical result represents a success.
Definition at line 109 of file Support.h.
mlirLogicalResultSuccess()
static MlirLogicalResult mlirLogicalResultSuccess () inline static
Creates a logical result representing a success.
Definition at line 119 of file Support.h.
Referenced by mlirInferTypeOpInterfaceInferReturnTypes().
mlirStringRefCreate()
static MlirStringRef mlirStringRefCreate (const char * str, size_t length) inline static
Constructs a string reference from the pointer and length.
The pointer need not reference to a null-terminated string.
Definition at line 69 of file Support.h.
References MlirStringRef::data, MlirStringRef::length, MLIR_CAPI_EXPORTED, mlirStringRefCreateFromCString(), and mlirStringRefEqual().
Referenced by mlir::python::PySymbolTable::dunderGetItem(), mlir::python::PyInferTypeOpInterface::inferReturnTypes(), mlirStringRefCreateFromCString(), mlir::python::PyConcreteOpInterface< PyInferTypeOpInterface >::PyConcreteOpInterface(), toMlirStringRef(), mlir::python::PySymbolTable::walkSymbolTables(), wrap(), and mlir::detail::CallbackOstream::write_impl().
mlirStringRefCreateFromCString()
MLIR_CAPI_EXPORTED MlirStringRef mlirStringRefCreateFromCString (const char * str)
Constructs a string reference from a null-terminated C string.
Prefer mlirStringRefCreate if the length of the string is known.
Definition at line 14 of file Support.cpp.
References mlirStringRefCreate().
Referenced by mlirStringRefCreate().
mlirStringRefEqual()
MLIR_CAPI_EXPORTED bool mlirStringRefEqual (MlirStringRef string, MlirStringRef other)
Returns true if two string references are equal, false otherwise.
Definition at line 18 of file Support.cpp.
References MlirStringRef::data, and MlirStringRef::length.
Referenced by mlirStringRefCreate().