MLIR: mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo Class Reference
mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo Class Reference
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
Public Member Functions
BufferizationAliasInfo (Operation *rootOp)
BufferizationAliasInfo (const BufferizationAliasInfo &)=delete
void createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
void insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
void insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
void bufferizeInPlace (OpResult result, OpOperand &operand)
Set the inPlace bufferization spec to true.
void bufferizeOutOfPlace (OpResult result)
Set the inPlace bufferization spec to false.
bool areEquivalentBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 bufferize to equivalent buffers.
bool areAliasingBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 bufferize to aliasing buffers.
void unionAliasSets (Value v1, Value v2)
Union the alias sets of v1 and v2.
void unionEquivalenceClasses (Value v1, Value v2)
Union the equivalence classes of v1 and v2.
void applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
void applyOnAliases (Value v, function_ref< void(Value)> fun) const
Apply fun to all aliases of v.
void markInPlace (OpResult v)
Mark a value as in-place bufferized.
bool isInPlace (OpResult opResult) const
Return true if a value was marked as in-place bufferized.
Detailed Description
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
Definition at line 125 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
BufferizationAliasInfo() [1/2]
BufferizationAliasInfo::BufferizationAliasInfo (Operation * rootOp) explicit
Definition at line 81 of file BufferizableOpInterface.cpp.
References mlir::Operation::getRegions(), mlir::Operation::getResults(), and mlir::Operation::walk().
BufferizationAliasInfo() [2/2]
mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::BufferizationAliasInfo (const BufferizationAliasInfo &) delete
Member Function Documentation
applyOnAliases()
void BufferizationAliasInfo::applyOnAliases (Value v, function_ref< void(Value)> fun) const
Apply fun to all aliases of v.
Definition at line 168 of file BufferizableOpInterface.cpp.
applyOnEquivalenceClass()
void BufferizationAliasInfo::applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
Definition at line 158 of file BufferizableOpInterface.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp().
areAliasingBufferizedValues()
bool mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areAliasingBufferizedValues (Value v1, Value v2) const inline
Return true if v1 and v2 bufferize to aliasing buffers.
Definition at line 157 of file BufferizableOpInterface.h.
areEquivalentBufferizedValues()
bool mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues (Value v1, Value v2) const inline
Return true if v1 and v2 bufferize to equivalent buffers.
Definition at line 152 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::areEquivalentExtractSliceOps(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferRelation(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::isNotConflicting(), and mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle::run().
bufferizeInPlace()
void BufferizationAliasInfo::bufferizeInPlace (OpResult result, OpOperand & operand)
Set the inPlace bufferization spec to true.
Merge result's and operand's aliasing sets and iterate to a fixed point.
Definition at line 139 of file BufferizableOpInterface.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), and mlir::Value::print().
bufferizeOutOfPlace()
void BufferizationAliasInfo::bufferizeOutOfPlace (OpResult result)
Set the inPlace bufferization spec to false.
Definition at line 149 of file BufferizableOpInterface.cpp.
References mlir::Value::print().
createAliasInfoEntry()
void BufferizationAliasInfo::createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
In the beginning the alias and equivalence sets only contain v itself.
Definition at line 113 of file BufferizableOpInterface.cpp.
insertNewBufferAlias()
void BufferizationAliasInfo::insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Definition at line 120 of file BufferizableOpInterface.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize().
insertNewBufferEquivalence()
void BufferizationAliasInfo::insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Additionally, merge their equivalence classes.
Definition at line 127 of file BufferizableOpInterface.cpp.
isInPlace()
bool BufferizationAliasInfo::isInPlace (OpResult opResult) const
Return true if a value was marked as in-place bufferized.
Definition at line 134 of file BufferizableOpInterface.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp(), mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run(), and mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run().
markInPlace()
void mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::markInPlace (OpResult v) inline
Mark a value as in-place bufferized.
Definition at line 176 of file BufferizableOpInterface.h.
References isInPlace().
unionAliasSets()
void mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::unionAliasSets (Value v1, Value v2) inline
Union the alias sets of v1 and v2.
Definition at line 162 of file BufferizableOpInterface.h.
unionEquivalenceClasses()
void mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::unionEquivalenceClasses (Value v1, Value v2) inline
Union the equivalence classes of v1 and v2.
Definition at line 165 of file BufferizableOpInterface.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h
lib/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.cpp