MLIR: mlir::FlatAffineConstraints Class Reference
mlir::FlatAffineConstraints Class Reference
A flat list of affine equalities and inequalities in the form.
#include "mlir/Analysis/AffineStructures.h"
Public Types
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints }
All derived classes of FlatAffineConstraints.
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Public Member Functions
FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineConstraints (const MutableAffineMap &map)
virtual ~FlatAffineConstraints ()=default
virtual Kind getKind () const
Return the kind of this FlatAffineConstraints.
virtual void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0)
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const FlatAffineConstraints &other)
Appends constraints from other into this.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> &repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
std::unique_ptr< FlatAffineConstraints > clone () const
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
virtual void swapId (unsigned posA, unsigned posB)
Swap the posA^th identifier with the posB^th identifier.
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const FlatAffineConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
virtual void clearAndCopyFrom (const FlatAffineConstraints &other)
Replaces the contents of this FlatAffineConstraints with other.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (FlatAffineConstraints &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void clearConstraints ()
Removes all equalities and inequalities.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static FlatAffineConstraints getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const FlatAffineConstraints *cst)
Protected Member Functions
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
void assertAtMostNumIdKind (unsigned value, IdKind kind) const
Assert that value is at most the number of ids of the specified kind.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Given an affine map that is aligned with this constraint system:
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
virtual void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Protected Attributes
unsigned numIds
Total number of identifiers.
unsigned numDims
Number of identifiers corresponding to real dimensions.
unsigned numSymbols
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
A flat list of affine equalities and inequalities in the form.
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} >= 0 Equality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} == 0
FlatAffineConstraints stores coefficients in a contiguous buffer (one buffer for equalities and one for inequalities). The size of each buffer is numReservedCols * number of inequalities (or equalities). The reserved size is numReservedCols * numReservedInequalities (or numReservedEqualities). A coefficient (r, c) lives at the location numReservedCols * r + c in the buffer. The extra space between getNumCols() and numReservedCols exists to prevent frequent movement of data when adding columns, especially at the end.
The identifiers x_0, x_1, ... appear in the order: dimensional identifiers, symbolic identifiers, and local identifiers. The local identifiers correspond to local/internal variables created when converting from AffineExpr's containing mod's and div's; they are thus needed to increase representational power. Each local identifier is always (by construction) a floordiv of a pure add/mul affine function of dimensional, symbolic, and other local identifiers, in a non-mutually recursive way. Hence, every local identifier can ultimately always be recovered as an affine function of dimensional and symbolic identifiers (involving floordiv's); note however that some floordiv combinations are converted to mod's by AffineExpr construction.
Definition at line 59 of file AffineStructures.h.
Member Enumeration Documentation
BoundType
enum mlir::FlatAffineConstraints::BoundType
The type of bound: equal, lower bound or upper bound.
Enumerator
EQ
LB
UB
Definition at line 216 of file AffineStructures.h.
IdKind
enum mlir::FlatAffineConstraints::IdKind
Kind of identifier (column).
Enumerator
Dimension
Symbol
Local
Definition at line 65 of file AffineStructures.h.
Kind
enum mlir::FlatAffineConstraints::Kind strong
All derived classes of FlatAffineConstraints.
Enumerator
FlatAffineConstraints
FlatAffineValueConstraints
Definition at line 62 of file AffineStructures.h.
Constructor & Destructor Documentation
FlatAffineConstraints() [1/4]
mlir::FlatAffineConstraints::FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals) inline
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
Definition at line 69 of file AffineStructures.h.
References numIds.
Referenced by getSliceBounds(), and reset().
FlatAffineConstraints() [2/4]
mlir::FlatAffineConstraints::FlatAffineConstraints (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Constructs a constraint system with the specified number of dimensions and symbols.
Definition at line 82 of file AffineStructures.h.
FlatAffineConstraints() [3/4]
FlatAffineConstraints::FlatAffineConstraints (IntegerSet set) explicit
Creates an affine constraint system from an IntegerSet.
Definition at line 159 of file AffineStructures.cpp.
References addEquality(), addInequality(), append(), appendLocalId(), mlir::failed(), mlir::getFlattenedAffineExprs(), getNumCols(), and getNumLocalIds().
FlatAffineConstraints() [4/4]
mlir::FlatAffineConstraints::FlatAffineConstraints (const MutableAffineMap & map)
~FlatAffineConstraints()
virtual mlir::FlatAffineConstraints::~FlatAffineConstraints () virtual default
Referenced by getUniverse().
Member Function Documentation
addBound() [1/3]
LogicalResult FlatAffineConstraints::addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
In case of an EQ bound, the bound map is expected to have exactly one result. In case of a LB/UB, the bound map may have more than one result, for each of which an inequality is added. Note: The dimensions/symbols of this FlatAffineConstraints must match the dimensions/symbols of the affine map.
Definition at line 2376 of file AffineStructures.cpp.
References addEquality(), addInequality(), mlir::failed(), mlir::failure(), flattenAlignedMapAndMergeLocals(), getNumCols(), getNumDimAndSymbolIds(), getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), and mlir::success().
Referenced by mlir::FlatAffineValueConstraints::classof(), mlir::getMemRefSizeInBytes(), and mlir::normalizeMemRefType().
addBound() [2/3]
void FlatAffineConstraints::addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
Definition at line 2533 of file AffineStructures.cpp.
References mlir::Matrix::appendExtraRow(), equalities, getNumCols(), inequalities, and value.
addBound() [3/3]
void FlatAffineConstraints::addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
Definition at line 2548 of file AffineStructures.cpp.
References mlir::Matrix::appendExtraRow(), getNumCols(), mlir::Matrix::getNumRows(), and inequalities.
addEquality()
void FlatAffineConstraints::addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
Definition at line 2519 of file AffineStructures.cpp.
References mlir::Matrix::appendExtraRow(), equalities, and getNumCols().
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain(), addBound(), addOrderingConstraints(), append(), composeMatchingMap(), computeDirectionVector(), FlatAffineConstraints(), getCommonConstraints(), and mlir::getRelationFromMap().
addInequality()
void FlatAffineConstraints::addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
Definition at line 2526 of file AffineStructures.cpp.
References mlir::Matrix::appendExtraRow(), getNumCols(), and inequalities.
Referenced by addBound(), addLocalFloorDiv(), addOrderingConstraints(), append(), canonicalizeMinMaxOp(), mlir::scf::canonicalizeMinMaxOpInLoop(), FlatAffineConstraints(), getCommonConstraints(), mlir::scf::rewritePeeledMinMaxOp(), and subtractRecursively().
addLocalFloorDiv()
void FlatAffineConstraints::addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in 'dividend' and with respect to a positive constant 'divisor'.
Two constraints are added to the system to capture equivalence with the floordiv: q = dividend floordiv c <=> c*q <= dividend <= c*q + c - 1.
Two constraints are added to the system to capture equivalence with the floordiv. q = expr floordiv c <=> c*q <= expr <= c*q + c - 1.
Definition at line 2564 of file AffineStructures.cpp.
References addInequality(), appendLocalId(), copy(), getNumCols(), and getNumIds().
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain().
append()
void FlatAffineConstraints::append (const FlatAffineConstraints & other)
Appends constraints from other into this.
This is equivalent to an intersection with no simplification of any sort attempted.
Definition at line 286 of file AffineStructures.cpp.
References addEquality(), addInequality(), equalities, getEquality(), getInequality(), getNumCols(), getNumDimIds(), getNumEqualities(), getNumInequalities(), mlir::Matrix::getNumRows(), getNumSymbolIds(), inequalities, and mlir::Matrix::reserveRows().
Referenced by mlir::FlatAffineValueConstraints::addAffineIfOpDomain(), classof(), mlir::FlatAffineRelation::compose(), FlatAffineConstraints(), flattenAlignedMapAndMergeLocals(), mlir::MemRefAccess::getAccessRelation(), and mlir::PresburgerSet::intersect().
appendDimId()
unsigned FlatAffineConstraints::appendDimId (unsigned num = 1)
Append num identifiers of the specified kind after the last identifier.
of that kind. Return the position of the first appended column. The coefficient columns corresponding to the added identifiers are initialized to zero.
Definition at line 303 of file AffineStructures.cpp.
References getNumDimIds(), and mlir::FlatAffineValueConstraints::insertId().
Referenced by mlir::getRelationFromMap().
appendLocalId()
unsigned FlatAffineConstraints::appendLocalId (unsigned num = 1)
Definition at line 327 of file AffineStructures.cpp.
References getNumLocalIds(), and mlir::FlatAffineValueConstraints::insertId().
Referenced by addLocalFloorDiv(), convertDimToLocal(), FlatAffineConstraints(), and flattenAlignedMapAndMergeLocals().
appendSymbolId()
unsigned FlatAffineConstraints::appendSymbolId (unsigned num = 1)
Definition at line 315 of file AffineStructures.cpp.
References getNumSymbolIds(), and mlir::FlatAffineValueConstraints::insertId().
assertAtMostNumIdKind()
void FlatAffineConstraints::assertAtMostNumIdKind (unsigned value, IdKind kind) const protected
Assert that value is at most the number of ids of the specified kind.
Definition at line 372 of file AffineStructures.cpp.
Referenced by getNumLocalIds().
atEq() [1/2]
int64_t mlir::FlatAffineConstraints::atEq (unsigned i, unsigned j) const inline
Returns the value at the specified equality row and column.
Definition at line 181 of file AffineStructures.h.
References equalities.
Referenced by computeConstantLowerOrUpperBound(), constantFoldId(), detectAsMod(), eliminateFromConstraint(), eliminateRedundantLocalId(), eqInvolvesSuffixDims(), findConstraintWithNonZeroAt(), findEqualityToConstant(), fourierMotzkinEliminate(), getBoundedDirections(), getConstantBoundOnDimSize(), getIndependentConstraints(), getLowerAndUpperBoundIndices(), getSliceBounds(), hasInvalidConstraint(), isEmptyByGCDTest(), isHyperRectangular(), normalizeConstraintByGCD(), print(), removeRedundantConstraints(), removeRedundantLocalVars(), setAndEliminate(), and swapId().
atEq() [2/2]
int64_t& mlir::FlatAffineConstraints::atEq (unsigned i, unsigned j) inline
Definition at line 182 of file AffineStructures.h.
References equalities.
atIneq() [1/2]
int64_t mlir::FlatAffineConstraints::atIneq (unsigned i, unsigned j) const inline
Returns the value at the specified inequality row and column.
Definition at line 185 of file AffineStructures.h.
References inequalities.
Referenced by computeConstantLowerOrUpperBound(), createSeparationCondition(), eliminateFromConstraint(), eliminateRedundantLocalId(), fillInequality(), findConstraintWithNonZeroAt(), findIntegerSample(), fourierMotzkinEliminate(), gcdTightenInequalities(), getBestIdToEliminate(), getBoundedDirections(), getConstantBoundOnDimSize(), getDivRepr(), getIndependentConstraints(), getLowerAndUpperBoundIndices(), hasInvalidConstraint(), ineqInvolvesSuffixDims(), isHyperRectangular(), negateInequality(), normalizeConstraintByGCD(), print(), removeRedundantConstraints(), removeRedundantInequalities(), removeTrivialRedundancy(), setAndEliminate(), and swapId().
atIneq() [2/2]
int64_t& mlir::FlatAffineConstraints::atIneq (unsigned i, unsigned j) inline
Definition at line 188 of file AffineStructures.h.
References inequalities.
classof()
static bool mlir::FlatAffineConstraints::classof (const FlatAffineConstraints * cst) inline static
Definition at line 107 of file AffineStructures.h.
References append(), clone(), containsPoint(), findIntegerSample(), getBoundedDirections(), getLocalReprs(), isEmpty(), isEmptyByGCDTest(), isIntegerEmpty(), numDims, numSymbols, and reset().
clearAndCopyFrom()
void FlatAffineConstraints::clearAndCopyFrom (const FlatAffineConstraints & other) virtual
Replaces the contents of this FlatAffineConstraints with other.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 3067 of file AffineStructures.cpp.
Referenced by getFlattenedAffineExprs(), and getNumLocalIds().
clearConstraints()
void FlatAffineConstraints::clearConstraints ()
Removes all equalities and inequalities.
Definition at line 3374 of file AffineStructures.cpp.
References equalities, inequalities, and mlir::Matrix::resizeVertically().
Referenced by getNumLocalIds().
clone()
std::unique_ptr< FlatAffineConstraints > FlatAffineConstraints::clone () const
Definition at line 149 of file AffineStructures.cpp.
Referenced by classof(), and mlir::FlatAffineValueConstraints::classof().
composeMatchingMap()
LogicalResult FlatAffineConstraints::composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
The results of the map other are added as the leading dimensions of this constraint system. Returns failure if other is a semi-affine map.
Definition at line 564 of file AffineStructures.cpp.
References addEquality(), mlir::failed(), mlir::failure(), flattenAlignedMapAndMergeLocals(), getNumCols(), getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), mlir::FlatAffineValueConstraints::insertDimId(), and mlir::success().
Referenced by mlir::FlatAffineValueConstraints::composeMap(), and mlir::normalizeMemRefType().
computeConstantLowerOrUpperBound()
template<bool isLower> Optional< int64_t > FlatAffineConstraints::computeConstantLowerOrUpperBound (unsigned pos) protected
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
Definition at line 2871 of file AffineStructures.cpp.
References atEq(), atIneq(), mlir::ceilDiv(), findEqualityToConstant(), mlir::floorDiv(), getNumCols(), getNumIds(), getNumInequalities(), and mlir::FlatAffineValueConstraints::projectOut().
Referenced by getConstantBound(), and getNumLocalIds().
constantFoldId()
LogicalResult FlatAffineConstraints::constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
Definition at line 2709 of file AffineStructures.cpp.
References atEq(), mlir::failure(), findEqualityToConstant(), getNumCols(), getNumIds(), setAndEliminate(), and mlir::success().
Referenced by constantFoldIdRange(), and projectOut().
constantFoldIdRange()
void FlatAffineConstraints::constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
Definition at line 2722 of file AffineStructures.cpp.
References constantFoldId(), and mlir::failed().
Referenced by projectOut().
containsPoint()
bool FlatAffineConstraints::containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
A point satisfies an equality iff the value of the equality at the expression is zero, and it satisfies an inequality iff the value of the inequality at that point is non-negative.
Definition at line 1343 of file AffineStructures.cpp.
References getEquality(), getInequality(), getNumEqualities(), getNumInequalities(), and valueAt().
Referenced by classof(), and findIntegerSample().
convertDimToLocal()
void FlatAffineConstraints::convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
Definition at line 2073 of file AffineStructures.cpp.
References appendLocalId(), getNumDimIds(), getNumIds(), mlir::FlatAffineValueConstraints::removeIdRange(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::FlatAffineRelation::compose(), mlir::FlatAffineRelation::getDomainSet(), getNumLocalIds(), and mlir::FlatAffineRelation::getRangeSet().
dump()
void FlatAffineConstraints::dump () const
Definition at line 2994 of file AffineStructures.cpp.
References print().
Referenced by mlir::checkMemrefAccessDependence(), fourierMotzkinEliminate(), getAsIntegerSet(), getNumLocalIds(), getSliceBounds(), and mlir::ComputationSliceState::isSliceValid().
findIntegerSample()
Optional< SmallVector< int64_t, 8 > > FlatAffineConstraints::findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Let this set be S.
Returns an integer sample point if one exists, or an empty Optional otherwise.
If S is bounded then we directly call into the GBR sampling algorithm. Otherwise, there are some unbounded directions, i.e., vectors v such that S extends to infinity along v or -v. In this case we use an algorithm described in the integer set library (isl) manual and used by the isl_set_sample function in that library. The algorithm is:
1) Apply a unimodular transform T to S to obtain S*T, such that all dimensions in which S*T is bounded lie in the linear span of a prefix of the dimensions.
2) Construct a set B by removing all constraints that involve the unbounded dimensions and then deleting the unbounded dimensions. Note that B is a Bounded set.
3) Try to obtain a sample from B using the GBR sampling algorithm. If no sample is found, return that S is empty.
4) Otherwise, substitute the obtained sample into S*T to obtain a set C. C is a full-dimensional Cone and always contains a sample.
5) Obtain an integer sample from C.
6) Return T*v, where v is the concatenation of the samples from B and C.
The following is a sketch of a proof that a) If the algorithm returns empty, then S is empty. b) If the algorithm returns a sample, it is a valid sample in S.
The algorithm returns empty only if B is empty, in which case S*T is certainly empty since B was obtained by removing constraints and then deleting unconstrained dimensions from S*T. Since T is unimodular, a vector v is in S*T iff T*v is in S. So in this case, since S*T is empty, S is empty too.
Otherwise, the algorithm substitutes the sample from B into S*T. All the constraints of S*T that did not involve unbounded dimensions are satisfied by this substitution. All dimensions in the linear span of the dimensions outside the prefix are unbounded in S*T (step 1). Substituting values for the bounded dimensions cannot make these dimensions bounded, and these are the only remaining dimensions in C, so C is unbounded along every vector (in the positive or negative direction, or both). C is hence a full-dimensional cone and therefore always contains an integer point.
Concatenating the samples from B and C gives a sample v in S*T, so the returned sample T*v is a sample in S.
Definition at line 1228 of file AffineStructures.cpp.
References mlir::LinearTransform::applyTo(), atIneq(), mlir::ceil(), containsPoint(), mlir::Simplex::findIntegerSample(), getBoundedDirections(), getNumIds(), getNumInequalities(), mlir::Simplex::getRationalSample(), mlir::Simplex::isEmpty(), isEmptyByGCDTest(), mlir::Simplex::isUnbounded(), mlir::LinearTransform::makeTransformToColumnEchelon(), numIds, mlir::LinearTransform::preMultiplyColumn(), removeConstraintsInvolvingSuffixDims(), removeIdRange(), and setAndEliminate().
Referenced by classof(), mlir::PresburgerSet::findIntegerSample(), and isIntegerEmpty().
flattenAlignedMapAndMergeLocals()
LogicalResult FlatAffineConstraints::flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs) protected
Given an affine map that is aligned with this constraint system:
Flatten the map.
Add newly introduced local columns at the beginning of this constraint system (local column pos 0).
Add equalities that define the new local columns to this constraint system.
Return the flattened expressions via flattenedExprs.
Note: This is a shared helper function of addLowerOrUpperBound and composeMatchingMap.
Definition at line 2352 of file AffineStructures.cpp.
References append(), appendLocalId(), mlir::failed(), mlir::failure(), mlir::getFlattenedAffineExprs(), getNumLocalIds(), insertLocalId(), and mlir::success().
Referenced by addBound(), composeMatchingMap(), and getNumLocalIds().
fourierMotzkinEliminate()
void FlatAffineConstraints::fourierMotzkinEliminate (unsigned pos, bool darkShadow = false, bool * isResultIntegerExact = nullptr) protected virtual
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
If the result of the elimination is integer exact, *isResultIntegerExact is set to true. If darkShadow is set to true, a potential under approximation (subset) of the rational shadow / exact integer shadow is computed.
Create the new system which has one identifier less.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 3157 of file AffineStructures.cpp.
References atEq(), atIneq(), mlir::FlatAffineValueConstraints::clearAndCopyFrom(), dump(), gaussianEliminateId(), gcdTightenInequalities(), getNewNumDimsSymbols(), getNumCols(), getNumEqualities(), getNumIds(), getNumInequalities(), mlir::FlatAffineValueConstraints::hasConsistentState(), mlir::lcm(), removeId(), and mlir::succeeded().
Referenced by mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), gaussianEliminateId(), isEmpty(), and mlir::FlatAffineValueConstraints::setValues().
gaussianEliminateId()
LogicalResult mlir::FlatAffineConstraints::gaussianEliminateId (unsigned position) inline protected
Eliminates a single identifier at position from equality and inequality constraints.
Returns success if the identifier was eliminated, and failure otherwise.
Definition at line 501 of file AffineStructures.h.
References fourierMotzkinEliminate(), gaussianEliminateIds(), gcdTightenInequalities(), normalizeConstraintsByGCD(), removeIdRange(), removeRedundantLocalVars(), and mlir::success().
Referenced by fourierMotzkinEliminate().
gaussianEliminateIds()
unsigned FlatAffineConstraints::gaussianEliminateIds (unsigned posStart, unsigned posLimit) protected
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
Returns the number of variables eliminated.
Definition at line 1556 of file AffineStructures.cpp.
References eliminateFromConstraint(), findConstraintWithNonZeroAt(), gcdTightenInequalities(), getNumEqualities(), getNumInequalities(), mlir::FlatAffineValueConstraints::hasConsistentState(), normalizeConstraintByGCD(), numIds, removeEquality(), and mlir::FlatAffineValueConstraints::removeIdRange().
Referenced by gaussianEliminateId(), isEmpty(), and projectOut().
gcdTightenInequalities()
void FlatAffineConstraints::gcdTightenInequalities () protected
Tightens inequalities given that we are dealing with integer spaces.
This is similar to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method (linear in the number of coefficients).
This is analogous to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method - linear in the number of coefficients.
Definition at line 1537 of file AffineStructures.cpp.
References atIneq(), mlir::floorDiv(), getNumCols(), and getNumInequalities().
Referenced by fourierMotzkinEliminate(), gaussianEliminateId(), gaussianEliminateIds(), projectOut(), removeRedundantConstraints(), and removeTrivialRedundancy().
getAsIntegerSet()
IntegerSet FlatAffineConstraints::getAsIntegerSet (MLIRContext * context) const
Returns the constraint system as an integer set.
Returns a null integer set if the system has no constraints, or if an integer set couldn't be constructed as a result of a local variable's explicit representation not being known and such a local variable appearing in any of the constraints.
Definition at line 3646 of file AffineStructures.cpp.
References computeLocalVars(), dump(), mlir::failed(), mlir::IntegerSet::get(), mlir::getAffineConstantExpr(), mlir::getAffineExprFromFlatForm(), getEquality(), getInequality(), getNumConstraints(), getNumDimAndSymbolIds(), getNumDimIds(), getNumEqualities(), getNumIds(), getNumInequalities(), getNumLocalIds(), getNumSymbolIds(), isColZero(), and numDims.
Referenced by createSeparationCondition(), and mlir::simplifyIntegerSet().
getBoundedDirections()
Matrix FlatAffineConstraints::getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
The span of the returned vectors is guaranteed to contain all such vectors. The returned vectors are NOT guaranteed to be linearly independent. This function should not be called on empty sets.
Definition at line 1110 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), mlir::Simplex::isBoundedAlongConstraint(), and mlir::Simplex::isEmpty().
Referenced by classof(), and findIntegerSample().
getConstantBound()
Optional< int64_t > FlatAffineConstraints::getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
Definition at line 2927 of file AffineStructures.cpp.
References computeConstantLowerOrUpperBound().
Referenced by computeDirectionVector(), detectAsMod(), getNumLocalIds(), getSliceBounds(), and mlir::normalizeMemRefType().
getConstantBoundOnDimSize()
Optional< int64_t > FlatAffineConstraints::getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > * lb = nullptr, int64_t * boundFloorDivisor = nullptr, SmallVectorImpl< int64_t > * ub = nullptr, unsigned * minLbPos = nullptr, unsigned * minUbPos = nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Returns a non-negative constant bound on the extent (upper bound - lower bound) of the specified identifier if it is found to be a constant; returns None if it's not a constant.
This constant bound is guaranteed to be non-negative. Returns None if it's not a constant. This method employs trivial (low complexity / cost) checks and detection. Symbolic identifiers are treated specially, i.e., it looks for constant differences between affine expressions involving only the symbolic identifiers. lb and ub (along with the boundFloorDivisor) are set to represent the lower and upper bound associated with the constant difference: lb, ub have the coefficients, and boundFloorDivisor, their divisor. minLbPos and minUbPos if non-null are set to the position of the constant lower bound and upper bound respectively (to the same if they are from an equality). Ex: if the lower bound is [(s0 + s2 - 1) floordiv 32] for a system with three symbolic identifiers, *lb = [1, 0, 1], lbDivisor = 32. See comments at function definition for examples.
This methods treats symbolic identifiers specially, i.e., it looks for constant differences between affine expressions involving only the symbolic identifiers. See comments at function definition for example. 'lb', if provided, is set to the lower bound associated with the constant difference. Note that 'lb' is purely symbolic and thus will contain the coefficients of the symbolic identifiers and the constant coefficient.
Definition at line 2743 of file AffineStructures.cpp.
References atEq(), atIneq(), mlir::ceilDiv(), findEqualityToConstant(), getEquality(), getLowerAndUpperBoundIndices(), getNumCols(), getNumDimAndSymbolIds(), getNumDimIds(), getNumInequalities(), and getNumSymbolIds().
Referenced by createFullTiles(), createSeparationCondition(), getNumLocalIds(), and unionBoundingBox().
getEquality()
ArrayRef<int64_t> mlir::FlatAffineConstraints::getEquality (unsigned idx) const inline
Definition at line 207 of file AffineStructures.h.
References equalities, and mlir::Matrix::getRow().
Referenced by append(), mlir::LinearTransform::applyTo(), containsPoint(), getAsIntegerSet(), getCommonConstraints(), getConstantBoundOnDimSize(), getLowerAndUpperBound(), getLowerAndUpperBoundIndices(), mlir::Simplex::intersectFlatAffineConstraints(), mlir::Simplex::Simplex(), and subtractRecursively().
getIdKindOffset()
unsigned FlatAffineConstraints::getIdKindOffset (IdKind kind) const protected
Return the index at which the specified kind of id starts.
Definition at line 384 of file AffineStructures.cpp.
Referenced by getNumLocalIds(), and mergeLocalIds().
getInequality()
ArrayRef<int64_t> mlir::FlatAffineConstraints::getInequality (unsigned idx) const inline
Definition at line 211 of file AffineStructures.h.
References mlir::Matrix::getRow(), and inequalities.
Referenced by append(), mlir::LinearTransform::applyTo(), containsPoint(), createSeparationCondition(), getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLowerAndUpperBound(), getLowerAndUpperBoundIndices(), mlir::Simplex::intersectFlatAffineConstraints(), mlir::Simplex::Simplex(), and subtractRecursively().
getKind()
virtual Kind mlir::FlatAffineConstraints::getKind () const inline virtual
Return the kind of this FlatAffineConstraints.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 105 of file AffineStructures.h.
References FlatAffineConstraints.
Referenced by mlir::FlatAffineValueConstraints::classof().
getLocalReprs() [1/3]
void FlatAffineConstraints::getLocalReprs (std::vector< SmallVector< int64_t, 8 >> & dividends, SmallVector< unsigned, 4 > & denominators, std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> & repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
The pairs are stored as indices of upperbound, lowerbound inequalities. If no such pair can be found, it is stored as llvm::None.
The dividends of the explicit representations are stored in dividends and the denominators in denominators. If no explicit representation could be found for the i^th local identifier, denominators[i] is set to 0.
Definition at line 1491 of file AffineStructures.cpp.
References getNumDimAndSymbolIds(), getNumIds(), and getNumLocalIds().
Referenced by classof(), getLocalReprs(), mergeLocalIds(), and subtractRecursively().
getLocalReprs() [2/3]
void FlatAffineConstraints::getLocalReprs (std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> & repr) const
Definition at line 1476 of file AffineStructures.cpp.
References getLocalReprs(), and getNumLocalIds().
getLocalReprs() [3/3]
void FlatAffineConstraints::getLocalReprs (std::vector< SmallVector< int64_t, 8 >> & dividends, SmallVector< unsigned, 4 > & denominators) const
Definition at line 1483 of file AffineStructures.cpp.
References getLocalReprs(), and getNumLocalIds().
getLowerAndUpperBound()
std::pair< AffineMap, AffineMap > FlatAffineConstraints::getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext * context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
The multi-dimensional maps in the returned pair represent the max and min of potentially multiple affine expressions. The upper bound is exclusive. localExprs holds pre-computed AffineExpr's for all local identifiers in the system.
Add to 'b' from 'a' in set [0, offset) U [offset + num, symbStartPos).
Definition at line 2093 of file AffineStructures.cpp.
References mlir::floorDiv(), mlir::AffineMap::get(), mlir::getAffineExprFromFlatForm(), getEquality(), getInequality(), getLowerAndUpperBoundIndices(), getNumDimAndSymbolIds(), getNumDimIds(), and getNumLocalIds().
Referenced by getNumLocalIds().
getLowerAndUpperBoundIndices()
void FlatAffineConstraints::getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > * lbIndices, SmallVectorImpl< unsigned > * ubIndices, SmallVectorImpl< unsigned > * eqIndices = nullptr, unsigned offset = 0, unsigned num = 0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
Gather all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
In addition, the bounds are to be independent of identifiers in position range [offset, offset + num).
Definition at line 1733 of file AffineStructures.cpp.
References atEq(), atIneq(), getEquality(), getInequality(), getNumCols(), getNumEqualities(), getNumIds(), and getNumInequalities().
Referenced by computeSingleVarRepr(), createSeparationCondition(), getConstantBoundOnDimSize(), getLowerAndUpperBound(), and getNumLocalIds().
getNumCols()
unsigned mlir::FlatAffineConstraints::getNumCols () const inline
Returns the number of columns in the constraint system.
Definition at line 191 of file AffineStructures.h.
References numIds.
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain(), addBound(), addEquality(), addInequality(), addLocalFloorDiv(), addOrderingConstraints(), append(), canonicalizeMinMaxOp(), mlir::scf::canonicalizeMinMaxOpInLoop(), composeMatchingMap(), computeConstantLowerOrUpperBound(), computeDirectionVector(), constantFoldId(), createSeparationCondition(), detectAsMod(), eliminateFromConstraint(), fillInequality(), findConstraintWithNonZeroAt(), FlatAffineConstraints(), fourierMotzkinEliminate(), gcdTightenInequalities(), generateCopy(), getBoundedDirections(), getConstantBoundOnDimSize(), getDivRepr(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLowerAndUpperBoundIndices(), mlir::getRelationFromMap(), hasInvalidConstraint(), isEmptyByGCDTest(), isHyperRectangular(), negateInequality(), normalizeConstraintByGCD(), print(), projectOut(), removeIdRange(), removeRedundantConstraints(), removeRedundantInequalities(), removeTrivialRedundancy(), setAndEliminate(), and unionBoundingBox().
getNumConstraints()
unsigned mlir::FlatAffineConstraints::getNumConstraints () const inline
Definition at line 350 of file AffineStructures.h.
References getNumEqualities(), and getNumInequalities().
Referenced by getAsIntegerSet(), isEmpty(), and print().
getNumDimAndSymbolIds()
unsigned mlir::FlatAffineConstraints::getNumDimAndSymbolIds () const inline
Definition at line 356 of file AffineStructures.h.
References numSymbols.
Referenced by addBound(), mlir::computeSliceUnion(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), createFullTiles(), createSeparationCondition(), detectAsMod(), eliminateRedundantLocalId(), getAsIntegerSet(), mlir::getComputationSliceState(), getConstantBoundOnDimSize(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), getLowerAndUpperBound(), mlir::getRelationFromMap(), getSliceBounds(), mergeAndAlignIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), removeRedundantLocalVars(), and turnSymbolIntoDim().
getNumDimIds()
unsigned mlir::FlatAffineConstraints::getNumDimIds () const inline
Definition at line 354 of file AffineStructures.h.
References numDims.
Referenced by addBound(), mlir::FlatAffineValueConstraints::addDomainFromSliceMaps(), addMissingLoopIVBounds(), addOrderingConstraints(), append(), appendDimId(), mlir::FlatAffineValueConstraints::appendDimId(), mlir::FlatAffineRelation::appendRangeId(), areIdsAligned(), assertDimensionsCompatible(), mlir::scf::canonicalizeMinMaxOpInLoop(), composeMatchingMap(), computeDirectionVector(), computeLocalVars(), mlir::computeSliceUnion(), convertDimToLocal(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), detectAsMod(), findEqualityToConstant(), generateCopy(), mlir::MemRefAccess::getAccessRelation(), getAsIntegerSet(), getCommonConstraints(), getConstantBoundOnDimSize(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLowerAndUpperBound(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeDimValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), getNumCommonLoops(), mlir::getRelationFromMap(), getSliceBounds(), mlir::linalg::getUpperBoundForIndex(), mlir::ComputationSliceState::isMaximal(), mergeAndAlignIds(), mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), print(), mlir::FlatAffineRelation::removeIdRange(), subtractRecursively(), turnSymbolIntoDim(), unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
getNumEqualities()
unsigned mlir::FlatAffineConstraints::getNumEqualities () const inline
Definition at line 193 of file AffineStructures.h.
References equalities, and mlir::Matrix::getNumRows().
Referenced by append(), mlir::LinearTransform::applyTo(), containsPoint(), detectAsMod(), eliminateRedundantLocalId(), findConstraintWithNonZeroAt(), findEqualityToConstant(), fourierMotzkinEliminate(), gaussianEliminateIds(), getAsIntegerSet(), getBoundedDirections(), getCommonConstraints(), getIndependentConstraints(), getLowerAndUpperBoundIndices(), getNumConstraints(), hasInvalidConstraint(), mlir::Simplex::intersectFlatAffineConstraints(), isEmptyByGCDTest(), isHyperRectangular(), normalizeConstraintsByGCD(), print(), removeConstraintsInvolvingSuffixDims(), removeRedundantConstraints(), removeRedundantLocalVars(), setAndEliminate(), mlir::Simplex::Simplex(), subtractRecursively(), and swapId().
getNumIds()
unsigned mlir::FlatAffineConstraints::getNumIds () const inline
Definition at line 353 of file AffineStructures.h.
References numIds.
Referenced by addLocalFloorDiv(), mlir::LinearTransform::applyTo(), areIdsAligned(), areIdsUnique(), computeConstantLowerOrUpperBound(), computeDirectionVector(), computeSingleVarRepr(), constantFoldId(), convertDimToLocal(), detectAsFloorDiv(), detectAsMod(), eqInvolvesSuffixDims(), findEqualityToConstant(), findIntegerSample(), fourierMotzkinEliminate(), mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), generateCopy(), getAsIntegerSet(), getBestIdToEliminate(), getDivRepr(), getIndependentConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), getLowerAndUpperBoundIndices(), getSliceBounds(), mlir::FlatAffineValueConstraints::hasConsistentState(), ineqInvolvesSuffixDims(), mlir::Simplex::intersectFlatAffineConstraints(), isEmpty(), mlir::ComputationSliceState::isSliceValid(), mlir::normalizeMemRefType(), print(), projectOut(), removeIndependentConstraints(), removeRedundantLocalVars(), setAndEliminate(), and swapId().
getNumInequalities()
unsigned mlir::FlatAffineConstraints::getNumInequalities () const inline
Definition at line 195 of file AffineStructures.h.
References mlir::Matrix::getNumRows(), and inequalities.
Referenced by append(), mlir::LinearTransform::applyTo(), computeConstantLowerOrUpperBound(), containsPoint(), eliminateRedundantLocalId(), findConstraintWithNonZeroAt(), findIntegerSample(), fourierMotzkinEliminate(), gaussianEliminateIds(), gcdTightenInequalities(), getAsIntegerSet(), getBestIdToEliminate(), getBoundedDirections(), getCommonConstraints(), getConstantBoundOnDimSize(), getDivRepr(), getIndependentConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLowerAndUpperBoundIndices(), getNumConstraints(), hasInvalidConstraint(), mlir::Simplex::intersectFlatAffineConstraints(), isHyperRectangular(), normalizeConstraintsByGCD(), print(), removeConstraintsInvolvingSuffixDims(), removeRedundantConstraints(), removeRedundantInequalities(), removeRedundantLocalVars(), removeTrivialRedundancy(), setAndEliminate(), mlir::Simplex::Simplex(), subtractRecursively(), and swapId().
getNumLocalIds()
unsigned mlir::FlatAffineConstraints::getNumLocalIds () const inline
Definition at line 357 of file AffineStructures.h.
References assertAtMostNumIdKind(), clearAndCopyFrom(), clearConstraints(), computeConstantLowerOrUpperBound(), convertDimToLocal(), dump(), flattenAlignedMapAndMergeLocals(), getConstantBound(), getConstantBoundOnDimSize(), getIdKindOffset(), getLowerAndUpperBound(), getLowerAndUpperBoundIndices(), hasConsistentState(), hasInvalidConstraint(), isHyperRectangular(), mergeLocalIds(), numIds, numSymbols, print(), removeIndependentConstraints(), removeRedundantConstraints(), removeRedundantInequalities(), and removeTrivialRedundancy().
Referenced by appendLocalId(), computeLocalVars(), mlir::computeSliceUnion(), eliminateRedundantLocalId(), FlatAffineConstraints(), flattenAlignedMapAndMergeLocals(), getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getLocalReprs(), getLowerAndUpperBound(), getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), mergeLocalIds(), mlir::normalizeMemRefType(), print(), removeIdRange(), subtractRecursively(), unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
getNumReservedEqualities()
unsigned mlir::FlatAffineConstraints::getNumReservedEqualities () const inline
Definition at line 199 of file AffineStructures.h.
References equalities, and mlir::Matrix::getNumReservedRows().
getNumReservedInequalities()
unsigned mlir::FlatAffineConstraints::getNumReservedInequalities () const inline
Definition at line 203 of file AffineStructures.h.
References mlir::Matrix::getNumReservedRows(), and inequalities.
getNumSymbolIds()
unsigned mlir::FlatAffineConstraints::getNumSymbolIds () const inline
Definition at line 355 of file AffineStructures.h.
References numSymbols.
Referenced by addBound(), append(), appendSymbolId(), mlir::FlatAffineValueConstraints::appendSymbolId(), areIdsAligned(), assertDimensionsCompatible(), mlir::scf::canonicalizeMinMaxOpInLoop(), composeMatchingMap(), computeLocalVars(), detectAsMod(), generateCopy(), getAsIntegerSet(), getCommonConstraints(), getConstantBoundOnDimSize(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), print(), subtractRecursively(), turnSymbolIntoDim(), and unionBoundingBox().
getSliceBounds()
void FlatAffineConstraints::getSliceBounds (unsigned offset, unsigned num, MLIRContext * context, SmallVectorImpl< AffineMap > * lbMaps, SmallVectorImpl< AffineMap > * ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
Computes the lower and upper bounds of the first 'num' dimensional identifiers (starting at 'offset') as affine maps of the remaining identifiers (dimensional and symbolic identifiers).
This method is able to detect identifiers as floordiv's and mod's of affine expressions of other identifiers with respect to (positive) constants. Sets bound map to a null AffineMap if such a bound can't be found (or yet unimplemented).
Local identifiers are themselves explicitly computed as affine functions of other identifiers in this process if needed.
Definition at line 2181 of file AffineStructures.cpp.
References atEq(), detectAsFloorDiv(), detectAsMod(), mlir::AffineMap::dump(), dump(), findConstraintWithNonZeroAt(), FlatAffineConstraints(), mlir::floorDiv(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), getConstantBound(), getNumDimAndSymbolIds(), getNumDimIds(), getNumIds(), getNumLocalIds(), mlir::AffineMap::getNumResults(), getNumSymbolIds(), normalizeConstraintsByGCD(), and mlir::simplifyAffineExpr().
Referenced by canonicalizeMinMaxOp(), mlir::computeSliceUnion(), mlir::getComputationSliceState(), and mlir::linalg::getUpperBoundForIndex().
getUniverse()
static FlatAffineConstraints mlir::FlatAffineConstraints::getUniverse (unsigned numDims = 0, unsigned numSymbols = 0) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 92 of file AffineStructures.h.
References FlatAffineConstraints, numDims, numSymbols, and ~FlatAffineConstraints().
Referenced by mlir::PresburgerSet::complement(), and mlir::PresburgerSet::getUniverse().
hasConsistentState()
bool FlatAffineConstraints::hasConsistentState () const protected virtual
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
This is meant to be used within an assert internally.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 864 of file AffineStructures.cpp.
References equalities, mlir::Matrix::hasConsistentState(), inequalities, numDims, numIds, and numSymbols.
Referenced by getNumLocalIds(), mlir::FlatAffineValueConstraints::hasConsistentState(), and mlir::FlatAffineValueConstraints::setValues().
hasInvalidConstraint()
bool FlatAffineConstraints::hasInvalidConstraint () const protected
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
Returns true if an invalid constraint is found; false otherwise.
Definition at line 882 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumInequalities(), and mlir::FlatAffineValueConstraints::hasConsistentState().
Referenced by getNumLocalIds(), and isEmpty().
insertDimId()
unsigned FlatAffineConstraints::insertDimId (unsigned pos, unsigned num = 1)
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. The coefficient columns corresponding to the added identifiers are initialized to zero. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Definition at line 333 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertId().
Referenced by mlir::FlatAffineValueConstraints::classof().
insertId()
unsigned FlatAffineConstraints::insertId (IdKind kind, unsigned pos, unsigned num = 1) virtual
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 355 of file AffineStructures.cpp.
Referenced by mlir::FlatAffineValueConstraints::classof().
insertLocalId()
unsigned FlatAffineConstraints::insertLocalId (unsigned pos, unsigned num = 1)
Definition at line 351 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertId().
Referenced by flattenAlignedMapAndMergeLocals(), and mergeLocalIds().
insertSymbolId()
unsigned FlatAffineConstraints::insertSymbolId (unsigned pos, unsigned num = 1)
Definition at line 342 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertId().
Referenced by mlir::FlatAffineValueConstraints::classof().
isEmpty()
bool FlatAffineConstraints::isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
Returns true if the GCD test fails for any equality, or if any invalid constraints are discovered on any row. Returns false otherwise.
Definition at line 1026 of file AffineStructures.cpp.
References fourierMotzkinEliminate(), gaussianEliminateIds(), getBestIdToEliminate(), getNumConstraints(), getNumIds(), hasInvalidConstraint(), isEmptyByGCDTest(), kExplosionFactor, and removeRedundantLocalVars().
Referenced by canonicalizeMinMaxOp(), mlir::checkMemrefAccessDependence(), classof(), mlir::PresburgerSet::intersect(), removeRedundantInequalities(), and mlir::simplifyIntegerSet().
isEmptyByGCDTest()
bool FlatAffineConstraints::isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
Returns true if this test fails on any equality. Returns false otherwise. This test can be used to disprove the existence of a solution. If it returns true, no integer solution to the equality constraints can exist.
Definition at line 1087 of file AffineStructures.cpp.
References atEq(), getNumCols(), getNumEqualities(), and mlir::FlatAffineValueConstraints::hasConsistentState().
Referenced by classof(), findIntegerSample(), isEmpty(), and subtractRecursively().
isHyperRectangular()
bool FlatAffineConstraints::isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
Definition at line 2937 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), and getNumInequalities().
Referenced by checkIfHyperRectangular(), and getNumLocalIds().
isIntegerEmpty()
bool FlatAffineConstraints::isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Uses the same algorithm as findIntegerSample.
Definition at line 1178 of file AffineStructures.cpp.
References findIntegerSample().
Referenced by classof(), and mlir::PresburgerSet::isIntegerEmpty().
mergeLocalIds()
void FlatAffineConstraints::mergeLocalIds (FlatAffineConstraints & other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
The ordering of the local ids in the sets may also be changed. After merging, if the i^th local variable in one set has a known division representation, then the i^th local variable in the other set either has the same division representation or no known division representation.
The number of dimensions and symbol ids in this and other should match.
To detect local ids that always take the same in both sets, each local id is represented as a floordiv with constant denominator in terms of other ids. After extracting these divisions, local ids with the same division representation are considered duplicate and are merged. It is possible that division representation for some local id cannot be obtained, and thus these local ids are not considered for detecting duplicates.
Definition at line 1951 of file AffineStructures.cpp.
References copy(), eliminateRedundantLocalId(), getIdKindOffset(), getLocalReprs(), getNumDimIds(), getNumLocalIds(), getNumSymbolIds(), and insertLocalId().
Referenced by mlir::FlatAffineRelation::compose(), getNumLocalIds(), mlir::PresburgerSet::intersect(), mergeAndAlignIds(), and subtractRecursively().
normalizeConstraintsByGCD()
void FlatAffineConstraints::normalizeConstraintsByGCD () protected
Normalized each constraints by the GCD of its coefficients.
Definition at line 855 of file AffineStructures.cpp.
References getNumEqualities(), getNumInequalities(), and normalizeConstraintByGCD().
Referenced by gaussianEliminateId(), getSliceBounds(), projectOut(), and removeTrivialRedundancy().
print()
void FlatAffineConstraints::print (raw_ostream & os) const
Definition at line 2962 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumCols(), getNumConstraints(), getNumDimIds(), getNumEqualities(), getNumIds(), getNumInequalities(), getNumLocalIds(), getNumSymbolIds(), and mlir::FlatAffineValueConstraints::hasConsistentState().
Referenced by dump(), getNumLocalIds(), and mlir::PresburgerSet::print().
projectOut() [1/2]
void FlatAffineConstraints::projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
The resulting constraint system is the shadow along the dimensions that still exist. This method may not always be integer exact.
Definition at line 3331 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), gaussianEliminateIds(), gcdTightenInequalities(), getBestIdToEliminate(), getNumCols(), getNumIds(), and normalizeConstraintsByGCD().
Referenced by mlir::normalizeMemRefType().
projectOut() [2/2]
void mlir::FlatAffineConstraints::projectOut (unsigned pos) inline
Definition at line 294 of file AffineStructures.h.
References constantFoldId(), constantFoldIdRange(), projectOut(), removeEquality(), removeEqualityRange(), removeId(), removeIdRange(), removeInequality(), removeInequalityRange(), setAndEliminate(), setDimSymbolSeparation(), and unionBoundingBox().
Referenced by projectOut().
removeEquality()
void FlatAffineConstraints::removeEquality (unsigned pos)
Definition at line 2640 of file AffineStructures.cpp.
References equalities, and mlir::Matrix::removeRow().
Referenced by gaussianEliminateIds(), projectOut(), removeConstraintsInvolvingSuffixDims(), removeIndependentConstraints(), and removeRedundantLocalVars().
removeEqualityRange()
void FlatAffineConstraints::removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
Definition at line 2648 of file AffineStructures.cpp.
References equalities, and mlir::Matrix::removeRows().
Referenced by projectOut(), and subtractRecursively().
removeId() [1/2]
void FlatAffineConstraints::removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
The specified location is relative to the first identifier of the specified kind.
Definition at line 423 of file AffineStructures.cpp.
Referenced by createSeparationCondition(), eliminateRedundantLocalId(), fourierMotzkinEliminate(), projectOut(), and removeRedundantLocalVars().
removeId() [2/2]
void FlatAffineConstraints::removeId (unsigned pos)
Removes the specified identifier from the system.
Definition at line 3088 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::removeIdRange().
removeIdRange() [1/2]
void FlatAffineConstraints::removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Definition at line 427 of file AffineStructures.cpp.
Referenced by findIntegerSample(), gaussianEliminateId(), projectOut(), mlir::FlatAffineValueConstraints::removeIdRange(), mlir::FlatAffineValueConstraints::setValues(), and subtractRecursively().
removeIdRange() [2/2]
void FlatAffineConstraints::removeIdRange (unsigned idStart, unsigned idLimit) protected virtual
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Reimplemented in mlir::FlatAffineRelation, and mlir::FlatAffineValueConstraints.
Definition at line 947 of file AffineStructures.cpp.
References equalities, getNumCols(), getNumLocalIds(), inequalities, max(), min(), numDims, numIds, numSymbols, and mlir::Matrix::removeColumns().
removeIndependentConstraints()
void FlatAffineConstraints::removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
Definition at line 3731 of file AffineStructures.cpp.
References getIndependentConstraints(), getNumIds(), removeEquality(), and removeInequality().
Referenced by createSeparationCondition(), and getNumLocalIds().
removeInequality()
void FlatAffineConstraints::removeInequality (unsigned pos)
Definition at line 2644 of file AffineStructures.cpp.
References inequalities, and mlir::Matrix::removeRow().
Referenced by projectOut(), removeConstraintsInvolvingSuffixDims(), removeIndependentConstraints(), and subtractRecursively().
removeInequalityRange()
void FlatAffineConstraints::removeInequalityRange (unsigned start, unsigned end)
Definition at line 2654 of file AffineStructures.cpp.
References inequalities, and mlir::Matrix::removeRows().
Referenced by projectOut(), and subtractRecursively().
removeRedundantConstraints()
void FlatAffineConstraints::removeRedundantConstraints ()
Removes redundant constraints using Simplex.
Although the algorithm can theoretically take exponential time in the worst case (rare), it is known to perform much better in the average case. If V is the number of vertices in the polytope and C is the number of constraints, the algorithm takes O(VC) time.
Definition at line 1878 of file AffineStructures.cpp.
References atEq(), atIneq(), mlir::Simplex::detectRedundant(), equalities, gcdTightenInequalities(), getNumCols(), getNumEqualities(), getNumInequalities(), inequalities, mlir::Simplex::isMarkedRedundant(), and mlir::Matrix::resizeVertically().
Referenced by getNumLocalIds().
removeRedundantInequalities()
void FlatAffineConstraints::removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
Definition at line 1838 of file AffineStructures.cpp.
References atIneq(), fillInequality(), getNumCols(), getNumInequalities(), inequalities, isEmpty(), negateInequality(), and mlir::Matrix::resizeVertically().
Referenced by getNumLocalIds().
removeRedundantLocalVars()
void FlatAffineConstraints::removeRedundantLocalVars () protected
Removes local variables using equalities.
Each equality is checked if it can be reduced to the form: e = affine-expr, where e is a local variable and affine-expr is an affine expression not containing e. If an equality satisfies this form, the local variable is replaced in each constraint and then removed. The equality used to replace this local variable is also removed.
Definition at line 2031 of file AffineStructures.cpp.
References atEq(), eliminateFromConstraint(), getNumDimAndSymbolIds(), getNumEqualities(), getNumIds(), getNumInequalities(), normalizeConstraintByGCD(), removeEquality(), and removeId().
Referenced by mlir::FlatAffineRelation::compose(), gaussianEliminateId(), and isEmpty().
removeTrivialRedundancy()
void FlatAffineConstraints::removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
A constraint of the form <non-negative constant> >= 0 is considered trivially true. This method is a linear time method on the constraints, does a single scan, and updates in place. It also normalizes constraints by their GCD and performs GCD tightening on inequalities.
A constraint of the form <non-negative constant> >= 0 is considered trivially true.
Definition at line 3002 of file AffineStructures.cpp.
References atIneq(), mlir::Matrix::copyRow(), gcdTightenInequalities(), getNumCols(), getNumInequalities(), inequalities, normalizeConstraintsByGCD(), and mlir::Matrix::resizeVertically().
Referenced by createSeparationCondition(), getNumLocalIds(), and mlir::simplifyIntegerSet().
reset() [1/2]
void FlatAffineConstraints::reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals = 0) virtual
Clears any existing data and reserves memory for the specified constraints.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 235 of file AffineStructures.cpp.
References FlatAffineConstraints().
Referenced by classof(), mlir::FlatAffineValueConstraints::classof(), getCommonConstraints(), getFlattenedAffineExprs(), and mlir::getFlattenedAffineExprs().
reset() [2/2]
void FlatAffineConstraints::reset (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0)
Definition at line 272 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::reset().
setAndEliminate()
void FlatAffineConstraints::setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
Definition at line 2691 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumCols(), getNumEqualities(), getNumIds(), getNumInequalities(), and mlir::FlatAffineValueConstraints::removeIdRange().
Referenced by constantFoldId(), findIntegerSample(), and projectOut().
setDimSymbolSeparation()
void FlatAffineConstraints::setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Depending on the new symbol count, either a chunk of trailing dimensional identifiers becomes symbols, or some of the leading symbols become dimensions.
Definition at line 2624 of file AffineStructures.cpp.
References numDims, and numSymbols.
Referenced by createFullTiles(), createSeparationCondition(), projectOut(), and turnSymbolIntoDim().
swapId()
void FlatAffineConstraints::swapId (unsigned posA, unsigned posB) virtual
Swap the posA^th identifier with the posB^th identifier.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 2606 of file AffineStructures.cpp.
References atEq(), atIneq(), getNumEqualities(), getNumIds(), and getNumInequalities().
Referenced by mlir::FlatAffineValueConstraints::classof(), and mlir::FlatAffineValueConstraints::swapId().
unionBoundingBox()
LogicalResult FlatAffineConstraints::unionBoundingBox (const FlatAffineConstraints & other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
For each of the dimensions, the min of the lower bounds (symbolic) and the max of the upper bounds (symbolic) is computed to determine such a bounding box. other is expected to have the same dimensional identifiers as this constraint system (in the same order).
E.g.: 1) this = {0 <= d0 <= 127}, other = {16 <= d0 <= 192}, output = {0 <= d0 <= 192} 2) this = {s0 + 5 <= d0 <= s0 + 20}, other = {s0 + 1 <= d0 <= s0 + 9}, output = {s0 + 1 <= d0 <= s0 + 20} 3) this = {0 <= d0 <= 5, 1 <= d1 <= 9} other = {2 <= d0 <= 6, 5 <= d1 <= 15}, output = {0 <= d0 <= 6, 1 <= d1 <= 15}
Definition at line 3429 of file AffineStructures.cpp.
References mlir::failure(), getCommonConstraints(), getConstantBoundOnDimSize(), getNumCols(), getNumDimIds(), getNumLocalIds(), getNumSymbolIds(), and numDims.
Referenced by projectOut(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
Member Data Documentation
equalities
Matrix mlir::FlatAffineConstraints::equalities protected
Coefficients of affine equalities (in == 0 form).
Definition at line 555 of file AffineStructures.h.
Referenced by addBound(), addEquality(), append(), atEq(), clearConstraints(), getEquality(), getNumEqualities(), getNumReservedEqualities(), hasConsistentState(), removeEquality(), removeEqualityRange(), removeIdRange(), and removeRedundantConstraints().
inequalities
Matrix mlir::FlatAffineConstraints::inequalities protected
Coefficients of affine inequalities (in >= 0 form).
Definition at line 558 of file AffineStructures.h.
Referenced by addBound(), addInequality(), append(), atIneq(), clearConstraints(), getInequality(), getNumInequalities(), getNumReservedInequalities(), hasConsistentState(), removeIdRange(), removeInequality(), removeInequalityRange(), removeRedundantConstraints(), removeRedundantInequalities(), and removeTrivialRedundancy().
kExplosionFactor
constexpr unsigned mlir::FlatAffineConstraints::kExplosionFactor = 32 static protected
A parameter that controls detection of an unrealistic number of constraints.
If the number of constraints is this many times the number of variables, we consider such a system out of line with the intended use case of FlatAffineConstraints.
Definition at line 570 of file AffineStructures.h.
Referenced by isEmpty().
numDims
unsigned mlir::FlatAffineConstraints::numDims protected
Number of identifiers corresponding to real dimensions.
Definition at line 548 of file AffineStructures.h.
Referenced by classof(), mlir::FlatAffineValueConstraints::computeAlignedMap(), computeLocalVars(), eqInvolvesSuffixDims(), getAsIntegerSet(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getNewNumDimsSymbols(), getNumDimIds(), getUniverse(), hasConsistentState(), ineqInvolvesSuffixDims(), removeIdRange(), setDimSymbolSeparation(), unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
numIds
unsigned mlir::FlatAffineConstraints::numIds protected
Total number of identifiers.
Definition at line 545 of file AffineStructures.h.
Referenced by mlir::FlatAffineValueConstraints::clearAndCopyFrom(), findIntegerSample(), FlatAffineConstraints(), mlir::FlatAffineValueConstraints::FlatAffineValueConstraints(), mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), gaussianEliminateIds(), mlir::FlatAffineValueConstraints::getAllValues(), getNumCols(), getNumIds(), getNumLocalIds(), mlir::FlatAffineValueConstraints::getValues(), hasConsistentState(), removeIdRange(), mlir::FlatAffineValueConstraints::setValue(), and mlir::FlatAffineValueConstraints::setValues().
numSymbols
unsigned mlir::FlatAffineConstraints::numSymbols protected
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Definition at line 552 of file AffineStructures.h.
Referenced by mlir::alignAffineMapWithValues(), classof(), mlir::FlatAffineValueConstraints::computeAlignedMap(), getNewNumDimsSymbols(), getNumDimAndSymbolIds(), getNumLocalIds(), getNumSymbolIds(), getUniverse(), hasConsistentState(), removeIdRange(), and setDimSymbolSeparation().
The documentation for this class was generated from the following files:
include/mlir/Analysis/AffineStructures.h
lib/Analysis/AffineStructures.cpp