MLIR: mlir::AsmParser Class Reference
mlir::AsmParser Class Reference abstract
This base class exposes generic asm parser hooks, usable across the various derived parsers.
#include "mlir/IR/OpImplementation.h"
Public Types
enum Delimiter {
Delimiter::None, Delimiter::Paren, Delimiter::Square, Delimiter::LessGreater,
Delimiter::Braces, Delimiter::OptionalParen, Delimiter::OptionalSquare, Delimiter::OptionalLessGreater,
Delimiter::OptionalBraces
}
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList and parseRegionArgumentList.
Public Member Functions
AsmParser ()=default
virtual ~AsmParser ()
MLIRContext * getContext () const
virtual llvm::SMLoc getNameLoc () const =0
Return the location of the original name token.
virtual InFlightDiagnostic emitError (llvm::SMLoc loc, const Twine &message={})=0
Emit a diagnostic at the specified location and return failure.
virtual Builder & getBuilder () const =0
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
virtual llvm::SMLoc getCurrentLocation ()=0
Get the location of the next token and store it into the argument.
ParseResult getCurrentLocation (llvm::SMLoc *loc)
virtual Location getEncodedSourceLoc (llvm::SMLoc loc)=0
Re-encode the given source location as an MLIR location and return it.
virtual ParseResult parseArrow ()=0
Parse a '->' token.
virtual ParseResult parseOptionalArrow ()=0
Parse a '->' token if present.
virtual ParseResult parseLBrace ()=0
Parse a { token.
virtual ParseResult parseOptionalLBrace ()=0
Parse a { token if present.
virtual ParseResult parseRBrace ()=0
Parse a } token.
virtual ParseResult parseOptionalRBrace ()=0
Parse a } token if present.
virtual ParseResult parseColon ()=0
Parse a : token.
virtual ParseResult parseOptionalColon ()=0
Parse a : token if present.
virtual ParseResult parseComma ()=0
Parse a , token.
virtual ParseResult parseOptionalComma ()=0
Parse a , token if present.
virtual ParseResult parseEqual ()=0
Parse a = token.
virtual ParseResult parseOptionalEqual ()=0
Parse a = token if present.
virtual ParseResult parseLess ()=0
Parse a '<' token.
virtual ParseResult parseOptionalLess ()=0
Parse a '<' token if present.
virtual ParseResult parseGreater ()=0
Parse a '>' token.
virtual ParseResult parseOptionalGreater ()=0
Parse a '>' token if present.
virtual ParseResult parseQuestion ()=0
Parse a '?' token.
virtual ParseResult parseOptionalQuestion ()=0
Parse a '?' token if present.
virtual ParseResult parsePlus ()=0
Parse a '+' token.
virtual ParseResult parseOptionalPlus ()=0
Parse a '+' token if present.
virtual ParseResult parseStar ()=0
Parse a '*' token.
virtual ParseResult parseOptionalStar ()=0
Parse a '*' token if present.
ParseResult parseString (std::string *string)
Parse a quoted string token.
virtual ParseResult parseOptionalString (std::string *string)=0
Parse a quoted string token if present.
ParseResult parseKeyword (StringRef keyword, const Twine &msg="")
Parse a given keyword.
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef keyword)=0
Parse the given keyword if present.
virtual ParseResult parseOptionalKeyword (StringRef *keyword)=0
Parse a keyword, if present, into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef *keyword, ArrayRef< StringRef > allowedValues)=0
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
ParseResult parseKeywordOrString (std::string *result)
Parse a keyword or a quoted string.
virtual ParseResult parseOptionalKeywordOrString (std::string *result)=0
Parse an optional keyword or string.
virtual ParseResult parseLParen ()=0
Parse a (token.
virtual ParseResult parseOptionalLParen ()=0
Parse a (token if present.
virtual ParseResult parseRParen ()=0
Parse a) token.
virtual ParseResult parseOptionalRParen ()=0
Parse a) token if present.
virtual ParseResult parseLSquare ()=0
Parse a [ token.
virtual ParseResult parseOptionalLSquare ()=0
Parse a [ token if present.
virtual ParseResult parseRSquare ()=0
Parse a ] token.
virtual ParseResult parseOptionalRSquare ()=0
Parse a ] token if present.
virtual ParseResult parseOptionalEllipsis ()=0
Parse a ... token if present;.
virtual ParseResult parseFloat (double &result)=0
Parse a floating point value from the stream.
template<typename IntT >
ParseResult parseInteger (IntT &result)
Parse an integer value from the stream.
virtual OptionalParseResult parseOptionalInteger (APInt &result)=0
Parse an optional integer value from the stream.
template<typename IntT >
OptionalParseResult parseOptionalInteger (IntT &result)
virtual ParseResult parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElementFn, StringRef contextMessage=StringRef())=0
Parse a list of comma-separated items with an optional delimiter.
ParseResult parseCommaSeparatedList (function_ref< ParseResult()> parseElementFn)
Parse a comma separated list of elements that must have at least one entry in it.
template<typename T , typename... ParamsT>
T getChecked (llvm::SMLoc loc, ParamsT &&... params)
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
template<typename T , typename... ParamsT>
T getChecked (ParamsT &&... params)
A variant of getChecked that uses the result of getNameLoc to emit errors.
virtual ParseResult parseAttribute (Attribute &result, Type type={})=0
Parse an arbitrary attribute of a given type and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type={})
Parse an attribute of a specific kind and type.
ParseResult parseAttribute (Attribute &result, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an attribute of a specific kind and type.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute of a given type and return it in result.
virtual OptionalParseResult parseOptionalAttribute (Attribute &result, Type type={})=0
Parse an arbitrary optional attribute of a given type and return it in result.
virtual OptionalParseResult parseOptionalAttribute (ArrayAttr &result, Type type={})=0
Parse an optional array attribute and return it in result.
virtual OptionalParseResult parseOptionalAttribute (StringAttr &result, Type type={})=0
Parse an optional string attribute and return it in result.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
virtual ParseResult parseOptionalAttrDict (NamedAttrList &result)=0
Parse a named dictionary into 'result' if it is present.
virtual ParseResult parseOptionalAttrDictWithKeyword (NamedAttrList &result)=0
Parse a named dictionary into 'result' if the attributes keyword is present.
virtual ParseResult parseAffineMap (AffineMap &map)=0
Parse an affine map instance into 'map'.
virtual ParseResult printIntegerSet (IntegerSet &set)=0
Parse an integer set instance into 'set'.
ParseResult parseSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)=0
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalLocationSpecifier (Optional< Location > &result)=0
Parse a loc(...) specifier if present, filling in result if so.
virtual ParseResult parseType (Type &result)=0
Parse a type.
virtual OptionalParseResult parseOptionalType (Type &result)=0
Parse an optional type.
template<typename TypeT >
ParseResult parseType (TypeT &result)
Parse a type of a specific type.
ParseResult parseTypeList (SmallVectorImpl< Type > &result)
Parse a type list.
virtual ParseResult parseArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an arrow followed by a type list.
virtual ParseResult parseOptionalArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional arrow followed by a type list.
virtual ParseResult parseColonType (Type &result)=0
Parse a colon followed by a type.
template<typename TypeType >
ParseResult parseColonType (TypeType &result)
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
virtual ParseResult parseColonTypeList (SmallVectorImpl< Type > &result)=0
Parse a colon followed by a type list, which must have at least one type.
virtual ParseResult parseOptionalColonTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional colon followed by a type list, which if present must have at least one type.
ParseResult parseKeywordType (const char *keyword, Type &result)
Parse a keyword followed by a type.
ParseResult addTypeToList (Type type, SmallVectorImpl< Type > &result)
Add the specified type to the end of the specified type list and return success.
ParseResult addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > &result)
Add the specified types to the end of the specified type list and return success.
virtual ParseResult parseDimensionList (SmallVectorImpl< int64_t > &dimensions, bool allowDynamic=true)=0
Parse a 'x' separated dimension list.
virtual ParseResult parseXInDimensionList ()=0
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
Detailed Description
This base class exposes generic asm parser hooks, usable across the various derived parsers.
Definition at line 324 of file OpImplementation.h.
Member Enumeration Documentation
Delimiter
enum mlir::AsmParser::Delimiter strong
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList and parseRegionArgumentList.
Enumerator
None
Zero or more operands with no delimiters.
Paren
Parens surrounding zero or more operands.
Square
Square brackets surrounding zero or more operands.
LessGreater
<> brackets surrounding zero or more operands.
Braces
{} brackets surrounding zero or more operands.
OptionalParen
Parens supporting zero or more operands, or nothing.
OptionalSquare
Square brackets supporting zero or more ops, or nothing.
OptionalLessGreater
<> brackets supporting zero or more ops, or nothing.
OptionalBraces
{} brackets surrounding zero or more operands, or nothing.
Definition at line 544 of file OpImplementation.h.
Constructor & Destructor Documentation
AsmParser()
mlir::AsmParser::AsmParser () default
~AsmParser()
AsmParser::~AsmParser () virtual
Definition at line 57 of file AsmPrinter.cpp.
Member Function Documentation
addTypesToList()
ParseResult mlir::AsmParser::addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > & result) inline
Add the specified types to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 827 of file OpImplementation.h.
References mlir::success().
Referenced by parseCompositeInsertOp(), parseExecuteOp(), and parseShuffleOp().
addTypeToList()
ParseResult mlir::AsmParser::addTypeToList (Type type, SmallVectorImpl< Type > & result) inline
Add the specified type to the end of the specified type list and return success.
This is a helper designed to allow parse methods to be simple and chain through || operators.
Definition at line 819 of file OpImplementation.h.
References mlir::success().
Referenced by foldTransferInBoundsAttribute(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineVectorLoadOp(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), mlir::impl::parseCastOp(), parseConstantOp(), parseContractionOp(), parseExecuteOp(), parseExtractOp(), parseGroupNonUniformArithmeticOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseShuffleOp(), parseTransferReadOp(), parseTransposeOp(), and parseViewOp().
emitError()
virtual InFlightDiagnostic mlir::AsmParser::emitError (llvm::SMLoc loc, const Twine & message = {}) pure virtual
Emit a diagnostic at the specified location and return failure.
Referenced by acceptBitWidth(), addNamedOpBuilders(), buildLLVMFunctionType(), mlir::pdl::PDLType::classof(), eachHasOnlyOneOfTypes(), foldTransferInBoundsAttribute(), getElementType(), getInsertExtractValueElementType(), getLoadStoreElementType(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), parseAsyncDependencies(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), mlir::Dialect::parseAttribute(), parseBound(), parseCalibratedType(), parseCallOp(), parseClauses(), parseCompositeConstructOp(), parseContractionOp(), parseCooperativeMatrixType(), parseDmaStartOp(), parseEnumStrAttr(), parseExpressedTypeAndRange(), parseExtractElementOp(), parseExtractOp(), parseForOp(), mlir::function_like_impl::parseFunctionArgumentList(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseIncludeOp(), parseInsertElementOp(), parseInterfaceVarABIAttr(), parseInvokeOp(), parseMatrixType(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOptionalArrayStride(), parseOuterProductOp(), parsePDLType(), parsePointerType(), parsePrefetchOp(), parseReductionOp(), parseScheduleClause(), parseShuffleOp(), parseShuffleVectorOp(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseStructType(), parseSynchronizationHint(), parseTargetEnvAttr(), parseTransferReadOp(), mlir::Dialect::parseType(), parseUniformType(), parseVariableOp(), parseVerCapExtAttr(), parseViewOp(), mlir::DataLayoutSpecAttr::print(), verify(), and verifyScheduleModifiers().
getBuilder()
virtual Builder& mlir::AsmParser::getBuilder () const pure virtual
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
Referenced by buildLLVMFunctionType(), foldTransferInBoundsAttribute(), mlir::DataLayoutEntryAttr::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAsyncDependencies(), parseAtomicCmpXchgOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), parseClauses(), parseCmpOp(), parseCommonStructuredOpParts(), parseConstShapeOp(), parseControlAttribute(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCreateOperationOpAttributes(), mlir::parseDimAndSymbolList(), parseDmaStartOp(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecuteOp(), parseExecutionModeOp(), parseFenceOp(), parseForOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGenericAtomicRMWOp(), parseGlobalOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInterfaceVarABIAttr(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseLoopOp(), parseMemoryAccessAttributes(), parseOperandsOrIntegersImpl(), parseOperationOpAttributes(), mlir::impl::parseOptionalVisibilityKeyword(), parseParallelOp(), parsePrefetchOp(), mlir::parseReshapeLikeOp(), parseResultsValueType(), parseSectionsOp(), parseSelectOp(), parseShuffleOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseStorageType(), parseStoreOp(), parseSynchronizationHint(), parseTiledLoopOp(), parseTransferReadOp(), parseVariableDecorations(), parseVariableOp(), parseVerCapExtAttr(), parseViewOp(), and parseWsLoopOp().
getChecked() [1/2]
template<typename T , typename... ParamsT> T mlir::AsmParser::getChecked (llvm::SMLoc loc, ParamsT &&... params) inline
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
Note that unlike OpBuilder::getType, this method does not implicitly insert a context parameter.
Definition at line 592 of file OpImplementation.h.
References mlir::emitError().
Referenced by acceptBitWidth(), parseAnyType(), parseCalibratedType(), and parseUniformType().
getChecked() [2/2]
template<typename T , typename... ParamsT> T mlir::AsmParser::getChecked (ParamsT &&... params) inline
A variant of getChecked that uses the result of getNameLoc to emit errors.
Definition at line 599 of file OpImplementation.h.
References mlir::emitError(), and mlir::parseAttribute().
getContext()
MLIRContext * AsmParser::getContext () const
Definition at line 61 of file AsmPrinter.cpp.
Referenced by acceptBitWidth(), getOption(), mlir::DataLayoutSpecAttr::parse(), parseCopyOpRegion(), parseFillOpRegion(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseImageOperands(), parseIncludeOp(), parseLLVMFuncOp(), parseNVVMVoteBallotOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), and parseSpecConstantOperationOp().
getCurrentLocation() [1/2]
virtual llvm::SMLoc mlir::AsmParser::getCurrentLocation () pure virtual
Get the location of the next token and store it into the argument.
This always succeeds.
Referenced by mlir::pdl::PDLType::classof(), foldTransferInBoundsAttribute(), mlir::DataLayoutEntryAttr::parse(), parseAccessChainOp(), parseAffineForOp(), parseAffineParallelOp(), parseAllocaOp(), parseAndVerify(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseArrayType(), parseAsyncDependencies(), parseAtomicBinOp(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicOrdering(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseClauses(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixType(), parseEnumStrAttr(), parseExecuteOp(), parseExpressedTypeAndRange(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), mlir::function_like_impl::parseFunctionArgumentList(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseInsertElementOp(), parseInsertValueOp(), parseInterfaceVarABIAttr(), parseInvokeOp(), parseKeywordList(), parseLoadOp(), parseMatrixType(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandList(), parseOptionalArrayStride(), parsePointerType(), parsePtrAccessChainOpImpl(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStorageRange(), parseStorageType(), parseStoreOp(), parseStructMemberDecorations(), parseSubgroupBlockWriteINTELOp(), parseSynchronizationHint(), parseTargetEnvAttr(), parseTiledLoopOp(), parseTransferReadOp(), parseUniformType(), parseVariableOp(), parseVerCapExtAttr(), parseViewOp(), parseYieldOp(), and verify().
getCurrentLocation() [2/2]
ParseResult mlir::AsmParser::getCurrentLocation (llvm::SMLoc * loc) inline
Definition at line 349 of file OpImplementation.h.
References mlir::success().
getEncodedSourceLoc()
virtual Location mlir::AsmParser::getEncodedSourceLoc (llvm::SMLoc loc) pure virtual
Re-encode the given source location as an MLIR location and return it.
Note: This method should only be used when a Location is necessary, as the encoding process is not efficient.
getNameLoc()
virtual llvm::SMLoc mlir::AsmParser::getNameLoc () const pure virtual
Return the location of the original name token.
Referenced by acceptBitWidth(), addNamedOpBuilders(), eachHasOnlyOneOfTypes(), getOption(), mlir::DataLayoutSpecAttr::parse(), mlir::OpState::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), mlir::Dialect::parseAttribute(), parseBound(), parseCalibratedType(), parseCallOp(), parseClauses(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseDmaStartOp(), parseForOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseIncludeOp(), parseInvokeOp(), parseNVVMVoteBallotOp(), parseOuterProductOp(), parseParallelOp(), parsePDLType(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseScheduleClause(), parseSelectOp(), parseShuffleOp(), parseStructType(), parseTargetEnvAttr(), mlir::Dialect::parseType(), mlir::DataLayoutSpecAttr::print(), and verifyScheduleModifiers().
parseAffineMap()
virtual ParseResult mlir::AsmParser::parseAffineMap (AffineMap & map) pure virtual
Parse an affine map instance into 'map'.
Referenced by parseTransposeOp().
parseArrow()
virtual ParseResult mlir::AsmParser::parseArrow () pure virtual
Parse a '->' token.
Referenced by parseAllocateAndAllocator(), parseForEachOp(), parseReductionVarList(), and parseResultsValueType().
parseArrowTypeList()
virtual ParseResult mlir::AsmParser::parseArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an arrow followed by a type list.
Referenced by parseAffineForOp(), parseAtomicReadOp(), and parseForOp().
parseAttribute() [1/5]
virtual ParseResult mlir::AsmParser::parseAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary attribute of a given type and return it in result.
Referenced by acceptBitWidth(), mlir::DataLayoutEntryAttr::parse(), mlir::FieldParser< AttributeT, std::enable_if_t< std::is_base_of< Attribute, AttributeT >::value, AttributeT > >::parse(), mlir::DataLayoutSpecAttr::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), parseClauses(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseCreateOperationOpAttributes(), parseEntryPointOp(), parseEnumStrAttr(), parseExecutionModeOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseFunctionLibraryOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseInsertValueOp(), parseInvokeOp(), parseMemoryAccessAttributes(), parseModuleOp(), parseOperationOpAttributes(), parsePrefetchOp(), parseReductionOp(), parseReductionVarList(), parseShuffleOp(), parseShuffleVectorOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseTargetEnvAttr(), parseTiledLoopOp(), and parseVariableDecorations().
parseAttribute() [2/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, Type type = {}) inline
Parse an attribute of a specific kind and type.
Definition at line 613 of file OpImplementation.h.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseAttribute(), and mlir::success().
parseAttribute() [3/5]
ParseResult mlir::AsmParser::parseAttribute (Attribute & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute and return it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 630 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [4/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an attribute of a specific kind and type.
Definition at line 637 of file OpImplementation.h.
References mlir::parseAttribute().
parseAttribute() [5/5]
template<typename AttrType > ParseResult mlir::AsmParser::parseAttribute (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse an arbitrary attribute of a given type and return it in result.
This also adds the attribute to the specified attribute list with the specified name.
Definition at line 646 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseAttribute(), and mlir::success().
parseColon()
virtual ParseResult mlir::AsmParser::parseColon () pure virtual
Parse a : token.
Referenced by parseAllocaOp(), parseCallOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseExpressedTypeAndRange(), parseExtractValueOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), mlir::impl::parseOneResultSameOperandTypeOp(), mlir::parseReshapeLikeOp(), parseShiftOp(), parseStorageRange(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseSwitchOpCases(), parseUniformType(), and parseVariableOp().
parseColonType() [1/2]
virtual ParseResult mlir::AsmParser::parseColonType (Type & result) pure virtual
Parse a colon followed by a type.
Referenced by mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocateAndAllocator(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicReadOp(), parseAtomicRMWOp(), parseAtomicUpdateOp(), parseAtomicWriteOp(), parseAttributions(), mlir::impl::parseCastOp(), parseClauses(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), parseForEachOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseGenericAtomicRMWOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseInsertElementOp(), parseLinearClause(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandAndType(), parseOperandAndTypeList(), parseOperandList(), parseOuterProductOp(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReduceOp(), parseReductionOp(), parseReductionVarList(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantCompositeOp(), parseTransposeOp(), parseUnaryOp(), parseViewOp(), parseWsLoopOp(), and verify().
parseColonType() [2/2]
template<typename TypeType > ParseResult mlir::AsmParser::parseColonType (TypeType & result) inline
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
Definition at line 787 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), and mlir::success().
parseColonTypeList()
virtual ParseResult mlir::AsmParser::parseColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse a colon followed by a type list, which must have at least one type.
Referenced by foldTransferInBoundsAttribute(), mlir::AffineDmaStartOp::parse(), parseCommonStructuredOpParts(), parseContractionOp(), parseDmaStartOp(), parseSwitchOpCases(), parseTransferReadOp(), and parseYieldOp().
parseComma()
virtual ParseResult mlir::AsmParser::parseComma () pure virtual
Parse a , token.
Referenced by foldTransferInBoundsAttribute(), mlir::DataLayoutEntryAttr::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAndVerify< unsigned >(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseAtomicWriteOp(), parseBranchConditionalOp(), parseContractionOp(), parseCooperativeMatrixStoreNVOp(), parseCooperativeMatrixType(), parseCopyMemoryOp(), parseDmaStartOp(), parseInsertElementOp(), parseInsertValueOp(), parseInterfaceVarABIAttr(), parseMemoryAccessAttributes(), parseOuterProductOp(), parsePointerType(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReductionOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseSourceMemoryAccessAttributes(), parseStoreOp(), parseStructMemberDecorations(), parseStructType(), parseTargetEnvAttr(), parseTiledLoopOp(), parseTransferReadOp(), parseUniformType(), parseVariableDecorations(), and parseVerCapExtAttr().
parseCommaSeparatedList() [1/2]
virtual ParseResult mlir::AsmParser::parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElementFn, StringRef contextMessage = StringRef()) pure virtual
Parse a list of comma-separated items with an optional delimiter.
If a delimiter is provided, then an empty list is allowed. If not, then at least one element will be parsed.
contextMessage is an optional message appended to "expected '('" sorts of diagnostics when parsing the delimeters.
Referenced by mlir::FieldParser< ContainerT, std::enable_if_t< std::is_member_function_pointer< decltype(&ContainerT::push_back)>::value, ContainerT > >::parse(), parseAllocateAndAllocator(), parseEntryPointOp(), parseExecuteOp(), and parseOperandAndTypeList().
parseCommaSeparatedList() [2/2]
ParseResult mlir::AsmParser::parseCommaSeparatedList (function_ref< ParseResult()> parseElementFn) inline
Parse a comma separated list of elements that must have at least one entry in it.
Definition at line 579 of file OpImplementation.h.
parseDimensionList()
virtual ParseResult mlir::AsmParser::parseDimensionList (SmallVectorImpl< int64_t > & dimensions, bool allowDynamic = true) pure virtual
Parse a 'x' separated dimension list.
This populates the dimension list, using -1 for the ? dimensions if allowDynamic is set and errors out on ? otherwise.
dimension-list ::= (dimension x)* dimension ::= ? | integer
When allowDynamic is not set, this is used to parse:
static-dimension-list ::= (integer x)*
Referenced by parseArrayType(), parseCooperativeMatrixType(), and parseMatrixType().
parseEqual()
virtual ParseResult mlir::AsmParser::parseEqual () pure virtual
Parse a = token.
Referenced by getOption(), parseAffineForOp(), parseAffineParallelOp(), parseCreateOperationOpAttributes(), parseForOp(), parseGenericOp(), parseLinearClause(), parseOperationOpAttributes(), parseOptionalArrayStride(), parseParallelOp(), parserOptionalOperandAndTypeWithPrefix(), parseSizeAssignment(), parseSpecConstantOp(), parseTiledLoopOp(), and parseWsLoopOp().
parseFloat()
virtual ParseResult mlir::AsmParser::parseFloat (double & result) pure virtual
Parse a floating point value from the stream.
Referenced by parseExpressedTypeAndRange(), and parseQuantParams().
parseGreater()
virtual ParseResult mlir::AsmParser::parseGreater () pure virtual
Parse a '>' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), parseAffinePrefetchOp(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parsePrefetchOp(), parseRuntimeArrayType(), parseSampledImageType(), parseStorageRange(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseInteger()
template<typename IntT > ParseResult mlir::AsmParser::parseInteger (IntT & result) inline
Parse an integer value from the stream.
Definition at line 511 of file OpImplementation.h.
References mlir::emitError(), and mlir::OptionalParseResult::hasValue().
Referenced by getOption(), mlir::FieldParser< IntT, std::enable_if_t< std::is_integral< IntT >::value, IntT > >::parse(), parseAndVerifyInteger(), parseQuantParams(), mlir::parseReshapeLikeOp(), parseStorageRange(), parseSwitchOpCases(), parseTargetEnvAttr(), and parseUniformType().
parseKeyword() [1/2]
ParseResult mlir::AsmParser::parseKeyword (StringRef keyword, const Twine & msg = "") inline
Parse a given keyword.
Definition at line 441 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by addNamedOpBuilders(), eachHasOnlyOneOfTypes(), getOption(), mlir::vector::CombiningKindAttr::parse(), parseAffineForOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAndVerify(), parseAtomicBinOp(), parseAtomicOrdering(), parseCalibratedType(), parseClauses(), parseExecuteOp(), parseForEachOp(), parseForOp(), parseFunctionLibraryOp(), parseInterfaceVarABIAttr(), parseInvokeOp(), parseKeywordList(), parseLaunchOp(), parseOptionalArrayStride(), parseParallelOp(), parsePDLType(), parsePointerType(), parsePrefetchOp(), mlir::parseReshapeLikeOp(), parseScheduleClause(), parseShuffleOp(), parseSizeAssignment(), parseSpecConstantOperationOp(), parseStorageType(), parseStructType(), parseSwitchOpCases(), parseSynchronizationHint(), parseTargetEnvAttr(), parseTiledLoopOp(), parseVerCapExtAttr(), parseWsLoopOp(), mlir::DataLayoutSpecAttr::print(), and verify().
parseKeyword() [2/2]
ParseResult mlir::AsmParser::parseKeyword (StringRef * keyword) inline
Parse a keyword into 'keyword'.
Definition at line 449 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
parseKeywordOrString()
ParseResult mlir::AsmParser::parseKeywordOrString (std::string * result) inline
Parse a keyword or a quoted string.
Definition at line 469 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), and mlir::success().
parseKeywordType()
ParseResult mlir::AsmParser::parseKeywordType (const char * keyword, Type & result) inline
Parse a keyword followed by a type.
Definition at line 812 of file OpImplementation.h.
References mlir::failure(), and mlir::parseType().
Referenced by mlir::impl::parseCastOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseReductionOp(), parseTransposeOp(), and parseViewOp().
parseLBrace()
virtual ParseResult mlir::AsmParser::parseLBrace () pure virtual
Parse a { token.
Referenced by parseUniformType().
parseLess()
virtual ParseResult mlir::AsmParser::parseLess () pure virtual
Parse a '<' token.
Referenced by acceptBitWidth(), mlir::pdl::PDLType::classof(), getOption(), mlir::DataLayoutEntryAttr::parse(), mlir::DataLayoutSpecAttr::parse(), mlir::vector::CombiningKindAttr::parse(), parseAffinePrefetchOp(), parseAnyType(), parseArrayType(), parseCalibratedType(), parseCooperativeMatrixType(), parseExpressedTypeAndRange(), parseImageType(), parseInterfaceVarABIAttr(), parseMatrixType(), parsePointerType(), parsePrefetchOp(), parseRuntimeArrayType(), parseSampledImageType(), parseStructType(), parseTargetEnvAttr(), parseUniformType(), and parseVerCapExtAttr().
parseLParen()
virtual ParseResult mlir::AsmParser::parseLParen () pure virtual
Parse a (token.
Referenced by parseAffineParallelOp(), parseAttributions(), parseClauses(), parseCommonStructuredOpParts(), parseControlAttribute(), parseFenceOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseGlobalOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseLinearClause(), parseOperandList(), parseOptionalOperand(), parseOptionalOperandAndType(), parseReduceOp(), parseReductionVarList(), parseScheduleClause(), parseSizeAssignment(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseStructType(), parseSynchronizationHint(), parseVariableDecorations(), and parseVariableOp().
parseLSquare()
virtual ParseResult mlir::AsmParser::parseLSquare () pure virtual
Parse a [ token.
Referenced by parseExtractElementOp(), parseInsertElementOp(), parseKeywordList(), parseOperandsOrIntegersImpl(), mlir::parseReshapeLikeOp(), and parseTiledLoopOp().
parseOptionalArrow()
virtual ParseResult mlir::AsmParser::parseOptionalArrow () pure virtual
Parse a '->' token if present.
Referenced by mlir::function_like_impl::parseFunctionSignature().
parseOptionalArrowTypeList()
virtual ParseResult mlir::AsmParser::parseOptionalArrowTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional arrow followed by a type list.
Referenced by parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseExecuteOp(), parseExecuteRegionOp(), parseIfOp(), parseLoopOp(), parseNamedStructuredOpResults(), parseParallelOp(), and parseReduceOp().
parseOptionalAttrDict()
virtual ParseResult mlir::AsmParser::parseOptionalAttrDict (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if it is present.
Referenced by foldTransferInBoundsAttribute(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCommonStructuredOpParts(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseCopyMemoryOp(), parseExecuteRegionOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseForEachOp(), parseForOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLaunchOp(), parseLLVMOpAttrs(), parseLoadOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parseReduceOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantOperationOp(), parseStoreOp(), parseTiledLoopOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableDecorations(), parseViewOp(), and parseYieldOp().
parseOptionalAttrDictWithKeyword()
virtual ParseResult mlir::AsmParser::parseOptionalAttrDictWithKeyword (NamedAttrList & result) pure virtual
Parse a named dictionary into 'result' if the attributes keyword is present.
Referenced by parseExecuteOp(), parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseLoopOp(), parseModuleOp(), parseParallelOp(), and verify().
parseOptionalAttribute() [1/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (Attribute & result, Type type = {}) pure virtual
Parse an arbitrary optional attribute of a given type and return it in result.
Referenced by parseIncludeOp().
parseOptionalAttribute() [2/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (ArrayAttr & result, Type type = {}) pure virtual
Parse an optional array attribute and return it in result.
parseOptionalAttribute() [3/5]
virtual OptionalParseResult mlir::AsmParser::parseOptionalAttribute (StringAttr & result, Type type = {}) pure virtual
Parse an optional string attribute and return it in result.
parseOptionalAttribute() [4/5]
template<typename AttrType > OptionalParseResult mlir::AsmParser::parseOptionalAttribute (AttrType & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an optional attribute of a specific type and add it to the list with the specified name.
Definition at line 680 of file OpImplementation.h.
parseOptionalAttribute() [5/5]
template<typename AttrType > OptionalParseResult mlir::AsmParser::parseOptionalAttribute (AttrType & result, Type type, StringRef attrName, NamedAttrList & attrs) inline
Parse an optional attribute of a specific type and add it to the list with the specified name.
Definition at line 689 of file OpImplementation.h.
References mlir::NamedAttrList::append(), mlir::OptionalParseResult::hasValue(), and mlir::succeeded().
parseOptionalColon()
virtual ParseResult mlir::AsmParser::parseOptionalColon () pure virtual
Parse a : token if present.
Referenced by parseAnyType(), parseQuantParams(), parseTargetEnvAttr(), and parseUniformType().
parseOptionalColonTypeList()
virtual ParseResult mlir::AsmParser::parseOptionalColonTypeList (SmallVectorImpl< Type > & result) pure virtual
Parse an optional colon followed by a type list, which if present must have at least one type.
Referenced by parseGlobalOp().
parseOptionalComma()
virtual ParseResult mlir::AsmParser::parseOptionalComma () pure virtual
Parse a , token if present.
Referenced by foldTransferInBoundsAttribute(), getOption(), mlir::DataLayoutSpecAttr::parse(), parseAffineParallelOp(), parseAttributions(), parseCopyMemoryOp(), parseCreateOperationOpAttributes(), parseEntryPointOp(), parseExecutionModeOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseInterfaceVarABIAttr(), parseKeywordList(), parseLinearClause(), parseLoopOp(), parseOperandList(), parseOperationOpAttributes(), parseOptionalArrayStride(), parseReductionVarList(), mlir::parseReshapeLikeOp(), parseScheduleClause(), parseSelectOp(), parseSpecConstantCompositeOp(), parseStructMemberDecorations(), parseStructType(), parseSwitchOpCases(), parseSynchronizationHint(), parseTransferReadOp(), and parseUniformType().
parseOptionalEllipsis()
virtual ParseResult mlir::AsmParser::parseOptionalEllipsis () pure virtual
Parse a ... token if present;.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalEqual()
virtual ParseResult mlir::AsmParser::parseOptionalEqual () pure virtual
Parse a = token if present.
Referenced by parseGlobalMemrefOpTypeAndInitialValue(), parseScheduleClause(), and parseStructMemberDecorations().
parseOptionalGreater()
virtual ParseResult mlir::AsmParser::parseOptionalGreater () pure virtual
Parse a '>' token if present.
Referenced by mlir::DataLayoutSpecAttr::parse(), parseIncludeOp(), and parseStructType().
parseOptionalInteger() [1/2]
virtual OptionalParseResult mlir::AsmParser::parseOptionalInteger (APInt & result) pure virtual
Parse an optional integer value from the stream.
Referenced by parseInterfaceVarABIAttr(), parseStructMemberDecorations(), and parseSwitchOpCases().
parseOptionalInteger() [2/2]
template<typename IntT > OptionalParseResult mlir::AsmParser::parseOptionalInteger (IntT & result) inline
Definition at line 523 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::OptionalParseResult::hasValue(), and mlir::success().
parseOptionalKeyword() [1/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef keyword) pure virtual
Parse the given keyword if present.
Referenced by getOption(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAsyncDependencies(), parseAtomicReductionRegion(), parseAttributions(), parseBound(), parseClauses(), parseCommonStructuredOpParts(), parseControlAttribute(), parseFenceOp(), parseForOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseLandingpadOp(), parseLaunchFuncOperands(), parseLaunchOp(), parseLoadOp(), parseLoopOp(), parseModuleOp(), parseOperandList(), parseOptionalKeywordAlternative(), parseOptionalOperand(), parseOptionalOperandAndType(), mlir::impl::parseOptionalVisibilityKeyword(), parseParallelOp(), parserOptionalOperandAndTypeWithPrefix(), parseSpecConstantOp(), parseStoreOp(), parseStructType(), parseSynchronizationHint(), parseTargetEnvAttr(), parseTiledLoopOp(), parseVariableDecorations(), parseVariableOp(), and parseWsLoopOp().
parseOptionalKeyword() [2/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef * keyword) pure virtual
Parse a keyword, if present, into 'keyword'.
parseOptionalKeyword() [3/3]
virtual ParseResult mlir::AsmParser::parseOptionalKeyword (StringRef * keyword, ArrayRef< StringRef > allowedValues) pure virtual
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
parseOptionalKeywordOrString()
virtual ParseResult mlir::AsmParser::parseOptionalKeywordOrString (std::string * result) pure virtual
Parse an optional keyword or string.
parseOptionalLBrace()
virtual ParseResult mlir::AsmParser::parseOptionalLBrace () pure virtual
Parse a { token if present.
Referenced by parseCreateOperationOpAttributes(), and parseOperationOpAttributes().
parseOptionalLess()
virtual ParseResult mlir::AsmParser::parseOptionalLess () pure virtual
Parse a '<' token if present.
Referenced by parseIncludeOp(), and parseStorageRange().
parseOptionalLocationSpecifier()
virtual ParseResult mlir::AsmParser::parseOptionalLocationSpecifier (Optional< Location > & result) pure virtual
Parse a loc(...) specifier if present, filling in result if so.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalLParen()
virtual ParseResult mlir::AsmParser::parseOptionalLParen () pure virtual
Parse a (token if present.
Referenced by parseClauses(), parseFunctionResultList(), parseLandingpadOp(), parseLoopOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOptionalOperandAndType(), and parseSwitchOpCases().
parseOptionalLSquare()
virtual ParseResult mlir::AsmParser::parseOptionalLSquare () pure virtual
Parse a [ token if present.
Referenced by parseBranchConditionalOp(), parseExecuteOp(), parseImageOperands(), parseMemoryAccessAttributes(), parseSourceMemoryAccessAttributes(), and parseStructType().
parseOptionalPlus()
virtual ParseResult mlir::AsmParser::parseOptionalPlus () pure virtual
Parse a '+' token if present.
parseOptionalQuestion()
virtual ParseResult mlir::AsmParser::parseOptionalQuestion () pure virtual
Parse a '?' token if present.
parseOptionalRBrace()
virtual ParseResult mlir::AsmParser::parseOptionalRBrace () pure virtual
Parse a } token if present.
parseOptionalRParen()
virtual ParseResult mlir::AsmParser::parseOptionalRParen () pure virtual
Parse a) token if present.
Referenced by parseAttributions(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalOp(), parseOperandList(), and parseStructType().
parseOptionalRSquare()
virtual ParseResult mlir::AsmParser::parseOptionalRSquare () pure virtual
Parse a ] token if present.
Referenced by parseKeywordList(), parseOperandsOrIntegersImpl(), mlir::parseReshapeLikeOp(), and parseStructMemberDecorations().
parseOptionalStar()
virtual ParseResult mlir::AsmParser::parseOptionalStar () pure virtual
Parse a '*' token if present.
parseOptionalString()
virtual ParseResult mlir::AsmParser::parseOptionalString (std::string * string) pure virtual
Parse a quoted string token if present.
Referenced by mlir::DataLayoutEntryAttr::parse().
parseOptionalSymbolName()
virtual ParseResult mlir::AsmParser::parseOptionalSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) pure virtual
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Referenced by parseModuleOp().
parseOptionalType()
virtual OptionalParseResult mlir::AsmParser::parseOptionalType (Type & result) pure virtual
Parse an optional type.
Referenced by mlir::DataLayoutEntryAttr::parse(), and parseStorageType().
parsePlus()
virtual ParseResult mlir::AsmParser::parsePlus () pure virtual
Parse a '+' token.
parseQuestion()
virtual ParseResult mlir::AsmParser::parseQuestion () pure virtual
Parse a '?' token.
parseRBrace()
virtual ParseResult mlir::AsmParser::parseRBrace () pure virtual
Parse a } token.
Referenced by parseCreateOperationOpAttributes(), parseOperationOpAttributes(), and parseUniformType().
parseRParen()
virtual ParseResult mlir::AsmParser::parseRParen () pure virtual
Parse a) token.
Referenced by parseAffineParallelOp(), parseAttributions(), parseClauses(), parseCommonStructuredOpParts(), parseControlAttribute(), parseFenceOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalOp(), parseGlobalVariableOp(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseLandingpadOp(), parseLinearClause(), parseLoopOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandList(), parseOptionalOperand(), parseOptionalOperandAndType(), parseReduceOp(), parseReductionVarList(), parseScheduleClause(), parseSizeAssignment(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseStructType(), parseSwitchOpCases(), parseSynchronizationHint(), parseVariableDecorations(), and parseVariableOp().
parseRSquare()
virtual ParseResult mlir::AsmParser::parseRSquare () pure virtual
Parse a ] token.
Referenced by parseBranchConditionalOp(), parseExecuteOp(), parseExtractElementOp(), parseImageOperands(), parseInsertElementOp(), parseKeywordList(), parseMemoryAccessAttributes(), mlir::parseReshapeLikeOp(), parseSourceMemoryAccessAttributes(), parseStructMemberDecorations(), and parseTiledLoopOp().
parseStar()
virtual ParseResult mlir::AsmParser::parseStar () pure virtual
Parse a '*' token.
parseString()
ParseResult mlir::AsmParser::parseString (std::string * string) inline
Parse a quoted string token.
Definition at line 430 of file OpImplementation.h.
References mlir::emitError(), and mlir::success().
Referenced by mlir::FieldParser< std::string >::parse().
parseSymbolName()
ParseResult mlir::AsmParser::parseSymbolName (StringAttr & result, StringRef attrName, NamedAttrList & attrs) inline
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
Definition at line 718 of file OpImplementation.h.
References mlir::emitError(), mlir::failed(), mlir::parseType(), and mlir::success().
Referenced by parseFuncOp(), parseFunctionLibraryOp(), mlir::function_like_impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseSpecConstantCompositeOp(), and parseSpecConstantOp().
parseType() [1/2]
virtual ParseResult mlir::AsmParser::parseType (Type & result) pure virtual
Parse a type.
Referenced by mlir::FieldParser< TypeT, std::enable_if_t< std::is_base_of< Type, TypeT >::value, TypeT > >::parse(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAndVerifyMatrixType(), parseAndVerifySampledImageType(), parseAndVerifyType(), parseAnyType(), parseAtomicWriteOp(), parseAwaitResultType(), parseCallOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseExpressedTypeAndRange(), parseExtractValueOp(), mlir::function_like_impl::parseFunctionArgumentList(), parseFunctionResultList(), parseGlobalMemrefOpTypeAndInitialValue(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), mlir::parseReshapeLikeOp(), parseResultsValueType(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStorageType(), parseStoreOp(), parseStructType(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseUniformType(), and parseVariableOp().
parseType() [2/2]
template<typename TypeT > ParseResult mlir::AsmParser::parseType (TypeT & result) inline
Parse a type of a specific type.
Definition at line 748 of file OpImplementation.h.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::parseType(), and mlir::success().
parseTypeList()
ParseResult mlir::AsmParser::parseTypeList (SmallVectorImpl< Type > & result) inline
Parse a type list.
Definition at line 765 of file OpImplementation.h.
References mlir::failure(), mlir::parseType(), mlir::succeeded(), and mlir::success().
Referenced by parseAccessChainOp(), and parsePtrAccessChainOpImpl().
parseXInDimensionList()
virtual ParseResult mlir::AsmParser::parseXInDimensionList () pure virtual
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
printIntegerSet()
virtual ParseResult mlir::AsmParser::printIntegerSet (IntegerSet & set) pure virtual
Parse an integer set instance into 'set'.
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/AsmPrinter.cpp