MLIR: mlir::GlobalCreator Class Reference
mlir::GlobalCreator Class Reference
#include "mlir/Transforms/BufferUtils.h"
Public Member Functions
GlobalCreator (ModuleOp module, unsigned alignment=0)
memref::GlobalOp getGlobalFor (arith::ConstantOp constantOp)
Detailed Description
Definition at line 127 of file BufferUtils.h.
Constructor & Destructor Documentation
GlobalCreator()
mlir::GlobalCreator::GlobalCreator (ModuleOp module, unsigned alignment = 0) inline
Definition at line 129 of file BufferUtils.h.
Member Function Documentation
getGlobalFor()
memref::GlobalOp GlobalCreator::getGlobalFor (arith::ConstantOp constantOp)
Definition at line 25 of file TensorConstantBufferize.cpp.
References mlir::failure(), getGlobalFor(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize(), and getGlobalFor().
The documentation for this class was generated from the following files:
include/mlir/Transforms/BufferUtils.h
lib/Dialect/StandardOps/Transforms/TensorConstantBufferize.cpp