MLIR: mlir::OpAsmParser Class Reference
mlir::OpAsmParser Class Reference abstract
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
#include "mlir/IR/OpImplementation.h"
Classes
struct OperandType
This is the representation of an operand reference.
Public Member Functions
~OpAsmParser () override
virtual std::pair< StringRef, unsigned > getResultName (unsigned resultNo) const =0
Return the name of the specified result in the specified syntax, as well as the sub-element in the name.
virtual size_t getNumResults () const =0
Return the number of declared SSA results.
virtual Operation * parseGenericOperation (Block *insertBlock, Block::iterator insertPt)=0
Parse an operation in its generic form.
virtual FailureOr< OperationName > parseCustomOperationName ()=0
Parse the name of an operation, in the custom form.
virtual ParseResult parseGenericOperationAfterOpName (OperationState &result, Optional< ArrayRef< OperandType >> parsedOperandType=llvm::None, Optional< ArrayRef< Block *>> parsedSuccessors=llvm::None, Optional< MutableArrayRef< std::unique_ptr< Region >>> parsedRegions=llvm::None, Optional< ArrayRef< NamedAttribute >> parsedAttributes=llvm::None, Optional< FunctionType > parsedFnType=llvm::None)=0
Parse different components, viz., use-info of operand(s), successor(s), region(s), attribute(s) and function-type, of the generic form of an operation instance and populate the input operation-state 'result' with those components.
virtual ParseResult parseOperand (OperandType &result)=0
Parse a single operand.
virtual OptionalParseResult parseOptionalOperand (OperandType &result)=0
Parse a single operand if present.
virtual ParseResult parseOperandList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more SSA comma-separated operand references with a specified surrounding delimiter, and an optional required operand count.
ParseResult parseOperandList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult parseTrailingOperandList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more trailing SSA comma-separated trailing operand references with a specified surrounding delimiter, and an optional required operand count.
ParseResult parseTrailingOperandList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult resolveOperand (const OperandType &operand, Type type, SmallVectorImpl< Value > &result)=0
Resolve an operand to an SSA value, emitting an error on failure.
ParseResult resolveOperands (ArrayRef< OperandType > operands, Type type, SmallVectorImpl< Value > &result)
Resolve a list of operands to SSA values, emitting an error on failure, or appending the results to the list on success.
ParseResult resolveOperands (ArrayRef< OperandType > operands, ArrayRef< Type > types, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
Resolve a list of operands and a list of operand types to SSA values, emitting an error and returning failure, or appending the results to the list on success.
template<typename Operands >
ParseResult resolveOperands (Operands &&operands, Type type, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
template<typename Operands , typename Types >
std::enable_if_t<!std::is_convertible< Types, Type >::value, ParseResult > resolveOperands (Operands &&operands, Types &&types, llvm::SMLoc loc, SmallVectorImpl< Value > &result)
virtual ParseResult parseAffineMapOfSSAIds (SmallVectorImpl< OperandType > &operands, Attribute &map, StringRef attrName, NamedAttrList &attrs, Delimiter delimiter=Delimiter::Square)=0
Parses an affine map attribute where dims and symbols are SSA operands.
virtual ParseResult parseAffineExprOfSSAIds (SmallVectorImpl< OperandType > &dimOperands, SmallVectorImpl< OperandType > &symbOperands, AffineExpr &expr)=0
Parses an affine expression where dims and symbols are SSA operands.
virtual ParseResult parseRegion (Region &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region.
virtual OptionalParseResult parseOptionalRegion (Region &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region if present.
virtual OptionalParseResult parseOptionalRegion (std::unique_ptr< Region > &region, ArrayRef< OperandType > arguments={}, ArrayRef< Type > argTypes={}, bool enableNameShadowing=false)=0
Parses a region if present.
virtual ParseResult parseRegionArgument (OperandType &argument)=0
Parse a region argument, this argument is resolved when calling 'parseRegion'.
virtual ParseResult parseRegionArgumentList (SmallVectorImpl< OperandType > &result, int requiredOperandCount=-1, Delimiter delimiter=Delimiter::None)=0
Parse zero or more region arguments with a specified surrounding delimiter, and an optional required argument count.
virtual ParseResult parseRegionArgumentList (SmallVectorImpl< OperandType > &result, Delimiter delimiter)
virtual ParseResult parseOptionalRegionArgument (OperandType &argument)=0
Parse a region argument if present.
virtual ParseResult parseSuccessor (Block *&dest)=0
Parse a single operation successor.
virtual OptionalParseResult parseOptionalSuccessor (Block *&dest)=0
Parse an optional operation successor.
virtual ParseResult parseSuccessorAndUseList (Block *&dest, SmallVectorImpl< Value > &operands)=0
Parse a single operation successor and its operand list.
ParseResult parseAssignmentList (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs)
Parse a list of assignments of the form (x1 = y1, x2 = y2, ...)
virtual OptionalParseResult parseOptionalAssignmentList (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs)=0
ParseResult parseAssignmentListWithTypes (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs, SmallVectorImpl< Type > &types)
Parse a list of assignments of the form (x1 = y1 : type1, x2 = y2 : type2, ...)
virtual OptionalParseResult parseOptionalAssignmentListWithTypes (SmallVectorImpl< OperandType > &lhs, SmallVectorImpl< OperandType > &rhs, SmallVectorImpl< Type > &types)=0
Public Member Functions inherited from mlir::AsmParser
AsmParser ()=default
virtual ~AsmParser ()
MLIRContext * getContext () const
virtual llvm::SMLoc getNameLoc () const =0
Return the location of the original name token.
virtual InFlightDiagnostic emitError (llvm::SMLoc loc, const Twine &message={})=0
Emit a diagnostic at the specified location and return failure.
virtual Builder & getBuilder () const =0
Return a builder which provides useful access to MLIRContext, global objects like types and attributes.
virtual llvm::SMLoc getCurrentLocation ()=0
Get the location of the next token and store it into the argument.
ParseResult getCurrentLocation (llvm::SMLoc *loc)
virtual Location getEncodedSourceLoc (llvm::SMLoc loc)=0
Re-encode the given source location as an MLIR location and return it.
virtual ParseResult parseArrow ()=0
Parse a '->' token.
virtual ParseResult parseOptionalArrow ()=0
Parse a '->' token if present.
virtual ParseResult parseLBrace ()=0
Parse a { token.
virtual ParseResult parseOptionalLBrace ()=0
Parse a { token if present.
virtual ParseResult parseRBrace ()=0
Parse a } token.
virtual ParseResult parseOptionalRBrace ()=0
Parse a } token if present.
virtual ParseResult parseColon ()=0
Parse a : token.
virtual ParseResult parseOptionalColon ()=0
Parse a : token if present.
virtual ParseResult parseComma ()=0
Parse a , token.
virtual ParseResult parseOptionalComma ()=0
Parse a , token if present.
virtual ParseResult parseEqual ()=0
Parse a = token.
virtual ParseResult parseOptionalEqual ()=0
Parse a = token if present.
virtual ParseResult parseLess ()=0
Parse a '<' token.
virtual ParseResult parseOptionalLess ()=0
Parse a '<' token if present.
virtual ParseResult parseGreater ()=0
Parse a '>' token.
virtual ParseResult parseOptionalGreater ()=0
Parse a '>' token if present.
virtual ParseResult parseQuestion ()=0
Parse a '?' token.
virtual ParseResult parseOptionalQuestion ()=0
Parse a '?' token if present.
virtual ParseResult parsePlus ()=0
Parse a '+' token.
virtual ParseResult parseOptionalPlus ()=0
Parse a '+' token if present.
virtual ParseResult parseStar ()=0
Parse a '*' token.
virtual ParseResult parseOptionalStar ()=0
Parse a '*' token if present.
ParseResult parseString (std::string *string)
Parse a quoted string token.
virtual ParseResult parseOptionalString (std::string *string)=0
Parse a quoted string token if present.
ParseResult parseKeyword (StringRef keyword, const Twine &msg="")
Parse a given keyword.
ParseResult parseKeyword (StringRef *keyword)
Parse a keyword into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef keyword)=0
Parse the given keyword if present.
virtual ParseResult parseOptionalKeyword (StringRef *keyword)=0
Parse a keyword, if present, into 'keyword'.
virtual ParseResult parseOptionalKeyword (StringRef *keyword, ArrayRef< StringRef > allowedValues)=0
Parse a keyword, if present, and if one of the 'allowedValues', into 'keyword'.
ParseResult parseKeywordOrString (std::string *result)
Parse a keyword or a quoted string.
virtual ParseResult parseOptionalKeywordOrString (std::string *result)=0
Parse an optional keyword or string.
virtual ParseResult parseLParen ()=0
Parse a (token.
virtual ParseResult parseOptionalLParen ()=0
Parse a (token if present.
virtual ParseResult parseRParen ()=0
Parse a) token.
virtual ParseResult parseOptionalRParen ()=0
Parse a) token if present.
virtual ParseResult parseLSquare ()=0
Parse a [ token.
virtual ParseResult parseOptionalLSquare ()=0
Parse a [ token if present.
virtual ParseResult parseRSquare ()=0
Parse a ] token.
virtual ParseResult parseOptionalRSquare ()=0
Parse a ] token if present.
virtual ParseResult parseOptionalEllipsis ()=0
Parse a ... token if present;.
virtual ParseResult parseFloat (double &result)=0
Parse a floating point value from the stream.
template<typename IntT >
ParseResult parseInteger (IntT &result)
Parse an integer value from the stream.
virtual OptionalParseResult parseOptionalInteger (APInt &result)=0
Parse an optional integer value from the stream.
template<typename IntT >
OptionalParseResult parseOptionalInteger (IntT &result)
virtual ParseResult parseCommaSeparatedList (Delimiter delimiter, function_ref< ParseResult()> parseElementFn, StringRef contextMessage=StringRef())=0
Parse a list of comma-separated items with an optional delimiter.
ParseResult parseCommaSeparatedList (function_ref< ParseResult()> parseElementFn)
Parse a comma separated list of elements that must have at least one entry in it.
template<typename T , typename... ParamsT>
T getChecked (llvm::SMLoc loc, ParamsT &&... params)
Invoke the getChecked method of the given Attribute or Type class, using the provided location to emit errors in the case of failure.
template<typename T , typename... ParamsT>
T getChecked (ParamsT &&... params)
A variant of getChecked that uses the result of getNameLoc to emit errors.
virtual ParseResult parseAttribute (Attribute &result, Type type={})=0
Parse an arbitrary attribute of a given type and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type={})
Parse an attribute of a specific kind and type.
ParseResult parseAttribute (Attribute &result, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute and return it in result.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an attribute of a specific kind and type.
template<typename AttrType >
ParseResult parseAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an arbitrary attribute of a given type and return it in result.
virtual OptionalParseResult parseOptionalAttribute (Attribute &result, Type type={})=0
Parse an arbitrary optional attribute of a given type and return it in result.
virtual OptionalParseResult parseOptionalAttribute (ArrayAttr &result, Type type={})=0
Parse an optional array attribute and return it in result.
virtual OptionalParseResult parseOptionalAttribute (StringAttr &result, Type type={})=0
Parse an optional string attribute and return it in result.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
template<typename AttrType >
OptionalParseResult parseOptionalAttribute (AttrType &result, Type type, StringRef attrName, NamedAttrList &attrs)
Parse an optional attribute of a specific type and add it to the list with the specified name.
virtual ParseResult parseOptionalAttrDict (NamedAttrList &result)=0
Parse a named dictionary into 'result' if it is present.
virtual ParseResult parseOptionalAttrDictWithKeyword (NamedAttrList &result)=0
Parse a named dictionary into 'result' if the attributes keyword is present.
virtual ParseResult parseAffineMap (AffineMap &map)=0
Parse an affine map instance into 'map'.
virtual ParseResult printIntegerSet (IntegerSet &set)=0
Parse an integer set instance into 'set'.
ParseResult parseSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)
Parse an -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalSymbolName (StringAttr &result, StringRef attrName, NamedAttrList &attrs)=0
Parse an optional -identifier and store it (without the '@' symbol) in a string attribute named 'attrName'.
virtual ParseResult parseOptionalLocationSpecifier (Optional< Location > &result)=0
Parse a loc(...) specifier if present, filling in result if so.
virtual ParseResult parseType (Type &result)=0
Parse a type.
virtual OptionalParseResult parseOptionalType (Type &result)=0
Parse an optional type.
template<typename TypeT >
ParseResult parseType (TypeT &result)
Parse a type of a specific type.
ParseResult parseTypeList (SmallVectorImpl< Type > &result)
Parse a type list.
virtual ParseResult parseArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an arrow followed by a type list.
virtual ParseResult parseOptionalArrowTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional arrow followed by a type list.
virtual ParseResult parseColonType (Type &result)=0
Parse a colon followed by a type.
template<typename TypeType >
ParseResult parseColonType (TypeType &result)
Parse a colon followed by a type of a specific kind, e.g. a FunctionType.
virtual ParseResult parseColonTypeList (SmallVectorImpl< Type > &result)=0
Parse a colon followed by a type list, which must have at least one type.
virtual ParseResult parseOptionalColonTypeList (SmallVectorImpl< Type > &result)=0
Parse an optional colon followed by a type list, which if present must have at least one type.
ParseResult parseKeywordType (const char *keyword, Type &result)
Parse a keyword followed by a type.
ParseResult addTypeToList (Type type, SmallVectorImpl< Type > &result)
Add the specified type to the end of the specified type list and return success.
ParseResult addTypesToList (ArrayRef< Type > types, SmallVectorImpl< Type > &result)
Add the specified types to the end of the specified type list and return success.
virtual ParseResult parseDimensionList (SmallVectorImpl< int64_t > &dimensions, bool allowDynamic=true)=0
Parse a 'x' separated dimension list.
virtual ParseResult parseXInDimensionList ()=0
Parse an 'x' token in a dimension list, handling the case where the x is juxtaposed with an element type, as in "xf32", leaving the "f32" as the next token.
Additional Inherited Members
Public Types inherited from mlir::AsmParser
enum Delimiter {
Delimiter::None, Delimiter::Paren, Delimiter::Square, Delimiter::LessGreater,
Delimiter::Braces, Delimiter::OptionalParen, Delimiter::OptionalSquare, Delimiter::OptionalLessGreater,
Delimiter::OptionalBraces
}
These are the supported delimiters around operand lists and region argument lists, used by parseOperandList and parseRegionArgumentList.
Detailed Description
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
It has an intentionally high-level API that is designed to reduce/constrain syntax innovation in individual operations.
For example, consider an op like this:
x = load p[%1, %2] : memref<...>
The "%x = load" tokens are already parsed and therefore invisible to the custom op parser. This can be supported by calling parseOperandList to parse the p, then calling parseOperandList with a SquareDelimiter to parse the indices, then calling parseColonTypeList to parse the result type.
Definition at line 875 of file OpImplementation.h.
Constructor & Destructor Documentation
~OpAsmParser()
OpAsmParser::~OpAsmParser () override
Definition at line 59 of file AsmPrinter.cpp.
Member Function Documentation
getNumResults()
virtual size_t mlir::OpAsmParser::getNumResults () const pure virtual
Return the number of declared SSA results.
This returns 4 for the foo.op example in the comment for getResultName.
Referenced by parseAsyncDependencies().
getResultName()
virtual std::pair<StringRef, unsigned> mlir::OpAsmParser::getResultName (unsigned resultNo) const pure virtual
Return the name of the specified result in the specified syntax, as well as the sub-element in the name.
It returns an empty string and ~0U for invalid result numbers. For example, in this operation:
x, y:2, z = foo.op
getResultName(0) == {"x", 0 } getResultName(1) == {"y", 0 } getResultName(2) == {"y", 1 } getResultName(3) == {"z", 0 } getResultName(4) == {"", ~0U }
parseAffineExprOfSSAIds()
virtual ParseResult mlir::OpAsmParser::parseAffineExprOfSSAIds (SmallVectorImpl< OperandType > & dimOperands, SmallVectorImpl< OperandType > & symbOperands, AffineExpr & expr) pure virtual
Parses an affine expression where dims and symbols are SSA operands.
Operand values must come from single-result sources, and be valid dimensions/symbol identifiers according to mlir::isValidDim/Symbol.
parseAffineMapOfSSAIds()
virtual ParseResult mlir::OpAsmParser::parseAffineMapOfSSAIds (SmallVectorImpl< OperandType > & operands, Attribute & map, StringRef attrName, NamedAttrList & attrs, Delimiter delimiter = Delimiter::Square) pure virtual
Parses an affine map attribute where dims and symbols are SSA operands.
Operand values must come from single-result sources, and be valid dimensions/symbol identifiers according to mlir::isValidDim/Symbol.
Referenced by mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineLoadOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), and parseAffineVectorStoreOp().
parseAssignmentList()
ParseResult mlir::OpAsmParser::parseAssignmentList (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs) inline
Parse a list of assignments of the form (x1 = y1, x2 = y2, ...)
Definition at line 1109 of file OpImplementation.h.
Referenced by parseAffineForOp(), and parseForOp().
parseAssignmentListWithTypes()
ParseResult mlir::OpAsmParser::parseAssignmentListWithTypes (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs, SmallVectorImpl< Type > & types) inline
Parse a list of assignments of the form (x1 = y1 : type1, x2 = y2 : type2, ...)
Definition at line 1123 of file OpImplementation.h.
References mlir::emitError(), mlir::OptionalParseResult::getValue(), and mlir::OptionalParseResult::hasValue().
Referenced by parseTiledLoopOp().
parseCustomOperationName()
virtual FailureOr<OperationName> mlir::OpAsmParser::parseCustomOperationName () pure virtual
Parse the name of an operation, in the custom form.
On success, return a an object of type 'OperationName'. Otherwise, failure is returned.
parseGenericOperation()
virtual Operation* mlir::OpAsmParser::parseGenericOperation (Block * insertBlock, Block::iterator insertPt) pure virtual
Parse an operation in its generic form.
The parsed operation is parsed in the current context and inserted in the provided block and insertion point. The results produced by this operation aren't mapped to any named value in the parser. Returns nullptr on failure.
Referenced by parseSpecConstantOperationOp().
parseGenericOperationAfterOpName()
virtual ParseResult mlir::OpAsmParser::parseGenericOperationAfterOpName (OperationState & result, Optional< ArrayRef< OperandType >> parsedOperandType = llvm::None, Optional< ArrayRef< Block *>> parsedSuccessors = llvm::None, Optional< MutableArrayRef< std::unique_ptr< Region >>> parsedRegions = llvm::None, Optional< ArrayRef< NamedAttribute >> parsedAttributes = llvm::None, Optional< FunctionType > parsedFnType = llvm::None) pure virtual
Parse different components, viz., use-info of operand(s), successor(s), region(s), attribute(s) and function-type, of the generic form of an operation instance and populate the input operation-state 'result' with those components.
If any of the components is explicitly provided, then skip parsing that component.
parseOperand()
virtual ParseResult mlir::OpAsmParser::parseOperand (OperandType & result) pure virtual
Parse a single operand.
Referenced by foldTransferInBoundsAttribute(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocateAndAllocator(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicReadOp(), parseAtomicRMWOp(), parseAtomicWriteOp(), parseBranchConditionalOp(), mlir::impl::parseCastOp(), parseClauses(), parseCompositeExtractOp(), parseContractionOp(), parseCopyMemoryOp(), parseCreateOperationOpAttributes(), parseDmaStartOp(), parseExecuteOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseForEachOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseLandingpadOp(), parseLaunchOp(), parseLinearClause(), parseLoadOp(), parseLogicalUnaryOp(), parseOperandAndType(), parseOperandAndTypeList(), parseOperationOpAttributes(), parseOptionalOperand(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReduceOp(), parseReductionVarList(), mlir::parseReshapeLikeOp(), parseScheduleClause(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseTransferReadOp(), parseTransposeOp(), parseUnaryOp(), parseVariableOp(), and parseViewOp().
parseOperandList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseOperandList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more SSA comma-separated operand references with a specified surrounding delimiter, and an optional required operand count.
Referenced by foldTransferInBoundsAttribute(), parseAccessChainOp(), parseAffineMinMaxOp(), parseAsyncDependencies(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), parseBound(), parseCallOp(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeInsertOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), mlir::parseDimAndSymbolList(), parseDmaStartOp(), parseExecuteOp(), parseGenericAtomicRMWOp(), parseInvokeOp(), parseLogicalBinaryOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReduceOp(), parseReductionOp(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseStoreOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseViewOp(), parseWsLoopOp(), and parseYieldOp().
parseOperandList() [2/2]
ParseResult mlir::OpAsmParser::parseOperandList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline
Definition at line 951 of file OpImplementation.h.
References parseOperandList().
parseOptionalAssignmentList()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAssignmentList (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs) pure virtual
Referenced by verify().
parseOptionalAssignmentListWithTypes()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalAssignmentListWithTypes (SmallVectorImpl< OperandType > & lhs, SmallVectorImpl< OperandType > & rhs, SmallVectorImpl< Type > & types) pure virtual
parseOptionalOperand()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalOperand (OperandType & result) pure virtual
Parse a single operand if present.
parseOptionalRegion() [1/2]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalRegion (Region & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region if present.
Referenced by parseFuncOp(), mlir::function_like_impl::parseFunctionLikeOp(), and parseGlobalOp().
parseOptionalRegion() [2/2]
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalRegion (std::unique_ptr< Region > & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region if present.
If the region is present, a new region is allocated and placed in region. If no region is present or on failure, region remains untouched.
parseOptionalRegionArgument()
virtual ParseResult mlir::OpAsmParser::parseOptionalRegionArgument (OperandType & argument) pure virtual
Parse a region argument if present.
Referenced by mlir::function_like_impl::parseFunctionArgumentList().
parseOptionalSuccessor()
virtual OptionalParseResult mlir::OpAsmParser::parseOptionalSuccessor (Block *& dest) pure virtual
Parse an optional operation successor.
parseRegion()
virtual ParseResult mlir::OpAsmParser::parseRegion (Region & region, ArrayRef< OperandType > arguments = {}, ArrayRef< Type > argTypes = {}, bool enableNameShadowing = false) pure virtual
Parses a region.
Any parsed blocks are appended to 'region' and must be moved to the op regions after the op is created. The first block of the region takes 'arguments' of types 'argTypes'. If 'enableNameShadowing' is set to true, the argument names are allowed to shadow the names of other existing SSA values defined above the region scope. 'enableNameShadowing' can only be set to true for regions attached to operations that are 'IsolatedFromAbove.
Referenced by parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAllocaScopeOp(), parseAssumingOp(), parseAtomicReductionRegion(), parseExecuteOp(), parseExecuteRegionOp(), parseForEachOp(), parseForOp(), parseFunctionLibraryOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseLaunchOp(), parseLoopOp(), parseModuleOp(), parseParallelOp(), parseReduceOp(), parseRegions(), parseSectionsOp(), parseSelectionOp(), parseTiledLoopOp(), parseWsLoopOp(), and verify().
parseRegionArgument()
virtual ParseResult mlir::OpAsmParser::parseRegionArgument (OperandType & argument) pure virtual
Parse a region argument, this argument is resolved when calling 'parseRegion'.
Referenced by parseAffineForOp(), parseAttributions(), parseForEachOp(), parseForOp(), parseOperandList(), and parseSizeAssignment().
parseRegionArgumentList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseRegionArgumentList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more region arguments with a specified surrounding delimiter, and an optional required argument count.
Region arguments define new values; so this also checks if values with the same names have not been defined yet.
Referenced by parseAffineParallelOp(), parseParallelOp(), parseSizeAssignment(), parseSwitchOpCases(), parseTiledLoopOp(), and parseWsLoopOp().
parseRegionArgumentList() [2/2]
virtual ParseResult mlir::OpAsmParser::parseRegionArgumentList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline virtual
Definition at line 1080 of file OpImplementation.h.
parseSuccessor()
virtual ParseResult mlir::OpAsmParser::parseSuccessor (Block *& dest) pure virtual
Parse a single operation successor.
Referenced by parseForEachOp(), and parseSwitchOpCases().
parseSuccessorAndUseList()
virtual ParseResult mlir::OpAsmParser::parseSuccessorAndUseList (Block *& dest, SmallVectorImpl< Value > & operands) pure virtual
Parse a single operation successor and its operand list.
Referenced by parseBranchConditionalOp(), and parseInvokeOp().
parseTrailingOperandList() [1/2]
virtual ParseResult mlir::OpAsmParser::parseTrailingOperandList (SmallVectorImpl< OperandType > & result, int requiredOperandCount = -1, Delimiter delimiter = Delimiter::None) pure virtual
Parse zero or more trailing SSA comma-separated trailing operand references with a specified surrounding delimiter, and an optional required operand count.
A leading comma is expected before the operands.
Referenced by mlir::AffineDmaStartOp::parse(), parseContractionOp(), and parseDmaStartOp().
parseTrailingOperandList() [2/2]
ParseResult mlir::OpAsmParser::parseTrailingOperandList (SmallVectorImpl< OperandType > & result, Delimiter delimiter) inline
Definition at line 963 of file OpImplementation.h.
resolveOperand()
virtual ParseResult mlir::OpAsmParser::resolveOperand (const OperandType & operand, Type type, SmallVectorImpl< Value > & result) pure virtual
Resolve an operand to an SSA value, emitting an error on failure.
Referenced by foldTransferInBoundsAttribute(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineForOp(), parseAffineLoadOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicReadOp(), parseAtomicRMWOp(), parseAtomicWriteOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::impl::parseCastOp(), parseClauses(), parseCompositeExtractOp(), parseContractionOp(), parseCopyMemoryOp(), parseDmaStartOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseForEachOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLoadOp(), parseLogicalUnaryOp(), parseOperandAndType(), parseOptionalOperand(), parseOuterProductOp(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReduceOp(), parseReductionOp(), mlir::parseReshapeLikeOp(), parseReturnOp(), parseShuffleOp(), parseShuffleVectorOp(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), parseTransferReadOp(), parseTransposeOp(), parseVariableOp(), and parseViewOp().
resolveOperands() [1/4]
ParseResult mlir::OpAsmParser::resolveOperands (ArrayRef< OperandType > operands, Type type, SmallVectorImpl< Value > & result) inline
Resolve a list of operands to SSA values, emitting an error on failure, or appending the results to the list on success.
This method should be used when all operands have the same type.
Definition at line 976 of file OpImplementation.h.
References mlir::failure(), and mlir::success().
Referenced by foldTransferInBoundsAttribute(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), parseCallOp(), parseClauses(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeInsertOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), mlir::parseDimAndSymbolList(), parseDmaStartOp(), parseExecuteOp(), parseGenericAtomicRMWOp(), parseInvokeOp(), parseLaunchOp(), parseLogicalBinaryOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandList(), parseParallelOp(), parsePrefetchOp(), parsePtrAccessChainOpImpl(), parseReduceOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseStoreOp(), parseSubgroupBlockWriteINTELOp(), parseTiledLoopOp(), parseTransferReadOp(), parseUnaryOp(), parseViewOp(), parseWsLoopOp(), parseYieldOp(), and verify().
resolveOperands() [2/4]
ParseResult mlir::OpAsmParser::resolveOperands (ArrayRef< OperandType > operands, ArrayRef< Type > types, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Resolve a list of operands and a list of operand types to SSA values, emitting an error and returning failure, or appending the results to the list on success.
Definition at line 987 of file OpImplementation.h.
References mlir::emitError(), mlir::failure(), and mlir::success().
resolveOperands() [3/4]
template<typename Operands > ParseResult mlir::OpAsmParser::resolveOperands (Operands && operands, Type type, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Definition at line 1001 of file OpImplementation.h.
References value.
resolveOperands() [4/4]
template<typename Operands , typename Types > std::enable_if_t<!std::is_convertible<Types, Type>::value, ParseResult> mlir::OpAsmParser::resolveOperands (Operands && operands, Types && types, llvm::SMLoc loc, SmallVectorImpl< Value > & result) inline
Definition at line 1008 of file OpImplementation.h.
References mlir::emitError(), mlir::failure(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/OpImplementation.h
lib/IR/AsmPrinter.cpp