MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.h"
#include <random>
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "comprehensive-module-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Functions
static std::string printOperationInfo (Operation *op, bool prefix)
Print the operation name and bufferization information.
static std::string printValueInfo (Value value, bool prefix)
Print the bufferization information for the defining op or block argument.
static bool isaTensor (Type t)
static void setInPlaceOpResult (OpResult opResult, bool inPlace)
Mark whether OpResult can actually be bufferized inplace.
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState &state, llvm::raw_ostream &os)
Helper method printing the bufferization information of a buffer / tensor.
static bool isInplaceMemoryWrite (OpOperand &opOperand, const BufferizationAliasInfo &aliasInfo)
Return true if opOperand has been decided to bufferize in-place.
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if, under current bufferization decisions, the buffer of value is not writable.
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo &aliasInfo)
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
static bool happensBefore (Operation *a, Operation *b, const DominanceInfo &domInfo)
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> &usesRead, const DenseSet< OpOperand *> &usesWrite, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo)
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
bool wouldCreateReadAfterWriteInterference (OpOperand &operand, OpResult result, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo, bool checkConsistencyOnly=false)
Return true if bufferizing result inplace would create a conflict.
static bool wouldCreateWriteToNonWritableBuffer (OpOperand &opOperand, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand &operand, OpResult result, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with result.
static LogicalResult inPlaceAnalysis (SmallVector< Operation *> &ops, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze the ops to determine which OpResults are inplaceable.
static LogicalResult inPlaceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze all ops that are contained in op.
static void equivalenceAnalysis (SmallVector< Operation *> &ops, BufferizationAliasInfo &aliasInfo)
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
static void equivalenceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo)
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
static LogicalResult checkAliasInfoConsistency (FuncOp funcOp, const DominanceInfo &domInfo, const BufferizationAliasInfo &aliasInfo)
Assert that the current bufferization decisions are consistent.
static void annotateOpsWithBufferizationMarkers (Operation *op, const BufferizationAliasInfo &aliasInfo)
Annotate the IR with the result of the analysis. For testing/debugging only.
Variables
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 130 of file ComprehensiveBufferize.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-module-bufferize"
Definition at line 123 of file ComprehensiveBufferize.cpp.
Referenced by printOperationInfo().
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 131 of file ComprehensiveBufferize.cpp.
Referenced by aliasesInPlaceWrite(), aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), hasReadAfterWriteInterference(), setInPlaceOpResult(), and wouldCreateWriteToNonWritableBuffer().
Function Documentation
aliasesInPlaceWrite()
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo & aliasInfo) static
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
Definition at line 283 of file ComprehensiveBufferize.cpp.
References mlir::Value::getUses(), isInplaceMemoryWrite(), LDBG, printOperationInfo(), and printValueInfo().
Referenced by wouldCreateWriteToNonWritableBuffer().
aliasesNonWritableBuffer()
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if, under current bufferization decisions, the buffer of value is not writable.
Definition at line 251 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), LDBG, and printValueInfo().
Referenced by wouldCreateWriteToNonWritableBuffer().
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (Operation * op, const BufferizationAliasInfo & aliasInfo) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 703 of file ComprehensiveBufferize.cpp.
References checkAliasInfoConsistency(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), mlir::Operation::getResults(), inPlaceAnalysis(), options, mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize(), setInPlaceOpResult(), mlir::success(), and mlir::Operation::walk().
bufferizableInPlaceAnalysisImpl()
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand & operand, OpResult result, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with result.
Definition at line 540 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), mlir::OpOperand::getOperandNumber(), mlir::OpResult::getResultNumber(), LDBG, printValueInfo(), mlir::success(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
Referenced by inPlaceAnalysis().
checkAliasInfoConsistency()
static LogicalResult checkAliasInfoConsistency (FuncOp funcOp, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo) static
Assert that the current bufferization decisions are consistent.
Definition at line 670 of file ComprehensiveBufferize.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::Operation::getOpOperands(), mlir::WalkResult::interrupt(), mlir::success(), mlir::WalkResult::wasInterrupted(), and wouldCreateReadAfterWriteInterference().
Referenced by annotateOpsWithBufferizationMarkers().
equivalenceAnalysis() [1/2]
static void equivalenceAnalysis (SmallVector< Operation *> & ops, BufferizationAliasInfo & aliasInfo) static
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
Definition at line 635 of file ComprehensiveBufferize.cpp.
Referenced by annotateOpsWithBufferizationMarkers(), and equivalenceAnalysis().
equivalenceAnalysis() [2/2]
static void equivalenceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo) static
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
Definition at line 654 of file ComprehensiveBufferize.cpp.
References equivalenceAnalysis(), mlir::Operation::getResultTypes(), isaTensor(), mlir::PostOrder, and mlir::Operation::walk().
happensBefore()
static bool happensBefore (Operation * a, Operation * b, const DominanceInfo & domInfo) static
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
Definition at line 307 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::isProperAncestor(), and mlir::DominanceInfo::properlyDominates().
Referenced by hasReadAfterWriteInterference().
hasReadAfterWriteInterference()
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> & usesRead, const DenseSet< OpOperand *> & usesWrite, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo) static
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
A conflict is: According to SSA use-def chains, a read R is supposed to read the result of a write W1. But because of bufferization decisions, R actually reads another write W2.
Definition at line 328 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), mlir::linalg::comprehensive_bufferize::findLastPrecedingWrite(), mlir::linalg::comprehensive_bufferize::getAliasingOpResult(), mlir::Value::getDefiningOp(), happensBefore(), mlir::insideMutuallyExclusiveRegions(), LDBG, printOperationInfo(), and printValueInfo().
inPlaceAnalysis() [1/2]
static LogicalResult inPlaceAnalysis (SmallVector< Operation *> & ops, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze the ops to determine which OpResults are inplaceable.
Walk ops in reverse and bufferize ops greedily. This is a good starter heuristic.
Even if an op does not read or write, it may still create an alias when bufferized in-place. An example of such ops is tensor.extract_slice.
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace:
When bufferized out of place, an ExtractSliceOp lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, an ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 589 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysisImpl(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by annotateOpsWithBufferizationMarkers(), and inPlaceAnalysis().
inPlaceAnalysis() [2/2]
static LogicalResult inPlaceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze all ops that are contained in op.
Definition at line 616 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), inPlaceAnalysis(), isaTensor(), and mlir::Operation::walk().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 139 of file ComprehensiveBufferize.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::bufferize(), mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize(), equivalenceAnalysis(), and inPlaceAnalysis().
isInplaceMemoryWrite()
static bool isInplaceMemoryWrite (OpOperand & opOperand, const BufferizationAliasInfo & aliasInfo) static
Return true if opOperand has been decided to bufferize in-place.
Definition at line 230 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite(), mlir::linalg::comprehensive_bufferize::getAliasingOpResult(), and mlir::detail::IROperandBase::getOwner().
Referenced by aliasesInPlaceWrite().
printOperationInfo()
static std::string printOperationInfo (Operation * op, bool prefix = true) static
Print the operation name and bufferization information.
Definition at line 190 of file ComprehensiveBufferize.cpp.
References DEBUG_TYPE, mlir::Operation::getName(), mlir::Operation::getOpOperands(), mlir::Operation::getOpResults(), mlir::Operation::getParentOfType(), and printTensorOrBufferInfo().
Referenced by aliasesInPlaceWrite(), hasReadAfterWriteInterference(), printValueInfo(), and setInPlaceOpResult().
printTensorOrBufferInfo()
static void printTensorOrBufferInfo (std::string prefix, Value value, AsmState & state, llvm::raw_ostream & os) static
Helper method printing the bufferization information of a buffer / tensor.
Definition at line 180 of file ComprehensiveBufferize.cpp.
References mlir::Value::getType(), mlir::Type::isa(), and mlir::Value::printAsOperand().
Referenced by printOperationInfo(), and printValueInfo().
printValueInfo()
static std::string printValueInfo (Value value, bool prefix = true) static
Print the bufferization information for the defining op or block argument.
Definition at line 211 of file ComprehensiveBufferize.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getParentOfType(), mlir::Value::getParentRegion(), printOperationInfo(), printTensorOrBufferInfo(), and value.
Referenced by aliasesInPlaceWrite(), aliasesNonWritableBuffer(), bufferizableInPlaceAnalysisImpl(), and hasReadAfterWriteInterference().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, bool inPlace) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is true, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inplace).
Definition at line 156 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, LDBG, printOperationInfo(), and mlir::Operation::setAttr().
Referenced by annotateOpsWithBufferizationMarkers().
wouldCreateReadAfterWriteInterference()
bool wouldCreateReadAfterWriteInterference (OpOperand & operand, OpResult result, const DominanceInfo & domInfo, const BufferizationAliasInfo & aliasInfo, bool checkConsistencyOnly = false)
Return true if bufferizing result inplace would create a conflict.
A read R and a write W of the same alias set is a conflict if inplace bufferization of W changes the value read by R to a value different from the one that would be expected by tracing back R's origin through SSA use-def chains. A conflict can only be introduced by a new alias and/or an inplace bufferization decision.
Example: %0 = tensor.extract_slice t[...][...][1, 1] {inplace?} %1 = vector.transfer_write v1, t {inplace} : vector<5xf32>, tensor<?xf32> e = tensor.extract_slice %1 %2 = vector.transfer_write v2, %0 {inplace} : vector<6xf32>, tensor<?xf32> %3 = vector.transfer_read e, cst : tensor<?xf32>, vector<7xf32>
In the above example, the two TransferWriteOps have already been decided to bufferize inplace. Bufferizing the ExtractSliceOp inplace would create a conflict because:
According to SSA use-def chains, we expect to read the result of %1.
However, adding an alias {%0, t} would mean that the second TransferWriteOp overwrites the first one. Therefore, the TransferReadOp would no longer be reading the result of %1.
If checkConsistencyOnly is true, this function checks if there is a read-after-write conflict without bufferizing operand inplace. This would indicate a problem with the current inplace bufferization decisions.
Note: If checkConsistencyOnly, this function may be called with a null OpResult. In that case, only the consistency of bufferization decisions involving aliases of the given OpOperand are checked.
Definition at line 453 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::getAliasingOpOperand().
Referenced by bufferizableInPlaceAnalysisImpl(), and checkAliasInfoConsistency().
wouldCreateWriteToNonWritableBuffer()
static bool wouldCreateWriteToNonWritableBuffer (OpOperand & opOperand, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
Definition at line 505 of file ComprehensiveBufferize.cpp.
References aliasesInPlaceWrite(), aliasesNonWritableBuffer(), mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), and LDBG.
Referenced by bufferizableInPlaceAnalysisImpl().
Variable Documentation
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 150 of file ComprehensiveBufferize.cpp.
Referenced by setInPlaceOpResult().