MLIR: lib/Dialect/Linalg/Transforms/Detensorize.cpp File Reference
Detensorize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/StandardOps/Transforms/FuncConversions.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <iterator>
#include <memory>
Functions
static Value sourceMaterializationCallback (OpBuilder &builder, Type type, ValueRange inputs, Location loc)
Function Documentation
sourceMaterializationCallback()
static Value sourceMaterializationCallback (OpBuilder & builder, Type type, ValueRange inputs, Location loc) static
Definition at line 24 of file Detensorize.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::TypeConverter::SignatureConversion::addInputs(), mlir::applyFullConversion(), mlir::applyPatternsAndFoldGreedily(), mlir::Block::begin(), mlir::ConversionPatternRewriter::cancelRootUpdate(), mlir::Value::cast(), mlir::ConversionPatternRewriter::convertNonEntryRegionTypes(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::ConversionPatternRewriter::finalizeRootUpdate(), mlir::BlockArgument::getArgNumber(), mlir::Value::getDefiningOp(), mlir::ShapedType::getElementType(), mlir::function_like_impl::getFunctionBody(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::BlockArgument::getOwner(), mlir::Value::getParentBlock(), mlir::ShapedType::getRank(), mlir::Operation::getResultTypes(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::Value::getUsers(), mlir::ShapedType::hasRank(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::RewritePatternSet::insert(), mlir::TypeConverter::isLegal(), mlir::isLegalForReturnOpTypeConversionPattern(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), mlir::ConversionTarget::markUnknownOpDynamicallyLegal(), mlir::ConversionPatternRewriter::mergeBlocks(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::populateBranchOpInterfaceTypeConversionPattern(), mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::Block::splitBlock(), mlir::ConversionPatternRewriter::startRootUpdate(), mlir::success(), and value.