MLIR: lib/Dialect/SCF/SCF.cpp File Reference
SCF.cpp File Reference
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Dialect/SCF/SCFOpsDialect.cpp.inc"
#include "mlir/Dialect/SCF/SCFOps.cpp.inc"
Classes
struct SingleBlockExecuteInliner
struct MultiBlockExecuteInliner
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void replaceOpWithRegion (PatternRewriter &rewriter, Operation *op, Region &region, ValueRange blockArgs={})
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
static ParseResult parseExecuteRegionOp (OpAsmParser &parser, OperationState &result)
(ssa-id =)? execute_region -> function-result-type { block+ }
static void print (OpAsmPrinter &p, ExecuteRegionOp op)
static LogicalResult verify (ExecuteRegionOp op)
static LogicalResult verify (ForOp op)
static void printInitializationList (OpAsmPrinter &p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix="")
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
static void print (OpAsmPrinter &p, ForOp op)
static ParseResult parseForOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (IfOp op)
static ParseResult parseIfOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, IfOp op)
static LogicalResult verify (ParallelOp op)
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ParallelOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
static LogicalResult verify (ReduceReturnOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseExecuteRegionOp()
static ParseResult parseExecuteRegionOp (OpAsmParser & parser, OperationState & result) static
(ssa-id =)? execute_region -> function-result-type { block+ }
Example: scf.execute_region -> i32 { idx = load rI[i] : memref<128xi32> return idx : i32 }
Definition at line 104 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::success(), and mlir::OperationState::types.
parseForOp()
static ParseResult parseForOp (OpAsmParser & parser, OperationState & result) static
Definition at line 356 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::ceilDiv(), mlir::Value::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::scf::getForInductionVarOwner(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), mlir::Value::getParentRegion(), mlir::Region::isAncestor(), mlir::OperationState::location, mlir::Operation::moveBefore(), mlir::OperationState::operands, mlir::AsmParser::parseArrowTypeList(), mlir::OpAsmParser::parseAssignmentList(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), mlir::success(), mlir::OperationState::types, and value.
parseIfOp()
static ParseResult parseIfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1090 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1717 of file SCF.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), mlir::OperationState::location, mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2024 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
print() [1/5]
static void print (OpAsmPrinter & p, ExecuteRegionOp op) static
Definition at line 118 of file SCF.cpp.
References mlir::AsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
Referenced by verify().
print() [2/5]
static void print (OpAsmPrinter & p, ForOp op) static
Definition at line 342 of file SCF.cpp.
References printInitializationList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [3/5]
static void print (OpAsmPrinter & p, IfOp op) static
Definition at line 1123 of file SCF.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Region::back(), mlir::Block::back(), mlir::OpBuilder::cloneWithoutRegions(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Region::empty(), mlir::detail::enumerate(), mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::OpResult::getResultNumber(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::RewriterBase::inlineRegionBefore(), mlir::OperationState::location, mlir::RewriterBase::mergeBlocks(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::Value::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), replaceOpWithRegion(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), mlir::RewriterBase::updateRootInPlace(), and mlir::Value::use_empty().
print() [4/5]
static void print (OpAsmPrinter & p, ParallelOp op) static
Definition at line 1788 of file SCF.cpp.
References mlir::Value::getParentRegion(), mlir::Region::isAncestor(), mlir::Operation::moveBefore(), mlir::AsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and mlir::success().
print() [5/5]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 2045 of file SCF.cpp.
References mlir::OpAsmPrinter::printRegion().
printInitializationList()
static void printInitializationList (OpAsmPrinter & p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix = "") static
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
Definition at line 326 of file SCF.cpp.
Referenced by print(), and verify().
replaceOpWithRegion()
static void replaceOpWithRegion (PatternRewriter & rewriter, Operation * op, Region & region, ValueRange blockArgs = {}) static
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
Definition at line 82 of file SCF.cpp.
References mlir::RewriterBase::eraseOp(), mlir::Region::front(), mlir::Operation::getOperands(), mlir::Block::getTerminator(), mlir::RewriterBase::mergeBlockBefore(), and mlir::RewriterBase::replaceOp().
Referenced by mlir::scf::buildLoopNest(), SingleBlockExecuteInliner::matchAndRewrite(), and print().
verify() [1/6]
static LogicalResult verify (ExecuteRegionOp op) static
Definition at line 128 of file SCF.cpp.
References mlir::success().
verify() [2/6]
static LogicalResult verify (ForOp op) static
Definition at line 279 of file SCF.cpp.
References mlir::success().
verify() [3/6]
static LogicalResult verify (IfOp op) static
Definition at line 1083 of file SCF.cpp.
verify() [4/6]
static LogicalResult verify (ParallelOp op) static
Definition at line 1656 of file SCF.cpp.
References mlir::Operation::emitOpError(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Block::getOps(), mlir::Block::getTerminator(), and mlir::success().
verify() [5/6]
static LogicalResult verify (ReduceOp op) static
Definition at line 2003 of file SCF.cpp.
References mlir::Operation::emitOpError(), mlir::Block::empty(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getTerminator(), and mlir::success().
verify() [6/6]
static LogicalResult verify (ReduceReturnOp op) static
Definition at line 2055 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::InFlightDiagnostic::attachNote(), mlir::OperationState::attributes, mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), diag(), mlir::AsmParser::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::Block::front(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getCurrentLocation(), mlir::Operation::getLoc(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::OptionalParseResult::getValue(), mlir::OptionalParseResult::hasValue(), mlir::RewriterBase::inlineRegionBefore(), mlir::RewritePatternSet::insert(), mlir::RewriterBase::mergeBlocks(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalAssignmentList(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), print(), mlir::OpAsmPrinter::printFunctionalType(), printInitializationList(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpAsmParser::resolveOperands(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), mlir::Value::use_empty(), and mlir::verify().