MLIR: lib/Dialect/Affine/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopUtils.h"
Functions
static void promoteIfBlock (AffineIfOp ifOp, bool elseBlock)
Promotes the then or the else block of ifOp (depending on whether elseBlock is false or true) into ifOp's containing block, and discards the rest of the op.
static Operation * getOutermostInvariantForOp (AffineIfOp ifOp)
Returns the outermost affine.for/parallel op that the ifOp is invariant on.
static AffineIfOp hoistAffineIfOp (AffineIfOp ifOp, Operation *hoistOverOp)
A helper for the mechanics of mlir::hoistAffineIfOp.
Function Documentation
getOutermostInvariantForOp()
static Operation* getOutermostInvariantForOp (AffineIfOp ifOp) static
Returns the outermost affine.for/parallel op that the ifOp is invariant on.
The ifOp could be hoisted and placed right before such an operation. This method assumes that the ifOp has been canonicalized (to be correct and effective).
Definition at line 44 of file Utils.cpp.
References mlir::Operation::getOperands().
Referenced by mlir::hoistAffineIfOp().
hoistAffineIfOp()
static AffineIfOp hoistAffineIfOp (AffineIfOp ifOp, Operation * hoistOverOp) static
A helper for the mechanics of mlir::hoistAffineIfOp.
Hoists ifOp just over hoistOverOp. Returns the new hoisted op if any hoisting happened, otherwise the same ifOp.
Definition at line 70 of file Utils.cpp.
References mlir::WalkResult::advance(), mlir::BlockAndValueMapping::clear(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Operation::getBlock(), mlir::Builder::getBoolAttr(), mlir::Block::getOperations(), mlir::Builder::getStringAttr(), mlir::WalkResult::interrupt(), promoteIfBlock(), and mlir::OpBuilder::setInsertionPointAfter().
promoteIfBlock()
static void promoteIfBlock (AffineIfOp ifOp, bool elseBlock) static
Promotes the then or the else block of ifOp (depending on whether elseBlock is false or true) into ifOp's containing block, and discards the rest of the op.
Definition at line 28 of file Utils.cpp.
References mlir::Block::begin(), mlir::Block::end(), and mlir::Block::getOperations().
Referenced by hoistAffineIfOp().