MLIR: lib/Dialect/Linalg/Transforms/Transforms.cpp File Reference
Transforms.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/HoistPadding.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Functions
static LogicalResult padOperandToSmallestStaticBoundingBox (OpBuilder &b, linalg::LinalgOp opToPad, OpOperand *opOperand, const PaddingValueComputationFunction &paddingFunc, const PaddingNoFoldComputationFunction &nofoldFunc, Value &result)
Helper function that tries to pad opOperand.
static SmallVector< Value, 4 > peelLoop (RewriterBase &rewriter, Operation *op)
Try to peel a loop op and return the new result.
static SmallVector< Value, 4 > peelLoop (RewriterBase &rewriter, TiledLoopOp tiledLoop, int64_t idx)
Try to peel a TiledLoopOp and return the new result.
static void peelLoops (RewriterBase &rewriter, TiledLinalgOp &res, const LinalgTilingOptions &options)
Peel loops after tiling.
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp)
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp)
static SmallVector< StringRef > getNParallelLoopsAttrs (unsigned nParallelLoops)
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 42 of file Transforms.cpp.
Referenced by mlir::linalg::applyStagedPatterns(), and padOperandToSmallestStaticBoundingBox().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 37 of file Transforms.cpp.
Function Documentation
getNParallelLoopsAttrs()
static SmallVector<StringRef> getNParallelLoopsAttrs (unsigned nParallelLoops) static
Definition at line 745 of file Transforms.cpp.
References mlir::getParallelIteratorTypeName().
Referenced by mlir::linalg::PadTensorOpTransformationPattern::matchAndRewrite().
getTiledAndFusedOpResult()
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp) static
Definition at line 375 of file Transforms.cpp.
References mlir::linalg::TiledAndFusedLinalgOps::fusedLoops, and mlir::linalg::TiledAndFusedLinalgOps::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
getTiledOpResult()
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp) static
Definition at line 368 of file Transforms.cpp.
References mlir::linalg::TiledLinalgOp::loops, and mlir::linalg::TiledLinalgOp::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
padOperandToSmallestStaticBoundingBox()
static LogicalResult padOperandToSmallestStaticBoundingBox (OpBuilder & b, linalg::LinalgOp opToPad, OpOperand * opOperand, const PaddingValueComputationFunction & paddingFunc, const PaddingNoFoldComputationFunction & nofoldFunc, Value & result) static
Helper function that tries to pad opOperand.
Exit early for scalar operands, if paddingFunc returns failure, or if opOperand is not defined by an ExtractSliceOp. Otherwise, try to pad the operand even if it already has a static shape. Set result to the result of the created PadTensorOp or and return success if the operand either has been padded to a static shape or already had a static shape and failure otherwise.
Definition at line 165 of file Transforms.cpp.
References DBGS, mlir::Attribute::dyn_cast(), mlir::failed(), mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::linalg::getConstantUpperBoundForIndex(), mlir::Value::getDefiningOp(), mlir::getElementTypeOrSelf(), mlir::ShapedType::kDynamicSize, mlir::linalg::makeComposedPadHighOp(), and mlir::success().
Referenced by mlir::linalg::rewriteAsPaddedOp().
peelLoop() [1/2]
static SmallVector<Value, 4> peelLoop (RewriterBase & rewriter, Operation * op) static
Try to peel a loop op and return the new result.
Definition at line 293 of file Transforms.cpp.
References mlir::Operation::getResults(), mlir::scf::peelAndCanonicalizeForLoop(), and mlir::succeeded().
peelLoop() [2/2]
static SmallVector<Value, 4> peelLoop (RewriterBase & rewriter, TiledLoopOp tiledLoop, int64_t idx) static
Try to peel a TiledLoopOp and return the new result.
Definition at line 307 of file Transforms.cpp.
References mlir::linalg::peelAndCanonicalizeTiledLoop(), and mlir::succeeded().
peelLoops()
static void peelLoops (RewriterBase & rewriter, TiledLinalgOp & res, const LinalgTilingOptions & options) static
Peel loops after tiling.
Definition at line 319 of file Transforms.cpp.