MLIR: lib/Dialect/Shape/IR/Shape.cpp File Reference
Shape.cpp File Reference
#include "mlir/Dialect/Shape/IR/Shape.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Shape/IR/ShapeOpsDialect.cpp.inc"
#include "ShapeCanonicalization.inc"
#include "mlir/Dialect/Shape/IR/ShapeOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isErrorPropagationPossible (TypeRange operandTypes)
static LogicalResult verifySizeOrIndexOp (Operation *op)
static LogicalResult verifyShapeOrExtentTensorOp (Operation *op)
template<typename... Ty>
static bool eachHasOnlyOneOfTypes (TypeRange typeRange)
template<typename... Ty, typename... ranges>
static bool eachHasOnlyOneOfTypes (TypeRange l, ranges... rs)
static ParseResult parseAssumingOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AssumingOp op)
static LogicalResult verify (AssumingAllOp op)
static LogicalResult verify (BroadcastOp op)
static void print (OpAsmPrinter &p, ConstShapeOp &op)
static ParseResult parseConstShapeOp (OpAsmParser &parser, OperationState &result)
static bool hasAtMostSingleNonScalar (ArrayRef< Attribute > attributes)
static LogicalResult verify (CstrBroadcastableOp op)
ParseResult parseFunctionLibraryOp (OpAsmParser &parser, OperationState &result)
void print (OpAsmPrinter &p, FunctionLibraryOp op)
static LogicalResult verify (shape::YieldOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1715 of file Shape.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
eachHasOnlyOneOfTypes() [1/2]
template<typename... Ty> static bool eachHasOnlyOneOfTypes (TypeRange typeRange) static
Definition at line 96 of file Shape.cpp.
Referenced by eachHasOnlyOneOfTypes().
eachHasOnlyOneOfTypes() [2/2]
template<typename... Ty, typename... ranges> static bool eachHasOnlyOneOfTypes (TypeRange l, ranges... rs) static
Definition at line 101 of file Shape.cpp.
References mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::DialectInlinerInterface::DialectInlinerInterface(), mlir::Attribute::dyn_cast(), eachHasOnlyOneOfTypes(), mlir::AsmParser::emitError(), mlir::Operation::emitError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::NamedAttribute::getName(), mlir::AsmParser::getNameLoc(), mlir::NamedAttribute::getValue(), mlir::Operation::hasTrait(), mlir::Type::isa(), mlir::shape::isExtentTensorType(), isLegalToInline(), mlir::SymbolTable::lookupSymbolIn(), materializeConstant(), mlir::AsmParser::parseKeyword(), mlir::LLVM::detail::parseType(), mlir::LLVM::detail::printType(), mlir::success(), and value.
hasAtMostSingleNonScalar()
static bool hasAtMostSingleNonScalar (ArrayRef< Attribute > attributes) static
Definition at line 866 of file Shape.cpp.
References mlir::failed(), mlir::BoolAttr::get(), mlir::shape::getShapeVec(), and mlir::OpTrait::util::staticallyKnownBroadcastable().
isErrorPropagationPossible()
static bool isErrorPropagationPossible (TypeRange operandTypes) static
Definition at line 65 of file Shape.cpp.
References mlir::Type::isa().
Referenced by verifyShapeOrExtentTensorOp(), and verifySizeOrIndexOp().
parseAssumingOp()
static ParseResult parseAssumingOp (OpAsmParser & parser, OperationState & result) static
Definition at line 256 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseConstShapeOp()
static ParseResult parseConstShapeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 785 of file Shape.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::emitOptionalError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseFunctionLibraryOp()
ParseResult parseFunctionLibraryOp (OpAsmParser & parser, OperationState & result)
Definition at line 1083 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getType(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), mlir::AsmParser::parseSymbolName(), and mlir::success().
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1677 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
print() [1/4]
static void print (OpAsmPrinter & p, AssumingOp op) static
Definition at line 283 of file Shape.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Block::back(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Region::front(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::BoolAttr::get(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::Operation::getOperands(), mlir::Block::getTerminator(), mlir::Value::getUses(), mlir::BoolAttr::getValue(), mlir::RewriterBase::inlineRegionBefore(), mlir::OperationState::location, mlir::m_Zero(), mlir::matchPattern(), mlir::RewriterBase::mergeBlocks(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::Region::push_back(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::RewriterBase::splitBlock(), and mlir::success().
print() [2/4]
static void print (OpAsmPrinter & p, ConstShapeOp & op) static
Definition at line 775 of file Shape.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::AsmPrinter::printType().
print() [3/4]
void print (OpAsmPrinter & p, FunctionLibraryOp op)
Definition at line 1109 of file Shape.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::BoolAttr::get(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getType(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::Type::isa(), mlir::OperationState::location, mlir::AsmPrinter::printAttributeWithoutType(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), and mlir::success().
Referenced by acceptBitWidth(), mlir::Diagnostic::append(), mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResult, AffineMapAccessInterface::Trait >::attachInterface(), mlir::pdl::PDLType::classof(), mlir::createLoopFusionPass(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Attribute::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::AffineMap::dump(), mlir::Type::dump(), mlir::OperationName::dump(), mlir::Operation::dump(), mlir::Value::dump(), mlir::Block::dump(), mlir::CallGraph::end(), mlir::TimingIdentifier::get(), mlir::python::PyOperationBase::getAsm(), mlir::tblgen::Operator::getDialect(), mlir::OperationName::getIdentifier(), getOption(), mlir::Block::getSublistAccess(), mlir::Value::getUsers(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::operator<<(), mlir::IntegerSet::operator==(), impl::MemRefDataPrinter< T >::print(), mlir::Operation::print(), mlir::Block::print(), mlir::AsmPrinter::Impl::printAttribute(), impl::MemRefDataPrinter< T >::printFirst(), mlir::AsmPrinter::Impl::printIntegerSet(), impl::MemRefDataPrinter< T >::printLast(), printMemRefMetaData(), mlir::raw_indented_ostream::printReindented(), shouldPrintElementsAttrWithHex(), mlir::OpState::verify(), and mlir::DebugCounter::~DebugCounter().
print() [4/4]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 1707 of file Shape.cpp.
References mlir::AsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
verify() [1/5]
static LogicalResult verify (AssumingAllOp op) static
Definition at line 530 of file Shape.cpp.
References mlir::OpTrait::util::getBroadcastedShape(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getType(), and mlir::success().
verify() [2/5]
static LogicalResult verify (BroadcastOp op) static
Definition at line 576 of file Shape.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::failure(), mlir::OpTrait::util::getBroadcastedShape(), mlir::shape::getExtentTensorType(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::Value::getType(), mlir::Type::isa(), max(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and verifyShapeOrExtentTensorOp().
verify() [3/5]
static LogicalResult verify (CstrBroadcastableOp op) static
Definition at line 913 of file Shape.cpp.
References mlir::RewritePatternSet::add(), mlir::BoolAttr::get(), mlir::Builder::getIndexAttr(), and mlir::success().
verify() [4/5]
static LogicalResult verify (shape::YieldOp op) static
Definition at line 1556 of file Shape.cpp.
References mlir::Block::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::failure(), mlir::impl::foldCastOp(), mlir::Region::front(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getContext(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::Region::push_back(), and mlir::success().
verify() [5/5]
static LogicalResult verify (ReduceOp op) static
Definition at line 1639 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Value::getType(), mlir::Type::isa(), and mlir::success().
verifyShapeOrExtentTensorOp()
static LogicalResult verifyShapeOrExtentTensorOp (Operation * op) static
Definition at line 83 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::ValueTypeRange< ValueRangeT >::front(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isErrorPropagationPossible(), and mlir::success().
Referenced by verify().
verifySizeOrIndexOp()
static LogicalResult verifySizeOrIndexOp (Operation * op) static
Definition at line 71 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::ValueTypeRange< ValueRangeT >::front(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isErrorPropagationPossible(), and mlir::success().