MLIR: lib/Dialect/MemRef/Transforms/FoldSubViewOps.cpp File Reference
FoldSubViewOps.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h.inc"
Macros
#define GEN_PASS_CLASSES
Functions
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter &rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
static Value getMemRefOperand (memref::LoadOp op)
Helpers to access the memref operand for each op.
static Value getMemRefOperand (vector::TransferReadOp op)
static Value getMemRefOperand (memref::StoreOp op)
static Value getMemRefOperand (vector::TransferWriteOp op)
static AffineMapAttr getPermutationMapAttr (MLIRContext *context, memref::SubViewOp subViewOp, AffineMap currPermutationMap)
Given the permutation map of the original vector.transfer_read/vector.transfer_write operations compute the permutation map to use after the subview is folded with it.
Macro Definition Documentation
GEN_PASS_CLASSES
#define GEN_PASS_CLASSES
Definition at line 255 of file FoldSubViewOps.cpp.
Function Documentation
getMemRefOperand() [1/4]
static Value getMemRefOperand (memref::LoadOp op) static
Helpers to access the memref operand for each op.
Definition at line 93 of file FoldSubViewOps.cpp.
Referenced by getPermutationMapAttr().
getMemRefOperand() [2/4]
static Value getMemRefOperand (vector::TransferReadOp op) static
Definition at line 95 of file FoldSubViewOps.cpp.
getMemRefOperand() [3/4]
static Value getMemRefOperand (memref::StoreOp op) static
Definition at line 97 of file FoldSubViewOps.cpp.
getMemRefOperand() [4/4]
static Value getMemRefOperand (vector::TransferWriteOp op) static
Definition at line 99 of file FoldSubViewOps.cpp.
getPermutationMapAttr()
static AffineMapAttr getPermutationMapAttr (MLIRContext * context, memref::SubViewOp subViewOp, AffineMap currPermutationMap) static
Given the permutation map of the original vector.transfer_read/vector.transfer_write operations compute the permutation map to use after the subview is folded with it.
Definition at line 106 of file FoldSubViewOps.cpp.
References mlir::AffineMap::compose(), mlir::failed(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), getMemRefOperand(), mlir::RewriterBase::replaceOpWithNewOp(), resolveSourceIndices(), and mlir::success().
resolveSourceIndices()
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter & rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
For example
%0 = ... : memref<12x42xf32> %1 = subview %0[arg0, arg1][][stride1, stride2] : memref<12x42xf32> to memref<4x4xf32, offset=?, strides=[?, ?]> %2 = load %1[i1, i2] : memref<4x4xf32, offset=?, strides=[?, ?]>
could be folded into
%2 = load %0[arg0 + i1 * stride1][arg1 + i2 * stride2] : memref<12x42xf32>
Definition at line 43 of file FoldSubViewOps.cpp.
References mlir::AffineExpr::cast(), mlir::OpBuilder::create(), mlir::failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), and mlir::success().
Referenced by getPermutationMapAttr().