MLIR: lib/Dialect/Linalg/Transforms/Hoisting.cpp File Reference
Hoisting.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Hoisting.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SCF/Utils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopUtils.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "linalg-hoisting"
#define DBGS() (dbgs() << '[' << DEBUG_TYPE << "] ")
Functions
static bool isEqualOffsetSizeOrStride (OpFoldResult op1, OpFoldResult op2)
Return true if op1 and op2 are the same constant or the same SSA value.
static bool sameOffsetsSizesAndStrides (tensor::ExtractSliceOp s, tensor::InsertSliceOp si)
Return true is all offsets, sizes and strides are equal.
static HoistableRead findMatchingTransferRead (HoistableWrite write, Value srcTensor)
Look for a HoistableRead, in the given tensor uses, accessing the same offset as the HoistableWrite.
static bool tensorChunkAccessedByUnknownOp (HoistableWrite write, HoistableRead candidateRead, BlockArgument tensorArg)
Check if the chunk of data inserted by the HoistableWrite are read by any other op than the HoistableRead candidate.
static HoistableWrite getLoopInvariantTransferWriteOpDefining (scf::ForOp forOp, OpOperand &yieldOperand)
Return the forOp-invariant HoistableWrite that produces yieldOperand.
static void hoistReadWrite (HoistableRead read, HoistableWrite write, BlockArgument tensorBBArg)
Mechanical hoisting of a matching HoistableRead / HoistableWrite pair.
Macro Definition Documentation
DBGS
#define DBGS () (dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 38 of file Hoisting.cpp.
Referenced by findMatchingTransferRead(), hoistReadWrite(), mlir::linalg::hoistRedundantVectorTransfers(), and mlir::linalg::hoistRedundantVectorTransfersOnTensor().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-hoisting"
Definition at line 36 of file Hoisting.cpp.
Function Documentation
findMatchingTransferRead()
static HoistableRead findMatchingTransferRead (HoistableWrite write, Value srcTensor) static
Look for a HoistableRead, in the given tensor uses, accessing the same offset as the HoistableWrite.
Definition at line 99 of file Hoisting.cpp.
References DBGS, mlir::Value::getUsers(), mlir::Operation::getUsers(), and sameOffsetsSizesAndStrides().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
getLoopInvariantTransferWriteOpDefining()
static HoistableWrite getLoopInvariantTransferWriteOpDefining (scf::ForOp forOp, OpOperand & yieldOperand) static
Return the forOp-invariant HoistableWrite that produces yieldOperand.
Return the null HoistableWrite() if it is not comprised of a vector.transfer_write + optional insert_slice or if any of the indexings is forOp-dependent.
Definition at line 223 of file Hoisting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), and mlir::OpOperand::getOperandNumber().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
hoistReadWrite()
static void hoistReadWrite (HoistableRead read, HoistableWrite write, BlockArgument tensorBBArg) static
Mechanical hoisting of a matching HoistableRead / HoistableWrite pair.
Definition at line 261 of file Hoisting.cpp.
References mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().
isEqualOffsetSizeOrStride()
static bool isEqualOffsetSizeOrStride (OpFoldResult op1, OpFoldResult op2) static
Return true if op1 and op2 are the same constant or the same SSA value.
Definition at line 59 of file Hoisting.cpp.
References mlir::Attribute::dyn_cast(), mlir::Attribute::dyn_cast_or_null(), mlir::getConstantIntValue(), and mlir::Value::getDefiningOp().
Referenced by sameOffsetsSizesAndStrides().
sameOffsetsSizesAndStrides()
static bool sameOffsetsSizesAndStrides (tensor::ExtractSliceOp s, tensor::InsertSliceOp si) static
Return true is all offsets, sizes and strides are equal.
Definition at line 77 of file Hoisting.cpp.
References isEqualOffsetSizeOrStride().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::areEquivalentExtractSliceOps(), and findMatchingTransferRead().
tensorChunkAccessedByUnknownOp()
static bool tensorChunkAccessedByUnknownOp (HoistableWrite write, HoistableRead candidateRead, BlockArgument tensorArg) static
Check if the chunk of data inserted by the HoistableWrite are read by any other op than the HoistableRead candidate.
Definition at line 162 of file Hoisting.cpp.
References mlir::Value::getUses().
Referenced by mlir::linalg::hoistRedundantVectorTransfersOnTensor().