MLIR: lib/Dialect/Linalg/IR/LinalgTypes.cpp File Reference
LinalgTypes.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionSupport.h"
#include "mlir/Parser.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_LIST
#define GET_OP_LIST
Typedefs
template<typename T , typename... Args>
using has_region_builder = decltype(T::regionBuilder)
Trait to check if T provides a regionBuilder method.
template<typename T >
using detect_has_region_builder = llvm::is_detected< has_region_builder, T >
Functions
template<typename OpType , typename = std::enable_if_t< !detect_has_region_builder<OpType>::value>>
void addNamedOpBuilderImpl (llvm::StringMap< LinalgDialect::RegionBuilderFunType > &map)
SFINAE helper for single C++ class without a regionBuilder method (e.g.
template<typename OpType , typename = std::enable_if_t<detect_has_region_builder<OpType>::value>, typename = void>
void addNamedOpBuilderImpl (llvm::StringMap< LinalgDialect::RegionBuilderFunType > &map)
template<typename... OpTypes>
void addNamedOpBuilders (llvm::StringMap< LinalgDialect::RegionBuilderFunType > &map)
static void print (RangeType rt, DialectAsmPrinter &os)
RangeType prints as just "range".
Macro Definition Documentation
GET_OP_LIST [1/3]
#define GET_OP_LIST
GET_OP_LIST [2/3]
#define GET_OP_LIST
GET_OP_LIST [3/3]
#define GET_OP_LIST
Typedef Documentation
detect_has_region_builder
template<typename T > using detect_has_region_builder = llvm::is_detected<has_region_builder, T>
Definition at line 80 of file LinalgTypes.cpp.
has_region_builder
template<typename T , typename... Args> using has_region_builder = decltype(T::regionBuilder)
Trait to check if T provides a regionBuilder method.
Definition at line 78 of file LinalgTypes.cpp.
Function Documentation
addNamedOpBuilderImpl() [1/2]
template<typename OpType , typename = std::enable_if_t< !detect_has_region_builder<OpType>::value>> void addNamedOpBuilderImpl (llvm::StringMap< LinalgDialect::RegionBuilderFunType > & map)
SFINAE helper for single C++ class without a regionBuilder method (e.g.
an OpInterface).
Definition at line 86 of file LinalgTypes.cpp.
References value.
addNamedOpBuilderImpl() [2/2]
template<typename OpType , typename = std::enable_if_t<detect_has_region_builder<OpType>::value>, typename = void> void addNamedOpBuilderImpl (llvm::StringMap< LinalgDialect::RegionBuilderFunType > & map)
Definition at line 94 of file LinalgTypes.cpp.
addNamedOpBuilders()
template<typename... OpTypes> void addNamedOpBuilders (llvm::StringMap< LinalgDialect::RegionBuilderFunType > & map)
Definition at line 102 of file LinalgTypes.cpp.
References mlir::AsmParser::emitError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::AsmParser::getNameLoc(), mlir::AsmParser::parseKeyword(), and mlir::LLVM::detail::parseType().
print()
static void print (RangeType rt, DialectAsmPrinter & os) static
RangeType prints as just "range".
Definition at line 144 of file LinalgTypes.cpp.
References mlir::Type::cast(), mlir::Operation::emitError(), mlir::NamedAttribute::getName(), mlir::NamedAttribute::getValue(), mlir::Operation::hasTrait(), mlir::Attribute::isa(), mlir::LLVM::detail::printType(), and mlir::success().