MLIR: lib/Dialect/Linalg/Transforms/Bufferize.cpp File Reference
Bufferize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/StandardOps/Transforms/Passes.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
Functions
static Value cloneMemref (Location loc, Value memref, OpBuilder &b)
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, ValueRange outputs, SmallVectorImpl< Value > &resultBuffers, OpBuilder &b)
Function Documentation
allocateBuffersForResults()
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, ValueRange outputs, SmallVectorImpl< Value > & resultBuffers, OpBuilder & b) static
Definition at line 39 of file Bufferize.cpp.
References cloneMemref(), mlir::detail::enumerate(), mlir::failure(), mlir::linalg::getDynOperands(), resultIndex(), and mlir::success().
Referenced by mlir::linalg::createLinalgOpOnBuffers().
cloneMemref()
static Value cloneMemref (Location loc, Value memref, OpBuilder & b) static
Definition at line 30 of file Bufferize.cpp.
References mlir::linalg::getDynOperands().
Referenced by allocateBuffersForResults(), and mlir::linalg::createLinalgOpOnBuffers().