MLIR: lib/Dialect/SCF/Transforms/LoopSpecialization.cpp File Reference
LoopSpecialization.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/SCF/Passes.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/SCF/Transforms.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/DenseMap.h"
Functions
static void specializeParallelLoopForUnrolling (ParallelOp op)
Rewrite a parallel loop with bounds defined by an affine.min with a constant into 2 loops after checking if the bounds are equal to that constant.
static void specializeForLoopForUnrolling (ForOp op)
Rewrite a for loop with bounds defined by an affine.min with a constant into 2 loops after checking if the bounds are equal to that constant.
static LogicalResult peelForLoop (RewriterBase &b, ForOp forOp, ForOp &partialIteration, Value &splitBound)
Rewrite a for loop with bounds/step that potentially do not divide evenly into a for loop where the step divides the iteration space evenly, followed by an scf.if for the last (partial) iteration (if any).
static void unpackOptionalValues (ArrayRef< Optional< Value >> source, SmallVector< Value > &target)
static LogicalResult alignAndAddBound (FlatAffineValueConstraints &constraints, FlatAffineConstraints::BoundType type, unsigned pos, AffineMap map, ValueRange operands)
Bound an identifier pos in a given FlatAffineValueConstraints with constraints drawn from an affine map.
static AffineMap addConstToResults (AffineMap map, int64_t val)
Add val to each result of map.
static LogicalResult canonicalizeMinMaxOp (RewriterBase &rewriter, Operation *op, AffineMap map, ValueRange operands, bool isMin, FlatAffineValueConstraints constraints)
This function tries to canonicalize min/max operations by proving that their value is bounded by the same lower and upper bound.
template<typename OpTy , bool IsMin>
static void rewriteAffineOpAfterPeeling (RewriterBase &rewriter, ForOp forOp, ForOp partialIteration, Value previousUb)
Variables
static constexpr char kPeeledLoopLabel [] = "__peeled_loop__"
static constexpr char kPartialIterationLabel [] = "__partial_iteration__"
Function Documentation
addConstToResults()
static AffineMap addConstToResults (AffineMap map, int64_t val) static
Add val to each result of map.
Definition at line 178 of file LoopSpecialization.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by canonicalizeMinMaxOp().
alignAndAddBound()
static LogicalResult alignAndAddBound (FlatAffineValueConstraints & constraints, FlatAffineConstraints::BoundType type, unsigned pos, AffineMap map, ValueRange operands) static
Bound an identifier pos in a given FlatAffineValueConstraints with constraints drawn from an affine map.
Before adding the constraint, the dimensions/symbols of the affine map are aligned with constraints. operands are the SSA Value operands used with the affine map. Note: This function adds a new symbol column to the constraints for each dimension/symbol that exists in the affine map but not in constraints.
Definition at line 162 of file LoopSpecialization.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::alignAffineMapWithValues(), mlir::FlatAffineValueConstraints::appendSymbolId(), mlir::FlatAffineValueConstraints::getMaybeDimValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), and unpackOptionalValues().
Referenced by canonicalizeMinMaxOp().
canonicalizeMinMaxOp()
static LogicalResult canonicalizeMinMaxOp (RewriterBase & rewriter, Operation * op, AffineMap map, ValueRange operands, bool isMin, FlatAffineValueConstraints constraints) static
This function tries to canonicalize min/max operations by proving that their value is bounded by the same lower and upper bound.
In that case, the operation can be folded away.
Bounds are computed by FlatAffineValueConstraints. Invariants required for finding/proving bounds should be supplied via constraints.
Add dimensions for op and opBound (lower or upper bound of op).
Compute an upper bound of op (in case of isMin) or a lower bound (in case of !isMin) and bind it to opBound. SSA values that are used in op but are not part of constraints, are added as extra symbols.
For each result of op: Add result as a dimension r_i. Prove that:
If isMin: r_i >= opBound
If isMax: r_i <= opBound If this is the case, ub(op) == lb(op).
Replace op with opBound.
In summary, the following constraints are added throughout this function. Note: invar are dimensions added by the caller to express the invariants. (Showing only the case where isMin.)
invar | op | opBound | r_i | extra syms... | const | eq/ineq ---—+----—+------—+--—+------------—+----—+----------------— (various eq./ineq. constraining invar, added by the caller) ... | 0 | 0 | 0 | 0 | ... | ... ---—+----—+------—+--—+------------—+----—+----------------— (various ineq. constraining op in terms of op operands (invar and extra op operands "extra syms" that are not in invar)). ... | -1 | 0 | 0 | ... | ... | >= 0 ---—+----—+------—+--—+------------—+----—+----------------— (set opBound to op upper bound in terms of invar and "extra syms") ... | 0 | -1 | 0 | ... | ... | = 0 ---—+----—+------—+--—+------------—+----—+----------------— (for each op map result r_i: set r_i to corresponding map result, prove that r_i >= minOpUb via contradiction) ... | 0 | 0 | -1 | ... | ... | = 0 0 | 0 | 1 | -1 | 0 | -1 | >= 0
Definition at line 225 of file LoopSpecialization.cpp.
References mlir::FlatAffineValueConstraints::addBound(), addConstToResults(), mlir::FlatAffineConstraints::addInequality(), alignAndAddBound(), mlir::FlatAffineValueConstraints::appendDimId(), mlir::canonicalizeMapAndOperands(), mlir::FlatAffineConstraints::EQ, mlir::failed(), mlir::failure(), mlir::Builder::getContext(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineConstraints::getNumCols(), mlir::AffineMap::getNumResults(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::AffineMap::getSubMap(), mlir::FlatAffineConstraints::isEmpty(), mlir::FlatAffineConstraints::LB, mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), mlir::AffineMap::shiftDims(), mlir::success(), mlir::FlatAffineConstraints::UB, and unpackOptionalValues().
Referenced by mlir::scf::canonicalizeMinMaxOpInLoop(), and mlir::scf::rewritePeeledMinMaxOp().
peelForLoop()
static LogicalResult peelForLoop (RewriterBase & b, ForOp forOp, ForOp & partialIteration, Value & splitBound) static
Rewrite a for loop with bounds/step that potentially do not divide evenly into a for loop where the step divides the iteration space evenly, followed by an scf.if for the last (partial) iteration (if any).
This function rewrites the given scf.for loop in-place and creates a new scf.if operation for the last iteration. It replaces all uses of the unpeeled loop with the results of the newly generated scf.if.
The newly generated scf.if operation is returned via ifOp. The boundary at which the loop is split (new upper bound) is returned via splitBound. The return value indicates whether the loop was rewritten or not.
Definition at line 111 of file LoopSpecialization.cpp.
References mlir::bindSymbols(), mlir::OpBuilder::clone(), mlir::OpBuilder::createOrFold(), mlir::failure(), mlir::AffineMap::get(), mlir::getConstantIntValue(), mlir::Builder::getContext(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and mlir::RewriterBase::updateRootInPlace().
Referenced by rewriteAffineOpAfterPeeling().
rewriteAffineOpAfterPeeling()
template<typename OpTy , bool IsMin> static void rewriteAffineOpAfterPeeling (RewriterBase & rewriter, ForOp forOp, ForOp partialIteration, Value previousUb) static
Definition at line 371 of file LoopSpecialization.cpp.
References mlir::failed(), mlir::failure(), mlir::scf::peelAndCanonicalizeForLoop(), peelForLoop(), mlir::scf::rewritePeeledMinMaxOp(), and mlir::success().
specializeForLoopForUnrolling()
static void specializeForLoopForUnrolling (ForOp op) static
Rewrite a for loop with bounds defined by an affine.min with a constant into 2 loops after checking if the bounds are equal to that constant.
This is beneficial if the loop will almost always have the constant bound and that version can be fully unrolled and vectorized.
Definition at line 75 of file LoopSpecialization.cpp.
References mlir::OpBuilder::create(), mlir::BlockAndValueMapping::map(), max(), and min().
specializeParallelLoopForUnrolling()
static void specializeParallelLoopForUnrolling (ParallelOp op) static
Rewrite a parallel loop with bounds defined by an affine.min with a constant into 2 loops after checking if the bounds are equal to that constant.
This is beneficial if the loop will almost always have the constant bound and that version can be fully unrolled and vectorized.
Definition at line 37 of file LoopSpecialization.cpp.
References mlir::OpBuilder::create(), mlir::BlockAndValueMapping::map(), max(), and min().
unpackOptionalValues()
static void unpackOptionalValues (ArrayRef< Optional< Value >> source, SmallVector< Value > & target) static
Definition at line 149 of file LoopSpecialization.cpp.
Referenced by alignAndAddBound(), and canonicalizeMinMaxOp().
Variable Documentation
kPartialIterationLabel
constexpr char kPartialIterationLabel[] = "__partial_iteration__" static
Definition at line 485 of file LoopSpecialization.cpp.
kPeeledLoopLabel
constexpr char kPeeledLoopLabel[] = "__peeled_loop__" static
Definition at line 484 of file LoopSpecialization.cpp.