MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp File Reference
ModuleBufferization.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Operation.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
Classes
struct mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
mlir::linalg::comprehensive_bufferize
mlir::linalg::comprehensive_bufferize::std_ext
Macros
#define DEBUG_TYPE "comprehensive-module-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X)
Functions
static ModuleBufferizationState & getModuleBufferizationState (BufferizationState &state)
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static bool isaTensor (Type t)
static Value getNonCastedValue (Value value)
If value is a memref::CastOp, return its source.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static FuncOp getCalledFunction (CallOpInterface callOp)
Return the FuncOp called by callOp.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > &bufferizedFunctionTypes)
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
static void equivalenceAnalysis (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, ModuleBufferizationState &moduleState)
Gather equivalence info of CallOps.
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationState &state)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > &orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> &callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void annotateOpsWithBufferizationMarkers (FuncOp funcOp, BufferizationState &state)
Annotate the IR with the result of the analysis. For testing/debugging only.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 21 of file ModuleBufferization.cpp.
Referenced by bufferizeFuncOpBoundary().
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-module-bufferize"
Definition at line 20 of file ModuleBufferization.cpp.
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X)
Definition at line 22 of file ModuleBufferization.cpp.
Referenced by getOrCreateBufferizedFunctionType().
Function Documentation
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (FuncOp funcOp, BufferizationState & state) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 747 of file ModuleBufferization.cpp.
References setInPlaceFuncArgument().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, BufferizationState & state) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. Reliance on this logic will need to be relaxed in the future.
Note: Returning a memref currently fails bufferization. If such memrefs originate from an op with an Alloc effect, they could be hoisted in the future.
Definition at line 226 of file ModuleBufferization.cpp.
References mlir::Block::addArgument(), DBGS, mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), getModuleBufferizationState(), getNonCastedValue(), mlir::Block::getNumArguments(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
equivalenceAnalysis()
static void equivalenceAnalysis (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, ModuleBufferizationState & moduleState) static
Gather equivalence info of CallOps.
Note: This only adds new equivalence info if funcOp was already analyzed.
Definition at line 189 of file ModuleBufferization.cpp.
References mlir::WalkResult::advance(), getCalledFunction(), and mlir::WalkResult::skip().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
foreachCaller()
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> & callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 405 of file ModuleBufferization.cpp.
getAssumedUniqueReturnOp()
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 54 of file ModuleBufferization.cpp.
References mlir::Attribute::cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getAttr(), mlir::Operation::getContext(), getModuleBufferizationState(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getType(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::Operation::setAttr(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 151 of file ModuleBufferization.cpp.
References mlir::linalg::comprehensive_bufferize::getContiguousOrUnrankedMemRefType(), mlir::linalg::comprehensive_bufferize::getDynamicMemRefType(), and rewrite().
Referenced by getOrCreateBufferizedFunctionType().
getCalledFunction()
static FuncOp getCalledFunction (CallOpInterface callOp) static
Return the FuncOp called by callOp.
Definition at line 137 of file ModuleBufferization.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and equivalenceAnalysis().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > & orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 353 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
getModuleBufferizationState()
static ModuleBufferizationState& getModuleBufferizationState (BufferizationState & state) static
Definition at line 47 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), bufferizeFuncOpBoundary(), getAssumedUniqueReturnOp(), mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isWritable(), and mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
getNonCastedValue()
static Value getNonCastedValue (Value value) static
If value is a memref::CastOp, return its source.
Otherwise, return value directly.
Definition at line 120 of file ModuleBufferization.cpp.
References mlir::Value::getDefiningOp(), and value.
Referenced by bufferizeFuncOpBoundary().
getOrCreateBufferizedFunctionType()
static FunctionType getOrCreateBufferizedFunctionType (FuncOp funcOp, TypeRange argumentTypes, TypeRange resultTypes, DenseMap< FuncOp, FunctionType > & bufferizedFunctionTypes) static
If an entry for funcOp is available in bufferizedFunctionTypes, return it.
Otherwise, construct a new entry based on argumentTypes and resultTypes.
Definition at line 172 of file ModuleBufferization.cpp.
References getBufferizedFunctionType(), and LDBG.
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 116 of file ModuleBufferization.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 417 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 128 of file ModuleBufferization.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 739 of file ModuleBufferization.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().