MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Namespaces
comprehensive_bufferize
detail
Classes
class Aliases
A very primitive alias analysis which just records for each view, either:
struct CodegenStrategy
Codegen strategy controls how a Linalg op is progressively lowered.
class ConvOpVectorization
Converts Convolution op into vector contraction.
class CopyOpToLibraryCallRewrite
Rewrite pattern specialization for CopyOp, kicks in when both input and output permutations are left unspecified or are the identity.
class CopyTransposeRewrite
Rewrite CopyOp with permutations into a sequence of TransposeOp and permutation-free CopyOp.
struct Decompose
Represent one application of createLinalgStrategyDecomposePass.
struct ExtractSliceOfPadTensorSwapPattern
Rewrite extract_slice(pad_tensor(x)) into pad_tensor(extract_slice(x)).
struct FusionInfo
A struct containing the Linalg producer before and after fusion.
struct Generalize
Represent one application of createLinalgStrategyGeneralizePass.
struct GeneralizePadTensorOpPattern
Rewrite a PadTensorOp into a sequence of InitTensorOp, FillOp and InsertSliceOp.
struct GenerateLoopNest
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
struct GenericOpInterchangePattern
Linalg generic interchage pattern.
struct Interchange
Represent one application of createLinalgStrategyInterchangePass.
struct LinalgBasePromotionPattern
Linalg promotion patterns.
struct LinalgBaseTileAndFusePattern
struct LinalgBaseTilingPattern
Base pattern that applied the tiling transformation specified by options.
struct LinalgBaseVectorizationPattern
struct LinalgCopyVTRForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
struct LinalgCopyVTWForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
struct LinalgElementwiseFusionOptions
Options that control fusion of elementwise operations.
struct LinalgEnablingOptions
Options to control the application of enabling transformations.
struct LinalgFusionOptions
struct LinalgGeneralizationPattern
Linalg generalization pattern.
struct LinalgGenericTilingPattern
struct LinalgLoopDistributionOptions
Options that allow distribution of loops generated in Linalg transforms to processors while generating the loops.
struct LinalgLoweringPattern
class LinalgOpToLibraryCallRewrite
struct LinalgPaddingOptions
struct LinalgPaddingPattern
Linalg padding pattern.
struct LinalgPromotionOptions
struct LinalgPromotionPattern
struct LinalgTileAndFusePattern
struct LinalgTileAndFuseTensorOpsPattern
Linalg tile and fuse tensor ops pattern.
struct LinalgTilingAndFusionOptions
struct LinalgTilingOptions
struct LinalgTilingPattern
struct LinalgTransformationFilter
Helper class to control application of linalg transformation patterns.
struct LinalgTransforms
struct LinalgVectorizationOptions
Linalg vectorization patterns.
struct LinalgVectorizationPattern
struct LinalgVectorLoweringOptions
Vector lowering options control how ops are lowered down to 1-D and scf.for form.
struct OpOperandVector
OpOperand vector that implicitly converts to a Value vector.
struct Pad
Represent one application of LinalgStrategyPadPass.
struct PadTensorOpTransformationPattern
PadTensorOp is not canonicalized away yet, so we provide a transformation to linalg.generic.
struct ProcInfo
Callback function type used to get processor ID, and number of processors used for distribution for all parallel loops generated.
struct Promote
Represent one application of createLinalgStrategyPromotePass.
struct PromotionInfo
Creates a new buffer using the allocationFn provided.
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct Tile
Represent one application of LinalgStrategyTilePass.
struct TileAndFuse
Represent one application of LinalgStrategyTileAndFusePass.
struct TiledAndFusedLinalgOps
Fuse a sequence of linalg operations (ops) using tile-and-fuse.
struct TiledLinalgOp
Performs standalone tiling of a single LinalgOp by tileSizes.
class TileLoopNest
A struct to manage the tile loop nest specific information.
struct Transformation
Abstract Transformation class applied in a sequence that also handles state through markers.
struct Vectorize
Represent one application of createLinalgStrategyVectorizePass.
struct VectorLowering
Represent one application of createLinalgStrategyLowerVectorsPass.
Typedefs
using LoopRangeBuilder = std::function< SmallVector< Range, 4 >(ImplicitLocOpBuilder)>
using LinalgLoops = SmallVector< Operation *, 4 >
using ControlElementwiseOpsFusionFn = std::function< bool(const OpResult &producer, OpOperand &consumer)>
Function type which is used to control when to stop fusion.
using AllocBufferCallbackFn = std::function< Optional< Value >(OpBuilder &b, memref::SubViewOp subView, ArrayRef< Value > boundingSubViewSize, DataLayout &layout)>
Callback function type used to perform the allocation for the promoted subView.
using DeallocBufferCallbackFn = std::function< LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
using CopyCallbackFn = std::function< LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
using TileSizeComputationFunction = std::function< SmallVector< Value, 4 >(OpBuilder &, Operation *)>
using PaddingValueComputationFunction = std::function< FailureOr< Value >(OpBuilder &, OpOperand &)>
Callback returning the padding value to use for a given OpOperand or failure for no padding.
using PaddingNoFoldComputationFunction = std::function< bool(OpOperand &)>
Callback returning true if the pad tensor operation defining the given OpOperand shall be marked as nofold to enable packing.
using PaddingHoistComputationFunction = std::function< int64_t(OpOperand &)>
Callback returning the number of loops to hoist the pad tensor operation defining the given OpOperand.
template<typename T , typename... Args>
using has_get_operation_name = decltype(T::getOperationName())
Trait to check if T provides a getOperationName method.
template<typename T >
using detect_has_get_operation_name = llvm::is_detected< has_get_operation_name, T >
using OptimizeCopyFn = std::function< LogicalResult(PatternRewriter &, PadTensorOp, Value)>
using FusableOpDependencesTy = llvm::MapVector< Operation *, SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 1 > >
using ProcInfoCallBackFn = std::function< SmallVector< ProcInfo, 2 >(OpBuilder &b, Location loc, ArrayRef< Range > parallelLoopRanges)>
using OneDimProcInfoCallBackFn = std::function< ProcInfo(OpBuilder &b, Location loc)>
Enumerations
enum LinalgLoweringType { LinalgLoweringType::LibraryCall = 0, LinalgLoweringType::Loops = 1, LinalgLoweringType::AffineLoops = 2, LinalgLoweringType::ParallelLoops = 3 }
Linalg lowering patterns.
enum LinalgTilingLoopType { LinalgTilingLoopType::Loops = 0, LinalgTilingLoopType::AffineLoops = 1, LinalgTilingLoopType::ParallelLoops = 2, LinalgTilingLoopType::TiledLoops = 3 }
The type of loops to be generated during tiling.
enum DistributionMethod { DistributionMethod::Cyclic = 0, DistributionMethod::CyclicNumProcsGeNumIters = 1, DistributionMethod::CyclicNumProcsEqNumIters = 2 }
Scheme used to distribute loops to processors.
Functions
void populateLinalgToStandardConversionPatterns (RewritePatternSet &patterns)
Populate the given list with patterns that convert from Linalg to Standard.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
bool isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
LoopRangeBuilder defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
void getDimsOfType (Operation *op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > &res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
void hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
void hoistRedundantVectorTransfersOnTensor (FuncOp func)
Same behavior as hoistRedundantVectorTransfers but works on tensors instead of buffers.
FailureOr< Value > hoistPaddingOnTensors (PadTensorOp opToHoist, int numLoops, PadTensorOp &hoistedOp)
Mechanically hoist padding operations on tensors by numLoops into a new, generally larger tensor.
bool skipUnitDimReshape (const OpResult &producer, OpOperand &consumer)
Default function to control reshape folding.
void populateConvVectorizationPatterns (MLIRContext *context, SmallVectorImpl< RewritePatternSet > &patterns, ArrayRef< int64_t > tileSizes)
[DEPRECATED] Populates patterns for vectorization of all ConvN-D ops.
void populateConvolutionVectorizationPatterns (RewritePatternSet &patterns, PatternBenefit benefit=1)
Populates patterns for vectorizing low-D convolution ops.
void populateElementwiseToLinalgConversionPatterns (RewritePatternSet &patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
void populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet &patterns, ControlElementwiseOpsFusionFn controlFoldingReshapes=skipUnitDimReshape)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
void populateFoldReshapeOpsByLinearizationPatterns (RewritePatternSet &patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic operation.
void populateFoldUnitDimsReshapeOpsByLinearizationPatterns (RewritePatternSet &patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic operation.
void populateLinalgBufferizePatterns (bufferization::BufferizeTypeConverter &converter, RewritePatternSet &patterns)
Populates the given list with patterns to bufferize linalg ops.
LinalgOp createLinalgOpOnBuffers (ConversionPatternRewriter &rewriter, LinalgOp linalgOp, ValueRange inputs, ValueRange outputs)
Create linalg op on buffers given the original tensor-based operation and the buffers for the outputs.
void populateFoldUnitExtentDimsPatterns (RewritePatternSet &patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
void populateInlineConstantOperandsPatterns (RewritePatternSet &patterns)
Patterns that are used to inline constant operands into linalg generic ops.
void populateTiledLoopToSCFPattern (RewritePatternSet &patterns)
Pattern to convert TiledLoopOp to SCF loops.
void populateElementwiseOpsFusionPatterns (RewritePatternSet &patterns, LinalgElementwiseFusionOptions options=LinalgElementwiseFusionOptions())
Patterns for fusing linalg operation on tensors.
void populatePushReshapeOpsPatterns (RewritePatternSet &patterns)
Patterns to push reshape op towards the end of the graph in order to expose more fusion opportunities.
FailureOr< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
FailureOr< TiledAndFusedLinalgOps > tileAndFuseLinalgOps (OpBuilder &builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph, const LinalgTilingOptions &tilingOptions)
void interchangeGenericOp (PatternRewriter &rewriter, GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
GenericOp generalizeNamedOp (PatternRewriter &rewriter, LinalgOp namedOp)
Creates a GenericOp from the given named operation namedOp.
FailureOr< PromotionInfo > promoteSubviewAsNewBuffer (OpBuilder &b, Location loc, memref::SubViewOp subView, AllocBufferCallbackFn allocationFn, DataLayout &layout)
FailureOr< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, LinalgPromotionOptions options)
Promotes the subViews into a new buffer allocated at the insertion point b.
LogicalResult vectorizeLinalgOp (OpBuilder &builder, Operation *op, SmallVectorImpl< Value > &newResults)
Emit a suitable vector form for a Linalg op with fully static shape.
FailureOr< LinalgLoops > linalgOpToLoops (PatternRewriter &rewriter, LinalgOp linalgOp)
Emits a loop nest of scf.for with the proper body for linalgOp.
FailureOr< LinalgLoops > linalgOpToParallelLoops (PatternRewriter &rewriter, LinalgOp linalgOp)
Emits a loop nest of scf.parallel with the proper body for linalgOp.
FailureOr< LinalgLoops > linalgOpToAffineLoops (PatternRewriter &rewriter, LinalgOp linalgOp)
Emits a loop nest of affine.for with the proper body for linalgOp.
LogicalResult interchangeGenericOpPrecondition (GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Emits a generic operation with the indexing_maps and iterator_types permutated according to permutation.
LogicalResult generalizeNamedOpPrecondition (Operation *op)
Generalize named operations to generic operations.
LogicalResult promoteSubviewsPrecondition (Operation *op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
RewritePatternSet getLinalgTilingCanonicalizationPatterns (MLIRContext *ctx)
Canonicalization patterns relevant to apply after tiling patterns.
void populateLinalgTilingCanonicalizationPatterns (RewritePatternSet &patterns)
template<typename OpType , typename = std::enable_if_t<detect_has_get_operation_name<OpType>::value>, typename = void>
void insertVectorizationPatternImpl (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ op with a getOperationName method.
template<typename OpType , typename = std::enable_if_t< !detect_has_get_operation_name<OpType>::value>>
void insertVectorizationPatternImpl (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ class without a getOperationName method (e.g.
template<typename... OpTypes>
void insertVectorizationPatterns (RewritePatternSet &patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f=linalg::LinalgTransformationFilter())
Variadic helper function to insert vectorization patterns for C++ ops.
void populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet &patterns, LinalgTransformationFilter filter=LinalgTransformationFilter())
Linalg generalization patterns.
void populateDecomposeConvolutionPatterns (RewritePatternSet &patterns, LinalgTransformationFilter filter=LinalgTransformationFilter(), PatternBenefit benefit=1)
Linalg decompose convolutions patterns.
void populateLinalgDistributeTiledLoopPattern (RewritePatternSet &patterns, const LinalgLoopDistributionOptions &opts, const LinalgTransformationFilter &marker)
Linalg distribution patterns.
FailureOr< SmallVector< Value > > rewriteAsPaddedOp (OpBuilder &b, LinalgOp opToPad, const PaddingValueComputationFunction &paddingFunc, const PaddingNoFoldComputationFunction &nofoldFunc, LinalgOp &paddedOp)
Pad the operands of opToPad to a static bounding box.
void populatePadTensorOpVectorizationPatterns (RewritePatternSet &patterns, PatternBenefit baseBenefit=1)
Populates patterns with patterns that vectorize linalg.pad_tensor.
LogicalResult peelAndCanonicalizeTiledLoop (RewriterBase &rewriter, TiledLoopOp loopOp, int64_t idx, TiledLoopOp &result)
Rewrite a TiledLoopOp with bounds/step that potentially do not divide evenly into a TiledLoopOp where the step divides the iteration space evenly, followed by another TiledLoopOp for the last (partial) iteration (if any).
LogicalResult applyStagedPatterns (Operation *op, ArrayRef< FrozenRewritePatternSet > stage1Patterns, const FrozenRewritePatternSet &stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda=nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
bool isPermutation (ArrayRef< int64_t > permutation)
Check if permutation is a permutation of the range [0, permutation.size()).
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< int64_t > permutation)
Apply the permutation defined by permutation to inVec.
Value createOrFoldDimOp (OpBuilder &b, Location loc, Value source, int64_t dim)
Helper function that creates a memref::DimOp or tensor::DimOp depending on the type of source.
SmallVector< Value, 4 > getDynOperands (Location loc, Value val, OpBuilder &b)
Given an operation, retrieves the value of each dynamic dimension through constructing the necessary DimOp operators.
void getUpperBoundForIndex (Value value, AffineMap &boundMap, SmallVectorImpl< Value > &boundOperands)
Computes an upper bound for the result value of an index computation.
FailureOr< int64_t > getConstantUpperBoundForIndex (Value value)
Returns a constant upper bound for the result value of an index computation.
tensor::ExtractSliceOp makeComposedExtractSliceOp (OpBuilder &b, Location loc, Value source, ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
Create an ExtractSliceOp and, if source is defined by an ExtractSliceOp, fold it by adding the offsets.
Value makeComposedPadHighOp (OpBuilder &b, Location loc, RankedTensorType type, Value source, Value pad, bool nofold)
Create a PadTensorOp that pads source to the size of the statically sized type whose static sizes are assumed to be greater than the dynamic source size.
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
SmallVector< Value > computeTileOffsets (OpBuilder &b, Location loc, ValueRange ivs, ValueRange tileSizes)
Compute tile offsets, given a list of loop ivs and tileSizes.
SmallVector< Value > computeTileSizes (OpBuilder &b, Location loc, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Compute tile sizes, given a list of loop ivs, tileSizes and dimension sizes (sizeBounds).
Value makeTiledShape (OpBuilder &builder, Location loc, Value valueToTile, ValueRange tileSizes, AffineMap map, ValueRange lbs, ValueRange ubs, ValueRange subShapeSizes)
Creates an extract_slice/subview op for a single valueToTile with builder.
SmallVector< Value, 4 > makeTiledShapes (OpBuilder &builder, Location loc, LinalgOp linalgOp, ArrayRef< Value > valuesToTile, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Creates extract_slice/subview ops for all valuesToTile of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
void addTileLoopIvsToIndexOpResults (OpBuilder &b, LinalgOp tiledOp, ArrayRef< Value > ivs)
Add the tile loop induction variables ivs to the IndexOp results found in the body of the tiledOp to account for the tile offset.
FusableOpDependencesTy findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph)
Find all dependences that are fusable.
FailureOr< FusionInfo > fuseProducerOfBuffer (OpBuilder &b, OpOperand &consumerOpOperand, const LinalgDependenceGraph &graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
FailureOr< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpOperand &consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
FailureOr< FusionInfo > fuseProducerOfTensor (OpBuilder &b, OpResult producerOpResult, OpOperand &consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
FailureOr< TileLoopNest > tileConsumerAndFuseProducers (OpBuilder &b, LinalgOp consumerOp, ArrayRef< int64_t > tileSizes, ArrayRef< int64_t > tileInterchange)
Tiles consumerOp and fuses its dependencies if possible.
void updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
static void generateParallelLoopNest (OpBuilder &b, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage, ArrayRef< DistributionMethod > distributionMethod={})
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
static Value fullyComposeAndAffineApply (OpBuilder &b, Location loc, AffineExpr expr, ValueRange operands)
Typedef Documentation
AllocBufferCallbackFn
using mlir::linalg::AllocBufferCallbackFn = typedef std::function<Optional<Value>(OpBuilder &b, memref::SubViewOp subView, ArrayRef<Value> boundingSubViewSize, DataLayout &layout)>
Callback function type used to perform the allocation for the promoted subView.
In boundingSubViewsize a best attempt is made to find the smallest constant value for the size of the buffer needed for each dimension. If that is not possible, contains the dynamic size of the subview. The call back should return the buffer to use.
Definition at line 258 of file Transforms.h.
ControlElementwiseOpsFusionFn
using mlir::linalg::ControlElementwiseOpsFusionFn = typedef std::function<bool(const OpResult &producer, OpOperand &consumer)>
Function type which is used to control when to stop fusion.
It is expected that OpOperand is not modified in the callback. The OpOperand is not marked as const to allow callers to use non-const methods.
Definition at line 66 of file Transforms.h.
CopyCallbackFn
using mlir::linalg::CopyCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
The copy has to happen from src to dst.
Definition at line 270 of file Transforms.h.
DeallocBufferCallbackFn
using mlir::linalg::DeallocBufferCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
Definition at line 263 of file Transforms.h.
detect_has_get_operation_name
template<typename T > using mlir::linalg::detect_has_get_operation_name = typedef llvm::is_detected<has_get_operation_name, T>
Definition at line 1069 of file Transforms.h.
FusableOpDependencesTy
using mlir::linalg::FusableOpDependencesTy = typedef llvm::MapVector< Operation *, SmallVector<LinalgDependenceGraph::LinalgDependenceGraphElem, 1> >
Definition at line 199 of file Utils.h.
has_get_operation_name
template<typename T , typename... Args> using mlir::linalg::has_get_operation_name = typedef decltype(T::getOperationName())
Trait to check if T provides a getOperationName method.
Definition at line 1066 of file Transforms.h.
LinalgLoops
using mlir::linalg::LinalgLoops = typedef SmallVector<Operation *, 4>
Definition at line 45 of file Transforms.h.
LoopRangeBuilder
using mlir::linalg::LoopRangeBuilder = typedef std::function<SmallVector<Range, 4>(ImplicitLocOpBuilder)>
Definition at line 42 of file LinalgOps.h.
OneDimProcInfoCallBackFn
using mlir::linalg::OneDimProcInfoCallBackFn = typedef std::function<ProcInfo(OpBuilder &b, Location loc)>
Definition at line 358 of file Utils.h.
OptimizeCopyFn
using mlir::linalg::OptimizeCopyFn = typedef std::function<LogicalResult(PatternRewriter &, PadTensorOp, Value)>
Definition at line 1217 of file Transforms.h.
PaddingHoistComputationFunction
using mlir::linalg::PaddingHoistComputationFunction = typedef std::function<int64_t(OpOperand &)>
Callback returning the number of loops to hoist the pad tensor operation defining the given OpOperand.
Definition at line 479 of file Transforms.h.
PaddingNoFoldComputationFunction
using mlir::linalg::PaddingNoFoldComputationFunction = typedef std::function<bool(OpOperand &)>
Callback returning true if the pad tensor operation defining the given OpOperand shall be marked as nofold to enable packing.
Definition at line 475 of file Transforms.h.
PaddingValueComputationFunction
using mlir::linalg::PaddingValueComputationFunction = typedef std::function<FailureOr<Value>(OpBuilder &, OpOperand &)>
Callback returning the padding value to use for a given OpOperand or failure for no padding.
This should be a function of both the operation and the operand type.
Definition at line 471 of file Transforms.h.
ProcInfoCallBackFn
using mlir::linalg::ProcInfoCallBackFn = typedef std::function<SmallVector<ProcInfo, 2>(OpBuilder &b, Location loc, ArrayRef<Range> parallelLoopRanges)>
Definition at line 356 of file Utils.h.
TileSizeComputationFunction
using mlir::linalg::TileSizeComputationFunction = typedef std::function<SmallVector<Value, 4>(OpBuilder &, Operation *)>
Definition at line 465 of file Transforms.h.
Enumeration Type Documentation
DistributionMethod
enum mlir::linalg::DistributionMethod strong
Scheme used to distribute loops to processors.
Enumerator
Cyclic
Cyclic distribution where no assumption is made about the dynamic relationship between number of processors and number of iterations of the distributed loop.
Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
scf.parallel(iv)= (lb + procId * step) to (ub) step (step * nprocs)
CyclicNumProcsGeNumIters
Cyclic distribution where the number of processors can be assumed to be more than or equal to the number of iterations of the distributed loop.
In such cases, a simple in-bounds check is enough (instead of materializing a loop). Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step cond = arith.cmpi "slt", iv, ub scf.if cond { ... }
CyclicNumProcsEqNumIters
Cyclic distribution where the number of processors can be assumed to be equal to the number of iterations of the distributed loop.
In such cases, no bounds check is needed. Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step
Definition at line 309 of file Utils.h.
LinalgLoweringType
enum mlir::linalg::LinalgLoweringType strong
Linalg lowering patterns.
Apply the linalgLowerOpToLoops transformation as a pattern. filter controls LinalgTransformMarker matching and update when specified. See linalgLowerOpToLoops for more details.
Enumerator
LibraryCall
Loops
AffineLoops
ParallelLoops
Definition at line 1112 of file Transforms.h.
LinalgTilingLoopType
enum mlir::linalg::LinalgTilingLoopType strong
The type of loops to be generated during tiling.
Enumerator
Loops
AffineLoops
ParallelLoops
TiledLoops
Definition at line 137 of file Utils.h.
Function Documentation
addTileLoopIvsToIndexOpResults()
void mlir::linalg::addTileLoopIvsToIndexOpResults (OpBuilder & b, LinalgOp tiledOp, ArrayRef< Value > ivs)
Add the tile loop induction variables ivs to the IndexOp results found in the body of the tiledOp to account for the tile offset.
Definition at line 903 of file Utils.cpp.
References mlir::bindDims(), mlir::Builder::getContext(), mlir::makeComposedAffineApply(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by fuse(), getTiledProducer(), and transformIndexOps().
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
Definition at line 434 of file LinalgInterfaces.cpp.
Referenced by getCollapsedOutputDimFromInputShape(), getExpandedOutputDimFromInputShape(), makeTiledLoopRanges(), makeTiledShape(), mlir::linalg::LinalgTilingOptions::scalarizeDynamicDims(), verify(), and HasAffineDimExprVisitor::visitSymbolExpr().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< int64_t > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 41 of file Utils.h.
References createOrFoldDimOp(), mlir::detail::enumerate(), getConstantUpperBoundForIndex(), getDynOperands(), getUpperBoundForIndex(), makeComposedExtractSliceOp(), makeComposedPadHighOp(), and value.
Referenced by interchangeGenericOp(), tileConsumerAndFuseProducers(), and tileLinalgOpImpl().
applyStagedPatterns()
LogicalResult mlir::linalg::applyStagedPatterns (Operation * op, ArrayRef< FrozenRewritePatternSet > stage1Patterns, const FrozenRewritePatternSet & stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda = nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
the first stage consists of a list of FrozenRewritePatternSet. Each FrozenRewritePatternSet in this list is applied once, in order.
the second stage consists of a single OwningRewritePattern that is applied greedily until convergence.
the third stage consists of applying a lambda, generally used for non-local transformation effects. This allows creating custom fused transformations where patterns can be ordered and applied at a finer granularity than a sequence of traditional compiler passes.
Definition at line 714 of file Transforms.cpp.
References mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::linalg::ConvOpVectorization< ConvOp, N >::ConvOpVectorization().
computeTileOffsets()
SmallVector< Value > mlir::linalg::computeTileOffsets (OpBuilder & b, Location loc, ValueRange ivs, ValueRange tileSizes)
Compute tile offsets, given a list of loop ivs and tileSizes.
In case a tile size is zero (i.e., no tiling), the corresponding offset is also zero.
Definition at line 828 of file Utils.cpp.
References mlir::OpBuilder::create(), isTiled(), and isZero().
Referenced by makeTiledShapes(), and tilePadTensorOp().
computeTileSizes()
SmallVector< Value > mlir::linalg::computeTileSizes (OpBuilder & b, Location loc, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Compute tile sizes, given a list of loop ivs, tileSizes and dimension sizes (sizeBounds).
In case a tile size is zero (i.e., no tiling), the corresponding result size is the corresponding value from sizeBounds. Note: The returned tile sizes are closed intervals.
Definition at line 843 of file Utils.cpp.
References fullyComposeAndAffineApply(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), isTiled(), and isZero().
Referenced by makeTiledShapes(), and tilePadTensorOp().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 2654 of file LinalgOps.cpp.
Referenced by mlir::Simplex::makeProduct().
createLinalgOpOnBuffers()
LinalgOp mlir::linalg::createLinalgOpOnBuffers (ConversionPatternRewriter & rewriter, LinalgOp linalgOp, ValueRange inputs, ValueRange outputs)
Create linalg op on buffers given the original tensor-based operation and the buffers for the outputs.
Definition at line 82 of file Bufferize.cpp.
References mlir::ConversionTarget::addDynamicallyLegalDialect(), mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalDialect(), allocateBuffersForResults(), mlir::applyPartialConversion(), cloneMemref(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Value::getType(), mlir::ConversionPattern::getTypeConverter(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::Type::isa(), mlir::TypeConverter::isLegal(), mlir::OpConversionPattern< SourceOp >::matchAndRewrite(), mlir::ConversionPatternRewriter::notifyMatchFailure(), populateLinalgBufferizePatterns(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and value.
createOrFoldDimOp()
Value mlir::linalg::createOrFoldDimOp (OpBuilder & b, Location loc, Value source, int64_t dim)
Helper function that creates a memref::DimOp or tensor::DimOp depending on the type of source.
Definition at line 160 of file Utils.cpp.
References mlir::OpBuilder::createOrFold(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by applyPermutationToVector(), createInBoundsCond(), createSubViewIntersection(), fuse(), genBuffers(), getDynOperands(), makeTiledShape(), MaterializeTransferMask< ConcreteOp >::matchAndRewrite(), and HasAffineDimExprVisitor::visitSymbolExpr().
defaultLoopRangesBuilder()
LoopRangeBuilder mlir::linalg::defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
This only works with permutation affine maps and patterns of the form (m, n)[s] -> (m + n - s floordiv 2). A more advanced Tensor-Comprehension like inference is possible but has proven to be ambiguous in unfavorable case. As a consequence, we relax the default behavior very conservatively and provide an op-specified hook so that Linalg ops may override the behavior.
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 2634 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
findAllFusableDependences()
FusableOpDependencesTy mlir::linalg::findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph)
Find all dependences that are fusable.
Definition at line 722 of file Fusion.cpp.
References findFusableProducer().
Referenced by tileAndFuseLinalgOpsImpl().
fullyComposeAndAffineApply()
static Value mlir::linalg::fullyComposeAndAffineApply (OpBuilder & b, Location loc, AffineExpr expr, ValueRange operands) static
Definition at line 710 of file Utils.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::OpBuilder::createOrFold(), mlir::fullyComposeAffineMapAndOperands(), and mlir::AffineMap::inferFromExprList().
Referenced by computeTileSizes(), and makeTiledShape().
fuseProducerOfBuffer()
FailureOr< FusionInfo > mlir::linalg::fuseProducerOfBuffer (OpBuilder & b, OpOperand & consumerOpOperand, const LinalgDependenceGraph & graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Implements the fusion part of the "tileAndFuse on buffers" transformation and thus requires the consumerOpOperand to be a subview op (generally obtained by applying the tiling transformation).
Definition at line 393 of file Fusion.cpp.
References mlir::failure(), findFusableProducer(), fuse(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getParentBlock(), and mlir::OpBuilder::setInsertionPoint().
fuseProducerOfTensor() [1/2]
FailureOr< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpOperand & consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation).
Definition at line 463 of file Fusion.cpp.
References mlir::failure(), mlir::IROperand< DerivedT, IRValueT >::get(), and getProducerOfTensor().
fuseProducerOfTensor() [2/2]
FailureOr< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, OpResult producerOpResult, OpOperand & consumerOpOperand)
Tensor counterpart of fuseProducerOfBuffer.
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerOpOperand to be a extract_slice op (generally obtained by applying the tiling transformation). Assumes producerOfTensor is a Linalg op that produces consumerOpOperand.
Definition at line 475 of file Fusion.cpp.
References mlir::OpBuilder::create(), mlir::failure(), fuse(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::OpResult::getOwner(), mlir::Value::getParentBlock(), mlir::OpResult::getResultNumber(), mlir::Value::getType(), mlir::IROperand< DerivedT, IRValueT >::set(), and mlir::OpBuilder::setInsertionPoint().
generalizeNamedOp()
GenericOp mlir::linalg::generalizeNamedOp (PatternRewriter & rewriter, LinalgOp namedOp)
Creates a GenericOp from the given named operation namedOp.
Assumes namedOp is not a GenericOp and has a region builder.
Definition at line 43 of file Generalization.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::OpBuilder::create(), mlir::RewriterBase::inlineRegionBefore(), and populateLinalgNamedOpsGeneralizationPatterns().
Referenced by mlir::linalg::LinalgGeneralizationPattern::matchAndRewrite().
generalizeNamedOpPrecondition()
LogicalResult mlir::linalg::generalizeNamedOpPrecondition (Operation * op)
Generalize named operations to generic operations.
Definition at line 32 of file Generalization.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgGeneralizationPattern::matchAndRewrite().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(f, A) : f32, memref<f32> name mangles into linalg_fill_f32_viewf32
linalg.dot A, B, C : (memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32>) name mangles into linalg_dot_viewxf32_viewxf32_viewf32
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32
Definition at line 2683 of file LinalgOps.cpp.
References appendMangledType(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), and mlir::OperationName::getStringRef().
generateParallelLoopNest()
static void mlir::linalg::generateParallelLoopNest (OpBuilder & b, Location loc, ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > & ivStorage, ArrayRef< DistributionMethod > distributionMethod = {}) static
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
` Consecutive parallel loops create a single scf.parallel operation; each sequential loop creates a new scf.for operation. The body of the innermost loop is populated by bodyBuilderFn that accepts a range of induction variables for all loops. ivStorage is used to store the partial list of induction variables.
Definition at line 530 of file Utils.cpp.
References mlir::ArithBuilder::_and(), mlir::scf::buildLoopNest(), mlir::OpBuilder::create(), Cyclic, CyclicNumProcsEqNumIters, CyclicNumProcsGeNumIters, mlir::isParallelIterator(), and mlir::ArithBuilder::slt().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
getConstantUpperBoundForIndex()
FailureOr< int64_t > mlir::linalg::getConstantUpperBoundForIndex (Value value)
Returns a constant upper bound for the result value of an index computation.
Calls getUpperBoundForIndex and returns a constant upper bound if the result of boundMap is a constant expression and failure otherwise.
Example:
%0 = affine.min affine.map<(d0) -> (40, d0)> (%d0)
%1 = affine.apply affine.map<(d0) -> (d0 + 2)> (%0)
getConstantUpperBoundForIndex(%1) returns 42 (boundsMap = affine.map<() -> (42)>)
Definition at line 265 of file Utils.cpp.
References mlir::failure(), mlir::AffineMap::getResults(), and getUpperBoundForIndex().
Referenced by applyPermutationToVector(), padOperandToSmallestStaticBoundingBox(), and promoteSubviewAsNewBuffer().
getDimsOfType()
void mlir::linalg::getDimsOfType (Operation * op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > & res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
Assumes op is a LinalgOp.
Definition at line 2619 of file LinalgOps.cpp.
getDynOperands()
SmallVector< Value, 4 > mlir::linalg::getDynOperands (Location loc, Value val, OpBuilder & b)
Given an operation, retrieves the value of each dynamic dimension through constructing the necessary DimOp operators.
Definition at line 170 of file Utils.cpp.
References mlir::Type::cast(), createOrFoldDimOp(), mlir::detail::enumerate(), mlir::Value::getType(), and mlir::ShapedType::kDynamicSize.
Referenced by allocateBuffersForResults(), applyPermutationToVector(), and cloneMemref().
getLinalgTilingCanonicalizationPatterns()
RewritePatternSet mlir::linalg::getLinalgTilingCanonicalizationPatterns (MLIRContext * ctx)
Canonicalization patterns relevant to apply after tiling patterns.
These are applied automatically by the tiling pass but need to be applied manually when tiling is called programmatically.
Definition at line 463 of file Tiling.cpp.
References populateLinalgTilingCanonicalizationPatterns().
Referenced by applyExtractSliceOfPadTensorSwapPattern(), and mlir::linalg::LinalgTilingOptions::setPeeledLoops().
getUpperBoundForIndex()
void mlir::linalg::getUpperBoundForIndex (Value value, AffineMap & boundMap, SmallVectorImpl< Value > & boundOperands)
Computes an upper bound for the result value of an index computation.
Translates AffineMinOps and AffineApplyOps along the use-def chains of the index computation to affine constraints and projects out intermediate values. The method sets boundMap to an affine map that given boundOperands evaluates to an upper bound for the index computation.
Example:
%dim0 = dim %tensor, %c0
%dim1 = dim %tensor, %c1
%0 = affine.min affine.map<(d0) -> (40, d0)> (%dim0)
%1 = affine.apply affine.map<(d0, d1) -> (d0 + d1)> (%0, %dim1)
getUpperBoundForIndex(%1, boundMap, boundOperands) set the output parameters to:
boundMap = affine.map<(d0) -> (d0 + 40)>
boundOperands = [dim1]
Definition at line 180 of file Utils.cpp.
References mlir::FlatAffineValueConstraints::addBound(), mlir::FlatAffineValueConstraints::appendDimId(), mlir::canonicalizeMapAndOperands(), mlir::FlatAffineValueConstraints::composeMap(), mlir::FlatAffineValueConstraints::computeAlignedMap(), mlir::FlatAffineValueConstraints::containsId(), mlir::failed(), mlir::FlatAffineValueConstraints::findId(), mlir::FlatAffineValueConstraints::getAllValues(), mlir::getBackwardSlice(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::Value::getType(), mlir::Type::isIndex(), mlir::FlatAffineConstraints::UB, and value.
Referenced by applyPermutationToVector(), getConstantUpperBoundForIndex(), and HoistingAnalysis::getPackedTensorSizes().
hoistPaddingOnTensors()
FailureOr< Value > mlir::linalg::hoistPaddingOnTensors (PadTensorOp opToHoist, int numLoops, PadTensorOp & hoistedOp)
Mechanically hoist padding operations on tensors by numLoops into a new, generally larger tensor.
This achieves packing of multiple padding ops into a larger tensor. On success, padTensorOp is replaced by the cloned version in the packing loop so the caller can continue reasoning about the padding operation.
Example in pseudo-mlir:
If hoistPaddingOnTensors is called with nLoops = 2 on the following IR.
scf.for (%i, %j, %k)
  %st0 = tensor.extract_slice f(%i, %k) : ... to tensor<?x?xf32>
  %0 = linalg.pad_tensor %st0 low[0, 0] high[...] {
  ^bb0( ... ):
    linalg.yield %pad
  } : tensor<?x?xf32> to tensor<4x8xf32>
  compute(%0)
IR resembling the following is produced:
scf.for (%i) {
  %packed_init = linalg.init_tensor range(%j) : tensor<?x4x8xf32>
  %packed = scf.for (%k) iter_args(%p : %packed_init) {
    %st0 = tensor.extract_slice f(%i, %k) : ... to tensor<?x?xf32>
    %0 = linalg.pad_tensor %st0 low[0, 0] high[...] {
    ^bb0( ... ):
      linalg.yield %pad
    } : tensor<?x?xf32> to tensor<4x8xf32>
    %1 = tensor.insert_slice %0 ...
        : tensor<4x8xf32> to tensor<?x4x8xf32>
    scf.yield %1: tensor<?x4x8xf32>
  } -> tensor<?x4x8xf32>
  scf.for (%j, %k) {
    %st0 = tensor.extract_slice %packed [%k, 0, 0][1, 4, 8][1, 1, 1] :
             tensor<?x4x8xf32> to tensor<4x8xf32>
    compute(%st0)
  }
}
Definition at line 376 of file HoistPadding.cpp.
References HoistingAnalysis::backwardSlice, buildLoopIterationCount(), DBGS, mlir::failure(), mlir::scf::getForInductionVarOwner(), HoistingAnalysis::getPackedTensorSizes(), mlir::ShapedType::isDynamic(), HoistingAnalysis::isValid(), mlir::ShapedType::kDynamicSize, mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), HoistingAnalysis::outermostEnclosingForOp, and HoistingAnalysis::packingLoops.
Referenced by mlir::linalg::LinalgPaddingPattern::matchAndRewrite().
hoistRedundantVectorTransfers()
void mlir::linalg::hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write on buffers pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
The two ops access the same memref with the same indices.
All operands are invariant under the enclosing scf::ForOp.
No uses of the memref either dominate the transfer_read or are dominated by the transfer_write (i.e. no aliasing between the write and the read across the loop) To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist. Hoisting the transfers results in scf::ForOp yielding the value that originally transited through memory.
Definition at line 393 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::getForwardSlice(), mlir::WalkResult::interrupt(), mlir::moveLoopInvariantCode(), and mlir::DominanceInfo::properlyDominates().
hoistRedundantVectorTransfersOnTensor()
void mlir::linalg::hoistRedundantVectorTransfersOnTensor (FuncOp func)
Same behavior as hoistRedundantVectorTransfers but works on tensors instead of buffers.
Definition at line 341 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::detail::enumerate(), findMatchingTransferRead(), getLoopInvariantTransferWriteOpDefining(), mlir::Operation::getOpOperand(), hoistReadWrite(), mlir::WalkResult::interrupt(), and tensorChunkAccessedByUnknownOp().
insertVectorizationPatternImpl() [1/2]
template<typename OpType , typename = std::enable_if_t<detect_has_get_operation_name<OpType>::value>, typename = void> void mlir::linalg::insertVectorizationPatternImpl (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ op with a getOperationName method.
Definition at line 1076 of file Transforms.h.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
insertVectorizationPatternImpl() [2/2]
template<typename OpType , typename = std::enable_if_t< !detect_has_get_operation_name<OpType>::value>> void mlir::linalg::insertVectorizationPatternImpl (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f)
SFINAE helper for single C++ class without a getOperationName method (e.g.
an OpInterface).
Definition at line 1087 of file Transforms.h.
References mlir::RewritePatternSet::add(), mlir::linalg::LinalgTransformationFilter::addOpFilter(), and mlir::RewritePatternSet::getContext().
insertVectorizationPatterns()
template<typename... OpTypes> void mlir::linalg::insertVectorizationPatterns (RewritePatternSet & patternList, linalg::LinalgVectorizationOptions options, linalg::LinalgTransformationFilter f = linalg::LinalgTransformationFilter())
Variadic helper function to insert vectorization patterns for C++ ops.
Definition at line 1096 of file Transforms.h.
References options.
interchangeGenericOp()
void mlir::linalg::interchangeGenericOp (PatternRewriter & rewriter, GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions and adapts the index accesses of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 46 of file Interchange.cpp.
References applyPermutationToVector(), mlir::AffineMap::compose(), mlir::OpBuilder::create(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getSubMap(), mlir::inversePermutation(), mlir::AffineMap::isEmpty(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::GenericOpInterchangePattern::matchAndRewrite().
interchangeGenericOpPrecondition()
LogicalResult mlir::linalg::interchangeGenericOpPrecondition (GenericOp genericOp, ArrayRef< unsigned > interchangeVector)
Emits a generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 33 of file Interchange.cpp.
References mlir::failure(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::GenericOpInterchangePattern::matchAndRewrite().
isaContractionOpInterface()
bool mlir::linalg::isaContractionOpInterface (LinalgOp linalgOp)
Checks whether linalgOp conforms to ContractionOpInterface.
Definition at line 121 of file LinalgInterfaces.cpp.
References isContractionInterfaceImpl(), and Success.
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 311 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by findFusableProducer().
isPermutation()
bool mlir::linalg::isPermutation (ArrayRef< int64_t > permutation)
Check if permutation is a permutation of the range [0, permutation.size()).
Definition at line 145 of file Utils.cpp.
Referenced by mlir::linalg::LinalgTileAndFuseTensorOpsPattern::matchAndRewrite(), and tileConsumerAndFuseProducers().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 287 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by isFusableInto().
linalgOpToAffineLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToAffineLoops (PatternRewriter & rewriter, LinalgOp linalgOp)
Emits a loop nest of affine.for with the proper body for linalgOp.
Definition at line 551 of file Loops.cpp.
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToLoops (PatternRewriter & rewriter, LinalgOp linalgOp)
Emits a loop nest of scf.for with the proper body for linalgOp.
Definition at line 557 of file Loops.cpp.
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToParallelLoops()
FailureOr< LinalgLoops > mlir::linalg::linalgOpToParallelLoops (PatternRewriter & rewriter, LinalgOp linalgOp)
Emits a loop nest of scf.parallel with the proper body for linalgOp.
Definition at line 564 of file Loops.cpp.
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 2645 of file LinalgOps.cpp.
makeComposedExtractSliceOp()
tensor::ExtractSliceOp mlir::linalg::makeComposedExtractSliceOp (OpBuilder & b, Location loc, Value source, ArrayRef< OpFoldResult > offsets, ArrayRef< OpFoldResult > sizes, ArrayRef< OpFoldResult > strides)
Create an ExtractSliceOp and, if source is defined by an ExtractSliceOp, fold it by adding the offsets.
Example:
%0 = tensor.extract_slice %arg0[3, 4][3, 32][1, 1] : tensor<64x64xf32> to
                                                       tensor<3x32xf32>
%1 = tensor.extract_slice %0[0, 5][3, 4][1, 1] : tensor<3x32xf32> to
                                                   tensor<3x4xf32>
folds into:
%1 = tensor.extract_slice %arg0[3, 9][3, 4][1, 1] : tensor<64x64xf32> to
                                                      tensor<3x4xf32>
Definition at line 283 of file Utils.cpp.
References mlir::bindDims(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::getConstantIntValue(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::getValueOrCreateConstantIndexOp(), and mlir::makeComposedAffineApply().
Referenced by applyPermutationToVector(), and makeTiledShape().
makeComposedPadHighOp()
Value mlir::linalg::makeComposedPadHighOp (OpBuilder & b, Location loc, RankedTensorType type, Value source, Value pad, bool nofold)
Create a PadTensorOp that pads source to the size of the statically sized type whose static sizes are assumed to be greater than the dynamic source size.
The padding introduces trailing pad values until the target size is met. If source is defined by one or more LinalgOps that have been padded with the same value and sizes, return their padded result instead of creating a PadTensorOp.
Example:
%0 = tensor.extract_slice %arg0 [%iv0, %iv1] [%sz0, %sz1]
%1 = linalg.pad_tensor %0 low[0, 0] high[...] { linalg.yield %cst }
%2 = linalg.matmul ins(...) outs(%1)
%3 = tensor.extract_slice %2 [0, 0] [%sz0, %sz1]
makeComposedPadHighOp(source=%3, pad=cst) returns %2 makeComposedPadHighOp(source=%3, pad=other_cst) returns %4
%4 = linalg.pad_tensor %3 low[0, 0] high[...] { linalg.yield %other_cst }
Definition at line 325 of file Utils.cpp.
References mlir::Value::cast(), mlir::getConstantIntValue(), mlir::Value::getDefiningOp(), mlir::OpResult::getResultNumber(), mlir::isEqualConstantIntOrValue(), mlir::m_Constant(), and mlir::matchPattern().
Referenced by applyPermutationToVector(), and padOperandToSmallestStaticBoundingBox().
makeTiledShape()
Value mlir::linalg::makeTiledShape (OpBuilder & builder, Location loc, Value valueToTile, ValueRange tileSizes, AffineMap map, ValueRange lbs, ValueRange ubs, ValueRange subShapeSizes)
Creates an extract_slice/subview op for a single valueToTile with builder.
This new operation extracts a tile of valueToTile, starting at offsets lbs and with sizes subShapeSizes.
Definition at line 719 of file Utils.cpp.
References applyMapToValues(), mlir::bindDims(), mlir::canonicalizeMapAndOperands(), mlir::OpBuilder::create(), createOrFoldDimOp(), mlir::Type::dyn_cast(), mlir::fullyComposeAffineMapAndOperands(), fullyComposeAndAffineApply(), mlir::getAffineSymbolExpr(), mlir::getAsOpFoldResult(), mlir::Builder::getContext(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::AffineMap::inferFromExprList(), mlir::ShapedType::isDynamic(), isTiled(), mlir::makeComposedAffineApply(), makeComposedExtractSliceOp(), and mlir::arith::ConstantIndexOp::value().
Referenced by makeTiledShapes(), and tilePadTensorOp().
makeTiledShapes()
SmallVector< Value, 4 > mlir::linalg::makeTiledShapes (OpBuilder & builder, Location loc, LinalgOp linalgOp, ArrayRef< Value > valuesToTile, ValueRange ivs, ValueRange tileSizes, ArrayRef< Value > sizeBounds)
Creates extract_slice/subview ops for all valuesToTile of the given linalgOp with builder, assuming linalgOp is being fused into a loop nest for tiling with the given induction variables ivs and tile sizes tileSizes.
sizeBounds are the iteration space bounds for all the implicit loops in linalgOp.
Note that a constant zero in tileSizes means no tiling at that implicit loop. The number of non-zero values in tileSizes should be equal to the number of values in ivs.
Definition at line 858 of file Utils.cpp.
References computeTileOffsets(), computeTileSizes(), isTiled(), isZero(), and makeTiledShape().
Referenced by fuse(), and getTiledProducer().
peelAndCanonicalizeTiledLoop()
LogicalResult mlir::linalg::peelAndCanonicalizeTiledLoop (RewriterBase & rewriter, TiledLoopOp loopOp, int64_t idx, TiledLoopOp & result)
Rewrite a TiledLoopOp with bounds/step that potentially do not divide evenly into a TiledLoopOp where the step divides the iteration space evenly, followed by another TiledLoopOp for the last (partial) iteration (if any).
This transformation is called "loop peeling".
This function peels the idx-th loop of the TiledLoopOp. To tile all loops in the loop nest, this function must be called multiple times.
After loop peeling, this function tries to simplify/canonicalize affine.min and affine.max ops in the body of the two TiledLoopOps. For more details, refer to mlir::scf::peelAndCanonicalizeForLoop.
The return value indicates whether the loop was rewritten or not. Loops are not rewritten if:
Loop step size is 1 or
Loop bounds and step size are static, and step already divides the iteration space evenly.
Note: This function rewrites the given TiledLoopOp in-place and clones the TileLoopOp operation for the last iteration. It replaces all uses of the unpeeled TiledLoopOp with the results of the newly generated TiledLoopOp.
Definition at line 499 of file Loops.cpp.
References mlir::failed(), mlir::failure(), peelTiledLoop(), rewriteAffineOpAfterPeeling(), and mlir::success().
Referenced by mlir::linalg::ConvOpVectorization< ConvOp, N >::ConvOpVectorization(), and peelLoop().
populateConvolutionVectorizationPatterns()
void mlir::linalg::populateConvolutionVectorizationPatterns (RewritePatternSet & patterns, PatternBenefit benefit = 1)
Populates patterns for vectorizing low-D convolution ops.
This is a step in progressive lowering for convolution ops, it assume high-D convolution ops were decomposed previously.
Definition at line 1774 of file Vectorization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateConvVectorizationPatterns()
void mlir::linalg::populateConvVectorizationPatterns (MLIRContext * context, SmallVectorImpl< RewritePatternSet > & patterns, ArrayRef< int64_t > tileSizes)
[DEPRECATED] Populates patterns for vectorization of all ConvN-D ops.
Definition at line 1187 of file Vectorization.cpp.
populateDecomposeConvolutionPatterns()
void mlir::linalg::populateDecomposeConvolutionPatterns (RewritePatternSet & patterns, LinalgTransformationFilter filter = LinalgTransformationFilter(), PatternBenefit benefit = 1)
Linalg decompose convolutions patterns.
Populates patterns to decompose high-D convolution ops into low-D ones. This is a step in progressive lowering for convolution ops, afterwards we can vectorize the low-D convolution ops.
Definition at line 1099 of file Transforms.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateElementwiseOpsFusionPatterns()
void mlir::linalg::populateElementwiseOpsFusionPatterns (RewritePatternSet & patterns, LinalgElementwiseFusionOptions options = LinalgElementwiseFusionOptions())
Patterns for fusing linalg operation on tensors.
Definition at line 1764 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), mlir::linalg::LinalgElementwiseFusionOptions::controlElementwiseOpsFusionFn, mlir::linalg::LinalgElementwiseFusionOptions::controlFoldingReshapesFn, mlir::RewritePatternSet::getContext(), and populateFoldReshapeOpsByExpansionPatterns().
Referenced by mlir::linalg::LinalgElementwiseFusionOptions::setControlElementwiseOpsFusionFn(), and skipUnitDimReshape().
populateElementwiseToLinalgConversionPatterns()
void mlir::linalg::populateElementwiseToLinalgConversionPatterns (RewritePatternSet & patterns)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
Definition at line 119 of file ElementwiseToLinalg.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPartialConversion(), mlir::failed(), mlir::RewritePatternSet::getContext(), isElementwiseMappableOpOnRankedTensors(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().
populateFoldReshapeOpsByExpansionPatterns()
void mlir::linalg::populateFoldReshapeOpsByExpansionPatterns (RewritePatternSet & patterns, ControlElementwiseOpsFusionFn controlFoldingReshapes = skipUnitDimReshape)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
Definition at line 1755 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by populateElementwiseOpsFusionPatterns().
populateFoldReshapeOpsByLinearizationPatterns()
void mlir::linalg::populateFoldReshapeOpsByLinearizationPatterns (RewritePatternSet & patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic operation.
Definition at line 1735 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by skipUnitDimReshape().
populateFoldUnitDimsReshapeOpsByLinearizationPatterns()
void mlir::linalg::populateFoldUnitDimsReshapeOpsByLinearizationPatterns (RewritePatternSet & patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic operation.
The patterns are applied only when the tensor reshape involved is collapsing (introducing) unit-extent dimensions.
Definition at line 1745 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by skipUnitDimReshape().
populateFoldUnitExtentDimsPatterns()
void mlir::linalg::populateFoldUnitExtentDimsPatterns (RewritePatternSet & patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
Patterns that are used to canonicalize the use of unit-extent dims for broadcasting.
Definition at line 545 of file DropUnitDims.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), and mlir::RewritePatternSet::getContext().
populateInlineConstantOperandsPatterns()
void mlir::linalg::populateInlineConstantOperandsPatterns (RewritePatternSet & patterns)
Patterns that are used to inline constant operands into linalg generic ops.
Definition at line 90 of file InlineScalarOperands.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPatternsAndFoldGreedily(), and mlir::RewritePatternSet::getContext().
populateLinalgBufferizePatterns()
void mlir::linalg::populateLinalgBufferizePatterns (bufferization::BufferizeTypeConverter & converter, RewritePatternSet & patterns)
Populates the given list with patterns to bufferize linalg ops.
Definition at line 348 of file Bufferize.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by createLinalgOpOnBuffers().
populateLinalgDistributeTiledLoopPattern()
void mlir::linalg::populateLinalgDistributeTiledLoopPattern (RewritePatternSet & patterns, const LinalgLoopDistributionOptions & opts, const LinalgTransformationFilter & marker)
Linalg distribution patterns.
Populates patterns with patterns to distribute linalg.tiled_loop.
Definition at line 81 of file Distribution.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgNamedOpsGeneralizationPatterns()
void mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns (RewritePatternSet & patterns, LinalgTransformationFilter filter = LinalgTransformationFilter())
Linalg generalization patterns.
Populates patterns with patterns to convert spec-generated named ops to linalg.generic ops.
Definition at line 80 of file Generalization.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by generalizeNamedOp(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgTilingCanonicalizationPatterns()
void mlir::linalg::populateLinalgTilingCanonicalizationPatterns (RewritePatternSet & patterns)
Definition at line 469 of file Tiling.cpp.
References mlir::RewritePatternSet::getContext().
Referenced by getLinalgTilingCanonicalizationPatterns(), and mlir::linalg::LinalgTilingOptions::setPeeledLoops().
populateLinalgToStandardConversionPatterns()
void mlir::linalg::populateLinalgToStandardConversionPatterns (RewritePatternSet & patterns)
Populate the given list with patterns that convert from Linalg to Standard.
Definition at line 165 of file LinalgToStandard.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), mlir::applyFullConversion(), mlir::failed(), and mlir::RewritePatternSet::getContext().
populatePadTensorOpVectorizationPatterns()
void mlir::linalg::populatePadTensorOpVectorizationPatterns (RewritePatternSet & patterns, PatternBenefit baseBenefit = 1)
Populates patterns with patterns that vectorize linalg.pad_tensor.
These patterns are meant to apply in a complementary fashion. Benefits are used to encode a certain ordering of pattern application. To avoid scattering magic constants throughout the code base, the patterns must be added with this function. baseBenefit can be used to offset the benefit of all PadTensorOp vectorization patterns by a certain value.
Definition at line 1078 of file Vectorization.cpp.
References mlir::RewritePatternSet::add(), mlir::PatternBenefit::getBenefit(), and mlir::RewritePatternSet::getContext().
populatePushReshapeOpsPatterns()
void mlir::linalg::populatePushReshapeOpsPatterns (RewritePatternSet & patterns)
Patterns to push reshape op towards the end of the graph in order to expose more fusion opportunities.
Definition at line 1781 of file ElementwiseOpFusion.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by mlir::linalg::LinalgElementwiseFusionOptions::setControlElementwiseOpsFusionFn().
populateTiledLoopToSCFPattern()
void mlir::linalg::populateTiledLoopToSCFPattern (RewritePatternSet & patterns)
Pattern to convert TiledLoopOp to SCF loops.
Definition at line 526 of file Loops.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
Referenced by linalgOpToLoopsImpl().
promoteSubviewAsNewBuffer()
FailureOr< PromotionInfo > mlir::linalg::promoteSubviewAsNewBuffer (OpBuilder & b, Location loc, memref::SubViewOp subView, AllocBufferCallbackFn allocationFn, DataLayout & layout)
Definition at line 214 of file Promotion.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), getConstantUpperBoundForIndex(), and mlir::Builder::getIndexAttr().
Referenced by promoteSubViews().
promoteSubViews()
FailureOr< LinalgOp > mlir::linalg::promoteSubViews (OpBuilder & b, LinalgOp op, LinalgPromotionOptions options)
Promotes the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer.
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns the modified linalg op (the modification happens in place) as well as all the copy ops created.
Definition at line 382 of file Promotion.cpp.
References mlir::DataLayout::closest().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and promoteSubViews().
promoteSubviewsPrecondition()
LogicalResult mlir::linalg::promoteSubviewsPrecondition (Operation * op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
Definition at line 360 of file Promotion.cpp.
References mlir::failure(), mlir::linalg::LinalgPromotionOptions::operandsToPromote, and mlir::success().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
rewriteAsPaddedOp()
FailureOr< SmallVector< Value > > mlir::linalg::rewriteAsPaddedOp (OpBuilder & b, LinalgOp opToPad, const PaddingValueComputationFunction & paddingFunc, const PaddingNoFoldComputationFunction & nofoldFunc, LinalgOp & paddedOp)
Pad the operands of opToPad to a static bounding box.
Use paddingFunc and nofoldFunc to set the padding value and the nofold attribute of the introduced PadTensorOps, respectively. Update paddedOp to the cloned statically shaped operation and return the extracted dynamically shaped results. If padding fails, return failure.
Definition at line 221 of file Transforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::getAsOpFoldResult(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), padOperandToSmallestStaticBoundingBox(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by mlir::linalg::LinalgPaddingPattern::matchAndRewrite().
skipUnitDimReshape()
bool mlir::linalg::skipUnitDimReshape (const OpResult & producer, OpOperand & consumer)
Default function to control reshape folding.
Skips folding unit dimension reshapes.
Definition at line 1606 of file ElementwiseOpFusion.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::RewriterBase::cancelRootUpdate(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failure(), mlir::RewriterBase::finalizeRootUpdate(), fuseElementwiseOps(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::detail::IROperandBase::getOwner(), mlir::OpResult::getOwner(), mlir::Operation::getRegions(), mlir::Value::getType(), isUnitDimExpansionOnly(), mlir::ShapedType::kDynamicSize, populateElementwiseOpsFusionPatterns(), populateFoldReshapeOpsByLinearizationPatterns(), populateFoldUnitDimsReshapeOpsByLinearizationPatterns(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::startRootUpdate(), mlir::success(), and mlir::GreedyRewriteConfig::useTopDownTraversal.
tileAndFuseLinalgOps()
FailureOr< TiledAndFusedLinalgOps > mlir::linalg::tileAndFuseLinalgOps (OpBuilder & builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph, const LinalgTilingOptions & tilingOptions)
Definition at line 943 of file Fusion.cpp.
References mlir::failure(), Loops, mlir::linalg::LinalgTilingOptions::loopType, ParallelLoops, tileAndFuseLinalgOpsImpl(), and TiledLoops.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
tileConsumerAndFuseProducers()
FailureOr< TileLoopNest > mlir::linalg::tileConsumerAndFuseProducers (OpBuilder & b, LinalgOp consumerOp, ArrayRef< int64_t > tileSizes, ArrayRef< int64_t > tileInterchange)
Tiles consumerOp and fuses its dependencies if possible.
Uses the tileSizes and tileInterchange parameters to control the tiling.
Definition at line 409 of file FusionOnTensors.cpp.
References applyPermutationToVector(), mlir::failed(), mlir::failure(), mlir::linalg::TileLoopNest::fuseProducer(), mlir::linalg::TileLoopNest::getRootOp(), mlir::isParallelIterator(), isPermutation(), and mlir::linalg::TileLoopNest::tileRootOp().
Referenced by mlir::linalg::TileLoopNest::getLoopOps(), and mlir::linalg::LinalgTileAndFuseTensorOpsPattern::matchAndRewrite().
tileLinalgOp()
FailureOr< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options)
Definition at line 322 of file Tiling.cpp.
References mlir::failure(), Loops, mlir::linalg::LinalgTilingOptions::loopType, options, ParallelLoops, and TiledLoops.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::TileLoopNest::tileRootOp(), and tileRootOperation().
updateBoundsForCyclicDistribution()
void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder & builder, Location loc, Value procId, Value nprocs, Value & lb, Value & ub, Value & step)
Update the lb, ub and step to get per processor lb, ub and step.
Definition at line 510 of file Utils.cpp.
References mlir::bindDims(), mlir::getAffineSymbolExpr(), mlir::Builder::getContext(), and mlir::makeComposedAffineApply().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
vectorizeLinalgOp()
LogicalResult mlir::linalg::vectorizeLinalgOp (OpBuilder & builder, Operation * op, SmallVectorImpl< Value > & newResults)
Emit a suitable vector form for a Linalg op with fully static shape.
Definition at line 631 of file Vectorization.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getResults(), LDBG, mlir::success(), vectorizeAsLinalgGeneric(), vectorizeConvolution(), and vectorizeLinalgOpPrecondition().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 602 of file Vectorization.cpp.
References allIndexingsAreProjectedPermutation(), mlir::failed(), mlir::failure(), isElementwise(), LDBG, reductionPreconditions(), and mlir::success().
Referenced by vectorizeLinalgOp().