MLIR: mlir::bufferization Namespace Reference
mlir::bufferization Namespace Reference
Classes
class BufferizeTypeConverter
A helper type converter class that automatically populates the relevant materializations and type conversions for bufferization.
Functions
void populateBufferizeMaterializationLegality (ConversionTarget &target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
void populateEliminateBufferizeMaterializationsPatterns (BufferizeTypeConverter &typeConverter, RewritePatternSet &patterns)
Populate patterns to eliminate bufferize materializations.
std::unique_ptr< Pass > createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
std::unique_ptr< FunctionPass > createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining bufferization.to_tensor and bufferization.to_memref operations.
Function Documentation
createBufferDeallocationPass()
std::unique_ptr< Pass > mlir::bufferization::createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
Definition at line 674 of file BufferDeallocation.cpp.
createFinalizingBufferizePass()
std::unique_ptr< FunctionPass > mlir::bufferization::createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining bufferization.to_tensor and bufferization.to_memref operations.
Definition at line 129 of file Bufferize.cpp.
populateBufferizeMaterializationLegality()
void mlir::bufferization::populateBufferizeMaterializationLegality (ConversionTarget & target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
This function should be called by all bufferization passes using BufferizeTypeConverter so that materializations work properly. One exception is bufferization passes doing "full" conversions, where it can be desirable for even the materializations to remain illegal so that they are eliminated, such as via the patterns in populateEliminateBufferizeMaterializationsPatterns.
Definition at line 52 of file Bufferize.cpp.
References mlir::ConversionTarget::addLegalOp(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by mlir::populateTensorBufferizePatterns().
populateEliminateBufferizeMaterializationsPatterns()
void mlir::bufferization::populateEliminateBufferizeMaterializationsPatterns (BufferizeTypeConverter & typeConverter, RewritePatternSet & patterns)
Populate patterns to eliminate bufferize materializations.
In particular, these are the tensor_load/buffer_cast ops.
Definition at line 89 of file Bufferize.cpp.
References mlir::RewritePatternSet::add(), mlir::applyFullConversion(), mlir::failed(), mlir::RewritePatternSet::getContext(), mlir::TypeConverter::isLegal(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().