MLIR: mlir::sparse_tensor Namespace Reference
mlir::sparse_tensor Namespace Reference
Classes
struct Children
Children subexpressions of tensor operations.
struct LatPoint
Lattice point.
class Merger
A class to handle all iteration lattice operations.
struct TensorExp
Tensor expression. Represents a MLIR expression in tensor index notation.
Enumerations
enum Dim { kSparse, kDense, kSingle, kUndef }
Dimension level type for a tensor (undef means index does not appear).
enum Kind {
kTensor = 0, kInvariant, kAbsF, kCeilF,
kFloorF, kNegF, kNegI, kTruncF,
kExtF, kCastFS, kCastFU, kCastSF,
kCastUF, kCastS, kCastU, kTruncI,
kBitCast, kMulF, kMulI, kDivF,
kDivS, kDivU, kAddF, kAddI,
kSubF, kSubI, kAndI, kOrI,
kXorI, kShrS, kShrU, kShlI
}
Tensor expression kind.
Functions
SparseTensorEncodingAttr getSparseTensorEncoding (Type type)
Convenience method to get a sparse encoding attribute from a type.
static const char * kindToOpSymbol (Kind kind)
Enumeration Type Documentation
Dim
enum mlir::sparse_tensor::Dim
Dimension level type for a tensor (undef means index does not appear).
Enumerator
kSparse
kDense
kSingle
kUndef
Definition at line 24 of file Merger.h.
Kind
enum mlir::sparse_tensor::Kind
Tensor expression kind.
Enumerator
kTensor
kInvariant
kAbsF
kCeilF
kFloorF
kNegF
kNegI
kTruncF
kExtF
kCastFS
kCastFU
kCastSF
kCastUF
kCastS
kCastU
kTruncI
kBitCast
kMulF
kMulI
kDivF
kDivS
kDivU
kAddF
kAddI
kSubF
kSubI
kAndI
kOrI
kXorI
kShrS
kShrU
kShlI
Definition at line 27 of file Merger.h.
Function Documentation
getSparseTensorEncoding()
SparseTensorEncodingAttr mlir::sparse_tensor::getSparseTensorEncoding (Type type)
Convenience method to get a sparse encoding attribute from a type.
Returns null-attribute for any type without an encoding.
Definition at line 186 of file SparseTensorDialect.cpp.
References mlir::Type::dyn_cast().
Referenced by computeIterationGraph(), denseUnitStrides(), findSparseAnnotations(), genBuffers(), genInvariants(), genSubscript(), and verify().
kindToOpSymbol()
static const char* mlir::sparse_tensor::kindToOpSymbol (Kind kind) static
Definition at line 270 of file Merger.cpp.