MLIR: mlir::arith Namespace Reference
mlir::arith Namespace Reference
Classes
class ConstantFloatOp
Specialization of arith.constant op that returns a floating point value.
class ConstantIndexOp
Specialization of arith.constant op that returns an integer of index type.
class ConstantIntOp
Specialization of arith.constant op that returns an integer value.
Functions
void populateArithmeticToLLVMConversionPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
std::unique_ptr< Pass > createConvertArithmeticToLLVMPass ()
void populateArithmeticToSPIRVPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
std::unique_ptr< Pass > createConvertArithmeticToSPIRVPass ()
bool applyCmpPredicate (arith::CmpIPredicate predicate, const APInt &lhs, const APInt &rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
bool applyCmpPredicate (arith::CmpFPredicate predicate, const APFloat &lhs, const APFloat &rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
void populateArithmeticBufferizePatterns (bufferization::BufferizeTypeConverter &typeConverter, RewritePatternSet &patterns)
Add patterns to bufferize Arithmetic ops.
std::unique_ptr< Pass > createArithmeticBufferizePass ()
Create a pass to bufferize Arithmetic ops.
void populateArithmeticExpandOpsPatterns (RewritePatternSet &patterns)
Add patterns to expand Arithmetic ops for LLVM lowering.
std::unique_ptr< Pass > createArithmeticExpandOpsPass ()
Create a pass to legalize Arithmetic ops for LLVM lowering.
Function Documentation
applyCmpPredicate() [1/2]
bool mlir::arith::applyCmpPredicate (arith::CmpIPredicate predicate, const APInt & lhs, const APInt & rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
Definition at line 1012 of file ArithmeticOps.cpp.
Referenced by mlir::arith::ConstantIndexOp::value().
applyCmpPredicate() [2/2]
bool mlir::arith::applyCmpPredicate (arith::CmpFPredicate predicate, const APFloat & lhs, const APFloat & rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
Definition at line 1082 of file ArithmeticOps.cpp.
createArithmeticBufferizePass()
std::unique_ptr< Pass > mlir::arith::createArithmeticBufferizePass ()
Create a pass to bufferize Arithmetic ops.
Definition at line 66 of file Bufferize.cpp.
createArithmeticExpandOpsPass()
std::unique_ptr< Pass > mlir::arith::createArithmeticExpandOpsPass ()
Create a pass to legalize Arithmetic ops for LLVM lowering.
Definition at line 245 of file ExpandOps.cpp.
createConvertArithmeticToLLVMPass()
std::unique_ptr< Pass > mlir::arith::createConvertArithmeticToLLVMPass ()
Definition at line 302 of file ArithmeticToLLVM.cpp.
createConvertArithmeticToSPIRVPass()
std::unique_ptr< Pass > mlir::arith::createConvertArithmeticToSPIRVPass ()
Definition at line 850 of file ArithmeticToSPIRV.cpp.
populateArithmeticBufferizePatterns()
void mlir::arith::populateArithmeticBufferizePatterns (bufferization::BufferizeTypeConverter & typeConverter, RewritePatternSet & patterns)
Add patterns to bufferize Arithmetic ops.
Definition at line 60 of file Bufferize.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateArithmeticExpandOpsPatterns()
void mlir::arith::populateArithmeticExpandOpsPatterns (RewritePatternSet & patterns)
Add patterns to expand Arithmetic ops for LLVM lowering.
Definition at line 228 of file ExpandOps.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().
populateArithmeticToLLVMConversionPatterns()
void mlir::arith::populateArithmeticToLLVMConversionPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Definition at line 261 of file ArithmeticToLLVM.cpp.
References mlir::RewritePatternSet::add().
Referenced by convertCmpPredicate(), encodeKernelName(), mlir::populateOpenMPToLLVMConversionPatterns(), and mlir::populateStdToLLVMConversionPatterns().
populateArithmeticToSPIRVPatterns()
void mlir::arith::populateArithmeticToSPIRVPatterns (SPIRVTypeConverter & typeConverter, RewritePatternSet & patterns)
Definition at line 778 of file ArithmeticToSPIRV.cpp.
References mlir::RewritePatternSet::add(), mlir::applyPartialConversion(), mlir::SPIRVTypeConverter::Options::emulateNon32BitScalarTypes, mlir::failed(), mlir::SPIRVConversionTarget::get(), mlir::RewritePatternSet::getContext(), mlir::spirv::lookupTargetEnvOrDefault(), and options.