MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext Namespace Reference
mlir::linalg::comprehensive_bufferize::tensor_ext Namespace Reference
Classes
struct CastOpInterface
struct DimOpInterface
struct ExtractOpInterface
struct ExtractSliceOpInterface
struct InplaceInsertSliceOpAnalysis
struct InsertOpInterface
struct InsertSliceOpInterface
Functions
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
static TensorBufferizationState & getTensorBufferizationState (BufferizationState &state)
static bool areEquivalentExtractSliceOps (const BufferizationAliasInfo &aliasInfo, ExtractSliceOp st, InsertSliceOp sti)
Return true if the (ExtractSliceOp, InsertSliceOp) pair match (i.e.
static bool isSourceEquivalentToAMatchingInplaceExtractSliceOp (const BufferizationAliasInfo &aliasInfo, InsertSliceOp insertSliceOp)
Return true if the source of a insertSliceOp bufferizes to an equivalent ExtractSliceOp that bufferizes inplace.
static bool hasMatchingExtractSliceOp (const BufferizationAliasInfo &aliasInfo, Value value, InsertSliceOp insertOp)
Return true if value is originating from an ExtractSliceOp that matches the given InsertSliceOp.
Function Documentation
areEquivalentExtractSliceOps()
static bool mlir::linalg::comprehensive_bufferize::tensor_ext::areEquivalentExtractSliceOps (const BufferizationAliasInfo & aliasInfo, ExtractSliceOp st, InsertSliceOp sti) static
Return true if the (ExtractSliceOp, InsertSliceOp) pair match (i.e.
equivalent operand / result and same offset/sizes/strides specification).
This is one particular type of relationship between ops on tensors that reduce to an equivalence on buffers. This should be generalized and exposed as interfaces on the proper types.
Definition at line 251 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::isEqualConstantIntOrValue(), and sameOffsetsSizesAndStrides().
Referenced by hasMatchingExtractSliceOp(), and isSourceEquivalentToAMatchingInplaceExtractSliceOp().
getTensorBufferizationState()
static TensorBufferizationState& mlir::linalg::comprehensive_bufferize::tensor_ext::getTensorBufferizationState (BufferizationState & state) static
Definition at line 35 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::getDialectState().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run().
hasMatchingExtractSliceOp()
static bool mlir::linalg::comprehensive_bufferize::tensor_ext::hasMatchingExtractSliceOp (const BufferizationAliasInfo & aliasInfo, Value value, InsertSliceOp insertOp) static
Return true if value is originating from an ExtractSliceOp that matches the given InsertSliceOp.
Definition at line 281 of file TensorInterfaceImpl.cpp.
References areEquivalentExtractSliceOps(), and mlir::linalg::comprehensive_bufferize::findValueInReverseUseDefChain().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::isNotConflicting().
isSourceEquivalentToAMatchingInplaceExtractSliceOp()
static bool mlir::linalg::comprehensive_bufferize::tensor_ext::isSourceEquivalentToAMatchingInplaceExtractSliceOp (const BufferizationAliasInfo & aliasInfo, InsertSliceOp insertSliceOp) static
Return true if the source of a insertSliceOp bufferizes to an equivalent ExtractSliceOp that bufferizes inplace.
Definition at line 264 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::applyOnEquivalenceClass(), areEquivalentExtractSliceOps(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace(), and value.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run().
registerBufferizableOpInterfaceExternalModels()
void mlir::linalg::comprehensive_bufferize::tensor_ext::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 457 of file TensorInterfaceImpl.cpp.
References mlir::DialectRegistry::addOpInterface().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run().