MLIR: mlir::impl Namespace Reference
mlir::impl Namespace Reference
Attribute collections provide a dictionary-like interface.
Classes
class DataLayoutEntryStorage
class DataLayoutSpecStorage
Functions
LogicalResult verifyHasDefaultDLTIDataLayoutTrait (Operation *op)
DataLayoutSpecInterface getDataLayoutSpec (Operation *op)
void ensureRegionTerminator (Region &region, OpBuilder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
void ensureRegionTerminator (Region &region, Builder &builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
ParseResult parseOneResultOneOperandTypeOp (OpAsmParser &parser, OperationState &result)
void buildBinaryOp (OpBuilder &builder, OperationState &result, Value lhs, Value rhs)
ParseResult parseOneResultSameOperandTypeOp (OpAsmParser &parser, OperationState &result)
void printOneResultOp (Operation *op, OpAsmPrinter &p)
LogicalResult foldCastInterfaceOp (Operation *op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > &foldResults)
Attempt to fold the given cast operation.
LogicalResult verifyCastInterfaceOp (Operation *op, function_ref< bool(TypeRange, TypeRange)> areCastCompatible)
Attempt to verify the given cast operation.
void buildCastOp (OpBuilder &builder, OperationState &result, Value source, Type destType)
ParseResult parseCastOp (OpAsmParser &parser, OperationState &result)
void printCastOp (Operation *op, OpAsmPrinter &p)
Value foldCastOp (Operation *op)
LogicalResult verifyCastOp (Operation *op, function_ref< bool(Type, Type)> areCastCompatible)
template<typename IteratorT , typename NameT >
std::pair< IteratorT, bool > findAttrUnsorted (IteratorT first, IteratorT last, NameT name)
Unsorted string search or identifier lookups are linear scans.
template<typename IteratorT >
std::pair< IteratorT, bool > findAttrSorted (IteratorT first, IteratorT last, StringRef name)
Using llvm::lower_bound requires an extra string comparison to check whether the returned iterator points to the found element or whether it indicates the lower bound.
template<typename IteratorT >
std::pair< IteratorT, bool > findAttrSorted (IteratorT first, IteratorT last, StringAttr name)
StringAttr lookups on large attribute lists will switch to string binary search.
ParseResult parseOptionalVisibilityKeyword (OpAsmParser &parser, NamedAttrList &attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
Detailed Description
Attribute collections provide a dictionary-like interface.
Define common lookup functions.
Function Documentation
buildBinaryOp()
void mlir::impl::buildBinaryOp (OpBuilder & builder, OperationState & result, Value lhs, Value rhs)
Definition at line 1122 of file Operation.cpp.
buildCastOp()
void mlir::impl::buildCastOp (OpBuilder & builder, OperationState & result, Value source, Type destType)
Definition at line 1223 of file Operation.cpp.
References mlir::OperationState::addOperands(), and mlir::OperationState::addTypes().
ensureRegionTerminator() [1/2]
void mlir::impl::ensureRegionTerminator (Region & region, OpBuilder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Insert an operation, generated by buildTerminatorOp, at the end of the region's only block if it does not have a terminator already.
If the region is empty, insert a new block first. buildTerminatorOp should return the terminator operation to insert.
Definition at line 1275 of file Operation.cpp.
References mlir::Region::back(), mlir::Block::back(), mlir::OpBuilder::createBlock(), mlir::Region::empty(), mlir::Block::empty(), mlir::Operation::hasTrait(), mlir::OpBuilder::insert(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by ensureRegionTerminator().
ensureRegionTerminator() [2/2]
void mlir::impl::ensureRegionTerminator (Region & region, Builder & builder, Location loc, function_ref< Operation *(OpBuilder &, Location)> buildTerminatorOp)
Create a simple OpBuilder and forward to the OpBuilder version of this function.
Definition at line 1292 of file Operation.cpp.
References ensureRegionTerminator(), and mlir::Builder::getContext().
Referenced by mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator(), and mlir::OptionalParseResult::operator*().
findAttrSorted() [1/2]
template<typename IteratorT > std::pair<IteratorT, bool> mlir::impl::findAttrSorted (IteratorT first, IteratorT last, StringRef name)
Using llvm::lower_bound requires an extra string comparison to check whether the returned iterator points to the found element or whether it indicates the lower bound.
Skip this redundant comparison by checking if compare == 0 during the binary search.
Definition at line 395 of file OperationSupport.h.
References mlir::compare().
Referenced by findDuplicateElement().
findAttrSorted() [2/2]
template<typename IteratorT > std::pair<IteratorT, bool> mlir::impl::findAttrSorted (IteratorT first, IteratorT last, StringAttr name)
StringAttr lookups on large attribute lists will switch to string binary search.
String binary searches become significantly faster than linear scans with the identifier when the attribute list becomes very large.
Definition at line 419 of file OperationSupport.h.
References findAttrUnsorted().
findAttrUnsorted()
template<typename IteratorT , typename NameT > std::pair<IteratorT, bool> mlir::impl::findAttrUnsorted (IteratorT first, IteratorT last, NameT name)
Unsorted string search or identifier lookups are linear scans.
Definition at line 382 of file OperationSupport.h.
Referenced by findAttrSorted().
foldCastInterfaceOp()
LogicalResult mlir::impl::foldCastInterfaceOp (Operation * op, ArrayRef< Attribute > attrOperands, SmallVectorImpl< OpFoldResult > & foldResults)
Attempt to fold the given cast operation.
Definition at line 1183 of file Operation.cpp.
References mlir::failure(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::OperandRange::getTypes(), mlir::ResultRange::getTypes(), and mlir::success().
foldCastOp()
Value mlir::impl::foldCastOp (Operation * op)
Definition at line 1247 of file Operation.cpp.
References mlir::Operation::getOperand(), mlir::Operation::getResult(), and mlir::Value::getType().
Referenced by verify().
getDataLayoutSpec()
DataLayoutSpecInterface mlir::impl::getDataLayoutSpec (Operation * op)
Definition at line 26 of file Traits.cpp.
References mlir::Operation::getAttrOfType().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::getDataLayoutSpec(), and verify().
parseCastOp()
ParseResult mlir::impl::parseCastOp (OpAsmParser & parser, OperationState & result)
Definition at line 1229 of file Operation.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseOneResultOneOperandTypeOp()
ParseResult mlir::impl::parseOneResultOneOperandTypeOp (OpAsmParser & parser, OperationState & result)
parseOneResultSameOperandTypeOp()
ParseResult mlir::impl::parseOneResultSameOperandTypeOp (OpAsmParser & parser, OperationState & result)
Definition at line 1129 of file Operation.cpp.
References mlir::OperationState::addTypes(), mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
parseOptionalVisibilityKeyword()
ParseResult mlir::impl::parseOptionalVisibilityKeyword (OpAsmParser & parser, NamedAttrList & attrs)
Parse an optional visibility attribute keyword (i.e., public, private, or nested) without quotes in a string attribute named 'attrName'.
Definition at line 1094 of file SymbolTable.cpp.
References mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getVisibilityAttrName(), mlir::AsmParser::parseOptionalKeyword(), mlir::NamedAttrList::push_back(), and mlir::success().
Referenced by mlir::OpTrait::SymbolTable< ConcreteType >::lookupSymbol(), and mlir::function_like_impl::parseFunctionLikeOp().
printCastOp()
void mlir::impl::printCastOp (Operation * op, OpAsmPrinter & p)
Definition at line 1240 of file Operation.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printOneResultOp()
void mlir::impl::printOneResultOp (Operation * op, OpAsmPrinter & p)
Definition at line 1158 of file Operation.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
verifyCastInterfaceOp()
LogicalResult mlir::impl::verifyCastInterfaceOp (Operation * op, function_ref< bool(TypeRange, TypeRange)> areCastCompatible)
Attempt to verify the given cast operation.
Definition at line 1200 of file Operation.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and mlir::success().
verifyCastOp()
LogicalResult mlir::impl::verifyCastOp (Operation * op, function_ref< bool(Type, Type)> areCastCompatible)
Definition at line 1255 of file Operation.cpp.
References mlir::Operation::emitError(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::success().
verifyHasDefaultDLTIDataLayoutTrait()
LogicalResult mlir::impl::verifyHasDefaultDLTIDataLayoutTrait (Operation * op)
Definition at line 15 of file Traits.cpp.
References mlir::success().
Referenced by mlir::HasDefaultDLTIDataLayout< ConcreteOp >::verifyTrait().