MLIR: lib/Dialect/LLVMIR/IR/NVVMDialect.cpp File Reference
NVVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/NVVMOpsDialect.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printNVVMIntrinsicOp (OpAsmPrinter &p, Operation *op)
static ParseResult parseNVVMVoteBallotOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (MmaOp op)
std::pair< mlir::Type, unsigned > inferMMAType (NVVM::MMATypes type, NVVM::MMAFrag frag, MLIRContext *context)
static LogicalResult verify (NVVM::WMMALoadOp op)
static LogicalResult verify (NVVM::WMMAStoreOp op)
static LogicalResult verify (NVVM::WMMAMmaOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 234 of file NVVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
inferMMAType()
std::pair<mlir::Type, unsigned> inferMMAType (NVVM::MMATypes type, NVVM::MMAFrag frag, MLIRContext * context)
Definition at line 110 of file NVVMDialect.cpp.
References mlir::Builder::getF16Type(), mlir::Builder::getF32Type(), and mlir::Builder::getI32Type().
Referenced by verify().
parseNVVMVoteBallotOp()
static ParseResult parseNVVMVoteBallotOp (OpAsmParser & parser, OperationState & result) static
Definition at line 47 of file NVVMDialect.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
printNVVMIntrinsicOp()
static void printNVVMIntrinsicOp (OpAsmPrinter & p, Operation * op) static
Definition at line 40 of file NVVMDialect.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getOperands(), and mlir::Operation::getResultTypes().
verify() [1/4]
static LogicalResult verify (MmaOp op) static
Definition at line 63 of file NVVMDialect.cpp.
References mlir::LLVM::getFixedVectorType(), mlir::LLVM::LLVMStructType::getLiteral(), and mlir::success().
verify() [2/4]
static LogicalResult verify (NVVM::WMMALoadOp op) static
Definition at line 132 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMStructType::getLiteral(), inferMMAType(), and mlir::success().
verify() [3/4]
static LogicalResult verify (NVVM::WMMAStoreOp op) static
Definition at line 152 of file NVVMDialect.cpp.
References inferMMAType(), and mlir::success().
verify() [4/4]
static LogicalResult verify (NVVM::WMMAMmaOp op) static
Definition at line 175 of file NVVMDialect.cpp.
References mlir::Operation::emitError(), mlir::LLVM::LLVMStructType::getLiteral(), mlir::NamedAttribute::getName(), inferMMAType(), and mlir::success().