MLIR: lib/Dialect/OpenMP/IR/OpenMPDialect.cpp File Reference
OpenMPDialect.cpp File Reference
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include <cstddef>
#include "mlir/Dialect/OpenMP/OpenMPOpsDialect.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOpsEnums.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPTypeInterfaces.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Enumerations
enum ClauseType {
ifClause, numThreadsClause, privateClause, firstprivateClause,
lastprivateClause, sharedClause, copyinClause, allocateClause,
defaultClause, procBindClause, reductionClause, nowaitClause,
linearClause, scheduleClause, collapseClause, orderClause,
orderedClause, memoryOrderClause, hintClause, COUNT
}
Functions
static ParseResult parseOperandAndTypeList (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operands, SmallVectorImpl< Type > &types)
Parse a list of operands with types.
static void printOperandAndTypeList (OpAsmPrinter &p, OperandRange operands)
Print an operand and type list with parentheses.
static void printDataVars (OpAsmPrinter &p, OperandRange operands, StringRef name)
Print data variables corresponding to a data-sharing clause name
static ParseResult parseAllocateAndAllocator (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operandsAllocate, SmallVectorImpl< Type > &typesAllocate, SmallVectorImpl< OpAsmParser::OperandType > &operandsAllocator, SmallVectorImpl< Type > &typesAllocator)
Parse an allocate clause with allocators and a list of operands with types.
static void printAllocateAndAllocator (OpAsmPrinter &p, OperandRange varsAllocate, OperandRange varsAllocator)
Print allocate clause.
static LogicalResult verifyParallelOp (ParallelOp op)
static void printParallelOp (OpAsmPrinter &p, ParallelOp op)
static ParseResult parseLinearClause (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &vars, SmallVectorImpl< Type > &types, SmallVectorImpl< OpAsmParser::OperandType > &stepVars)
linear ::= linear (linear-list) linear-list := linear-val | linear-val linear-list linear-val := ssa-id-and-type = ssa-id-and-type
static void printLinearClause (OpAsmPrinter &p, OperandRange linearVars, OperandRange linearStepVars)
Print Linear Clause.
static ParseResult verifyScheduleModifiers (OpAsmParser &parser, SmallVectorImpl< SmallString< 12 >> &modifiers)
static ParseResult parseScheduleClause (OpAsmParser &parser, SmallString< 8 > &schedule, SmallVectorImpl< SmallString< 12 >> &modifiers, Optional< OpAsmParser::OperandType > &chunkSize)
schedule ::= schedule (sched-list) sched-list ::= sched-val | sched-val sched-list | sched-val , sched-modifier sched-val ::= sched-with-chunk | sched-wo-chunk sched-with-chunk ::= sched-with-chunk-types (= ssa-id-and-type)? sched-with-chunk-types ::= static | dynamic | guided sched-wo-chunk ::= auto | runtime sched-modifier ::= sched-mod-val | sched-mod-val , sched-mod-val sched-mod-val ::= monotonic | nonmonotonic | simd | none
static void printScheduleClause (OpAsmPrinter &p, StringRef &sched, llvm::Optional< StringRef > modifier, bool simd, Value scheduleChunkVar)
Print schedule clause.
static ParseResult parseReductionVarList (OpAsmParser &parser, SmallVectorImpl< SymbolRefAttr > &symbols, SmallVectorImpl< OpAsmParser::OperandType > &operands, SmallVectorImpl< Type > &types)
reduction ::= reduction (reduction-entry-list) reduction-entry-list ::= reduction-entry | reduction-entry-list , reduction-entry reduction-entry ::= symbol-ref -> ssa-id : type
static void printReductionVarList (OpAsmPrinter &p, Optional< ArrayAttr > reductions, OperandRange reduction_vars)
Print Reduction clause.
static LogicalResult verifyReductionVarList (Operation *op, Optional< ArrayAttr > reductions, OperandRange reduction_vars)
Verifies Reduction Clause.
static ParseResult parseSynchronizationHint (OpAsmParser &parser, IntegerAttr &hintAttr, bool parseKeyword=true)
Parses a Synchronization Hint clause.
static void printSynchronizationHint (OpAsmPrinter &p, Operation *op, IntegerAttr hintAttr)
Prints a Synchronization Hint clause.
static LogicalResult verifySynchronizationHint (Operation *op, uint64_t hint)
Verifies a synchronization hint clause.
static ParseResult parseClauses (OpAsmParser &parser, OperationState &result, SmallVectorImpl< ClauseType > &clauses, SmallVectorImpl< int > &segments)
Parse a list of clauses.
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
Parses a parallel operation.
static ParseResult parseSectionsOp (OpAsmParser &parser, OperationState &result)
Parses an OpenMP Sections operation.
static void printSectionsOp (OpAsmPrinter &p, SectionsOp op)
static LogicalResult verifySectionsOp (SectionsOp op)
static ParseResult parseWsLoopOp (OpAsmParser &parser, OperationState &result)
Parses an OpenMP Workshare Loop operation.
static void printWsLoopOp (OpAsmPrinter &p, WsLoopOp op)
static ParseResult parseAtomicReductionRegion (OpAsmParser &parser, Region &region)
static void printAtomicReductionRegion (OpAsmPrinter &printer, ReductionDeclareOp op, Region &region)
static LogicalResult verifyReductionDeclareOp (ReductionDeclareOp op)
static LogicalResult verifyReductionOp (ReductionOp op)
static LogicalResult verifyWsLoopOp (WsLoopOp op)
static LogicalResult verifyCriticalDeclareOp (CriticalDeclareOp op)
static LogicalResult verifyCriticalOp (CriticalOp op)
static LogicalResult verifyOrderedOp (OrderedOp op)
static LogicalResult verifyOrderedRegionOp (OrderedRegionOp op)
static ParseResult parseAtomicReadOp (OpAsmParser &parser, OperationState &result)
Parser for AtomicReadOp.
static void printAtomicReadOp (OpAsmPrinter &p, AtomicReadOp op)
Printer for AtomicReadOp.
static LogicalResult verifyAtomicReadOp (AtomicReadOp op)
Verifier for AtomicReadOp.
static ParseResult parseAtomicWriteOp (OpAsmParser &parser, OperationState &result)
Parser for AtomicWriteOp.
static void printAtomicWriteOp (OpAsmPrinter &p, AtomicWriteOp op)
Printer for AtomicWriteOp.
static LogicalResult verifyAtomicWriteOp (AtomicWriteOp op)
Verifier for AtomicWriteOp.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1426 of file OpenMPDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
ClauseType
enum ClauseType
Enumerator
ifClause
numThreadsClause
privateClause
firstprivateClause
lastprivateClause
sharedClause
copyinClause
allocateClause
defaultClause
procBindClause
reductionClause
nowaitClause
linearClause
scheduleClause
collapseClause
orderClause
orderedClause
memoryOrderClause
hintClause
COUNT
Definition at line 521 of file OpenMPDialect.cpp.
Function Documentation
parseAllocateAndAllocator()
static ParseResult parseAllocateAndAllocator (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & operandsAllocate, SmallVectorImpl< Type > & typesAllocate, SmallVectorImpl< OpAsmParser::OperandType > & operandsAllocator, SmallVectorImpl< Type > & typesAllocator) static
Parse an allocate clause with allocators and a list of operands with types.
allocate ::= allocate (allocate-operand-list) allocate-operand-list :: = allocate-operand | allocator-operand , allocate-operand-list allocate-operand :: = ssa-id-and-type -> ssa-id-and-type ssa-id-and-type ::= ssa-id : type
Definition at line 125 of file OpenMPDialect.cpp.
References mlir::failure(), mlir::AsmParser::Paren, mlir::AsmParser::parseArrow(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCommaSeparatedList(), mlir::OpAsmParser::parseOperand(), and mlir::success().
Referenced by parseClauses().
parseAtomicReadOp()
static ParseResult parseAtomicReadOp (OpAsmParser & parser, OperationState & result) static
Parser for AtomicReadOp.
operation ::= omp.atomic.read atomic-clause-list address -> result-type address ::= operand : type
Definition at line 1334 of file OpenMPDialect.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), hintClause, memoryOrderClause, mlir::OperationState::operands, mlir::AsmParser::parseArrowTypeList(), parseClauses(), mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseAtomicReductionRegion()
static ParseResult parseAtomicReductionRegion (OpAsmParser & parser, Region & region) static
Definition at line 1104 of file OpenMPDialect.cpp.
References mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), and mlir::success().
parseAtomicWriteOp()
static ParseResult parseAtomicWriteOp (OpAsmParser & parser, OperationState & result) static
Parser for AtomicWriteOp.
operation ::= omp.atomic.write atomic-clause-list operands operands ::= address , value address ::= operand : type value ::= operand : type
Definition at line 1386 of file OpenMPDialect.cpp.
References mlir::failure(), hintClause, memoryOrderClause, mlir::OperationState::operands, parseClauses(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and value.
parseClauses()
static ParseResult parseClauses (OpAsmParser & parser, OperationState & result, SmallVectorImpl< ClauseType > & clauses, SmallVectorImpl< int > & segments) static
Parse a list of clauses.
The clauses can appear in any order, but their operand segment indices are in the same order that they are passed in the clauses list. The operand segments are added over the prevSegments clause-list ::= clause clause-list | empty clause ::= if | num-threads | private | firstprivate | lastprivate | shared | copyin | allocate | default | proc-bind | reduction | nowait | linear | schedule | collapse | order | ordered | inclusive if ::= if (ssa-id-and-type) num-threads ::= num_threads (ssa-id-and-type) private ::= private operand-and-type-list firstprivate ::= firstprivate operand-and-type-list lastprivate ::= lastprivate operand-and-type-list shared ::= shared operand-and-type-list copyin ::= copyin operand-and-type-list allocate ::= allocate (allocate-operand-list) default ::= default ((private | firstprivate | shared | none) proc-bind ::= proc_bind ((master | close | spread)) reduction ::= reduction (reduction-entry-list) nowait ::= nowait linear ::= linear (linear-list) schedule ::= schedule (sched-list) collapse ::= collapse (ssa-id-and-type) order ::= order (concurrent) ordered ::= ordered (ssa-id-and-type) inclusive ::= inclusive
Note that each clause can only appear once in the clase-list.
Definition at line 577 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), allocateClause, collapseClause, copyinClause, COUNT, defaultClause, mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), firstprivateClause, mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32Type(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getI64Type(), mlir::AsmParser::getNameLoc(), mlir::Builder::getStringAttr(), mlir::OperationName::getStringRef(), hintClause, ifClause, lastprivateClause, linearClause, memoryOrderClause, mlir::mod(), mlir::OperationState::name, nowaitClause, numThreadsClause, mlir::OperationState::operands, orderClause, orderedClause, parseAllocateAndAllocator(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeyword(), parseLinearClause(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), parseOperandAndTypeList(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLParen(), parseReductionVarList(), mlir::AsmParser::parseRParen(), parseScheduleClause(), parseSynchronizationHint(), privateClause, procBindClause, reductionClause, mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), scheduleClause, sharedClause, mlir::succeeded(), and mlir::success().
Referenced by parseAtomicReadOp(), parseAtomicWriteOp(), parseParallelOp(), parseSectionsOp(), and parseWsLoopOp().
parseLinearClause()
static ParseResult parseLinearClause (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & vars, SmallVectorImpl< Type > & types, SmallVectorImpl< OpAsmParser::OperandType > & stepVars) static
linear ::= linear (linear-list) linear-list := linear-val | linear-val linear-list linear-val := ssa-id-and-type = ssa-id-and-type
Definition at line 203 of file OpenMPDialect.cpp.
References mlir::failure(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by parseClauses().
parseOperandAndTypeList()
static ParseResult parseOperandAndTypeList (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & operands, SmallVectorImpl< Type > & types) static
Parse a list of operands with types.
operand-and-type-list ::= (ssa-id-and-type-list) ssa-id-and-type-list ::= ssa-id-and-type | ssa-id-and-type , ssa-id-and-type-list ssa-id-and-type ::= ssa-id : type
Definition at line 82 of file OpenMPDialect.cpp.
References mlir::failure(), mlir::AsmParser::Paren, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseCommaSeparatedList(), mlir::OpAsmParser::parseOperand(), and mlir::success().
Referenced by parseClauses().
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Parses a parallel operation.
operation ::= omp.parallel clause-list clause-list ::= clause | clause clause-list clause ::= if | num-threads | private | firstprivate | shared | copyin | allocate | default | proc-bind
Definition at line 895 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), allocateClause, copyinClause, defaultClause, mlir::failed(), mlir::failure(), firstprivateClause, mlir::AsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), ifClause, numThreadsClause, parseClauses(), mlir::OpAsmParser::parseRegion(), privateClause, procBindClause, sharedClause, and mlir::success().
parseReductionVarList()
static ParseResult parseReductionVarList (OpAsmParser & parser, SmallVectorImpl< SymbolRefAttr > & symbols, SmallVectorImpl< OpAsmParser::OperandType > & operands, SmallVectorImpl< Type > & types) static
reduction ::= reduction (reduction-entry-list) reduction-entry-list ::= reduction-entry | reduction-entry-list , reduction-entry reduction-entry ::= symbol-ref -> ssa-id : type
Definition at line 359 of file OpenMPDialect.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::parseArrow(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseRParen(), and mlir::succeeded().
Referenced by parseClauses().
parseScheduleClause()
static ParseResult parseScheduleClause (OpAsmParser & parser, SmallString< 8 > & schedule, SmallVectorImpl< SmallString< 12 >> & modifiers, Optional< OpAsmParser::OperandType > & chunkSize) static
schedule ::= schedule (sched-list) sched-list ::= sched-val | sched-val sched-list | sched-val , sched-modifier sched-val ::= sched-with-chunk | sched-wo-chunk sched-with-chunk ::= sched-with-chunk-types (= ssa-id-and-type)? sched-with-chunk-types ::= static | dynamic | guided sched-wo-chunk ::= auto | runtime sched-modifier ::= sched-mod-val | sched-mod-val , sched-mod-val sched-mod-val ::= monotonic | nonmonotonic | simd | none
Definition at line 293 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getNameLoc(), mlir::mod(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalEqual(), mlir::AsmParser::parseRParen(), mlir::succeeded(), mlir::success(), and verifyScheduleModifiers().
Referenced by parseClauses().
parseSectionsOp()
static ParseResult parseSectionsOp (OpAsmParser & parser, OperationState & result) static
Parses an OpenMP Sections operation.
sections ::= omp.sections clause-list clause-list ::= clause clause-list | empty clause ::= private | firstprivate | lastprivate | reduction | allocate | nowait
Definition at line 928 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), allocateClause, mlir::failed(), mlir::failure(), firstprivateClause, mlir::AsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), lastprivateClause, nowaitClause, parseClauses(), mlir::OpAsmParser::parseRegion(), privateClause, reductionClause, and mlir::success().
parseSynchronizationHint()
static ParseResult parseSynchronizationHint (OpAsmParser & parser, IntegerAttr & hintAttr, bool parseKeyword = true) static
Parses a Synchronization Hint clause.
The value of hint is an integer which is a combination of different hints from omp_sync_hint_t.
hint-clause = hint (hint-value)
Definition at line 437 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI64Type(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by parseClauses().
parseWsLoopOp()
static ParseResult parseWsLoopOp (OpAsmParser & parser, OperationState & result) static
Parses an OpenMP Workshare Loop operation.
wsloop ::= omp.wsloop loop-control clause-list loop-control ::= (ssa-id-list) : type = loop-bounds loop-bounds := (ssa-id-list) to (ssa-id-list) inclusive? steps steps := step (ssa-id-list) clause-list ::= clause clause-list | empty clause ::= private | firstprivate | lastprivate | linear | schedule |
Definition at line 1004 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), collapseClause, mlir::failed(), mlir::failure(), firstprivateClause, mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::Builder::getI32VectorAttr(), lastprivateClause, linearClause, nowaitClause, mlir::OperationState::operands, orderClause, orderedClause, mlir::AsmParser::Paren, parseClauses(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), privateClause, reductionClause, mlir::OpAsmParser::resolveOperands(), scheduleClause, mlir::succeeded(), and mlir::success().
printAllocateAndAllocator()
static void printAllocateAndAllocator (OpAsmPrinter & p, OperandRange varsAllocate, OperandRange varsAllocator) static
Print allocate clause.
Definition at line 152 of file OpenMPDialect.cpp.
References mlir::OperandRange::getType().
Referenced by printParallelOp(), and printSectionsOp().
printAtomicReadOp()
static void printAtomicReadOp (OpAsmPrinter & p, AtomicReadOp op) static
Printer for AtomicReadOp.
Definition at line 1355 of file OpenMPDialect.cpp.
References printSynchronizationHint().
printAtomicReductionRegion()
static void printAtomicReductionRegion (OpAsmPrinter & printer, ReductionDeclareOp op, Region & region) static
Definition at line 1111 of file OpenMPDialect.cpp.
References mlir::Region::empty(), and mlir::OpAsmPrinter::printRegion().
printAtomicWriteOp()
static void printAtomicWriteOp (OpAsmPrinter & p, AtomicWriteOp op) static
Printer for AtomicWriteOp.
Definition at line 1405 of file OpenMPDialect.cpp.
References printSynchronizationHint().
printDataVars()
static void printDataVars (OpAsmPrinter & p, OperandRange operands, StringRef name) static
Print data variables corresponding to a data-sharing clause name
Definition at line 106 of file OpenMPDialect.cpp.
References printOperandAndTypeList().
Referenced by printParallelOp(), printSectionsOp(), and printWsLoopOp().
printLinearClause()
static void printLinearClause (OpAsmPrinter & p, OperandRange linearVars, OperandRange linearStepVars) static
Print Linear Clause.
Definition at line 230 of file OpenMPDialect.cpp.
Referenced by printWsLoopOp().
printOperandAndTypeList()
static void printOperandAndTypeList (OpAsmPrinter & p, OperandRange operands) static
Print an operand and type list with parentheses.
Definition at line 98 of file OpenMPDialect.cpp.
References mlir::Value::getType().
Referenced by printDataVars().
printParallelOp()
static void printParallelOp (OpAsmPrinter & p, ParallelOp op) static
Definition at line 170 of file OpenMPDialect.cpp.
References printAllocateAndAllocator(), printDataVars(), and mlir::OpAsmPrinter::printRegion().
printReductionVarList()
static void printReductionVarList (OpAsmPrinter & p, Optional< ArrayAttr > reductions, OperandRange reduction_vars) static
Print Reduction clause.
Definition at line 376 of file OpenMPDialect.cpp.
References mlir::OperandRange::getType().
Referenced by printSectionsOp(), and printWsLoopOp().
printScheduleClause()
static void printScheduleClause (OpAsmPrinter & p, StringRef & sched, llvm::Optional< StringRef > modifier, bool simd, Value scheduleChunkVar) static
Print schedule clause.
Definition at line 336 of file OpenMPDialect.cpp.
Referenced by printWsLoopOp().
printSectionsOp()
static void printSectionsOp (OpAsmPrinter & p, SectionsOp op) static
Definition at line 950 of file OpenMPDialect.cpp.
References printAllocateAndAllocator(), printDataVars(), printReductionVarList(), and mlir::OpAsmPrinter::printRegion().
printSynchronizationHint()
static void printSynchronizationHint (OpAsmPrinter & p, Operation * op, IntegerAttr hintAttr) static
Prints a Synchronization Hint clause.
Definition at line 471 of file OpenMPDialect.cpp.
References value.
Referenced by printAtomicReadOp(), and printAtomicWriteOp().
printWsLoopOp()
static void printWsLoopOp (OpAsmPrinter & p, WsLoopOp op) static
Definition at line 1062 of file OpenMPDialect.cpp.
References printDataVars(), printLinearClause(), printReductionVarList(), mlir::OpAsmPrinter::printRegion(), and printScheduleClause().
verifyAtomicReadOp()
static LogicalResult verifyAtomicReadOp (AtomicReadOp op) static
Verifier for AtomicReadOp.
Definition at line 1366 of file OpenMPDialect.cpp.
References verifySynchronizationHint().
verifyAtomicWriteOp()
static LogicalResult verifyAtomicWriteOp (AtomicWriteOp op) static
Verifier for AtomicWriteOp.
Definition at line 1416 of file OpenMPDialect.cpp.
References verifySynchronizationHint().
verifyCriticalDeclareOp()
static LogicalResult verifyCriticalDeclareOp (CriticalDeclareOp op) static
Definition at line 1270 of file OpenMPDialect.cpp.
References verifySynchronizationHint().
verifyCriticalOp()
static LogicalResult verifyCriticalOp (CriticalOp op) static
Definition at line 1274 of file OpenMPDialect.cpp.
References mlir::success().
verifyOrderedOp()
static LogicalResult verifyOrderedOp (OrderedOp op) static
Definition at line 1293 of file OpenMPDialect.cpp.
References mlir::success().
verifyOrderedRegionOp()
static LogicalResult verifyOrderedRegionOp (OrderedRegionOp op) static
Definition at line 1310 of file OpenMPDialect.cpp.
References mlir::failure(), and mlir::success().
verifyParallelOp()
static LogicalResult verifyParallelOp (ParallelOp op) static
Definition at line 163 of file OpenMPDialect.cpp.
References mlir::success().
verifyReductionDeclareOp()
static LogicalResult verifyReductionDeclareOp (ReductionDeclareOp op) static
Definition at line 1119 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArgumentTypes(), mlir::Block::getNumArguments(), mlir::Value::getType(), and mlir::success().
verifyReductionOp()
static LogicalResult verifyReductionOp (ReductionOp op) static
Definition at line 1169 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OpBuilder::createBlock(), mlir::Builder::getI32VectorAttr(), mlir::ValueRange::getType(), and mlir::success().
verifyReductionVarList()
static LogicalResult verifyReductionVarList (Operation * op, Optional< ArrayAttr > reductions, OperandRange reduction_vars) static
Verifies Reduction Clause.
Definition at line 390 of file OpenMPDialect.cpp.
References mlir::Type::cast(), mlir::Operation::emitOpError(), mlir::Value::getType(), and mlir::success().
Referenced by verifySectionsOp(), and verifyWsLoopOp().
verifyScheduleModifiers()
static ParseResult verifyScheduleModifiers (OpAsmParser & parser, SmallVectorImpl< SmallString< 12 >> & modifiers) static
Definition at line 248 of file OpenMPDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getNameLoc(), mlir::mod(), and mlir::success().
Referenced by parseScheduleClause().
verifySectionsOp()
static LogicalResult verifySectionsOp (SectionsOp op) static
Definition at line 968 of file OpenMPDialect.cpp.
References verifyReductionVarList().
verifySynchronizationHint()
static LogicalResult verifySynchronizationHint (Operation * op, uint64_t hint) static
Verifies a synchronization hint clause.
Definition at line 502 of file OpenMPDialect.cpp.
References mlir::Operation::emitOpError(), mlir::success(), and value.
Referenced by verifyAtomicReadOp(), verifyAtomicWriteOp(), and verifyCriticalDeclareOp().
verifyWsLoopOp()
static LogicalResult verifyWsLoopOp (WsLoopOp op) static
Definition at line 1262 of file OpenMPDialect.cpp.
References verifyReductionVarList().