MLIR: lib/Dialect/StandardOps/IR/Ops.cpp File Reference
Ops.cpp File Reference
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include <numeric>
#include "mlir/Dialect/StandardOps/IR/OpsDialect.cpp.inc"
#include "mlir/Dialect/StandardOps/IR/OpsEnums.cpp.inc"
#include "mlir/Dialect/StandardOps/IR/Ops.cpp.inc"
Classes
struct SelectToNot
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult verify (AtomicRMWOp op)
static LogicalResult verify (GenericAtomicRMWOp op)
static ParseResult parseGenericAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GenericAtomicRMWOp op)
static LogicalResult verify (AtomicYieldOp op)
static LogicalResult collapseBranch (Block *&successor, ValueRange &successorOperands, SmallVectorImpl< Value > &argStorage)
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter &rewriter)
Simplify a branch to a block that has a single predecessor.
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter &rewriter)
br ^bb1 ^bb1 br ^bbN(...)
static Type getI1SameShape (Type type)
static void print (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ConstantOp &op)
The constant op requires an attribute, and furthermore requires that it matches the return type.
static LogicalResult verify (ReturnOp op)
static void print (OpAsmPrinter &p, SelectOp op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SelectOp op)
static LogicalResult verify (SplatOp op)
static ParseResult parseSwitchOpCases (OpAsmParser &parser, Type &flagType, Block *&defaultDestination, SmallVectorImpl< OpAsmParser::OperandType > &defaultOperands, SmallVectorImpl< Type > &defaultOperandTypes, DenseIntElementsAttr &caseValues, SmallVectorImpl< Block *> &caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::OperandType >> &caseOperands, SmallVectorImpl< SmallVector< Type >> &caseOperandTypes)
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
static void printSwitchOpCases (OpAsmPrinter &p, SwitchOp op, Type flagType, Block *defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, TypeRangeRange caseOperandTypes)
static LogicalResult verify (SwitchOp op)
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
static void foldSwitch (SwitchOp op, PatternRewriter &rewriter, APInt caseValue)
Helper for folding a switch with a constant value.
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter &rewriter)
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter &rewriter)
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1532 of file Ops.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
collapseBranch()
static LogicalResult collapseBranch (Block *& successor, ValueRange & successorOperands, SmallVectorImpl< Value > & argStorage) static
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
If the successor is collapsable, successor and successorOperands are updated to reference the new destination and values. argStorage is used as storage if operands to the collapsed successor need to be remapped. It must outlive uses of successorOperands.
Definition at line 343 of file Ops.cpp.
References mlir::Block::args_empty(), mlir::Block::begin(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::failure(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArguments(), mlir::BlockArgument::getOwner(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), and mlir::success().
Referenced by getI1SameShape(), simplifyPassThroughBr(), and simplifyPassThroughSwitch().
dropSwitchCasesThatMatchDefault()
static LogicalResult dropSwitchCasesThatMatchDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb1, 43: ^bb2 ] -> switch flag : i32, [ default: ^bb1, 43: ^bb2 ]
Definition at line 1268 of file Ops.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
foldSwitch()
static void foldSwitch (SwitchOp op, PatternRewriter & rewriter, APInt caseValue) static
Helper for folding a switch with a constant value.
switch c_42 : i32, [ default: ^bb1 , 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 1303 of file Ops.cpp.
References mlir::detail::enumerate(), and mlir::RewriterBase::replaceOpWithNewOp().
Referenced by simplifyConstSwitchValue(), and simplifySwitchFromSwitchOnSameCondition().
getI1SameShape()
static Type getI1SameShape (Type type) static
Definition at line 511 of file Ops.cpp.
References mlir::RewritePatternSet::add(), collapseBranch(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::Type::getContext(), mlir::Builder::getI1Type(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::Block::getUniquePredecessor(), mlir::Type::isa(), mlir::m_NonZero(), mlir::m_Zero(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::RewriterBase::updateRootInPlace(), and vectorType().
Referenced by verify().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 792 of file Ops.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseGenericAtomicRMWOp()
static ParseResult parseGenericAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 291 of file Ops.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, mlir::success(), and mlir::OperationState::types.
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1022 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::succeeded().
parseSwitchOpCases()
static ParseResult parseSwitchOpCases (OpAsmParser & parser, Type & flagType, Block *& defaultDestination, SmallVectorImpl< OpAsmParser::OperandType > & defaultOperands, SmallVectorImpl< Type > & defaultOperandTypes, DenseIntElementsAttr & caseValues, SmallVectorImpl< Block *> & caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::OperandType >> & caseOperands, SmallVectorImpl< SmallVector< Type >> & caseOperandTypes) static
<cases> ::= default : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)*
Definition at line 1124 of file Ops.cpp.
References mlir::failed(), mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::Type::getIntOrFloatBitWidth(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::parseSuccessor(), mlir::succeeded(), and mlir::success().
print() [1/3]
static void print (OpAsmPrinter & p, GenericAtomicRMWOp op) static
Definition at line 313 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/3]
static void print (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 779 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/3]
static void print (OpAsmPrinter & p, SelectOp op) static
Definition at line 1013 of file Ops.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printSwitchOpCases()
static void printSwitchOpCases (OpAsmPrinter & p, SwitchOp op, Type flagType, Block * defaultDestination, OperandRange defaultOperands, TypeRange defaultOperandTypes, DenseIntElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, TypeRangeRange caseOperandTypes) static
Definition at line 1174 of file Ops.cpp.
References mlir::detail::enumerate(), mlir::OpAsmPrinter::printNewline(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
simplifyBrToBlockWithSinglePred()
static LogicalResult simplifyBrToBlockWithSinglePred (BranchOp op, PatternRewriter & rewriter) static
Simplify a branch to a block that has a single predecessor.
This effectively merges the two blocks.
Definition at line 389 of file Ops.cpp.
References mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::getPredecessors(), mlir::RewriterBase::mergeBlocks(), and mlir::success().
Referenced by simplifyPassThroughBr().
simplifyConstSwitchValue()
static LogicalResult simplifyConstSwitchValue (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, 43: ^bb3 ] -> br ^bb2
Definition at line 1324 of file Ops.cpp.
References mlir::failure(), foldSwitch(), mlir::m_ConstantInt(), mlir::matchPattern(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifyPassThroughBr()
static LogicalResult simplifyPassThroughBr (BranchOp op, PatternRewriter & rewriter) static
br ^bb1 ^bb1 br ^bbN(...)
-> br ^bbN(...)
Definition at line 408 of file Ops.cpp.
References collapseBranch(), diag(), mlir::failed(), mlir::failure(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyBrToBlockWithSinglePred(), mlir::succeeded(), and mlir::success().
simplifyPassThroughSwitch()
static LogicalResult simplifyPassThroughSwitch (SwitchOp op, PatternRewriter & rewriter) static
switch c_42 : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3 -> switch c_42 : i32, [ default: ^bb1, 42: ^bb3, ]
Definition at line 1345 of file Ops.cpp.
References collapseBranch(), mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchFromDefaultSwitchOnSameCondition()
static LogicalResult simplifySwitchFromDefaultSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2 ] ^bb1: switch flag : i32, [ default: ^bb3, 42: ^bb4, 43: ^bb5 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb1: switch flag : i32, [ default: ^bb3, 43: ^bb5 ]
Definition at line 1468 of file Ops.cpp.
References mlir::RewritePatternSet::add(), dropSwitchCasesThatMatchDefault(), mlir::detail::enumerate(), mlir::failure(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), simplifyConstSwitchValue(), simplifyPassThroughSwitch(), simplifySwitchFromSwitchOnSameCondition(), simplifySwitchWithOnlyDefault(), and mlir::success().
simplifySwitchFromSwitchOnSameCondition()
static LogicalResult simplifySwitchFromSwitchOnSameCondition (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 42: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb4
and
switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: switch flag : i32, [ default: ^bb3, 43: ^bb4 ] -> switch flag : i32, [ default: ^bb1, 42: ^bb2, ] ^bb2: br ^bb3
Definition at line 1417 of file Ops.cpp.
References mlir::failure(), foldSwitch(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
simplifySwitchWithOnlyDefault()
static LogicalResult simplifySwitchWithOnlyDefault (SwitchOp op, PatternRewriter & rewriter) static
switch flag : i32, [ default: ^bb1 ] -> br ^bb1
Definition at line 1247 of file Ops.cpp.
References mlir::failure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by simplifySwitchFromDefaultSwitchOnSameCondition().
verify() [1/8]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 138 of file Ops.cpp.
References mlir::success().
verify() [2/8]
static LogicalResult verify (GenericAtomicRMWOp op) static
Definition at line 270 of file Ops.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failure(), hasSideEffects(), mlir::WalkResult::interrupt(), and mlir::success().
verify() [3/8]
static LogicalResult verify (AtomicYieldOp op) static
Definition at line 324 of file Ops.cpp.
References mlir::success().
verify() [4/8]
static LogicalResult verify (ConstantOp & op) static
The constant op requires an attribute, and furthermore requires that it matches the return type.
Definition at line 813 of file Ops.cpp.
References mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Attribute::getType(), mlir::FlatSymbolRefAttr::getValue(), mlir::Attribute::isa(), mlir::Type::isa(), mlir::success(), and value.
verify() [5/8]
static LogicalResult verify (ReturnOp op) static
Definition at line 920 of file Ops.cpp.
References mlir::success().
verify() [6/8]
static LogicalResult verify (SelectOp op) static
Definition at line 1045 of file Ops.cpp.
References getI1SameShape(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), and mlir::success().
verify() [7/8]
static LogicalResult verify (SplatOp op) static
Definition at line 1070 of file Ops.cpp.
References mlir::DenseElementsAttr::get(), mlir::DenseIntElementsAttr::get(), getElementType(), mlir::Value::getType(), and mlir::success().
verify() [8/8]
static LogicalResult verify (SwitchOp op) static
Definition at line 1197 of file Ops.cpp.
References mlir::detail::enumerate(), and mlir::success().