MLIR: lib/Dialect/PDL/IR/PDL.cpp File Reference
PDL.cpp File Reference
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/PDL/IR/PDLOpsDialect.cpp.inc"
#include "mlir/Dialect/PDL/IR/PDLOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool hasBindingUse (Operation *op)
Returns true if the given operation is used by a "binding" pdl operation.
static LogicalResult verifyHasBindingUse (Operation *op)
Returns success if the given operation is not in the main matcher body or is used by a "binding" operation.
static void visit (Operation *op, DenseSet< Operation *> &visited)
Visits all the pdl.operand(s), pdl.result(s), and pdl.operation(s) connected to the given operation.
static LogicalResult verify (ApplyNativeConstraintOp op)
static LogicalResult verify (ApplyNativeRewriteOp op)
static LogicalResult verify (AttributeOp op)
static LogicalResult verify (OperandOp op)
static LogicalResult verify (OperandsOp op)
static ParseResult parseOperationOpAttributes (OpAsmParser &p, SmallVectorImpl< OpAsmParser::OperandType > &attrOperands, ArrayAttr &attrNamesAttr)
static void printOperationOpAttributes (OpAsmPrinter &p, OperationOp op, OperandRange attrArgs, ArrayAttr attrNames)
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, OperandRange resultTypes)
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
static LogicalResult verify (OperationOp op)
static LogicalResult verify (PatternOp pattern)
static LogicalResult verify (ReplaceOp op)
static ParseResult parseResultsValueType (OpAsmParser &p, IntegerAttr index, Type &resultType)
static void printResultsValueType (OpAsmPrinter &p, ResultsOp op, IntegerAttr index, Type resultType)
static LogicalResult verify (ResultsOp op)
static LogicalResult verify (RewriteOp op)
static LogicalResult verify (TypeOp op)
static LogicalResult verify (TypesOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 446 of file PDL.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
hasBindingUse()
static bool hasBindingUse (Operation * op) static
Returns true if the given operation is used by a "binding" pdl operation.
Definition at line 39 of file PDL.cpp.
References mlir::Operation::getUsers().
Referenced by verifyHasBindingUse().
parseOperationOpAttributes()
static ParseResult parseOperationOpAttributes (OpAsmParser & p, SmallVectorImpl< OpAsmParser::OperandType > & attrOperands, ArrayAttr & attrNamesAttr) static
Definition at line 141 of file PDL.cpp.
References mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), mlir::succeeded(), and mlir::success().
parseResultsValueType()
static ParseResult parseResultsValueType (OpAsmParser & p, IntegerAttr index, Type & resultType) static
Definition at line 369 of file PDL.cpp.
References mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getType(), mlir::AsmParser::parseArrow(), mlir::AsmParser::parseType(), and mlir::success().
printOperationOpAttributes()
static void printOperationOpAttributes (OpAsmPrinter & p, OperationOp op, OperandRange attrArgs, ArrayAttr attrNames) static
Definition at line 163 of file PDL.cpp.
printResultsValueType()
static void printResultsValueType (OpAsmPrinter & p, ResultsOp op, IntegerAttr index, Type resultType) static
Definition at line 380 of file PDL.cpp.
verify() [1/12]
static LogicalResult verify (ApplyNativeConstraintOp op) static
Definition at line 93 of file PDL.cpp.
References mlir::success().
verify() [2/12]
static LogicalResult verify (ApplyNativeRewriteOp op) static
Definition at line 103 of file PDL.cpp.
References mlir::success().
verify() [3/12]
static LogicalResult verify (AttributeOp op) static
Definition at line 113 of file PDL.cpp.
References verifyHasBindingUse().
verify() [4/12]
static LogicalResult verify (OperandOp op) static
Definition at line 129 of file PDL.cpp.
References verifyHasBindingUse().
verify() [5/12]
static LogicalResult verify (OperandsOp op) static
Definition at line 135 of file PDL.cpp.
References verifyHasBindingUse().
verify() [6/12]
static LogicalResult verify (OperationOp op) static
Definition at line 229 of file PDL.cpp.
References mlir::failed(), mlir::failure(), mlir::RegisteredOperationName::lookup(), verifyHasBindingUse(), and verifyResultTypesAreInferrable().
verify() [7/12]
static LogicalResult verify (PatternOp pattern) static
Definition at line 268 of file PDL.cpp.
References mlir::WalkResult::advance(), mlir::InFlightDiagnostic::attachNote(), mlir::Operation::emitOpError(), mlir::failure(), mlir::Region::front(), mlir::Operation::getDialect(), mlir::Builder::getI16IntegerAttr(), mlir::Operation::getLoc(), mlir::Block::getOps(), mlir::Region::getParentOp(), mlir::Region::getParentRegion(), mlir::Builder::getStringAttr(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), mlir::WalkResult::interrupt(), mlir::OperationState::regions, mlir::success(), visit(), mlir::Region::walk(), and mlir::WalkResult::wasInterrupted().
verify() [8/12]
static LogicalResult verify (ReplaceOp op) static
Definition at line 358 of file PDL.cpp.
References mlir::success().
verify() [9/12]
static LogicalResult verify (ResultsOp op) static
Definition at line 386 of file PDL.cpp.
References mlir::success().
verify() [10/12]
static LogicalResult verify (RewriteOp op) static
Definition at line 399 of file PDL.cpp.
References mlir::Region::empty(), and mlir::success().
verify() [11/12]
static LogicalResult verify (TypeOp op) static
Definition at line 434 of file PDL.cpp.
References verifyHasBindingUse().
verify() [12/12]
static LogicalResult verify (TypesOp op) static
Definition at line 440 of file PDL.cpp.
References verifyHasBindingUse().
verifyHasBindingUse()
static LogicalResult verifyHasBindingUse (Operation * op) static
Returns success if the given operation is not in the main matcher body or is used by a "binding" operation.
On failure, emits an error.
Definition at line 49 of file PDL.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getParentOp(), hasBindingUse(), and mlir::success().
Referenced by verify().
verifyResultTypesAreInferrable()
static LogicalResult verifyResultTypesAreInferrable (OperationOp op, OperandRange resultTypes) static
Verifies that the result types of this operation, defined within a pdl.rewrite, can be inferred.
Definition at line 176 of file PDL.cpp.
References mlir::detail::enumerate(), mlir::Operation::getBlock(), mlir::Operation::isBeforeInBlock(), and mlir::success().
Referenced by verify().
visit()
static void visit (Operation * op, DenseSet< Operation *> & visited) static
Visits all the pdl.operand(s), pdl.result(s), and pdl.operation(s) connected to the given operation.
Definition at line 62 of file PDL.cpp.
References mlir::Operation::getParentOp(), and mlir::Operation::getUsers().
Referenced by computeIterationGraph(), isZero(), GpuAsyncRegionPass::ThreadTokenCallback::operator()(), shouldPrintElementsAttrWithHex(), verify(), and HasAffineDimExprVisitor::visitAffineBinaryOpExpr().