MLIR: lib/Dialect/PDLInterp/IR/PDLInterp.cpp File Reference
PDLInterp.cpp File Reference
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOpsDialect.cpp.inc"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseCreateOperationOpAttributes (OpAsmParser &p, SmallVectorImpl< OpAsmParser::OperandType > &attrOperands, ArrayAttr &attrNamesAttr)
static void printCreateOperationOpAttributes (OpAsmPrinter &p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames)
static ParseResult parseForEachOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ForEachOp op)
static LogicalResult verify (ForEachOp op)
static Type getGetValueTypeOpValueType (Type type)
Given the result type of a GetValueTypeOp, return the expected input type.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 161 of file PDLInterp.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getGetValueTypeOpValueType()
static Type getGetValueTypeOpValueType (Type type) static
Given the result type of a GetValueTypeOp, return the expected input type.
Definition at line 152 of file PDLInterp.cpp.
References mlir::Type::getContext(), and mlir::Type::isa().
parseCreateOperationOpAttributes()
static ParseResult parseCreateOperationOpAttributes (OpAsmParser & p, SmallVectorImpl< OpAsmParser::OperandType > & attrOperands, ArrayAttr & attrNamesAttr) static
Definition at line 34 of file PDLInterp.cpp.
References mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalLBrace(), mlir::AsmParser::parseRBrace(), mlir::succeeded(), and mlir::success().
parseForEachOp()
static ParseResult parseForEachOp (OpAsmParser & parser, OperationState & result) static
Definition at line 83 of file PDLInterp.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseArrow(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::parseSuccessor(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
print()
static void print (OpAsmPrinter & p, ForEachOp op) static
Definition at line 123 of file PDLInterp.cpp.
References mlir::Value::getType(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and mlir::OpAsmPrinter::printSuccessor().
printCreateOperationOpAttributes()
static void printCreateOperationOpAttributes (OpAsmPrinter & p, CreateOperationOp op, OperandRange attrArgs, ArrayAttr attrNames) static
Definition at line 56 of file PDLInterp.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::OperationState::regions.
verify()
static LogicalResult verify (ForEachOp op) static
Definition at line 132 of file PDLInterp.cpp.
References mlir::Value::getType(), and mlir::success().