MLIR: lib/Dialect/Quant/IR/QuantOps.cpp File Reference
QuantOps.cpp File Reference
#include "mlir/Dialect/Quant/QuantOps.h"
#include "TypeDetail.h"
#include "mlir/Dialect/Quant/QuantTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/MathExtras.h"
#include <numeric>
#include "mlir/Dialect/Quant/QuantOpsDialect.cpp.inc"
#include "mlir/Dialect/Quant/QuantOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isValidQuantizationSpec (Attribute quantSpec, Type expressed)
The quantization specification should match the expressed type.
static LogicalResult verifyRegionOp (QuantizeRegionOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 96 of file QuantOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
isValidQuantizationSpec()
static bool isValidQuantizationSpec (Attribute quantSpec, Type expressed) static
The quantization specification should match the expressed type.
Definition at line 47 of file QuantOps.cpp.
References mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Type::isa(), and vectorType().
Referenced by verifyRegionOp().
verifyRegionOp()
static LogicalResult verifyRegionOp (QuantizeRegionOp op) static
Definition at line 68 of file QuantOps.cpp.
References isValidQuantizationSpec(), and mlir::success().