MLIR: lib/Dialect/SPIRV/IR/SPIRVOps.cpp File Reference
SPIRVOps.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/ParserUtils.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpTraits.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/bit.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAvailability.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpAvailabilityImpl.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define GET_OP_CLASSES
Functions
static bool isNestedInFunctionLikeOp (Operation *op)
Returns true if the given op is a function-like op or nested in a function-like op without a module-like op in the middle.
static bool isDirectInModuleLikeOp (Operation *op)
Returns true if the given op is an module-like op that maintains a symbol table.
static LogicalResult extractValueFromConstOp (Operation *op, int32_t &value)
template<typename Ty >
static ArrayAttr getStrArrayAttrForEnumList (Builder &builder, ArrayRef< Ty > enumValues, function_ref< StringRef(Ty)> stringifyFn)
template<typename EnumClass >
static ParseResult parseEnumStrAttr (EnumClass &value, OpAsmParser &parser, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next string attribute in parser as an enumerant of the given EnumClass.
template<typename EnumClass >
static ParseResult parseEnumStrAttr (EnumClass &value, OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next string attribute in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
template<typename EnumClass >
static ParseResult parseEnumKeywordAttr (EnumClass &value, OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next keyword in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
template<typename EnumClass >
static ParseResult parseControlAttribute (OpAsmParser &parser, OperationState &state, StringRef attrName=spirv::attributeName< EnumClass >())
Parses Function, Selection and Loop control attributes.
static ParseResult parseMemoryAccessAttributes (OpAsmParser &parser, OperationState &state)
Parses optional memory access attributes attached to a memory access operand/pointer.
static ParseResult parseSourceMemoryAccessAttributes (OpAsmParser &parser, OperationState &state)
template<typename MemoryOpTy >
static void printMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue=None, Optional< uint32_t > alignmentAttrValue=None)
template<typename MemoryOpTy >
static void printSourceMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue=None, Optional< uint32_t > alignmentAttrValue=None)
static ParseResult parseImageOperands (OpAsmParser &parser, spirv::ImageOperandsAttr &attr)
static void printImageOperands (OpAsmPrinter &printer, Operation *imageOp, spirv::ImageOperandsAttr attr)
template<typename Op >
static LogicalResult verifyImageOperands (Op imageOp, spirv::ImageOperandsAttr attr, Operation::operand_range operands)
static LogicalResult verifyCastOp (Operation *op, bool requireSameBitWidth=true, bool skipBitWidthCheck=false)
template<typename MemoryOpTy >
static LogicalResult verifyMemoryAccessAttribute (MemoryOpTy memoryOp)
template<typename MemoryOpTy >
static LogicalResult verifySourceMemoryAccessAttribute (MemoryOpTy memoryOp)
static LogicalResult verifyMemorySemantics (Operation *op, spirv::MemorySemantics memorySemantics)
template<typename LoadStoreOpTy >
static LogicalResult verifyLoadStorePtrAndValTypes (LoadStoreOpTy op, Value ptr, Value val)
template<typename BlockReadWriteOpTy >
static LogicalResult verifyBlockReadWritePtrAndValTypes (BlockReadWriteOpTy op, Value ptr, Value val)
static ParseResult parseVariableDecorations (OpAsmParser &parser, OperationState &state)
static void printVariableDecorations (Operation *op, OpAsmPrinter &printer, SmallVectorImpl< StringRef > &elidedAttrs)
static unsigned getBitWidth (Type type)
static Type getElementType (Type type, ArrayRef< int32_t > indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn)
Walks the given type hierarchy with the given indices, potentially down to component granularity, to select an element type.
static Type getElementType (Type type, Attribute indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn)
static Type getElementType (Type type, Attribute indices, Location loc)
static Type getElementType (Type type, Attribute indices, OpAsmParser &parser, llvm::SMLoc loc)
static bool isMergeBlock (Block &block)
Returns true if the given block only contains one spv.mlir.merge op.
static ParseResult parseAtomicUpdateOp (OpAsmParser &parser, OperationState &state, bool hasValue)
static void printAtomicUpdateOp (Operation *op, OpAsmPrinter &printer)
template<typename T >
static StringRef stringifyTypeName ()
template<>
StringRef stringifyTypeName< IntegerType > ()
template<>
StringRef stringifyTypeName< FloatType > ()
template<typename ExpectedElementType >
static LogicalResult verifyAtomicUpdateOp (Operation *op)
static ParseResult parseGroupNonUniformArithmeticOp (OpAsmParser &parser, OperationState &state)
static void printGroupNonUniformArithmeticOp (Operation *groupOp, OpAsmPrinter &printer)
static LogicalResult verifyGroupNonUniformArithmeticOp (Operation *groupOp)
static ParseResult parseUnaryOp (OpAsmParser &parser, OperationState &state)
static void printUnaryOp (Operation *unaryOp, OpAsmPrinter &printer)
static Type getUnaryOpResultType (Builder &builder, Type operandType)
Result of a logical op must be a scalar or vector of boolean type.
static ParseResult parseLogicalUnaryOp (OpAsmParser &parser, OperationState &state)
static ParseResult parseLogicalBinaryOp (OpAsmParser &parser, OperationState &result)
static void printLogicalOp (Operation *logicalOp, OpAsmPrinter &printer)
static ParseResult parseShiftOp (OpAsmParser &parser, OperationState &state)
static void printShiftOp (Operation *op, OpAsmPrinter &printer)
static LogicalResult verifyShiftOp (Operation *op)
static void buildLogicalBinaryOp (OpBuilder &builder, OperationState &state, Value lhs, Value rhs)
static void buildLogicalUnaryOp (OpBuilder &builder, OperationState &state, Value value)
static Type getElementPtrType (Type type, ValueRange indices, Location baseLoc)
static ParseResult parseAccessChainOp (OpAsmParser &parser, OperationState &state)
template<typename Op >
static void printAccessChain (Op op, ValueRange indices, OpAsmPrinter &printer)
static void print (spirv::AccessChainOp op, OpAsmPrinter &printer)
template<typename Op >
static LogicalResult verifyAccessChain (Op accessChainOp, ValueRange indices)
static LogicalResult verify (spirv::AccessChainOp accessChainOp)
static LogicalResult verify (spirv::AddressOfOp addressOfOp)
template<typename T >
static void printAtomicCompareExchangeImpl (T atomOp, OpAsmPrinter &printer)
static ParseResult parseAtomicCompareExchangeImpl (OpAsmParser &parser, OperationState &state)
template<typename T >
static LogicalResult verifyAtomicCompareExchangeImpl (T atomOp)
static void print (spirv::AtomicExchangeOp atomOp, OpAsmPrinter &printer)
static ParseResult parseAtomicExchangeOp (OpAsmParser &parser, OperationState &state)
static LogicalResult verify (spirv::AtomicExchangeOp atomOp)
static LogicalResult verify (spirv::BitcastOp bitcastOp)
static ParseResult parseBranchConditionalOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::BranchConditionalOp branchOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::BranchConditionalOp branchOp)
static ParseResult parseCompositeConstructOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::CompositeConstructOp compositeConstructOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::CompositeConstructOp compositeConstructOp)
static ParseResult parseCompositeExtractOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::CompositeExtractOp compositeExtractOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::CompositeExtractOp compExOp)
static ParseResult parseCompositeInsertOp (OpAsmParser &parser, OperationState &state)
static LogicalResult verify (spirv::CompositeInsertOp compositeInsertOp)
static void print (spirv::CompositeInsertOp compositeInsertOp, OpAsmPrinter &printer)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::ConstantOp constOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::ConstantOp constOp)
static ParseResult parseEntryPointOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::EntryPointOp entryPointOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::EntryPointOp entryPointOp)
static ParseResult parseExecutionModeOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::ExecutionModeOp execModeOp, OpAsmPrinter &printer)
static ParseResult parseFuncOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::FuncOp fnOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::FunctionCallOp functionCallOp)
static ParseResult parseGlobalVariableOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::GlobalVariableOp varOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::GlobalVariableOp varOp)
static LogicalResult verify (spirv::GroupBroadcastOp broadcastOp)
static LogicalResult verify (spirv::GroupNonUniformBallotOp ballotOp)
static LogicalResult verify (spirv::GroupNonUniformBroadcastOp broadcastOp)
static ParseResult parseSubgroupBlockReadINTELOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SubgroupBlockReadINTELOp blockReadOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SubgroupBlockReadINTELOp blockReadOp)
static ParseResult parseSubgroupBlockWriteINTELOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SubgroupBlockWriteINTELOp blockWriteOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SubgroupBlockWriteINTELOp blockWriteOp)
static LogicalResult verify (spirv::GroupNonUniformElectOp groupOp)
static ParseResult parseLoadOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::LoadOp loadOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::LoadOp loadOp)
static ParseResult parseLoopOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::LoopOp loopOp, OpAsmPrinter &printer)
static bool hasOneBranchOpTo (Block &srcBlock, Block &dstBlock)
Returns true if the given srcBlock contains only one spv.Branch to the given dstBlock.
static LogicalResult verify (spirv::LoopOp loopOp)
static LogicalResult verify (spirv::MergeOp mergeOp)
static ParseResult parseModuleOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::ModuleOp moduleOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::ModuleOp moduleOp)
static LogicalResult verify (spirv::ReferenceOfOp referenceOfOp)
static LogicalResult verify (spirv::ReturnOp returnOp)
static LogicalResult verify (spirv::ReturnValueOp retValOp)
static LogicalResult verify (spirv::SelectOp op)
static ParseResult parseSelectionOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SelectionOp selectionOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SelectionOp selectionOp)
static ParseResult parseSpecConstantOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SpecConstantOp constOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SpecConstantOp constOp)
static ParseResult parseStoreOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::StoreOp storeOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::StoreOp storeOp)
static LogicalResult verify (spirv::UnreachableOp unreachableOp)
static ParseResult parseVariableOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::VariableOp varOp, OpAsmPrinter &printer)
static LogicalResult verify (spirv::VariableOp varOp)
static LogicalResult verify (spirv::VectorShuffleOp shuffleOp)
static ParseResult parseCooperativeMatrixLoadNVOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::CooperativeMatrixLoadNVOp M, OpAsmPrinter &printer)
static LogicalResult verifyPointerAndCoopMatrixType (Operation *op, Type pointer, Type coopMatrix)
static ParseResult parseCooperativeMatrixStoreNVOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::CooperativeMatrixStoreNVOp coopMatrix, OpAsmPrinter &printer)
static LogicalResult verifyCoopMatrixMulAdd (spirv::CooperativeMatrixMulAddNVOp op)
static LogicalResult verifyMatrixTimesScalar (spirv::MatrixTimesScalarOp op)
static void print (spirv::CopyMemoryOp copyMemory, OpAsmPrinter &printer)
static ParseResult parseCopyMemoryOp (OpAsmParser &parser, OperationState &state)
static LogicalResult verifyCopyMemory (spirv::CopyMemoryOp copyMemory)
static LogicalResult verifyTranspose (spirv::TransposeOp op)
static LogicalResult verifyMatrixTimesMatrix (spirv::MatrixTimesMatrixOp op)
static ParseResult parseSpecConstantCompositeOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SpecConstantCompositeOp op, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SpecConstantCompositeOp constOp)
static ParseResult parseSpecConstantOperationOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::SpecConstantOperationOp op, OpAsmPrinter &printer)
static LogicalResult verify (spirv::SpecConstantOperationOp constOp)
static LogicalResult verifyGLSLFrexpStructOp (spirv::GLSLFrexpStructOp frexpStructOp)
static LogicalResult verify (spirv::GLSLLdexpOp ldexpOp)
static LogicalResult verify (spirv::ImageDrefGatherOp imageDrefGatherOp)
static LogicalResult verify (spirv::ImageQuerySizeOp imageQuerySizeOp)
static ParseResult parsePtrAccessChainOpImpl (StringRef opName, OpAsmParser &parser, OperationState &state)
template<typename Op >
static auto concatElemAndIndices (Op op)
static ParseResult parseInBoundsPtrAccessChainOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::InBoundsPtrAccessChainOp op, OpAsmPrinter &printer)
static LogicalResult verify (spirv::InBoundsPtrAccessChainOp accessChainOp)
static ParseResult parsePtrAccessChainOp (OpAsmParser &parser, OperationState &state)
static void print (spirv::PtrAccessChainOp op, OpAsmPrinter &printer)
static LogicalResult verify (spirv::PtrAccessChainOp accessChainOp)
Variables
static constexpr const char kMemoryAccessAttrName [] = "memory_access"
static constexpr const char kSourceMemoryAccessAttrName []
static constexpr const char kAlignmentAttrName [] = "alignment"
static constexpr const char kSourceAlignmentAttrName [] = "source_alignment"
static constexpr const char kBranchWeightAttrName [] = "branch_weights"
static constexpr const char kCallee [] = "callee"
static constexpr const char kClusterSize [] = "cluster_size"
static constexpr const char kControl [] = "control"
static constexpr const char kDefaultValueAttrName [] = "default_value"
static constexpr const char kExecutionScopeAttrName [] = "execution_scope"
static constexpr const char kEqualSemanticsAttrName [] = "equal_semantics"
static constexpr const char kFnNameAttrName [] = "fn"
static constexpr const char kGroupOperationAttrName [] = "group_operation"
static constexpr const char kIndicesAttrName [] = "indices"
static constexpr const char kInitializerAttrName [] = "initializer"
static constexpr const char kInterfaceAttrName [] = "interface"
static constexpr const char kMemoryScopeAttrName [] = "memory_scope"
static constexpr const char kSemanticsAttrName [] = "semantics"
static constexpr const char kSpecIdAttrName [] = "spec_id"
static constexpr const char kTypeAttrName [] = "type"
static constexpr const char kUnequalSemanticsAttrName [] = "unequal_semantics"
static constexpr const char kValueAttrName [] = "value"
static constexpr const char kValuesAttrName [] = "values"
static constexpr const char kCompositeSpecConstituentsName [] = "constituents"
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3983 of file SPIRVOps.cpp.
Function Documentation
buildLogicalBinaryOp()
static void buildLogicalBinaryOp (OpBuilder & builder, OperationState & state, Value lhs, Value rhs) static
Definition at line 967 of file SPIRVOps.cpp.
buildLogicalUnaryOp()
static void buildLogicalUnaryOp (OpBuilder & builder, OperationState & state, Value value) static
Definition at line 979 of file SPIRVOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::Builder::getI1Type(), and mlir::Value::getType().
concatElemAndIndices()
template<typename Op > static auto concatElemAndIndices (Op op) static
Definition at line 3918 of file SPIRVOps.cpp.
References copy(), getElementPtrType(), mlir::Value::getType(), and mlir::OperationState::location.
Referenced by print().
extractValueFromConstOp()
static LogicalResult extractValueFromConstOp (Operation * op, int32_t & value) static
Definition at line 85 of file SPIRVOps.cpp.
References mlir::failure(), and mlir::success().
Referenced by getElementPtrType(), and verifyGroupNonUniformArithmeticOp().
getBitWidth()
static unsigned getBitWidth (Type type) static
Definition at line 617 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), and vectorType().
Referenced by verify().
getElementPtrType()
static Type getElementPtrType (Type type, ValueRange indices, Location baseLoc) static
Definition at line 993 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), extractValueFromConstOp(), mlir::failed(), mlir::spirv::PointerType::get(), mlir::Operation::getName(), mlir::Value::getType(), and mlir::OperationState::location.
Referenced by concatElemAndIndices(), isAsyncWithOneDependency(), isDefinedByCallTo(), parseAccessChainOp(), parsePtrAccessChainOpImpl(), verify(), and verifyAccessChain().
getElementType() [1/4]
static Type getElementType (Type type, ArrayRef< int32_t > indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn) static
Walks the given type hierarchy with the given indices, potentially down to component granularity, to select an element type.
Returns null type and emits errors with the given loc on failure.
Definition at line 639 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast().
Referenced by castBoolToIntN(), mlir::pdl::PDLType::classof(), mlir::DenseFPElementsAttr::classof(), mlir::DenseIntElementsAttr::classof(), mlir::ShapedType::clone(), mlir::DenseElementsAttr::complex_float_value_begin(), mlir::DenseElementsAttr::complex_float_value_end(), mlir::DenseElementsAttr::complex_value_begin(), mlir::DenseElementsAttr::complex_value_end(), mlir::convertMMAToLLVMType(), convertStructType(), createLinalgBodyCalculationForElementwiseOp(), createReassociationMapsForCollapse(), mlir::LLVM::detail::extractNDVectorTypeInfo(), mlir::DenseElementsAttr::float_value_begin(), mlir::DenseElementsAttr::float_value_end(), foldExtractStridedOpFromInsertChain(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), fuseWithReshapeByExpansion(), genLoad(), mlir::spirv::ImageType::get(), mlir::spirv::ArrayType::getCapabilities(), mlir::spirv::RuntimeArrayType::getCapabilities(), mlir::spirv::CooperativeMatrixNVType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), mlir::spirv::MatrixType::getElementType(), getElementType(), mlir::ShapedType::getElementTypeBitWidth(), mlir::spirv::ArrayType::getExtensions(), mlir::spirv::RuntimeArrayType::getExtensions(), mlir::spirv::CooperativeMatrixNVType::getExtensions(), mlir::DenseElementsAttr::getFloatValues(), getLocalInvocationDimSize(), getPushConstantVariable(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::ShapedType::getSizeInBits(), mlir::spirv::ArrayType::getSizeInBytes(), getSrcVectorElementType(), mlir::getStridesAndOffset(), mlir::DenseElementsAttr::getValues(), mlir::vector::getVectorReductionOp(), handleMultidimensionalVectors(), mlir::ShapedType::hasStaticShape(), isAsyncWithOneDependency(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isComplexOfIntType(), isMatchingWidth(), mlir::DenseElementsAttr::isValidBool(), mlir::DenseElementsAttr::isValidComplex(), mlir::TensorType::isValidElementType(), mlir::DenseElementsAttr::isValidIntOrFloat(), mlir::OperandElementTypeIterator::mapElement(), mlir::ResultElementTypeIterator::mapElement(), mlir::GPUFuncOpLowering::matchAndRewrite(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), mlirComplexTypeGetElementType(), mlirShapedTypeGetElementType(), mlir::spirv::StructType::MemberDecorationInfo::operator<(), parseCompositeExtractOp(), printAllocaOp(), printOperation(), mlir::replaceAllMemRefUsesWith(), mlir::MemRefType::Builder::setMemorySpace(), mlir::DenseElementsAttr::value_begin(), mlir::DenseElementsAttr::value_end(), vectorType(), verify(), verifyAveragePoolOp(), verifyCastOp(), and writeAPIntsToBuffer().
getElementType() [2/4]
static Type getElementType (Type type, Attribute indices, function_ref< InFlightDiagnostic(StringRef)> emitErrorFn) static
Definition at line 665 of file SPIRVOps.cpp.
References mlir::Attribute::dyn_cast(), and getElementType().
getElementType() [3/4]
static Type getElementType (Type type, Attribute indices, Location loc) static
Definition at line 690 of file SPIRVOps.cpp.
References mlir::emitError(), and getElementType().
getElementType() [4/4]
static Type getElementType (Type type, Attribute indices, OpAsmParser & parser, llvm::SMLoc loc) static
Definition at line 697 of file SPIRVOps.cpp.
References mlir::AsmParser::emitError(), and getElementType().
getStrArrayAttrForEnumList()
template<typename Ty > static ArrayAttr getStrArrayAttrForEnumList (Builder & builder, ArrayRef< Ty > enumValues, function_ref< StringRef(Ty)> stringifyFn) static
Definition at line 106 of file SPIRVOps.cpp.
References mlir::Builder::getStrArrayAttr().
getUnaryOpResultType()
static Type getUnaryOpResultType (Builder & builder, Type operandType) static
Result of a logical op must be a scalar or vector of boolean type.
Definition at line 896 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Builder::getIntegerType().
Referenced by parseLogicalBinaryOp(), and parseLogicalUnaryOp().
hasOneBranchOpTo()
static bool hasOneBranchOpTo (Block & srcBlock, Block & dstBlock) inline static
Returns true if the given srcBlock contains only one spv.Branch to the given dstBlock.
Definition at line 2494 of file SPIRVOps.cpp.
References mlir::Block::back().
Referenced by verify().
isDirectInModuleLikeOp()
static bool isDirectInModuleLikeOp (Operation * op) static
Returns true if the given op is an module-like op that maintains a symbol table.
Definition at line 81 of file SPIRVOps.cpp.
References mlir::Operation::hasTrait().
isMergeBlock()
static bool isMergeBlock (Block & block) inline static
Returns true if the given block only contains one spv.mlir.merge op.
Definition at line 706 of file SPIRVOps.cpp.
References mlir::Block::begin(), mlir::Block::empty(), mlir::Block::end(), and mlir::Block::front().
Referenced by verify().
isNestedInFunctionLikeOp()
static bool isNestedInFunctionLikeOp (Operation * op) static
Returns true if the given op is a function-like op or nested in a function-like op without a module-like op in the middle.
Definition at line 69 of file SPIRVOps.cpp.
References mlir::Operation::getParentOp(), and mlir::Operation::hasTrait().
parseAccessChainOp()
static ParseResult parseAccessChainOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1051 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), getElementPtrType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseTypeList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
parseAtomicCompareExchangeImpl()
static ParseResult parseAtomicCompareExchangeImpl (OpAsmParser & parser, OperationState & state) static
Definition at line 1163 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), kEqualSemanticsAttrName, kMemoryScopeAttrName, kUnequalSemanticsAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAtomicExchangeOp()
static ParseResult parseAtomicExchangeOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1237 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), kMemoryScopeAttrName, kSemanticsAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAtomicUpdateOp()
static ParseResult parseAtomicUpdateOp (OpAsmParser & parser, OperationState & state, bool hasValue) static
Definition at line 717 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), kMemoryScopeAttrName, kSemanticsAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseBranchConditionalOp()
static ParseResult parseBranchConditionalOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1334 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addSuccessors(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIntegerType(), kBranchWeightAttrName, mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), mlir::OpAsmParser::parseSuccessorAndUseList(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::success().
parseCompositeConstructOp()
static ParseResult parseCompositeConstructOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1422 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), and mlir::OpAsmParser::resolveOperands().
parseCompositeExtractOp()
static ParseResult parseCompositeExtractOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1506 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getCurrentLocation(), getElementType(), kIndicesAttrName, mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseCompositeInsertOp()
static ParseResult parseCompositeInsertOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1563 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypesToList(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getCurrentLocation(), kIndicesAttrName, mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1616 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Type::isa(), kValueAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::OperationState::types, and value.
parseControlAttribute()
template<typename EnumClass > static ParseResult parseControlAttribute (OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses Function, Selection and Loop control attributes.
If no control is specified, "None" is used as a default.
Definition at line 181 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), kControl, mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
parseCooperativeMatrixLoadNVOp()
static ParseResult parseCooperativeMatrixLoadNVOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3231 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseKeywordType(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseCooperativeMatrixStoreNVOp()
static ParseResult parseCooperativeMatrixStoreNVOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3285 of file SPIRVOps.cpp.
References mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseCopyMemoryOp()
static ParseResult parseCopyMemoryOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3417 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::spirv::PointerType::get(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalComma(), parseSourceMemoryAccessAttributes(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseEntryPointOp()
static ParseResult parseEntryPointOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1841 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), kFnNameAttrName, kInterfaceAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseCommaSeparatedList(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalComma(), and mlir::success().
parseEnumKeywordAttr()
template<typename EnumClass > static ParseResult parseEnumKeywordAttr (EnumClass & value, OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next keyword in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
Definition at line 166 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), mlir::parseEnumKeywordAttr(), and mlir::success().
parseEnumStrAttr() [1/2]
template<typename EnumClass > static ParseResult parseEnumStrAttr (EnumClass & value, OpAsmParser & parser, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next string attribute in parser as an enumerant of the given EnumClass.
Definition at line 123 of file SPIRVOps.cpp.
References mlir::Attribute::cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getNoneType(), mlir::Attribute::isa(), mlir::AsmParser::parseAttribute(), and mlir::success().
Referenced by parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), parseCopyMemoryOp(), parseEntryPointOp(), parseEnumStrAttr(), parseExecutionModeOp(), parseFuncOp(), parseGroupNonUniformArithmeticOp(), parseImageOperands(), parseLoadOp(), parseMemoryAccessAttributes(), parseSourceMemoryAccessAttributes(), parseStoreOp(), parseSubgroupBlockReadINTELOp(), and parseSubgroupBlockWriteINTELOp().
parseEnumStrAttr() [2/2]
template<typename EnumClass > static ParseResult parseEnumStrAttr (EnumClass & value, OpAsmParser & parser, OperationState & state, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next string attribute in parser as an enumerant of the given EnumClass and inserts the enumerant into state as an 32-bit integer attribute with the enum class's name as attribute name.
Definition at line 151 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32IntegerAttr(), parseEnumStrAttr(), and mlir::success().
parseExecutionModeOp()
static ParseResult parseExecutionModeOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1902 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getIntegerType(), kFnNameAttrName, kValuesAttrName, mlir::AsmParser::parseAttribute(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalComma(), mlir::success(), and value.
parseFuncOp()
static ParseResult parseFuncOp (OpAsmParser & parser, OperationState & state) static
Definition at line 1944 of file SPIRVOps.cpp.
References mlir::function_like_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getFunctionType(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_like_impl::getTypeAttrName(), mlir::OptionalParseResult::hasValue(), parseEnumStrAttr(), mlir::function_like_impl::parseFunctionSignature(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalRegion(), and mlir::AsmParser::parseSymbolName().
parseGlobalVariableOp()
static ParseResult parseGlobalVariableOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2163 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::SymbolTable::getSymbolAttrName(), mlir::Type::isa(), kInitializerAttrName, kTypeAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), parseVariableDecorations(), mlir::succeeded(), and mlir::success().
parseGroupNonUniformArithmeticOp()
static ParseResult parseGroupNonUniformArithmeticOp (OpAsmParser & parser, OperationState & state) static
Definition at line 797 of file SPIRVOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kClusterSize, kExecutionScopeAttrName, kGroupOperationAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), parseEnumStrAttr(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::OperationState::types.
parseImageOperands()
static ParseResult parseImageOperands (OpAsmParser & parser, spirv::ImageOperandsAttr & attr) static
Definition at line 319 of file SPIRVOps.cpp.
References mlir::failure(), mlir::AsmParser::getContext(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
parseInBoundsPtrAccessChainOp()
static ParseResult parseInBoundsPtrAccessChainOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3938 of file SPIRVOps.cpp.
References parsePtrAccessChainOpImpl().
parseLoadOp()
static ParseResult parseLoadOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2419 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::spirv::PointerType::get(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), parseEnumStrAttr(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseLogicalBinaryOp()
static ParseResult parseLogicalBinaryOp (OpAsmParser & parser, OperationState & result) static
Definition at line 916 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), mlir::AsmParser::getBuilder(), getUnaryOpResultType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseLogicalUnaryOp()
static ParseResult parseLogicalUnaryOp (OpAsmParser & parser, OperationState & state) static
Definition at line 904 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), mlir::AsmParser::getBuilder(), getUnaryOpResultType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseLoopOp()
static ParseResult parseLoopOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2475 of file SPIRVOps.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), and mlir::OpAsmParser::parseRegion().
parseMemoryAccessAttributes()
static ParseResult parseMemoryAccessAttributes (OpAsmParser & parser, OperationState & state) static
Parses optional memory access attributes attached to a memory access operand/pointer.
Specifically, parses the following syntax: ([ memory-access ])? where: memory-access ::= "None" | "Volatile" | "Aligned", integer-literal | "NonTemporal"
Definition at line 202 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kAlignmentAttrName, kMemoryAccessAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
Referenced by parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseLoadOp(), and parseStoreOp().
parseModuleOp()
static ParseResult parseModuleOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2672 of file SPIRVOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Region::empty(), mlir::failure(), mlir::SymbolTable::getSymbolAttrName(), mlir::AsmParser::parseAttribute(), mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseOptionalAttrDictWithKeyword(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalSymbolName(), mlir::OpAsmParser::parseRegion(), mlir::Region::push_back(), mlir::succeeded(), and mlir::success().
parsePtrAccessChainOp()
static ParseResult parsePtrAccessChainOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3964 of file SPIRVOps.cpp.
References parsePtrAccessChainOpImpl().
parsePtrAccessChainOpImpl()
static ParseResult parsePtrAccessChainOpImpl (StringRef opName, OpAsmParser & parser, OperationState & state) static
Definition at line 3875 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), getElementPtrType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseTypeList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
Referenced by parseInBoundsPtrAccessChainOp(), and parsePtrAccessChainOp().
parseSelectionOp()
static ParseResult parseSelectionOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2865 of file SPIRVOps.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), and mlir::OpAsmParser::parseRegion().
parseShiftOp()
static ParseResult parseShiftOp (OpAsmParser & parser, OperationState & state) static
Definition at line 933 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseSourceMemoryAccessAttributes()
static ParseResult parseSourceMemoryAccessAttributes (OpAsmParser & parser, OperationState & state) static
Definition at line 233 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), kSourceAlignmentAttrName, kSourceMemoryAccessAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), parseEnumStrAttr(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseRSquare(), and mlir::success().
Referenced by parseCopyMemoryOp().
parseSpecConstantCompositeOp()
static ParseResult parseSpecConstantCompositeOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3552 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::SymbolTable::getSymbolAttrName(), kCompositeSpecConstituentsName, kTypeAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), and mlir::success().
parseSpecConstantOp()
static ParseResult parseSpecConstantOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2980 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::SymbolTable::getSymbolAttrName(), kDefaultValueAttrName, kSpecIdAttrName, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), mlir::succeeded(), and mlir::success().
parseSpecConstantOperationOp()
static ParseResult parseSpecConstantOperationOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3641 of file SPIRVOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Region::back(), mlir::Block::begin(), mlir::OpBuilder::create(), mlir::failure(), mlir::AsmParser::getContext(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::OperationState::location, mlir::OpAsmParser::parseGenericOperation(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalAttrDict(), mlir::Region::push_back(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
parseStoreOp()
static ParseResult parseStoreOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3033 of file SPIRVOps.cpp.
References mlir::failure(), mlir::spirv::PointerType::get(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), parseEnumStrAttr(), parseMemoryAccessAttributes(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseSubgroupBlockReadINTELOp()
static ParseResult parseSubgroupBlockReadINTELOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2313 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::failure(), mlir::spirv::PointerType::get(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseSubgroupBlockWriteINTELOp()
static ParseResult parseSubgroupBlockWriteINTELOp (OpAsmParser & parser, OperationState & state) static
Definition at line 2355 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::failure(), mlir::spirv::PointerType::get(), mlir::AsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), parseEnumStrAttr(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseUnaryOp()
static ParseResult parseUnaryOp (OpAsmParser & parser, OperationState & state) static
Definition at line 879 of file SPIRVOps.cpp.
References mlir::OperationState::addTypes(), mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseVariableDecorations()
static ParseResult parseVariableDecorations (OpAsmParser & parser, OperationState & state) static
Definition at line 552 of file SPIRVOps.cpp.
References mlir::OperationState::attributes, bindingName(), descriptorSetName(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by parseGlobalVariableOp(), and parseVariableOp().
parseVariableOp()
static ParseResult parseVariableOp (OpAsmParser & parser, OperationState & state) static
Definition at line 3101 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), parseVariableDecorations(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::success().
print() [1/27]
static void print (spirv::AccessChainOp op, OpAsmPrinter & printer) static
Definition at line 1103 of file SPIRVOps.cpp.
References printAccessChain().
print() [2/27]
static void print (spirv::AtomicExchangeOp atomOp, OpAsmPrinter & printer) static
Definition at line 1231 of file SPIRVOps.cpp.
print() [3/27]
static void print (spirv::BranchConditionalOp branchOp, OpAsmPrinter & printer) static
Definition at line 1385 of file SPIRVOps.cpp.
References mlir::OpAsmPrinter::printSuccessorAndUseList().
print() [4/27]
static void print (spirv::CompositeConstructOp compositeConstructOp, OpAsmPrinter & printer) static
Definition at line 1456 of file SPIRVOps.cpp.
print() [5/27]
static void print (spirv::CompositeExtractOp compositeExtractOp, OpAsmPrinter & printer) static
Definition at line 1530 of file SPIRVOps.cpp.
print() [6/27]
static void print (spirv::CompositeInsertOp compositeInsertOp, OpAsmPrinter & printer) static
Definition at line 1604 of file SPIRVOps.cpp.
print() [7/27]
static void print (spirv::ConstantOp constOp, OpAsmPrinter & printer) static
Definition at line 1630 of file SPIRVOps.cpp.
print() [8/27]
static void print (spirv::EntryPointOp entryPointOp, OpAsmPrinter & printer) static
Definition at line 1872 of file SPIRVOps.cpp.
References mlir::AsmPrinter::printSymbolName().
print() [9/27]
static void print (spirv::ExecutionModeOp execModeOp, OpAsmPrinter & printer) static
Definition at line 1926 of file SPIRVOps.cpp.
References mlir::Attribute::cast(), and mlir::AsmPrinter::printSymbolName().
print() [10/27]
static void print (spirv::FuncOp fnOp, OpAsmPrinter & printer) static
Definition at line 1991 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::WalkResult::advance(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Region::empty(), mlir::failure(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_like_impl::getTypeAttrName(), mlir::Type::isa(), mlir::function_like_impl::printFunctionAttributes(), mlir::function_like_impl::printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), mlir::success(), and mlir::detail::walk().
print() [11/27]
static void print (spirv::GlobalVariableOp varOp, OpAsmPrinter & printer) static
Definition at line 2199 of file SPIRVOps.cpp.
References mlir::SymbolTable::getSymbolAttrName(), kInitializerAttrName, kTypeAttrName, mlir::AsmPrinter::printSymbolName(), and printVariableDecorations().
print() [12/27]
static void print (spirv::SubgroupBlockReadINTELOp blockReadOp, OpAsmPrinter & printer) static
Definition at line 2336 of file SPIRVOps.cpp.
print() [13/27]
static void print (spirv::SubgroupBlockWriteINTELOp blockWriteOp, OpAsmPrinter & printer) static
Definition at line 2379 of file SPIRVOps.cpp.
print() [14/27]
static void print (spirv::LoadOp loadOp, OpAsmPrinter & printer) static
Definition at line 2440 of file SPIRVOps.cpp.
References printMemoryAccessAttribute(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [15/27]
static void print (spirv::LoopOp loopOp, OpAsmPrinter & printer) static
Definition at line 2482 of file SPIRVOps.cpp.
References mlir::OpAsmPrinter::printRegion().
print() [16/27]
static void print (spirv::ModuleOp moduleOp, OpAsmPrinter & printer) static
Definition at line 2708 of file SPIRVOps.cpp.
References mlir::SymbolTable::getSymbolAttrName(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), and mlir::AsmPrinter::printSymbolName().
print() [17/27]
static void print (spirv::SelectionOp selectionOp, OpAsmPrinter & printer) static
Definition at line 2873 of file SPIRVOps.cpp.
References mlir::OpAsmPrinter::printRegion().
print() [18/27]
static void print (spirv::SpecConstantOp constOp, OpAsmPrinter & printer) static
Definition at line 3005 of file SPIRVOps.cpp.
References kSpecIdAttrName, and mlir::AsmPrinter::printSymbolName().
print() [19/27]
static void print (spirv::StoreOp storeOp, OpAsmPrinter & printer) static
Definition at line 3054 of file SPIRVOps.cpp.
References printMemoryAccessAttribute(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [20/27]
static void print (spirv::VariableOp varOp, OpAsmPrinter & printer) static
Definition at line 3142 of file SPIRVOps.cpp.
References printVariableDecorations().
print() [21/27]
static void print (spirv::CooperativeMatrixLoadNVOp M, OpAsmPrinter & printer) static
Definition at line 3253 of file SPIRVOps.cpp.
print() [22/27]
static void print (spirv::CooperativeMatrixStoreNVOp coopMatrix, OpAsmPrinter & printer) static
Definition at line 3307 of file SPIRVOps.cpp.
print() [23/27]
static void print (spirv::CopyMemoryOp copyMemory, OpAsmPrinter & printer) static
Definition at line 3385 of file SPIRVOps.cpp.
References mlir::Type::cast(), printMemoryAccessAttribute(), mlir::OpAsmPrinter::printOptionalAttrDict(), and printSourceMemoryAccessAttribute().
print() [24/27]
static void print (spirv::SpecConstantCompositeOp op, OpAsmPrinter & printer) static
Definition at line 3592 of file SPIRVOps.cpp.
References mlir::AsmPrinter::printSymbolName().
print() [25/27]
static void print (spirv::SpecConstantOperationOp op, OpAsmPrinter & printer) static
Definition at line 3668 of file SPIRVOps.cpp.
References mlir::OpAsmPrinter::printGenericOp().
print() [26/27]
static void print (spirv::InBoundsPtrAccessChainOp op, OpAsmPrinter & printer) static
Definition at line 3944 of file SPIRVOps.cpp.
References concatElemAndIndices(), and printAccessChain().
print() [27/27]
static void print (spirv::PtrAccessChainOp op, OpAsmPrinter & printer) static
Definition at line 3970 of file SPIRVOps.cpp.
References concatElemAndIndices(), and printAccessChain().
printAccessChain()
template<typename Op > static void printAccessChain (Op op, ValueRange indices, OpAsmPrinter & printer) static
Definition at line 1098 of file SPIRVOps.cpp.
References mlir::ValueRange::getTypes().
Referenced by print().
printAtomicCompareExchangeImpl()
template<typename T > static void printAtomicCompareExchangeImpl (T atomOp, OpAsmPrinter & printer) static
Definition at line 1156 of file SPIRVOps.cpp.
printAtomicUpdateOp()
static void printAtomicUpdateOp (Operation * op, OpAsmPrinter & printer) static
Definition at line 746 of file SPIRVOps.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Value::getType(), kMemoryScopeAttrName, kSemanticsAttrName, and stringifyTypeName().
printGroupNonUniformArithmeticOp()
static void printGroupNonUniformArithmeticOp (Operation * groupOp, OpAsmPrinter & printer) static
Definition at line 833 of file SPIRVOps.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), kClusterSize, kExecutionScopeAttrName, and kGroupOperationAttrName.
printImageOperands()
static void printImageOperands (OpAsmPrinter & printer, Operation * imageOp, spirv::ImageOperandsAttr attr) static
Definition at line 334 of file SPIRVOps.cpp.
printLogicalOp()
static void printLogicalOp (Operation * logicalOp, OpAsmPrinter & printer) static
Definition at line 928 of file SPIRVOps.cpp.
References mlir::Operation::getOperand(), mlir::Operation::getOperands(), and mlir::Value::getType().
printMemoryAccessAttribute()
template<typename MemoryOpTy > static void printMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue = None, Optional< uint32_t > alignmentAttrValue = None) static
Definition at line 261 of file SPIRVOps.cpp.
References kAlignmentAttrName, and kMemoryAccessAttrName.
Referenced by print().
printShiftOp()
static void printShiftOp (Operation * op, OpAsmPrinter & printer) static
Definition at line 950 of file SPIRVOps.cpp.
References mlir::Operation::getOperand(), and mlir::Value::getType().
printSourceMemoryAccessAttribute()
template<typename MemoryOpTy > static void printSourceMemoryAccessAttribute (MemoryOpTy memoryOp, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs, Optional< spirv::MemoryAccess > memoryAccessAtrrValue = None, Optional< uint32_t > alignmentAttrValue = None) static
Definition at line 291 of file SPIRVOps.cpp.
References kSourceAlignmentAttrName, and kSourceMemoryAccessAttrName.
Referenced by print().
printUnaryOp()
static void printUnaryOp (Operation * unaryOp, OpAsmPrinter & printer) static
Definition at line 890 of file SPIRVOps.cpp.
References mlir::Operation::getOperand(), and mlir::Value::getType().
printVariableDecorations()
static void printVariableDecorations (Operation * op, OpAsmPrinter & printer, SmallVectorImpl< StringRef > & elidedAttrs) static
Definition at line 589 of file SPIRVOps.cpp.
References bindingName(), descriptorSetName(), mlir::Operation::getAttrOfType(), mlir::Operation::getAttrs(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by print().
stringifyTypeName()
template<typename T > static StringRef stringifyTypeName () static
Referenced by printAtomicUpdateOp().
stringifyTypeName< FloatType >()
template<> StringRef stringifyTypeName< FloatType > ()
Definition at line 768 of file SPIRVOps.cpp.
stringifyTypeName< IntegerType >()
template<> StringRef stringifyTypeName< IntegerType > ()
Definition at line 763 of file SPIRVOps.cpp.
verify() [1/39]
static LogicalResult verify (spirv::AccessChainOp accessChainOp) static
Definition at line 1128 of file SPIRVOps.cpp.
References verifyAccessChain().
verify() [2/39]
static LogicalResult verify (spirv::AddressOfOp addressOfOp) static
Definition at line 1141 of file SPIRVOps.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [3/39]
static LogicalResult verify (spirv::AtomicExchangeOp atomOp) static
Definition at line 1263 of file SPIRVOps.cpp.
References mlir::Type::cast(), and mlir::success().
verify() [4/39]
static LogicalResult verify (spirv::BitcastOp bitcastOp) static
Definition at line 1284 of file SPIRVOps.cpp.
References getBitWidth(), and mlir::success().
verify() [5/39]
static LogicalResult verify (spirv::BranchConditionalOp branchOp) static
Definition at line 1404 of file SPIRVOps.cpp.
References mlir::Attribute::cast(), and mlir::success().
verify() [6/39]
static LogicalResult verify (spirv::CompositeConstructOp compositeConstructOp) static
Definition at line 1462 of file SPIRVOps.cpp.
References getElementType(), mlir::Builder::getI32ArrayAttr(), mlir::Value::getType(), mlir::OperationState::location, and mlir::success().
verify() [7/39]
static LogicalResult verify (spirv::CompositeExtractOp compExOp) static
Definition at line 1537 of file SPIRVOps.cpp.
References mlir::failure(), getElementType(), mlir::Builder::getI32ArrayAttr(), mlir::Value::getType(), and mlir::success().
verify() [8/39]
static LogicalResult verify (spirv::CompositeInsertOp compositeInsertOp) static
Definition at line 1580 of file SPIRVOps.cpp.
References mlir::failure(), getElementType(), and mlir::success().
verify() [9/39]
static LogicalResult verify (spirv::ConstantOp constOp) static
Definition at line 1636 of file SPIRVOps.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::DenseElementsAttr::get(), mlir::DenseFPElementsAttr::get(), mlir::Builder::getArrayAttr(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::Type::getDialect(), mlir::spirv::ArrayType::getElementType(), mlir::Builder::getFloatAttr(), mlir::Builder::getIntegerAttr(), mlir::ShapedType::getNumElements(), mlir::spirv::ArrayType::getNumElements(), mlir::Type::isa(), mlir::success(), value, and vectorType().
verify() [10/39]
static LogicalResult verify (spirv::EntryPointOp entryPointOp) static
Definition at line 1883 of file SPIRVOps.cpp.
References mlir::Builder::getContext(), mlir::Builder::getI32ArrayAttr(), and mlir::success().
verify() [11/39]
static LogicalResult verify (spirv::FunctionCallOp functionCallOp) static
Definition at line 2077 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), kCallee, mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [12/39]
static LogicalResult verify (spirv::GlobalVariableOp varOp) static
Definition at line 2222 of file SPIRVOps.cpp.
References mlir::Operation::emitOpError(), kInitializerAttrName, mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [13/39]
static LogicalResult verify (spirv::GroupBroadcastOp broadcastOp) static
Definition at line 2255 of file SPIRVOps.cpp.
References mlir::success().
verify() [14/39]
static LogicalResult verify (spirv::GroupNonUniformBallotOp ballotOp) static
Definition at line 2274 of file SPIRVOps.cpp.
References mlir::success().
verify() [15/39]
static LogicalResult verify (spirv::GroupNonUniformBroadcastOp broadcastOp) static
Definition at line 2287 of file SPIRVOps.cpp.
References mlir::spirv::getDefaultTargetEnv(), mlir::spirv::lookupTargetEnvOrDefault(), and mlir::success().
verify() [16/39]
static LogicalResult verify (spirv::SubgroupBlockReadINTELOp blockReadOp) static
Definition at line 2343 of file SPIRVOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyBlockReadWritePtrAndValTypes().
verify() [17/39]
static LogicalResult verify (spirv::SubgroupBlockWriteINTELOp blockWriteOp) static
Definition at line 2386 of file SPIRVOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyBlockReadWritePtrAndValTypes().
verify() [18/39]
static LogicalResult verify (spirv::GroupNonUniformElectOp groupOp) static
Definition at line 2398 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::success().
verify() [19/39]
static LogicalResult verify (spirv::LoadOp loadOp) static
Definition at line 2453 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::failed(), mlir::failure(), mlir::Builder::getI32IntegerAttr(), verifyLoadStorePtrAndValTypes(), and verifyMemoryAccessAttribute().
verify() [20/39]
static LogicalResult verify (spirv::LoopOp loopOp) static
Definition at line 2503 of file SPIRVOps.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::Block::back(), mlir::OpBuilder::create(), mlir::Operation::emitOpError(), mlir::Block::front(), mlir::Block::getNumSuccessors(), mlir::Block::getSuccessor(), hasOneBranchOpTo(), isMergeBlock(), and mlir::success().
verify() [21/39]
static LogicalResult verify (spirv::MergeOp mergeOp) static
Definition at line 2626 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Block::back(), mlir::OpBuilder::createBlock(), mlir::Operation::emitOpError(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Block::getTerminator(), and mlir::success().
verify() [22/39]
static LogicalResult verify (spirv::ModuleOp moduleOp) static
Definition at line 2732 of file SPIRVOps.cpp.
References mlir::Operation::emitError(), mlir::SymbolTable::lookup(), and mlir::success().
verify() [23/39]
static LogicalResult verify (spirv::ReferenceOfOp referenceOfOp) static
Definition at line 2799 of file SPIRVOps.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [24/39]
static LogicalResult verify (spirv::ReturnOp returnOp) static
Definition at line 2828 of file SPIRVOps.cpp.
References mlir::success().
verify() [25/39]
static LogicalResult verify (spirv::ReturnValueOp retValOp) static
Definition at line 2837 of file SPIRVOps.cpp.
References mlir::success().
verify() [26/39]
static LogicalResult verify (spirv::SelectOp op) static
Definition at line 2846 of file SPIRVOps.cpp.
References mlir::success().
verify() [27/39]
static LogicalResult verify (spirv::SelectionOp selectionOp) static
Definition at line 2882 of file SPIRVOps.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), isMergeBlock(), and mlir::success().
verify() [28/39]
static LogicalResult verify (spirv::SpecConstantOp constOp) static
Definition at line 3013 of file SPIRVOps.cpp.
References kSpecIdAttrName, and mlir::success().
verify() [29/39]
static LogicalResult verify (spirv::StoreOp storeOp) static
Definition at line 3067 of file SPIRVOps.cpp.
References mlir::failed(), mlir::failure(), verifyLoadStorePtrAndValTypes(), and verifyMemoryAccessAttribute().
verify() [30/39]
static LogicalResult verify (spirv::UnreachableOp unreachableOp) static
Definition at line 3081 of file SPIRVOps.cpp.
References mlir::success().
verify() [31/39]
static LogicalResult verify (spirv::VariableOp varOp) static
Definition at line 3153 of file SPIRVOps.cpp.
References bindingName(), descriptorSetName(), and mlir::success().
verify() [32/39]
static LogicalResult verify (spirv::VectorShuffleOp shuffleOp) static
Definition at line 3201 of file SPIRVOps.cpp.
References max(), and mlir::success().
verify() [33/39]
static LogicalResult verify (spirv::SpecConstantCompositeOp constOp) static
Definition at line 3604 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::spirv::CompositeType::getNumElements(), mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [34/39]
static LogicalResult verify (spirv::SpecConstantOperationOp constOp) static
Definition at line 3673 of file SPIRVOps.cpp.
References mlir::Operation::emitOpError(), mlir::Block::front(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::Operation::hasTrait(), and mlir::success().
verify() [35/39]
static LogicalResult verify (spirv::GLSLLdexpOp ldexpOp) static
Definition at line 3748 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::isa(), mlir::success(), and vectorType().
verify() [36/39]
static LogicalResult verify (spirv::ImageDrefGatherOp imageDrefGatherOp) static
Definition at line 3772 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::spirv::SampledImageType::getImageType(), mlir::Type::isa(), and verifyImageOperands().
verify() [37/39]
static LogicalResult verify (spirv::ImageQuerySizeOp imageQuerySizeOp) static
Definition at line 3814 of file SPIRVOps.cpp.
References mlir::spirv::ImageType::getArrayedInfo(), mlir::spirv::ImageType::getDim(), mlir::spirv::ImageType::getSamplerUseInfo(), mlir::spirv::ImageType::getSamplingInfo(), and mlir::success().
verify() [38/39]
static LogicalResult verify (spirv::InBoundsPtrAccessChainOp accessChainOp) static
Definition at line 3948 of file SPIRVOps.cpp.
References getElementPtrType(), mlir::Value::getType(), mlir::OperationState::location, and verifyAccessChain().
verify() [39/39]
static LogicalResult verify (spirv::PtrAccessChainOp accessChainOp) static
Definition at line 3974 of file SPIRVOps.cpp.
References verifyAccessChain().
verifyAccessChain()
template<typename Op > static LogicalResult verifyAccessChain (Op accessChainOp, ValueRange indices) static
Definition at line 1108 of file SPIRVOps.cpp.
References mlir::OpState::emitOpError(), mlir::failure(), getElementPtrType(), mlir::OpState::getLoc(), and mlir::success().
Referenced by verify().
verifyAtomicCompareExchangeImpl()
template<typename T > static LogicalResult verifyAtomicCompareExchangeImpl (T atomOp) static
Definition at line 1195 of file SPIRVOps.cpp.
References mlir::success().
verifyAtomicUpdateOp()
template<typename ExpectedElementType > static LogicalResult verifyAtomicUpdateOp (Operation * op) static
Definition at line 774 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::spirv::PointerType::getPointeeType(), mlir::Value::getType(), kSemanticsAttrName, mlir::success(), and verifyMemorySemantics().
verifyBlockReadWritePtrAndValTypes()
template<typename BlockReadWriteOpTy > static LogicalResult verifyBlockReadWritePtrAndValTypes (BlockReadWriteOpTy op, Value ptr, Value val) static
Definition at line 540 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::success().
Referenced by verify().
verifyCastOp()
static LogicalResult verifyCastOp (Operation * op, bool requireSameBitWidth = true, bool skipBitWidthCheck = false) static
Definition at line 370 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::Operation::emitOpError(), getElementType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::success(), and vectorType().
verifyCoopMatrixMulAdd()
static LogicalResult verifyCoopMatrixMulAdd (spirv::CooperativeMatrixMulAddNVOp op) static
Definition at line 3323 of file SPIRVOps.cpp.
References mlir::spirv::CooperativeMatrixNVType::getColumns(), mlir::spirv::CooperativeMatrixNVType::getElementType(), mlir::spirv::CooperativeMatrixNVType::getRows(), mlir::spirv::CooperativeMatrixNVType::getScope(), and mlir::success().
verifyCopyMemory()
static LogicalResult verifyCopyMemory (spirv::CopyMemoryOp copyMemory) static
Definition at line 3459 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::failed(), mlir::failure(), verifyMemoryAccessAttribute(), and verifySourceMemoryAccessAttribute().
verifyGLSLFrexpStructOp()
static LogicalResult verifyGLSLFrexpStructOp (spirv::GLSLFrexpStructOp frexpStructOp) static
Definition at line 3697 of file SPIRVOps.cpp.
References mlir::Type::dyn_cast(), mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getNumElements(), and mlir::success().
verifyGroupNonUniformArithmeticOp()
static LogicalResult verifyGroupNonUniformArithmeticOp (Operation * groupOp) static
Definition at line 850 of file SPIRVOps.cpp.
References mlir::Operation::emitOpError(), extractValueFromConstOp(), mlir::failed(), mlir::Operation::getAttrOfType(), mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), kExecutionScopeAttrName, kGroupOperationAttrName, and mlir::success().
verifyImageOperands()
template<typename Op > static LogicalResult verifyImageOperands (Op imageOp, spirv::ImageOperandsAttr attr, Operation::operand_range operands) static
Definition at line 343 of file SPIRVOps.cpp.
References mlir::OpState::emitError(), and mlir::success().
Referenced by verify().
verifyLoadStorePtrAndValTypes()
template<typename LoadStoreOpTy > static LogicalResult verifyLoadStorePtrAndValTypes (LoadStoreOpTy op, Value ptr, Value val) static
Definition at line 525 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::success().
Referenced by verify().
verifyMatrixTimesMatrix()
static LogicalResult verifyMatrixTimesMatrix (spirv::MatrixTimesMatrixOp op) static
Definition at line 3515 of file SPIRVOps.cpp.
References mlir::spirv::MatrixType::getElementType(), mlir::spirv::MatrixType::getNumColumns(), mlir::spirv::MatrixType::getNumRows(), and mlir::success().
verifyMatrixTimesScalar()
static LogicalResult verifyMatrixTimesScalar (spirv::MatrixTimesScalarOp op) static
Definition at line 3348 of file SPIRVOps.cpp.
References mlir::spirv::MatrixType::getElementType(), mlir::spirv::MatrixType::getNumColumns(), mlir::spirv::MatrixType::getNumRows(), and mlir::success().
verifyMemoryAccessAttribute()
template<typename MemoryOpTy > static LogicalResult verifyMemoryAccessAttribute (MemoryOpTy memoryOp) static
Definition at line 417 of file SPIRVOps.cpp.
References kAlignmentAttrName, kMemoryAccessAttrName, and mlir::success().
Referenced by verify(), and verifyCopyMemory().
verifyMemorySemantics()
static LogicalResult verifyMemorySemantics (Operation * op, spirv::MemorySemantics memorySemantics) static
Definition at line 501 of file SPIRVOps.cpp.
References mlir::Operation::emitError(), and mlir::success().
Referenced by verifyAtomicUpdateOp().
verifyPointerAndCoopMatrixType()
static LogicalResult verifyPointerAndCoopMatrixType (Operation * op, Type pointer, Type coopMatrix) static
Definition at line 3262 of file SPIRVOps.cpp.
References mlir::Type::cast(), mlir::Operation::emitError(), mlir::Type::isa(), and mlir::success().
verifyShiftOp()
static LogicalResult verifyShiftOp (Operation * op) static
Definition at line 957 of file SPIRVOps.cpp.
References mlir::Operation::emitError(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Value::getType(), and mlir::success().
verifySourceMemoryAccessAttribute()
template<typename MemoryOpTy > static LogicalResult verifySourceMemoryAccessAttribute (MemoryOpTy memoryOp) static
Definition at line 461 of file SPIRVOps.cpp.
References kSourceAlignmentAttrName, kSourceMemoryAccessAttrName, and mlir::success().
Referenced by verifyCopyMemory().
verifyTranspose()
static LogicalResult verifyTranspose (spirv::TransposeOp op) static
Definition at line 3490 of file SPIRVOps.cpp.
References mlir::spirv::MatrixType::getElementType(), mlir::spirv::MatrixType::getNumColumns(), mlir::spirv::MatrixType::getNumRows(), and mlir::success().
Variable Documentation
kAlignmentAttrName
constexpr const char kAlignmentAttrName[] = "alignment" static
Definition at line 40 of file SPIRVOps.cpp.
Referenced by parseMemoryAccessAttributes(), printMemoryAccessAttribute(), and verifyMemoryAccessAttribute().
kBranchWeightAttrName
constexpr const char kBranchWeightAttrName[] = "branch_weights" static
Definition at line 42 of file SPIRVOps.cpp.
Referenced by parseBranchConditionalOp().
kCallee
constexpr const char kCallee[] = "callee" static
Definition at line 43 of file SPIRVOps.cpp.
Referenced by verify().
kClusterSize
constexpr const char kClusterSize[] = "cluster_size" static
Definition at line 44 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), and printGroupNonUniformArithmeticOp().
kCompositeSpecConstituentsName
constexpr const char kCompositeSpecConstituentsName[] = "constituents" static
Definition at line 61 of file SPIRVOps.cpp.
Referenced by parseSpecConstantCompositeOp().
kControl
constexpr const char kControl[] = "control" static
Definition at line 45 of file SPIRVOps.cpp.
Referenced by parseControlAttribute().
kDefaultValueAttrName
constexpr const char kDefaultValueAttrName[] = "default_value" static
Definition at line 46 of file SPIRVOps.cpp.
Referenced by parseSpecConstantOp().
kEqualSemanticsAttrName
constexpr const char kEqualSemanticsAttrName[] = "equal_semantics" static
Definition at line 48 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl().
kExecutionScopeAttrName
constexpr const char kExecutionScopeAttrName[] = "execution_scope" static
Definition at line 47 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), printGroupNonUniformArithmeticOp(), and verifyGroupNonUniformArithmeticOp().
kFnNameAttrName
constexpr const char kFnNameAttrName[] = "fn" static
Definition at line 49 of file SPIRVOps.cpp.
Referenced by parseEntryPointOp(), and parseExecutionModeOp().
kGroupOperationAttrName
constexpr const char kGroupOperationAttrName[] = "group_operation" static
Definition at line 50 of file SPIRVOps.cpp.
Referenced by parseGroupNonUniformArithmeticOp(), printGroupNonUniformArithmeticOp(), and verifyGroupNonUniformArithmeticOp().
kIndicesAttrName
constexpr const char kIndicesAttrName[] = "indices" static
Definition at line 51 of file SPIRVOps.cpp.
Referenced by parseCompositeExtractOp(), and parseCompositeInsertOp().
kInitializerAttrName
constexpr const char kInitializerAttrName[] = "initializer" static
Definition at line 52 of file SPIRVOps.cpp.
Referenced by parseGlobalVariableOp(), print(), and verify().
kInterfaceAttrName
constexpr const char kInterfaceAttrName[] = "interface" static
Definition at line 53 of file SPIRVOps.cpp.
Referenced by parseEntryPointOp().
kMemoryAccessAttrName
constexpr const char kMemoryAccessAttrName[] = "memory_access" static
Definition at line 37 of file SPIRVOps.cpp.
Referenced by parseMemoryAccessAttributes(), printMemoryAccessAttribute(), and verifyMemoryAccessAttribute().
kMemoryScopeAttrName
constexpr const char kMemoryScopeAttrName[] = "memory_scope" static
Definition at line 54 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl(), parseAtomicExchangeOp(), parseAtomicUpdateOp(), and printAtomicUpdateOp().
kSemanticsAttrName
constexpr const char kSemanticsAttrName[] = "semantics" static
Definition at line 55 of file SPIRVOps.cpp.
Referenced by parseAtomicExchangeOp(), parseAtomicUpdateOp(), printAtomicUpdateOp(), and verifyAtomicUpdateOp().
kSourceAlignmentAttrName
constexpr const char kSourceAlignmentAttrName[] = "source_alignment" static
Definition at line 41 of file SPIRVOps.cpp.
Referenced by parseSourceMemoryAccessAttributes(), printSourceMemoryAccessAttribute(), and verifySourceMemoryAccessAttribute().
kSourceMemoryAccessAttrName
constexpr const char kSourceMemoryAccessAttrName[] static
Initial value:
=
    "source_memory_access"
Definition at line 38 of file SPIRVOps.cpp.
Referenced by parseSourceMemoryAccessAttributes(), printSourceMemoryAccessAttribute(), and verifySourceMemoryAccessAttribute().
kSpecIdAttrName
constexpr const char kSpecIdAttrName[] = "spec_id" static
Definition at line 56 of file SPIRVOps.cpp.
Referenced by parseSpecConstantOp(), print(), and verify().
kTypeAttrName
constexpr const char kTypeAttrName[] = "type" static
Definition at line 57 of file SPIRVOps.cpp.
Referenced by parseGlobalVariableOp(), parseSpecConstantCompositeOp(), and print().
kUnequalSemanticsAttrName
constexpr const char kUnequalSemanticsAttrName[] = "unequal_semantics" static
Definition at line 58 of file SPIRVOps.cpp.
Referenced by parseAtomicCompareExchangeImpl().
kValueAttrName
constexpr const char kValueAttrName[] = "value" static
Definition at line 59 of file SPIRVOps.cpp.
Referenced by parseConstantOp().
kValuesAttrName
constexpr const char kValuesAttrName[] = "values" static
Definition at line 60 of file SPIRVOps.cpp.
Referenced by parseExecutionModeOp().