MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo) const
bool isNotConflicting (Operation *op, OpOperand *uRead, OpOperand *uConflictingWrite, const BufferizationAliasInfo &aliasInfo) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 294 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 392 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns, mlir::Type::cast(), mlir::OpBuilder::create(), mlir::failure(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::linalg::comprehensive_bufferize::tensor_ext::getTensorBufferizationState(), mlir::Value::getType(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::options, mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 297 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 301 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getOpOperand().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo) const inline
Definition at line 311 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::Equivalent.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 305 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getOpOperand(), and mlir::Operation::getResult().
isNotConflicting()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::isNotConflicting (Operation * op, OpOperand * uRead, OpOperand * uConflictingWrite, const BufferizationAliasInfo & aliasInfo) const inline
Definition at line 316 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::detail::IROperandBase::getOwner(), and mlir::linalg::comprehensive_bufferize::tensor_ext::hasMatchingExtractSliceOp().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp