MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 88 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 103 of file TensorInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::Value::replaceAllUsesWith(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 91 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 95 of file TensorInterfaceImpl.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 99 of file TensorInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp