MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 179 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 194 of file TensorInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 182 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 186 of file TensorInterfaceImpl.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 190 of file TensorInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp