MLIR: mlir::linalg::comprehensive_bufferize::bufferization_ext::ToTensorOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::bufferization_ext::ToTensorOpInterface Struct Reference
ToTensorOp conceptually loads a tensor from a memory location.
Public Member Functions
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
Detailed Description
ToTensorOp conceptually loads a tensor from a memory location.
Such ops do not lower any further, and they should have disappeared by the time the input is fully bufferized.
The analysis has no information about the memref that is loaded from by the ToTensorOp. We have to assume that the loaded tensor may after bufferization potentially alias with any other bufferized tensor. Since ToTensorOp and ToMemrefOp have no aliasing OpOperand/OpResult pairs, this cannot be encoded directly in the analysis. However, declaring ToTensorOp results as not writable also enforces a buffer copy and has the same effect.
Definition at line 64 of file BufferizationInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::bufferization_ext::ToTensorOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 67 of file BufferizationInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), and mlir::success().
isWritable()
bool mlir::linalg::comprehensive_bufferize::bufferization_ext::ToTensorOpInterface::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Definition at line 74 of file BufferizationInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::bufferization_ext::registerBufferizableOpInterfaceExternalModels().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/BufferizationInterfaceImpl.cpp