MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 115 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
If not inplaceable, copy.
Definition at line 137 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns, mlir::Type::cast(), mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::createAllocDeallocFn(), mlir::Value::getType(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::insertNewBufferAlias(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace(), mlir::linalg::comprehensive_bufferize::isValueRead(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::options, and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 118 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 122 of file TensorInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo) const inline
Definition at line 132 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::None.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 126 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getOpOperand(), and mlir::Operation::getResult().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp