MLIR: mlir::linalg::comprehensive_bufferize::BufferizationState Struct Reference
mlir::linalg::comprehensive_bufferize::BufferizationState Struct Reference
BufferizationState keeps track of bufferization state and provides access to the results of the analysis.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
Public Member Functions
BufferizationState (ModuleOp moduleOp, const BufferizationOptions &options)
BufferizationState (const BufferizationState &)=delete
Value createAllocDeallocFn (OpBuilder &builder, Location loc, Value shapedValue)
A function that creates an alloc-dealloc pair.
void mapBuffer (ValueRange tensors, ValueRange buffers)
Map tensor values to memref buffers.
void mapBuffer (Value tensor, Value buffer)
Map a tensor value to a memref buffer.
Value lookupBuffer (Value tensor)
Lookup the memref buffer that is associated to the given tensor value.
bool isMapped (Value value) const
Return true if the given value is mapped.
Value getResultBuffer (OpResult result)
Return the result buffer (memref) for a given OpResult (tensor).
void markOpObsolete (Operation *op)
Mark op as obsolete, so that it is deleted after bufferization.
void eraseObsoleteOps ()
Erase all ops that were marked obsolete.
template<typename StateT >
StateT & getDialectState (StringRef name)
Return dialect-specific bufferization state.
Public Attributes
BufferizationAliasInfo aliasInfo
aliasInfo keeps track of aliasing and equivalent values.
BlockAndValueMapping mapping
The mapping of tensors to buffers.
SmallVector< Operation * > obsoleteOps
Obsolete ops that should be deleted after bufferization.
DenseMap< StringRef, std::unique_ptr< DialectBufferizationState > > dialectState
Dialect-specific bufferization state.
const BufferizationOptions & options
A reference to current bufferization options.
OpBuilder builder
The OpBuilder used during bufferization.
Detailed Description
BufferizationState keeps track of bufferization state and provides access to the results of the analysis.
Definition at line 286 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
BufferizationState() [1/2]
mlir::linalg::comprehensive_bufferize::BufferizationState::BufferizationState (ModuleOp moduleOp, const BufferizationOptions & options) inline
Definition at line 287 of file BufferizableOpInterface.h.
BufferizationState() [2/2]
mlir::linalg::comprehensive_bufferize::BufferizationState::BufferizationState (const BufferizationState &) delete
Member Function Documentation
createAllocDeallocFn()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::createAllocDeallocFn (OpBuilder & b, Location loc, Value shapedValue)
A function that creates an alloc-dealloc pair.
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
This function may perform additional optimizations such as buffer allocation hoisting. This function calls allocationFn and deallocationFn to create (de)allocations.
Definition at line 553 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getAllocationTypeAndShape(), mlir::Value::getType(), mlir::Type::isa(), options, and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), and getAllocationTypeAndShape().
eraseObsoleteOps()
void mlir::linalg::comprehensive_bufferize::BufferizationState::eraseObsoleteOps ()
Erase all ops that were marked obsolete.
Definition at line 660 of file BufferizableOpInterface.cpp.
Referenced by markOpObsolete().
getDialectState()
template<typename StateT > StateT& mlir::linalg::comprehensive_bufferize::BufferizationState::getDialectState (StringRef name) inline
Return dialect-specific bufferization state.
Definition at line 325 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::getTensorBufferizationState().
getResultBuffer()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer (OpResult result)
Return the result buffer (memref) for a given OpResult (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization is necessary.
Definition at line 337 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::bufferizesToMemoryWrite(), mlir::Value::cast(), mlir::Operation::emitError(), mlir::linalg::comprehensive_bufferize::findLastPrecedingWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::OpResult::getOwner(), mlir::linalg::comprehensive_bufferize::isValueRead(), options, and setInsertionPointAfter().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::findLastPrecedingWrite().
isMapped()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::isMapped (Value value) const
Return true if the given value is mapped.
Definition at line 649 of file BufferizableOpInterface.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::bufferize().
lookupBuffer()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer (Value tensor)
Lookup the memref buffer that is associated to the given tensor value.
Wrapper for better debugging.
Asserts if no buffer is associated.
Definition at line 616 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), mlir::Value::dump(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), mlir::linalg::comprehensive_bufferize::getDynamicMemRefType(), mlir::Value::getLoc(), mlir::Value::getType(), mlir::Type::isa(), options, and setInsertionPointAfter().
Referenced by mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferize().
mapBuffer() [1/2]
void mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer (ValueRange tensors, ValueRange buffers)
Map tensor values to memref buffers.
Wrapper for better debugging.
Definition at line 585 of file BufferizableOpInterface.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::bufferization_ext::ToTensorOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::bufferize().
mapBuffer() [2/2]
void mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer (Value tensor, Value buffer)
Map a tensor value to a memref buffer.
Wrapper for better debugging.
Definition at line 604 of file BufferizableOpInterface.cpp.
References mlir::Value::getType(), and mlir::Type::isa().
markOpObsolete()
void mlir::linalg::comprehensive_bufferize::BufferizationState::markOpObsolete (Operation * op)
Mark op as obsolete, so that it is deleted after bufferization.
Definition at line 654 of file BufferizableOpInterface.cpp.
References eraseObsoleteOps().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize().
Member Data Documentation
aliasInfo
BufferizationAliasInfo mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo
aliasInfo keeps track of aliasing and equivalent values.
Definition at line 333 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run(), mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle::run(), mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run(), and mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
builder
OpBuilder mlir::linalg::comprehensive_bufferize::BufferizationState::builder
The OpBuilder used during bufferization.
Definition at line 348 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::bufferize().
dialectState
DenseMap<StringRef, std::unique_ptr<DialectBufferizationState> > mlir::linalg::comprehensive_bufferize::BufferizationState::dialectState
Dialect-specific bufferization state.
Definition at line 342 of file BufferizableOpInterface.h.
mapping
BlockAndValueMapping mlir::linalg::comprehensive_bufferize::BufferizationState::mapping
The mapping of tensors to buffers.
Definition at line 336 of file BufferizableOpInterface.h.
obsoleteOps
SmallVector<Operation *> mlir::linalg::comprehensive_bufferize::BufferizationState::obsoleteOps
Obsolete ops that should be deleted after bufferization.
Definition at line 339 of file BufferizableOpInterface.h.
options
const BufferizationOptions& mlir::linalg::comprehensive_bufferize::BufferizationState::options
A reference to current bufferization options.
Definition at line 345 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h
lib/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.cpp