MLIR: mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep Struct Reference
mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep Struct Reference
Try to eliminate InitTensorOps inside funcOp that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h"
Public Member Functions
LogicalResult run (FuncOp funcOp, BufferizationState &state, SmallVector< Operation *> &newOps) override
Try to eliminate InitTensorOps inside funcOp.
Public Member Functions inherited from mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep
LogicalResult eliminateInitTensors (FuncOp funcOp, BufferizationState &state, std::function< bool(OpOperand &)> anchorMatchFunc, std::function< Value(OpBuilder &, Location, OpOperand &)> rewriteFunc, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside funcOp.
Public Member Functions inherited from mlir::linalg::comprehensive_bufferize::PostAnalysisStep
virtual ~PostAnalysisStep ()
Detailed Description
Try to eliminate InitTensorOps inside funcOp that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
Definition at line 46 of file LinalgInterfaceImpl.h.
Member Function Documentation
run()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run (FuncOp funcOp, BufferizationState & state, SmallVector< Operation *> & newOps) override virtual
Try to eliminate InitTensorOps inside funcOp.
An InitTensorOp can be eliminated if it is eventually inserted into another tensor (and some other conditions are met).
E.g.: %0 = linalg.init_tensor %1 = linalg.fill(cst, %0) {inplace = [true]} %2 = tensor.insert_slice %1 into t[10][20][1]
InitTensorOp elimination will try to fill t inplace instead of filling a new allocation %0 and inserting it into t. This is done by replacing the InitTensorOp with:
%0 = tensor.extract_slice t[10][20][1]
The analysis looks for matching ExtractSliceOp/InsertSliceOp pairs and lets those bufferize inplace in the absence of other conflicts.
Starting from an InsertSliceOp, an InitTensorOp at the end of the insert source's reverse use-def chain is eliminated if:
The InsertSliceOp was decided to bufferize inplace.
On the reverse use-def chain path from the InsertSliceOp to the InitTensorOp, all ops were decided to bufferize inplace and the buffer relation is "equivalent" (TODO: can be relaxed if needed).
The reverse use-def chain has exactly one end, which is the InitTensorOp.
Note that the newly inserted ExtractSliceOp may have to bufferize out-of-place due to RaW conflicts.
Implements mlir::linalg::comprehensive_bufferize::PostAnalysisStep.
Definition at line 475 of file LinalgInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::OpBuilder::create(), mlir::detail::IROperandBase::getOwner(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace(), and mlir::linalg::comprehensive_bufferize::linalg_ext::registerBufferizableOpInterfaceExternalModels().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.cpp