MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 170 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 217 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::failed(), mlir::failure(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle::run(), mlir::IROperand< DerivedT, IRValueT >::set(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 173 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::isValueRead().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand) const inline
Definition at line 180 of file SCFInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo) const inline
Definition at line 194 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::linalg::comprehensive_bufferize::Equivalent, mlir::OpResult::getResultNumber(), and mlir::linalg::comprehensive_bufferize::None.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 187 of file SCFInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
isWritable()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Definition at line 207 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp