MLIR: mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep Struct Reference
mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep Struct Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h"
Public Member Functions
LogicalResult eliminateInitTensors (FuncOp funcOp, BufferizationState &state, std::function< bool(OpOperand &)> anchorMatchFunc, std::function< Value(OpBuilder &, Location, OpOperand &)> rewriteFunc, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside funcOp.
Public Member Functions inherited from mlir::linalg::comprehensive_bufferize::PostAnalysisStep
virtual ~PostAnalysisStep ()
virtual LogicalResult run (FuncOp funcOp, BufferizationState &state, SmallVector< Operation *> &newOps)=0
Run the post analysis step.
Detailed Description
Definition at line 25 of file LinalgInterfaceImpl.h.
Member Function Documentation
eliminateInitTensors()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors (FuncOp funcOp, BufferizationState & state, std::function< bool(OpOperand &)> anchorMatchFunc, std::function< Value(OpBuilder &, Location, OpOperand &)> rewriteFunc, SmallVector< Operation *> & newOps)
Try to eliminate InitTensorOps inside funcOp.
Try to eliminate InitTensorOps inside funcOp.
rewriteFunc generates the replacement for the InitTensorOp.
Only InitTensorOps that are anchored on a matching OpOperand as per anchorMatchFunc are considered. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
The result of rewriteFunc must usually be analyzed for inplacability. This analysis can be skipped with skipAnalysis.
An InitTensorOp is replaced with the the result of rewriteFunc if it is anchored on a matching OpOperand. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
Definition at line 380 of file LinalgInterfaceImpl.cpp.
References mlir::WalkResult::advance(), mlir::linalg::comprehensive_bufferize::BufferizationState::aliasInfo, mlir::Value::dyn_cast(), mlir::failure(), mlir::linalg::comprehensive_bufferize::findValueInReverseUseDefChain(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::linalg::comprehensive_bufferize::getAliasingOpOperand(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Operation::getOpOperands(), mlir::Value::replaceAllUsesWith(), mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run(), mlir::OpBuilder::setInsertionPoint(), mlir::WalkResult::skip(), and mlir::WalkResult::wasInterrupted().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.cpp