MLIR: mlir::linalg::LinalgGenericTilingPattern Struct Reference
mlir::linalg::LinalgGenericTilingPattern Struct Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LinalgGenericTilingPattern (MLIRContext *context, LinalgTransformationFilter filter, LinalgTilingOptions options=LinalgTilingOptions(), PatternBenefit benefit=1)
Entry point to match any LinalgOp OpInterface.
LinalgGenericTilingPattern (StringRef opName, MLIRContext *context, LinalgTilingOptions options, LinalgTransformationFilter filter=LinalgTransformationFilter(), PatternBenefit benefit=1)
Entry point to match a specific Linalg op.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::linalg::LinalgBaseTilingPattern
LinalgBaseTilingPattern (MLIRContext *context, LinalgTilingOptions options, LinalgTransformationFilter filter=LinalgTransformationFilter(), PatternBenefit benefit=1)
LinalgBaseTilingPattern (StringRef opName, MLIRContext *context, LinalgTilingOptions options, LinalgTransformationFilter filter=LinalgTransformationFilter(), PatternBenefit benefit=1)
Linalg base tiling pattern.
LogicalResult matchAndRewriteBase (Operation *op, PatternRewriter &rewriter, TiledLinalgOp &result) const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&... args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Definition at line 661 of file Transforms.h.
Constructor & Destructor Documentation
LinalgGenericTilingPattern() [1/2]
mlir::linalg::LinalgGenericTilingPattern::LinalgGenericTilingPattern (MLIRContext * context, LinalgTransformationFilter filter, LinalgTilingOptions options = LinalgTilingOptions(), PatternBenefit benefit = 1) inline
Entry point to match any LinalgOp OpInterface.
MatchAnyOpTag-based constructor with a mandatory filter.
Definition at line 664 of file Transforms.h.
LinalgGenericTilingPattern() [2/2]
mlir::linalg::LinalgGenericTilingPattern::LinalgGenericTilingPattern (StringRef opName, MLIRContext * context, LinalgTilingOptions options, LinalgTransformationFilter filter = LinalgTransformationFilter(), PatternBenefit benefit = 1) inline
Entry point to match a specific Linalg op.
Definition at line 670 of file Transforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::linalg::LinalgGenericTilingPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 676 of file Transforms.h.
References mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::RewriterBase::replaceOp(), mlir::success(), and mlir::linalg::TiledLinalgOp::tensorResults.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Transforms/Transforms.h