MLIR: mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface Struct Reference
Public Member Functions
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
Detailed Description
Definition at line 23 of file ArithInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 26 of file ArithInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::GlobalCreator::getGlobalFor(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), and mlir::success().
isWritable()
bool mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Definition at line 45 of file ArithInterfaceImpl.cpp.
References mlir::Value::isa(), and mlir::linalg::comprehensive_bufferize::arith_ext::registerBufferizableOpInterfaceExternalModels().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ArithInterfaceImpl.cpp