MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface Struct Reference
Public Member Functions
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult) const
bool isMemoryWrite (Operation *op, OpResult opResult) const
bool mustBufferizeInPlace (Operation *op, OpResult opResult) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo) const
Detailed Description
Definition at line 77 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 128 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::failed(), mlir::failure(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), and mlir::success().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo) const inline
Definition at line 156 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::linalg::comprehensive_bufferize::Equivalent, and mlir::linalg::comprehensive_bufferize::None.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult) const inline
Definition at line 79 of file SCFInterfaceImpl.cpp.
References mlir::Operation::getOpResults().
isMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::isMemoryWrite (Operation * op, OpResult opResult) const inline
Definition at line 96 of file SCFInterfaceImpl.cpp.
mustBufferizeInPlace()
bool mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::mustBufferizeInPlace (Operation * op, OpResult opResult) const inline
Definition at line 122 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp