MLIR: mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
Detailed Description
Definition at line 500 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow FuncOp that are inplaceable to write inPlace.
Definition at line 520 of file ModuleBufferization.cpp.
References mlir::OpBuilder::create(), getAssumedUniqueReturnOp(), getCalledFunction(), getModuleBufferizationState(), getOrCreateBufferizedFunctionType(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::markOpObsolete(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand) const inline
Definition at line 502 of file ModuleBufferization.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand) const inline
Definition at line 510 of file ModuleBufferization.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp