MLIR: mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface Struct Reference
Public Member Functions
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
Return true if the given function argument is writable.
bool isAllocationHoistingBarrier (Operation *op) const
Detailed Description
Definition at line 669 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 671 of file ModuleBufferization.cpp.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::linalg::comprehensive_bufferize::getContiguousOrUnrankedMemRefType(), mlir::linalg::comprehensive_bufferize::getDynamicMemRefType(), mlir::linalg::comprehensive_bufferize::BufferizationState::mapBuffer(), and mlir::OpBuilder::setInsertionPointToStart().
isAllocationHoistingBarrier()
bool mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isAllocationHoistingBarrier (Operation * op) const inline
Definition at line 722 of file ModuleBufferization.cpp.
References mlir::linalg::comprehensive_bufferize::std_ext::registerBufferizableOpInterfaceExternalModels().
isWritable()
bool mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Return true if the given function argument is writable.
Definition at line 697 of file ModuleBufferization.cpp.
References mlir::Value::dyn_cast(), getModuleBufferizationState(), and mlir::BoolAttr::getValue().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp