MLIR: mlir::MemRefRegion Struct Reference
mlir::MemRefRegion Struct Reference
A region of a memref's data space; this is typically constructed by analyzing load/store op's on this memref and the index space of loops surrounding such op's.
#include "mlir/Analysis/Utils.h"
Public Member Functions
MemRefRegion (Location loc)
LogicalResult compute (Operation *op, unsigned loopDepth, const ComputationSliceState *sliceState=nullptr, bool addMemRefDimBounds=true)
Computes the memory region accessed by this memref with the region represented as constraints symbolic/parametric in 'loopDepth' loops surrounding opInst.
FlatAffineValueConstraints * getConstraints ()
const FlatAffineValueConstraints * getConstraints () const
bool isWrite () const
void setWrite (bool flag)
Optional< int64_t > getConstantBoundingSizeAndShape (SmallVectorImpl< int64_t > *shape=nullptr, std::vector< SmallVector< int64_t, 4 >> *lbs=nullptr, SmallVectorImpl< int64_t > *lbDivisors=nullptr) const
Returns a constant upper bound on the number of elements in this region if bounded by a known constant (always possible for static shapes), None otherwise.
void getLowerAndUpperBound (unsigned pos, AffineMap &lbMap, AffineMap &ubMap) const
Gets the lower and upper bound map for the dimensional identifier at pos.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *lbFloorDivisor=nullptr) const
A wrapper around FlatAffineValueConstraints::getConstantBoundOnDimSize().
Optional< int64_t > getRegionSize ()
Returns the size of this MemRefRegion in bytes.
LogicalResult unionBoundingBox (const MemRefRegion &other)
unsigned getRank () const
Returns the rank of the memref that this region corresponds to.
Public Attributes
Value memref
Memref that this region corresponds to.
bool write
Read or write.
Location loc
If there is more than one load/store op associated with the region, the location information would correspond to one of those op's.
FlatAffineValueConstraints cst
Region (data space) of the memref accessed.
Detailed Description
A region of a memref's data space; this is typically constructed by analyzing load/store op's on this memref and the index space of loops surrounding such op's.
Definition at line 247 of file Utils.h.
Constructor & Destructor Documentation
MemRefRegion()
mlir::MemRefRegion::MemRefRegion (Location loc) inline explicit
Definition at line 248 of file Utils.h.
Member Function Documentation
compute()
LogicalResult MemRefRegion::compute (Operation * op, unsigned loopDepth, const ComputationSliceState * sliceState = nullptr, bool addMemRefDimBounds = true)
Computes the memory region accessed by this memref with the region represented as constraints symbolic/parametric in 'loopDepth' loops surrounding opInst.
Computes the memory region accessed by this memref with the region represented as constraints symbolic/parametric in 'loopDepth' loops surrounding opInst and any additional Function symbols.
The computed region's 'cst' field has exactly as many dimensional identifiers as the rank of the memref, and potentially additional symbolic identifiers which could include any of the loop IVs surrounding opInst up until 'loopDepth' and another additional Function symbols involved with the access (for eg., those appear in affine.apply's, loop bounds, etc.). If 'sliceState' is non-null, operands from 'sliceState' are added as symbols, and the following constraints are added to the system: *) Inequality constraints which represent loop bounds for 'sliceState' operands which are loop IVS (these represent the destination loop IVs of the slice, and are added as symbols to MemRefRegion's constraint system). *) Inequality constraints for the slice bounds in 'sliceState', which represent the bounds on the loop IVs in this constraint system w.r.t to slice operands (which correspond to symbols). If 'addMemRefDimBounds' is true, constant upper/lower bounds [0, memref.getDimSize(i)) are added for each MemRef dimension 'i'.
For example, the memref region for this operation at loopDepth = 1 will be:
affine.for i = 0 to 32 { affine.for ii = i to (d0) -> (d0 + 8) (i) { load A[ii] } }
{memref = A, write = false, {i <= m0 <= i + 7} } The last field is a 2-d FlatAffineValueConstraints symbolic in i.
Definition at line 447 of file Utils.cpp.
References mlir::AffineMap::dump(), mlir::Operation::emitError(), mlir::FlatAffineConstraints::EQ, mlir::extractForInductionVars(), mlir::failed(), mlir::failure(), mlir::MemRefAccess::getAccessMap(), mlir::AffineValueMap::getAffineMap(), mlir::getForInductionVarOwner(), mlir::getLoopIVs(), mlir::AffineMap::getNumDims(), mlir::AffineValueMap::getNumOperands(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperand(), mlir::MemRefAccess::getRank(), mlir::MemRefAccess::isStore(), mlir::isValidSymbol(), mlir::ComputationSliceState::ivs, mlir::FlatAffineConstraints::LB, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::MemRefAccess::memref, mlir::succeeded(), mlir::success(), mlir::FlatAffineConstraints::UB, and mlir::ComputationSliceState::ubs.
getConstantBoundingSizeAndShape()
Optional< int64_t > MemRefRegion::getConstantBoundingSizeAndShape (SmallVectorImpl< int64_t > * shape = nullptr, std::vector< SmallVector< int64_t, 4 >> * lbs = nullptr, SmallVectorImpl< int64_t > * lbDivisors = nullptr) const
Returns a constant upper bound on the number of elements in this region if bounded by a known constant (always possible for static shapes), None otherwise.
Note that the symbols of the region are treated specially, i.e., the returned bounding constant holds for any given value of the symbol identifiers. The 'shape' vector is set to the corresponding dimension-wise bounds major to minor. The number of elements and all the dimension-wise bounds are guaranteed to be non-negative. We use int64_t instead of uint64_t since index types can be at most int64_t. lbs are set to the lower bounds for each of the rank dimensions, and lbDivisors contains the corresponding denominators for floorDivs.
Definition at line 345 of file Utils.cpp.
References mlir::ShapedType::isDynamic(), mlir::FlatAffineConstraints::LB, mlir::ComputationSliceState::lbs, and mlir::FlatAffineConstraints::UB.
Referenced by generateCopy().
getConstantBoundOnDimSize()
Optional<int64_t> mlir::MemRefRegion::getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > * lb = nullptr, int64_t * lbFloorDivisor = nullptr) const inline
A wrapper around FlatAffineValueConstraints::getConstantBoundOnDimSize().
'pos' corresponds to the position of the memref shape's dimension (major to minor) which matches 1:1 with the dimensional identifier positions in 'cst'.
Definition at line 316 of file Utils.h.
getConstraints() [1/2]
FlatAffineValueConstraints* mlir::MemRefRegion::getConstraints () inline
Definition at line 286 of file Utils.h.
Referenced by findHighestBlockForPlacement(), generateCopy(), getFullMemRefAsRegion(), and unionBoundingBox().
getConstraints() [2/2]
const FlatAffineValueConstraints* mlir::MemRefRegion::getConstraints () const inline
Definition at line 287 of file Utils.h.
getLowerAndUpperBound()
void MemRefRegion::getLowerAndUpperBound (unsigned pos, AffineMap & lbMap, AffineMap & ubMap) const
Gets the lower and upper bound map for the dimensional identifier at pos.
Definition at line 406 of file Utils.cpp.
References mlir::AffineMap::getNumInputs().
Referenced by generateCopy().
getRank()
unsigned MemRefRegion::getRank () const
Returns the rank of the memref that this region corresponds to.
Definition at line 341 of file Utils.cpp.
getRegionSize()
Optional< int64_t > MemRefRegion::getRegionSize ()
Returns the size of this MemRefRegion in bytes.
Definition at line 617 of file Utils.cpp.
References getMemRefEltSizeInBytes().
isWrite()
bool mlir::MemRefRegion::isWrite () const inline
Definition at line 288 of file Utils.h.
Referenced by generateCopy().
setWrite()
void mlir::MemRefRegion::setWrite (bool flag) inline
Definition at line 289 of file Utils.h.
Referenced by getFullMemRefAsRegion().
unionBoundingBox()
LogicalResult MemRefRegion::unionBoundingBox (const MemRefRegion & other)
Definition at line 425 of file Utils.cpp.
References getConstraints(), and memref.
Member Data Documentation
cst
FlatAffineValueConstraints mlir::MemRefRegion::cst
Region (data space) of the memref accessed.
This set will thus have at least as many dimensional identifiers as the shape dimensionality of the memref, and these are the leading dimensions of the set appearing in that order (major to minor / outermost to innermost). There may be additional identifiers since getMemRefRegion() is called with a specific loop depth, and thus the region is symbolic in the outer surrounding loops at that depth.
Definition at line 350 of file Utils.h.
loc
Location mlir::MemRefRegion::loc
If there is more than one load/store op associated with the region, the location information would correspond to one of those op's.
Definition at line 340 of file Utils.h.
Referenced by generateCopy().
memref
Value mlir::MemRefRegion::memref
Memref that this region corresponds to.
Definition at line 333 of file Utils.h.
Referenced by generateCopy(), mlir::generateCopyForMemRegion(), getFullMemRefAsRegion(), getMultiLevelStrides(), and unionBoundingBox().
write
bool mlir::MemRefRegion::write
Read or write.
Definition at line 336 of file Utils.h.
The documentation for this struct was generated from the following files:
include/mlir/Analysis/Utils.h
lib/Analysis/Utils.cpp