MLIR: lib/Conversion/TosaToLinalg/TosaToLinalg.cpp File Reference
TosaToLinalg.cpp File Reference
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <numeric>
Functions
static SmallVector< StringRef > getNParallelLoopsAttrs (unsigned nParallelLoops)
template<typename T >
static arith::ConstantOp createConstFromIntAttribute (Operation *op, std::string attrName, Type requiredAttrType, OpBuilder &rewriter)
template<typename T >
static void getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > &arrayValues)
template<typename T , typename P >
static mlir::SelectOp clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder &rewriter)
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder &rewriter)
static SmallVector< Value > filterDynamicDims (SmallVector< Value > dynDims)
static Value createLinalgBodyCalculationForElementwiseOp (Operation *op, ValueRange args, ArrayRef< Type > resultTypes, PatternRewriter &rewriter)
static LogicalResult elementwiseMatchAndRewriteHelper (Operation *operation, PatternRewriter &rewriter)
static Attribute createInitialValueForReduceOp (Operation *op, Type elementTy, PatternRewriter &rewriter)
static Value createLinalgBodyCalculationForReduceOp (Operation *op, ValueRange args, Type elementTy, PatternRewriter &rewriter)
static LogicalResult reduceMatchAndRewriteHelper (Operation *op, uint64_t axis, PatternRewriter &rewriter)
static bool findIntermediateShape (ArrayRef< int64_t > lhsShape, ArrayRef< int64_t > rhsShape, SmallVector< int64_t > &intermediateShape, bool isDynamic)
static bool createReassociationMapsForCollapse (PatternRewriter &rewriter, ArrayRef< int64_t > srcShape, ArrayRef< int64_t > dstShape, SmallVector< ReassociationExprs, 4 > &reassociationMap, bool isDynamic)
Function Documentation
applyPad()
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder & rewriter) static
Definition at line 64 of file TosaToLinalg.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::ShapedType::getElementType(), mlir::Builder::getIndexAttr(), mlir::ShapedType::getShape(), and mlir::Value::getType().
Referenced by createReassociationMapsForCollapse().
clampHelper()
template<typename T , typename P > static mlir::SelectOp clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder & rewriter) static
Definition at line 54 of file TosaToLinalg.cpp.
References mlir::OpBuilder::create(), max(), and min().
createConstFromIntAttribute()
template<typename T > static arith::ConstantOp createConstFromIntAttribute (Operation * op, std::string attrName, Type requiredAttrType, OpBuilder & rewriter) static
Definition at line 37 of file TosaToLinalg.cpp.
References mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::Operation::getAttr(), and mlir::Operation::getLoc().
createInitialValueForReduceOp()
static Attribute createInitialValueForReduceOp (Operation * op, Type elementTy, PatternRewriter & rewriter) static
Definition at line 775 of file TosaToLinalg.cpp.
References mlir::Type::cast(), mlir::Builder::getFloatAttr(), mlir::FloatType::getFloatSemantics(), mlir::Builder::getIntegerAttr(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isa(), and mlir::Type::isInteger().
Referenced by createReassociationMapsForCollapse(), and reduceMatchAndRewriteHelper().
createLinalgBodyCalculationForElementwiseOp()
static Value createLinalgBodyCalculationForElementwiseOp (Operation * op, ValueRange args, ArrayRef< Type > resultTypes, PatternRewriter & rewriter) static
Definition at line 104 of file TosaToLinalg.cpp.
References mlir::Attribute::cast(), mlir::Type::cast(), clamp(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Block::getArgument(), mlir::Operation::getAttr(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), getElementType(), mlir::Builder::getF32FloatAttr(), mlir::Builder::getFloatAttr(), mlir::Builder::getI32Type(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::Value::getType(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), mlir::Type::isInteger(), mlir::Type::isUnsignedInteger(), max(), min(), mlir::RewriterBase::notifyMatchFailure(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by elementwiseMatchAndRewriteHelper().
createLinalgBodyCalculationForReduceOp()
static Value createLinalgBodyCalculationForReduceOp (Operation * op, ValueRange args, Type elementTy, PatternRewriter & rewriter) static
Definition at line 827 of file TosaToLinalg.cpp.
References mlir::OpBuilder::create(), mlir::Operation::getLoc(), mlir::Type::isa(), and mlir::Type::isInteger().
Referenced by reduceMatchAndRewriteHelper().
createReassociationMapsForCollapse()
static bool createReassociationMapsForCollapse (PatternRewriter & rewriter, ArrayRef< int64_t > srcShape, ArrayRef< int64_t > dstShape, SmallVector< ReassociationExprs, 4 > & reassociationMap, bool isDynamic) static
Definition at line 1002 of file TosaToLinalg.cpp.
References applyPad(), mlir::Attribute::cast(), mlir::Location::cast(), mlir::Type::cast(), clamp(), mlir::ShapedType::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createInitialValueForReduceOp(), mlir::OpBuilder::createOrFold(), elementwiseMatchAndRewriteHelper(), mlir::detail::enumerate(), mlir::failure(), filterDynamicDims(), findIntermediateShape(), mlir::AffineMap::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getAffineDimExpr(), mlir::getAffineDimExpr(), mlir::Block::getArgument(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::ShapedType::getElementType(), getElementType(), mlir::Builder::getF32FloatAttr(), mlir::Builder::getF32Type(), mlir::Builder::getFloatAttr(), mlir::FloatType::getFloatSemantics(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Builder::getI8IntegerAttr(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Builder::getMultiDimIdentityMap(), getNParallelLoopsAttrs(), mlir::getParallelIteratorTypeName(), mlir::ShapedType::getRank(), mlir::getReductionIteratorTypeName(), mlir::ShapedType::getShape(), mlir::Value::getType(), getValuesFromIntArrayAttribute(), mlir::Builder::getZeroAttr(), mlir::ShapedType::hasRank(), mlir::ShapedType::hasStaticShape(), mlir::AffineMap::inferFromExprList(), mlir::Type::isa(), mlir::ShapedType::isDynamicDim(), mlir::Type::isUnsignedInteger(), mlir::m_Constant(), mlir::matchPattern(), max(), min(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::RewriterBase::notifyMatchFailure(), reduceMatchAndRewriteHelper(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), resultIndex(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and value.
elementwiseMatchAndRewriteHelper()
static LogicalResult elementwiseMatchAndRewriteHelper (Operation * operation, PatternRewriter & rewriter) static
Definition at line 663 of file TosaToLinalg.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), createLinalgBodyCalculationForElementwiseOp(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failure(), filterDynamicDims(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::ShapedType::getElementType(), mlir::getElementTypeOrSelf(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), getNParallelLoopsAttrs(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::ShapedType::getRank(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::ShapedType::getShape(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), and mlir::success().
Referenced by createReassociationMapsForCollapse().
filterDynamicDims()
static SmallVector<Value> filterDynamicDims (SmallVector< Value > dynDims) static
Definition at line 95 of file TosaToLinalg.cpp.
Referenced by createReassociationMapsForCollapse(), and elementwiseMatchAndRewriteHelper().
findIntermediateShape()
static bool findIntermediateShape (ArrayRef< int64_t > lhsShape, ArrayRef< int64_t > rhsShape, SmallVector< int64_t > & intermediateShape, bool isDynamic) static
Definition at line 949 of file TosaToLinalg.cpp.
Referenced by createReassociationMapsForCollapse().
getNParallelLoopsAttrs()
static SmallVector<StringRef> getNParallelLoopsAttrs (unsigned nParallelLoops) static
Definition at line 31 of file TosaToLinalg.cpp.
References mlir::getParallelIteratorTypeName().
Referenced by createReassociationMapsForCollapse(), and elementwiseMatchAndRewriteHelper().
getValuesFromIntArrayAttribute()
template<typename T > static void getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > & arrayValues) static
Definition at line 46 of file TosaToLinalg.cpp.
Referenced by createReassociationMapsForCollapse().
reduceMatchAndRewriteHelper()
static LogicalResult reduceMatchAndRewriteHelper (Operation * op, uint64_t axis, PatternRewriter & rewriter) static
Definition at line 884 of file TosaToLinalg.cpp.
References mlir::OpBuilder::create(), createInitialValueForReduceOp(), createLinalgBodyCalculationForReduceOp(), mlir::failure(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Operation::getLoc(), mlir::Operation::getOperand(), mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::Value::getType(), mlir::AffineMap::inferFromExprList(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by createReassociationMapsForCollapse().