MLIR: lib/Transforms/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Transforms/Utils.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/TypeSwitch.h"
Macros
#define DEBUG_TYPE "transforms-utils"
Enumerations
enum TileExprPattern { TileFloorDiv, TileMod, TileNone }
Enum to set patterns of affine expr in tiled-layout map.
Functions
static LogicalResult getTileSizePos (AffineMap map, SmallVectorImpl< std::tuple< AffineExpr, unsigned, unsigned >> &tileSizePos)
Check if map is a tiled layout.
static bool isNormalizedMemRefDynamicDim (unsigned dim, AffineMap layoutMap, SmallVectorImpl< unsigned > &inMemrefTypeDynDims, MLIRContext *context)
Check if dim dimension of memrefType with layoutMap becomes dynamic after normalization.
static AffineExpr createDimSizeExprForTiledLayout (AffineExpr oldMapOutput, TileExprPattern pat)
Create affine expr to calculate dimension size for a tiled-layout map.
static void createNewDynamicSizes (MemRefType oldMemRefType, MemRefType newMemRefType, AffineMap map, memref::AllocOp *allocOp, OpBuilder b, SmallVectorImpl< Value > &newDynamicSizes)
Create new maps to calculate each dimension size of newMemRefType, and create newDynamicSizes from them by using AffineApplyOp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "transforms-utils"
Definition at line 28 of file Utils.cpp.
Enumeration Type Documentation
TileExprPattern
enum TileExprPattern
Enum to set patterns of affine expr in tiled-layout map.
TileFloorDiv: <dim expr>=""> div <tile size>=""> TileMod: <dim expr>=""> mod <tile size>=""> TileNone: None of the above Example: #tiled_2d_128x256 = affine_map<(d0, d1) -> (d0 div 128, d1 div 256, d0 mod 128, d1 mod 256)> "d0 div 128" and "d1 div 256" ==> TileFloorDiv "d0 mod 128" and "d1 mod 256" ==> TileMod
Enumerator
TileFloorDiv
TileMod
TileNone
Definition at line 402 of file Utils.cpp.
Function Documentation
createDimSizeExprForTiledLayout()
static AffineExpr createDimSizeExprForTiledLayout (AffineExpr oldMapOutput, TileExprPattern pat) static
Create affine expr to calculate dimension size for a tiled-layout map.
Definition at line 529 of file Utils.cpp.
References mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::getAffineBinaryOpExpr(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), TileFloorDiv, and TileMod.
Referenced by createNewDynamicSizes().
createNewDynamicSizes()
static void createNewDynamicSizes (MemRefType oldMemRefType, MemRefType newMemRefType, AffineMap map, memref::AllocOp * allocOp, OpBuilder b, SmallVectorImpl< Value > & newDynamicSizes) static
Create new maps to calculate each dimension size of newMemRefType, and create newDynamicSizes from them by using AffineApplyOp.
Steps for normalizing dynamic memrefs for a tiled layout map Example: #map0 = affine_map<(d0, d1) -> (d0, d1 floordiv 32, d1 mod 32)> %0 = dim arg0, c1 :memref<4x?xf32> %1 = alloc(%0) : memref<4x?xf32, #map0>
(Before this function)
Check if map(#map0) is a tiled layout using getTileSizePos(). Only single layout map is supported.
Create normalized memrefType using isNormalizedMemRefDynamicDim(). It is memref<4x?x?xf32> in the above example.
(In this function)
Create new maps to calculate each dimension of the normalized memrefType using createDimSizeExprForTiledLayout(). In the tiled layout, the dimension size can be calculated by replacing "floordiv <tile size>" with "ceildiv <tile size>" and "mod <tile size>" with "<tile size>".
New map in the above example #map0 = affine_map<(d0, d1) -> (d0)> #map1 = affine_map<(d0, d1) -> (d1 ceildiv 32)> #map2 = affine_map<(d0, d1) -> (32)>
Create AffineApplyOp to apply the new maps. The output of AffineApplyOp is used in dynamicSizes of new AllocOp. %0 = dim arg0, c1 : memref<4x?xf32> c4 = arith.constant 4 : index %1 = affine.apply #map1(c4, %0) %2 = affine.apply #map2(c4, %0)
Definition at line 584 of file Utils.cpp.
References mlir::OpBuilder::create(), createDimSizeExprForTiledLayout(), mlir::AffineMap::get(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), getTileSizePos(), TileFloorDiv, TileMod, and TileNone.
Referenced by mlir::normalizeMemRef().
getTileSizePos()
static LogicalResult getTileSizePos (AffineMap map, SmallVectorImpl< std::tuple< AffineExpr, unsigned, unsigned >> & tileSizePos) static
Check if map is a tiled layout.
In the tiled layout, specific k dimensions being floordiv'ed by respective tile sizes appeare in a mod with the same tile sizes, and no other expression involves those k dimensions. This function stores a vector of tuples (tileSizePos) including AffineExpr for tile size, positions of corresponding floordiv and mod. If it is not a tiled layout, an empty vector is returned.
Definition at line 410 of file Utils.cpp.
References mlir::AffineExpr::cast(), mlir::FloorDiv, mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineMap::getResults(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineExpr::isa(), mlir::Mod, and mlir::success().
Referenced by createNewDynamicSizes(), mlir::normalizeMemRef(), and mlir::normalizeMemRefType().
isNormalizedMemRefDynamicDim()
static bool isNormalizedMemRefDynamicDim (unsigned dim, AffineMap layoutMap, SmallVectorImpl< unsigned > & inMemrefTypeDynDims, MLIRContext * context) static
Check if dim dimension of memrefType with layoutMap becomes dynamic after normalization.
Dimensions that include dynamic dimensions in the map output will become dynamic dimensions. Return true if dim is dynamic dimension.
Example: #map0 = affine_map<(d0, d1) -> (d0, d1 floordiv 32, d1 mod 32)>
If d1 is dynamic dimension, 2nd and 3rd dimension of map output are dynamic. memref<4x?xf32, #map0> ==> memref<4x?x?xf32>
Definition at line 509 of file Utils.cpp.
References mlir::AffineMap::getResults(), mlir::AffineExpr::isa(), and mlir::AffineExpr::walk().
Referenced by mlir::normalizeMemRefType().