MLIR: lib/Translation/Translation.cpp File Reference
Translation.cpp File Reference
#include "mlir/Translation.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/ToolUtilities.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static llvm::StringMap< TranslateFunction > & getTranslationRegistry ()
Get the mutable static map between registered file-to-file MLIR translations and the TranslateFunctions that perform those translations.
static void registerTranslation (StringRef name, const TranslateFunction &function)
Register the given translation.
static void registerTranslateToMLIRFunction (StringRef name, const TranslateSourceMgrToMLIRFunction &function)
Function Documentation
getTranslationRegistry()
static llvm::StringMap<TranslateFunction>& getTranslationRegistry () static
Get the mutable static map between registered file-to-file MLIR translations and the TranslateFunctions that perform those translations.
Definition at line 33 of file Translation.cpp.
Referenced by registerTranslation(), and mlir::TranslationParser::TranslationParser().
registerTranslateToMLIRFunction()
static void registerTranslateToMLIRFunction (StringRef name, const TranslateSourceMgrToMLIRFunction & function) static
Definition at line 61 of file Translation.cpp.
References mlir::failed(), mlir::failure(), registerTranslation(), mlir::success(), mlir::TranslateToMLIRRegistration::TranslateToMLIRRegistration(), and mlir::verify().
registerTranslation()
static void registerTranslation (StringRef name, const TranslateFunction & function) static
Register the given translation.
Definition at line 39 of file Translation.cpp.
References getTranslationRegistry().
Referenced by registerTranslateToMLIRFunction(), mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(), and mlir::TranslateRegistration::TranslateRegistration().