MLIR: lib/Conversion/VectorToGPU/VectorToGPU.cpp File Reference
VectorToGPU.cpp File Reference
#include <type_traits>
#include "mlir/Conversion/VectorToGPU/VectorToGPU.h"
#include "../PassDetail.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
Namespaces
mlir
Include the generated interface declarations.
Functions
static bool contractSupportsMMAMatrixType (vector::ContractionOp contract)
static llvm::Optional< int64_t > getMemrefConstantHorizontalStride (ShapedType type)
static bool transferReadSupportsMMAMatrixType (vector::TransferReadOp readOp)
static bool transferWriteSupportsMMAMatrixType (vector::TransferWriteOp writeOp)
static bool constantSupportsMMAMatrixType (arith::ConstantOp constantOp)
Return true if the constant is a splat to a 2D vector so that it can be converted to a MMA constant matrix op.
static bool broadcastSupportsMMAMatrixType (vector::BroadcastOp broadcastOp)
Return true if this is a broadcast from scalar to a 2D vector.
static llvm::Optional< gpu::MMAElementwiseOp > convertElementwiseOpToMMA (Operation *op)
Return the MMA elementwise enum associated with op if it is supported.
static bool elementwiseSupportsMMAMatrixType (Operation *op)
Return true if the op is supported as elementwise op on MMAMatrix type.
static bool supportsMMaMatrixType (Operation *op)
static SetVector< Operation * > getSliceContract (Operation *op, TransitiveFilter backwardFilter, TransitiveFilter forwardFilter)
Return an unsorted slice handling scf.for region differently than getSlice.
static SetVector< Operation * > getOpToConvert (mlir::Operation *op)
template<typename OpTy >
static const char * inferFragType (OpTy op)
static void convertTransferReadOp (vector::TransferReadOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertTransferWriteOp (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertContractOp (vector::ContractionOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertConstantOp (arith::ConstantOp op, llvm::DenseMap< Value, Value > &valueMapping)
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
static void convertBroadcastOp (vector::BroadcastOp op, llvm::DenseMap< Value, Value > &valueMapping)
Convert a vector.broadcast from scalar to a SubgroupMmaConstantMatrix op.
static scf::ForOp replaceForOpWithNewSignature (OpBuilder &b, scf::ForOp loop, ValueRange newIterOperands)
static void convertForOp (scf::ForOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertYieldOp (scf::YieldOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertElementwiseOp (Operation *op, gpu::MMAElementwiseOp opType, llvm::DenseMap< Value, Value > &valueMapping)
Convert an elementwise op to the equivalent elementwise op on MMA matrix.
void mlir::populatePrepareVectorToMMAPatterns (RewritePatternSet &patterns)
Patterns to transform vector ops into a canonical form to convert to MMA matrix operations.
void mlir::convertVectorToMMAOps (FuncOp funcOp)
Convert vector ops to MMA matrix operations.
Function Documentation
broadcastSupportsMMAMatrixType()
static bool broadcastSupportsMMAMatrixType (vector::BroadcastOp broadcastOp) static
Return true if this is a broadcast from scalar to a 2D vector.
Definition at line 120 of file VectorToGPU.cpp.
Referenced by convertBroadcastOp(), and supportsMMaMatrixType().
constantSupportsMMAMatrixType()
static bool constantSupportsMMAMatrixType (arith::ConstantOp constantOp) static
Return true if the constant is a splat to a 2D vector so that it can be converted to a MMA constant matrix op.
Definition at line 112 of file VectorToGPU.cpp.
Referenced by convertConstantOp(), and supportsMMaMatrixType().
contractSupportsMMAMatrixType()
static bool contractSupportsMMAMatrixType (vector::ContractionOp contract) static
Definition at line 34 of file VectorToGPU.cpp.
References mlir::bindDims(), mlir::AffineMap::inferFromExprList(), mlir::isParallelIterator(), and mlir::isReductionIterator().
Referenced by supportsMMaMatrixType().
convertBroadcastOp()
static void convertBroadcastOp (vector::BroadcastOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Convert a vector.broadcast from scalar to a SubgroupMmaConstantMatrix op.
Definition at line 411 of file VectorToGPU.cpp.
References broadcastSupportsMMAMatrixType(), mlir::OpBuilder::create(), mlir::gpu::MMAMatrixType::get(), and inferFragType().
Referenced by mlir::convertVectorToMMAOps().
convertConstantOp()
static void convertConstantOp (arith::ConstantOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
Definition at line 393 of file VectorToGPU.cpp.
References mlir::Attribute::cast(), constantSupportsMMAMatrixType(), mlir::OpBuilder::create(), mlir::gpu::MMAMatrixType::get(), mlir::Attribute::getType(), and inferFragType().
Referenced by mlir::convertVectorToMMAOps().
convertContractOp()
static void convertContractOp (vector::ContractionOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 381 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), and mlir::Value::getType().
Referenced by mlir::convertVectorToMMAOps().
convertElementwiseOp()
static void convertElementwiseOp (Operation * op, gpu::MMAElementwiseOp opType, llvm::DenseMap< Value, Value > & valueMapping) static
Convert an elementwise op to the equivalent elementwise op on MMA matrix.
Definition at line 493 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), and mlir::Operation::getResult().
Referenced by mlir::convertVectorToMMAOps().
convertElementwiseOpToMMA()
static llvm::Optional<gpu::MMAElementwiseOp> convertElementwiseOpToMMA (Operation * op) static
Return the MMA elementwise enum associated with op if it is supported.
Return llvm::None otherwise.
Definition at line 128 of file VectorToGPU.cpp.
Referenced by mlir::convertVectorToMMAOps(), and elementwiseSupportsMMAMatrixType().
convertForOp()
static void convertForOp (scf::ForOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 450 of file VectorToGPU.cpp.
References mlir::detail::enumerate(), mlir::Block::getArgument(), and replaceForOpWithNewSignature().
Referenced by mlir::convertVectorToMMAOps().
convertTransferReadOp()
static void convertTransferReadOp (vector::TransferReadOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 345 of file VectorToGPU.cpp.
References mlir::gpu::MMAMatrixType::get(), getMemrefConstantHorizontalStride(), inferFragType(), and transferReadSupportsMMAMatrixType().
Referenced by mlir::convertVectorToMMAOps().
convertTransferWriteOp()
static void convertTransferWriteOp (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 368 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexAttr(), getMemrefConstantHorizontalStride(), and transferWriteSupportsMMAMatrixType().
Referenced by mlir::convertVectorToMMAOps().
convertYieldOp()
static void convertYieldOp (scf::YieldOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 474 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), and mlir::detail::enumerate().
Referenced by mlir::convertVectorToMMAOps().
elementwiseSupportsMMAMatrixType()
static bool elementwiseSupportsMMAMatrixType (Operation * op) static
Return true if the op is supported as elementwise op on MMAMatrix type.
Definition at line 143 of file VectorToGPU.cpp.
References convertElementwiseOpToMMA().
Referenced by supportsMMaMatrixType().
getMemrefConstantHorizontalStride()
static llvm::Optional<int64_t> getMemrefConstantHorizontalStride (ShapedType type) static
Definition at line 59 of file VectorToGPU.cpp.
References mlir::Type::dyn_cast(), mlir::failed(), mlir::getStridesAndOffset(), and mlir::ShapedType::kDynamicStrideOrOffset.
Referenced by convertTransferReadOp(), convertTransferWriteOp(), transferReadSupportsMMAMatrixType(), and transferWriteSupportsMMAMatrixType().
getOpToConvert()
static SetVector<Operation *> getOpToConvert (mlir::Operation * op) static
Definition at line 203 of file VectorToGPU.cpp.
References contract(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), getSliceContract(), supportsMMaMatrixType(), mlir::topologicalSort(), and mlir::Operation::walk().
Referenced by mlir::convertVectorToMMAOps().
getSliceContract()
static SetVector<Operation *> getSliceContract (Operation * op, TransitiveFilter backwardFilter, TransitiveFilter forwardFilter) static
Return an unsorted slice handling scf.for region differently than getSlice.
In scf.for we only want to include as part of the slice elements that are part of the use/def chain.
Definition at line 166 of file VectorToGPU.cpp.
References mlir::getBackwardSlice(), and mlir::getForwardSlice().
Referenced by getOpToConvert().
inferFragType()
template<typename OpTy > static const char* inferFragType (OpTy op) static
Definition at line 332 of file VectorToGPU.cpp.
References contract(), and mlir::Operation::getUsers().
Referenced by convertBroadcastOp(), convertConstantOp(), and convertTransferReadOp().
replaceForOpWithNewSignature()
static scf::ForOp replaceForOpWithNewSignature (OpBuilder & b, scf::ForOp loop, ValueRange newIterOperands) static
Definition at line 426 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), and mlir::OpBuilder::setInsertionPoint().
Referenced by convertForOp().
supportsMMaMatrixType()
static bool supportsMMaMatrixType (Operation * op) static
Definition at line 147 of file VectorToGPU.cpp.
References broadcast(), broadcastSupportsMMAMatrixType(), constantSupportsMMAMatrixType(), contract(), contractSupportsMMAMatrixType(), elementwiseSupportsMMAMatrixType(), transferReadSupportsMMAMatrixType(), and transferWriteSupportsMMAMatrixType().
Referenced by getOpToConvert().
transferReadSupportsMMAMatrixType()
static bool transferReadSupportsMMAMatrixType (vector::TransferReadOp readOp) static
Definition at line 73 of file VectorToGPU.cpp.
References mlir::AffineMap::get(), mlir::AffineExpr::getContext(), getMemrefConstantHorizontalStride(), mlir::AffineMap::getNumDims(), and mlir::AffineMap::isMinorIdentity().
Referenced by convertTransferReadOp(), and supportsMMaMatrixType().
transferWriteSupportsMMAMatrixType()
static bool transferWriteSupportsMMAMatrixType (vector::TransferWriteOp writeOp) static
Definition at line 94 of file VectorToGPU.cpp.
References getMemrefConstantHorizontalStride().
Referenced by convertTransferWriteOp(), and supportsMMaMatrixType().