MLIR: lib/Dialect/X86Vector/Transforms/LegalizeForLLVMExport.cpp File Reference
LegalizeForLLVMExport.cpp File Reference
#include "mlir/Dialect/X86Vector/Transforms.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/X86Vector/X86VectorDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
Functions
template<typename OpTy >
static Type getSrcVectorElementType (OpTy op)
Extracts the "main" vector element type from the given X86Vector operation.
template<>
Type getSrcVectorElementType (Vp2IntersectOp op)
Function Documentation
getSrcVectorElementType() [1/2]
template<typename OpTy > static Type getSrcVectorElementType (OpTy op) static
Extracts the "main" vector element type from the given X86Vector operation.
Definition at line 25 of file LegalizeForLLVMExport.cpp.
References getElementType().
getSrcVectorElementType() [2/2]
template<> Type getSrcVectorElementType (Vp2IntersectOp op)
Definition at line 29 of file LegalizeForLLVMExport.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalOp(), mlir::OpBuilder::create(), mlir::Pattern::getContext(), getElementType(), mlir::Builder::getI8IntegerAttr(), mlir::Type::getIntOrFloatBitWidth(), mlir::ConversionPattern::getTypeConverter(), mlir::Builder::getZeroAttr(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::LLVM::detail::oneToOneRewrite(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().